import { systemText, useI18n, i18n } from '../../i18n/runtime'
import { useEffect, useMemo, useState } from 'react'
import ReactECharts from 'echarts-for-react'
import { timingApi, timingNumber, timingPercent, timingReason, type TimingMetrics, type TimingPeriod, type TimingProductResult, type TimingRun } from '../../services/timingResearch'
import { timingField } from './TimingRuleEditor'
import { timingPriceOption } from './timingPriceChart'
import TimingTrainingAudit from './TimingTrainingAudit'

const tableClass = 'w-full text-left text-xs [&_th]:whitespace-nowrap [&_th]:bg-slate-50 [&_th]:px-3 [&_th]:py-3 [&_th]:font-medium [&_th]:text-slate-600 [&_td]:whitespace-nowrap [&_td]:border-t [&_td]:border-slate-100 [&_td]:px-3 [&_td]:py-3 [&_td]:text-slate-700'
function Periods({ rows, label }: { rows: TimingPeriod[]; label: string }) {
  useI18n()
  return <div className="max-h-[420px] overflow-auto rounded-lg border border-slate-200"><table aria-label={label} className={tableClass}><thead><tr><th scope="col">{systemText('preInvestment.timingResults.period')}</th><th scope="col">{systemText('preInvestment.timingResults.strategyReturn')}</th><th scope="col">{systemText('preInvestment.timingResults.buyAndHold')}</th><th scope="col">{systemText('preInvestment.timingResults.maximumDrawdown')}</th><th scope="col">{systemText('preInvestment.timingResults.closedTrades')}</th><th scope="col">{systemText('preInvestment.timingResults.winRate')}</th><th scope="col">{systemText('preInvestment.timingResults.timeInMarket')}</th></tr></thead><tbody>{rows.map(row => <tr key={row.period}><td>{row.period}</td><td>{timingPercent(row.total_return)}</td><td>{timingPercent(row.buy_hold_return)}</td><td>{timingPercent(row.max_drawdown)}</td><td>{timingNumber(row.trade_count, 0)}</td><td>{timingPercent(row.win_rate)}</td><td>{timingPercent(row.exposure)}</td></tr>)}</tbody></table>{!rows.length && <p className="p-4 text-sm text-slate-600">{systemText('preInvestment.timingResults.noUsableStatisticsForThisInterval')}</p>}</div>
}
function Summary({ metrics }: { metrics?: TimingMetrics }) {
  useI18n()
  const items = [ [systemText('preInvestment.timingResults.strategyReturn'), timingPercent(metrics?.total_return)], [systemText('preInvestment.timingResults.buyAndHold'), timingPercent(metrics?.buy_hold_return)], [systemText('preInvestment.timingResults.maximumDrawdown'), timingPercent(metrics?.max_drawdown)], [systemText('preInvestment.timingResults.closedTrades'), timingNumber(metrics?.trade_count, 0)], [systemText('preInvestment.timingResults.tradeWinRate'), timingPercent(metrics?.win_rate)], [systemText('preInvestment.timingResults.timeInMarket2'), timingPercent(metrics?.exposure)] ]
  return <div className="grid grid-cols-2 gap-3 lg:grid-cols-3">{items.map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-xs text-slate-600">{label}</p><p className="mt-1 text-xl font-semibold tabular-nums text-slate-900">{value}</p></div>)}</div>
}

export default function TimingResults({ run }: { run: TimingRun }) {
  useI18n()
  const [productId, setProductId] = useState(run.products[0]?.product_id || '')
  const [loaded, setLoaded] = useState<TimingProductResult | null>(null)
  const [loadError, setLoadError] = useState('')
  const [retry, setRetry] = useState(0)
  const [tab, setTab] = useState<'overview' | 'periods' | 'trades' | 'nodes'>('overview')
  const [sample, setSample] = useState<'out_of_sample' | 'in_sample' | 'all'>('out_of_sample')
  const [period, setPeriod] = useState<'yearly' | 'monthly' | 'walk_forward'>('yearly')
  const [channelId, setChannelId] = useState('')
  const [selectedDate, setSelectedDate] = useState('')
  const [page, setPage] = useState(0)
  const [curvePage, setCurvePage] = useState(0)
  const manifestProduct = run.products.find(product => product.product_id === productId) || run.products[0]
  const product = loaded?.product_id === productId ? loaded : manifestProduct
  const needsDetail = manifestProduct?.status === 'ok' && manifestProduct.detail_loaded === false
  useEffect(() => {
    setLoaded(null); setLoadError(''); setSelectedDate(''); setChannelId(''); setPage(0); setCurvePage(0)
    if (!needsDetail) return
    const controller = new AbortController()
    void timingApi.product(run.id, productId, controller.signal).then(value => { if (!controller.signal.aborted) setLoaded(value) }).catch(error => { if (!controller.signal.aborted) setLoadError(error instanceof Error ? error.message : systemText('preInvestment.timingResults.unableToLoadProductResults')) })
    return () => controller.abort()
  }, [run.id, productId, needsDetail, retry])
  const curve = product?.curve || []
  const trades = product?.trades || []
  const channel = product?.channels?.find(item => item.id === channelId) || product?.channels?.[0]
  const selectedPoint = curve.find(point => point.date === selectedDate)
  const diagnostics = sample === 'in_sample' ? undefined : product?.diagnostics?.[sample]
  const chartOption = useMemo(() => ({
    animation: false, aria: { enabled: true }, legend: { data: [systemText('preInvestment.timingResults.timingStrategy'), systemText('preInvestment.timingResults.buyAndHold')], top: 0 },
    tooltip: { trigger: 'axis', confine: true, renderMode: 'richText', valueFormatter: (value: number) => timingNumber(value, 4) },
    grid: { left: 50, right: 16, top: 40, bottom: 70 }, xAxis: { type: 'category', data: curve.map(point => point.date), axisLabel: { hideOverlap: true } }, yAxis: { type: 'value', scale: true, name: systemText('preInvestment.timingResults.nav') },
    dataZoom: [{ type: 'inside' }, { type: 'slider', bottom: 10, height: 22 }],
    series: [{ name: systemText('preInvestment.timingResults.timingStrategy'), type: 'line', showSymbol: false, connectNulls: false, data: curve.map(point => point.nav), itemStyle: { color: '#4f46e5' } }, { name: systemText('preInvestment.timingResults.buyAndHold'), type: 'line', showSymbol: false, connectNulls: false, data: curve.map(point => point.buy_hold_nav), itemStyle: { color: '#94a3b8' }, lineStyle: { type: 'dashed' } }],
  }), [curve, i18n.language])
  const priceOption = useMemo(() => timingPriceOption(curve, trades), [curve, trades, i18n.language])
  const nodeOption = useMemo(() => ({
    animation: false, aria: { enabled: true }, tooltip: { trigger: 'axis', confine: true, renderMode: 'richText' }, grid: { left: 55, right: 20, top: 20, bottom: 55 },
    xAxis: { type: 'category', data: curve.map(point => point.date), axisLabel: { hideOverlap: true } }, yAxis: { type: 'value', scale: true },
    dataZoom: [{ type: 'inside' }, { type: 'slider', bottom: 5, height: 20 }], series: [{ name: channel?.label, type: 'line', showSymbol: false, step: channel?.type === 'condition' ? 'end' : false, connectNulls: false, data: channel?.values, itemStyle: { color: '#4f46e5' } }],
  }), [curve, channel])
  const chartEvents = useMemo(() => ({ click: (event: { name?: string }) => { if (event.name) setSelectedDate(event.name) } }), [])
  if (!product) return <p className="p-6 text-sm text-slate-600">{systemText('preInvestment.timingResults.thisStudyHasNoProductResults')}</p>
  return <section aria-label={systemText('preInvestment.timingResults.timingResearchResults')} className="min-w-0 space-y-4">
    <div className="flex flex-wrap items-end justify-between gap-3"><label className="min-w-[180px] text-xs text-slate-600">{systemText('preInvestment.timingResults.viewProduct')}<select className={timingField} value={productId} onChange={event => setProductId(event.target.value)}>{run.products.map(item => <option key={item.product_id} value={item.product_id}>{item.product_id}{item.status === 'error' ? " " + systemText('preInvestment.timingResults.insufficientData') : ''}</option>)}</select></label><span className="text-xs text-slate-600">{systemText('preInvestment.timingResults.runAt') + " "}{run.created_at?.replace('T', ' ').slice(0, 19)}</span></div>
    {product.status === 'error' ? <p role="alert" className="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">{product.error || systemText('preInvestment.timingResults.researchCouldNotCompleteForThisProduct')}</p> : <>
      <div className="flex flex-wrap gap-2" aria-label={systemText('preInvestment.timingResults.statisticalSample')}>{(['out_of_sample', 'in_sample', 'all'] as const).map(value => <button key={value} type="button" aria-pressed={sample === value} className={`min-h-9 rounded-lg px-3 text-sm ${sample === value ? 'bg-accent-50 font-semibold text-accent-700' : 'text-slate-600 hover:bg-slate-50'}`} onClick={() => setSample(value)}>{({ out_of_sample: systemText('preInvestment.timingResults.outOfSample'), in_sample: systemText('preInvestment.timingResults.inSample'), all: systemText('preInvestment.timingResults.fullInterval') })[value]}</button>)}</div>
      <Summary metrics={product.summary?.[sample]} />
      <TimingTrainingAudit audit={product.training} definition={run.definition_snapshot} />
      {product.summary?.[sample]?.trade_count === 0 && <p role="status" className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">{systemText('preInvestment.timingResults.noCompletedValidTradesInThisSample')}</p>}
      {diagnostics && <details className="rounded-xl border border-slate-200 p-3"><summary className="cursor-pointer text-sm font-medium text-slate-700">{systemText('preInvestment.timingResults.signalCoverageAndMonthlyStability')}</summary><div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-3">{[
        [systemText('preInvestment.timingResults.candidateSignalCount'), timingNumber(diagnostics.raw_signal_count, 0)],
        [systemText('preInvestment.timingResults.shareOfSignalsInTheBusiestMonth'), timingPercent(diagnostics.top_month_signal_share)],
        [systemText('preInvestment.timingResults.shareOfMonthsWithPositiveReturns'), timingPercent(diagnostics.positive_month_fraction)],
      ].map(([label, value]) => <div key={label} className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-600">{label}</p><p className="mt-1 text-lg font-semibold tabular-nums text-slate-900">{value}</p></div>)}</div><p className="mt-3 text-xs leading-5 text-slate-600">{systemText('preInvestment.timingResults.monthsWithSignals') + " "}{timingNumber(diagnostics.active_month_count, 0)} / {timingNumber(diagnostics.total_month_count, 0)}{systemText('preInvestment.timingResults.includesIncompleteFirstLastMonthsAndIs')}</p></details>}
      <div className="flex flex-wrap gap-2 border-b border-slate-200" role="tablist" aria-label={systemText('preInvestment.timingResults.researchResultViews')}>{(['overview', 'periods', 'trades', 'nodes'] as const).map(value => <button key={value} id={`timing-tab-${value}`} type="button" role="tab" aria-selected={tab === value} aria-controls="timing-result-panel" onClick={() => setTab(value)} className={`min-h-11 border-b-2 px-3 text-sm ${tab === value ? 'border-accent-600 font-semibold text-accent-700' : 'border-transparent text-slate-600'}`}>{({ overview: systemText('preInvestment.timingResults.navAndSignals'), periods: systemText('preInvestment.timingResults.annualMonthly'), trades: systemText('preInvestment.timingResults.individualTrades'), nodes: systemText('preInvestment.timingResults.stepPreview') })[value]}</button>)}</div>
      <div id="timing-result-panel" role="tabpanel" aria-labelledby={`timing-tab-${tab}`} className="min-w-0 space-y-4">
        {loadError ? <div role="alert" className="rounded-lg bg-rose-50 p-4 text-sm text-rose-700">{loadError}<button type="button" className="ml-3 underline" onClick={() => setRetry(value => value + 1)}>{systemText('preInvestment.timingResults.reload')}</button></div> : needsDetail && !loaded ? <p role="status" className="p-5 text-sm text-slate-600">{systemText('preInvestment.timingResults.loadingCurvesAndStepsForThisProduct')}</p> : <>
          {tab === 'overview' && <><p className="text-xs leading-5 text-slate-600">{systemText('preInvestment.timingResults.chartsShowTheFullResearchIntervalOut') + " "}{run.request_snapshot.holdout_start} {" " + systemText('preInvestment.timingResults.statisticsAboveFollowTheSelectedSample')}</p><ReactECharts option={chartOption} notMerge style={{ height: 330, width: '100%' }} onEvents={chartEvents} />
            <div role="group" aria-label={systemText('preInvestment.timingResults.tradeMarkerChart')} className="min-w-0">
              <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-slate-600"><h3 className="mr-auto text-sm font-medium text-slate-800">{systemText('preInvestment.timingResults.priceAndTrades')}</h3><span className="inline-flex items-center gap-1.5"><span className="rounded-lg border border-rose-200 bg-rose-50 px-1.5 py-0.5 font-bold text-rose-700">B</span>{systemText('preInvestment.timingResults.buy')}</span><span className="inline-flex items-center gap-1.5"><span className="rounded-lg border border-emerald-200 bg-emerald-50 px-1.5 py-0.5 font-bold text-emerald-700">S</span>{systemText('preInvestment.timingResults.sell')}</span></div>
              <ReactECharts option={priceOption} notMerge style={{ height: 300, width: '100%' }} onEvents={chartEvents} />
              <p className="text-xs leading-5 text-slate-600">{systemText('preInvestment.timingResults.bAppearsBelowBuysAndSAbove')}</p>
            </div>
            <label className="block max-w-xs text-xs text-slate-600">{systemText('preInvestment.timingResults.viewSignalsForADate')}<input type="date" className={timingField} min={curve[0]?.date} max={curve[curve.length - 1]?.date} value={selectedDate} onChange={event => setSelectedDate(event.target.value)} /></label>{selectedDate && <div className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{selectedPoint ? systemText('preInvestment.timingResults.price', { p0: selectedPoint.date, p1: timingNumber(selectedPoint.close, 4), p2: selectedPoint.position > 0 ? systemText('preInvestment.timingResults.invested') : systemText('preInvestment.timingResults.outOfMarket'), p3: timingReason(selectedPoint.reason) }) : systemText('preInvestment.timingResults.noResearchDataForThisDateSelect')}</div>}
            <details><summary className="cursor-pointer py-2 text-sm text-accent-700">{systemText('preInvestment.timingResults.viewChartDataTable')}</summary><div className="overflow-auto rounded-lg border border-slate-200"><table className={tableClass} aria-label={systemText('preInvestment.timingResults.navAndSignalData')}><thead><tr><th scope="col">{systemText('preInvestment.timingResults.date')}</th><th scope="col">{systemText('preInvestment.timingResults.price2')}</th><th scope="col">{systemText('preInvestment.timingResults.strategyNav')}</th><th scope="col">{systemText('preInvestment.timingResults.buyAndHoldNav')}</th><th scope="col">{systemText('preInvestment.timingResults.invested')}</th><th scope="col">{systemText('preInvestment.timingResults.actionReason')}</th></tr></thead><tbody>{curve.slice(curvePage * 100, curvePage * 100 + 100).map(point => <tr key={point.date}><td>{point.date}</td><td>{timingNumber(point.close, 4)}</td><td>{timingNumber(point.nav, 4)}</td><td>{timingNumber(point.buy_hold_nav, 4)}</td><td>{point.position > 0 ? systemText('preInvestment.timingResults.invested') : systemText('preInvestment.timingResults.outOfMarket')}</td><td>{timingReason(point.reason)}</td></tr>)}</tbody></table></div><Pager page={curvePage} total={curve.length} onChange={setCurvePage} /></details>
            {!!product.signal_quality?.length && <details><summary className="cursor-pointer py-2 text-sm text-accent-700">{systemText('preInvestment.timingResults.viewSignalValidityAndHoldingExperience')}</summary><p className="mb-2 text-xs text-slate-600">{systemText('preInvestment.timingResults.theseDiagnosticsExaminePathsAfterSignalsNot')}</p><div className="overflow-auto"><table className={tableClass} aria-label={systemText('preInvestment.timingResults.signalQuality')}><thead><tr><th scope="col">{systemText('preInvestment.timingResults.observationHorizon')}</th><th scope="col">{systemText('preInvestment.timingResults.candidatesMatureSamples')}</th><th scope="col">{systemText('preInvestment.timingResults.positiveReturnShare')}</th><th scope="col">{systemText('preInvestment.timingResults.medianReturn')}</th><th scope="col">{systemText('preInvestment.timingResults.meanMaximumAdverseExcursion')}</th><th scope="col">{systemText('preInvestment.timingResults.meanMaximumFavorableExcursion')}</th><th scope="col">{systemText('preInvestment.timingResults.timeHeldAtAProfit')}</th></tr></thead><tbody>{product.signal_quality.map(row => <tr key={row.horizon}><td>{row.horizon} {" " + systemText('preInvestment.timingResults.days')}</td><td>{row.signal_count} / {row.eligible_count}</td><td>{timingPercent(row.win_rate)}</td><td>{timingPercent(row.median_return)}</td><td>{timingPercent(row.mean_max_adverse)}</td><td>{timingPercent(row.mean_max_favorable)}</td><td>{timingPercent(row.positive_close_fraction)}</td></tr>)}</tbody></table></div></details>}</>}
          {tab === 'periods' && <><label className="block max-w-xs text-xs text-slate-600">{systemText('preInvestment.timingResults.statisticalFrequency')}<select className={timingField} value={period} onChange={event => setPeriod(event.target.value as typeof period)}><option value="yearly">{systemText('preInvestment.timingResults.annually')}</option><option value="monthly">{systemText('preInvestment.timingResults.monthly')}</option><option value="walk_forward">{systemText('preInvestment.timingResults.stabilityAcrossTimePeriods')}</option></select></label><p className="text-xs text-slate-600">{systemText('preInvestment.timingResults.statisticsCoverEachPeriodOfTheFull')}</p><Periods rows={product[period] || []} label={period === 'yearly' ? systemText('preInvestment.timingResults.annualPerformance') : period === 'monthly' ? systemText('preInvestment.timingResults.monthlyPerformance') : systemText('preInvestment.timingResults.performanceByPeriod')} /></>}
          {tab === 'trades' && <><p className="text-xs text-slate-600">{systemText('preInvestment.timingResults.closeSignalsExecuteAtTheNextTrading')}</p><div className="overflow-auto rounded-lg border border-slate-200"><table className={tableClass} aria-label={systemText('preInvestment.timingResults.individualTrades')}><thead><tr><th scope="col">{systemText('preInvestment.timingResults.signalDate')}</th><th scope="col">{systemText('preInvestment.timingResults.buyDate')}</th><th scope="col">{systemText('preInvestment.timingResults.sellDate')}</th><th scope="col">{systemText('preInvestment.timingResults.netReturn')}</th><th scope="col">{systemText('preInvestment.timingResults.holdingDays')}</th><th scope="col">{systemText('preInvestment.timingResults.exitReason')}</th><th scope="col">{systemText('preInvestment.timingResults.maximumAdverseExcursion')}</th><th scope="col">{systemText('preInvestment.timingResults.maximumFavorableExcursion')}</th></tr></thead><tbody>{trades.slice(page * 100, page * 100 + 100).map((trade, index) => <tr key={`${trade.entry_date}:${index}`}><td>{trade.signal_date}</td><td>{trade.entry_date}</td><td>{trade.exit_date}</td><td>{timingPercent(trade.net_return)}</td><td>{trade.holding_days}</td><td>{timingReason(trade.reason)}</td><td>{timingPercent(trade.max_adverse_excursion)}</td><td>{timingPercent(trade.max_favorable_excursion)}</td></tr>)}</tbody></table>{!trades.length && <p className="p-4 text-sm text-slate-600">{systemText('preInvestment.timingResults.noCompletedTradesInThisIntervalConsider')}</p>}</div><Pager page={page} total={trades.length} onChange={setPage} /></>}
          {tab === 'nodes' && <><label className="block text-xs text-slate-600">{systemText('preInvestment.timingResults.selectACalculationStep')}<select className={timingField} value={channel?.id || ''} onChange={event => setChannelId(event.target.value)}>{product.channels?.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><p className="text-xs text-slate-600">{channel?.type === 'condition' ? systemText('preInvestment.timingResults.conditions1MeansTrue0FalseAnd') : systemText('preInvestment.timingResults.showsOriginalStepResultsSavedWithThis')}</p><ReactECharts option={nodeOption} notMerge style={{ height: 320, width: '100%' }} /><details><summary className="cursor-pointer py-2 text-sm text-accent-700">{systemText('preInvestment.timingResults.viewStepDataTable')}</summary><div className="max-h-80 overflow-auto"><table className={tableClass} aria-label={systemText('preInvestment.timingResults.stepData')}><thead><tr><th scope="col">{systemText('preInvestment.timingResults.date')}</th><th scope="col">{channel?.label || systemText('preInvestment.timingResults.number')}</th></tr></thead><tbody>{curve.slice(curvePage * 100, curvePage * 100 + 100).map((point, index) => <tr key={point.date}><td>{point.date}</td><td>{timingNumber(channel?.values[curvePage * 100 + index], 6)}</td></tr>)}</tbody></table></div><Pager page={curvePage} total={curve.length} onChange={setCurvePage} /></details></>}
        </>}
      </div>
    </>}
    {!!product.warnings?.length && <div className="space-y-1 rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-800">{product.warnings.map((warning, index) => <p key={index}>{warning}</p>)}</div>}
    {!!run.restrictions?.length && <details className="rounded-lg bg-slate-50 p-3"><summary className="cursor-pointer text-xs font-medium text-slate-600">{systemText('preInvestment.timingResults.researchBoundariesAndDataConventions')}</summary><div className="mt-2 space-y-1 text-xs leading-5 text-slate-600">{run.restrictions.map((restriction, index) => <p key={index}>{restriction}</p>)}</div></details>}
  </section>
}

function Pager({ page, total, onChange }: { page: number; total: number; onChange: (page: number) => void }) {
  useI18n()
  if (total <= 100) return null
  return <div className="mt-3 flex items-center justify-between gap-2 text-xs text-slate-600"><button type="button" className="min-h-9 rounded-lg border px-3 disabled:opacity-40" disabled={page === 0} onClick={() => onChange(page - 1)}>{systemText('preInvestment.timingResults.previous')}</button><span>{page + 1} / {Math.ceil(total / 100)} {" " + systemText('preInvestment.timingResults.pageS') + " "}{total} {" " + systemText('preInvestment.timingResults.items')}</span><button type="button" className="min-h-9 rounded-lg border px-3 disabled:opacity-40" disabled={(page + 1) * 100 >= total} onClick={() => onChange(page + 1)}>{systemText('preInvestment.timingResults.next')}</button></div>
}
