import { systemText, useI18n } from '../../i18n/runtime'
import { timingNumber, timingPercent, type TimingDefinition, type TimingTrainingAudit as Audit } from '../../services/timingResearch'
import { trainingModeLabels } from './TimingTrainingEditor'

function SelectedParameters({ audit, definition }: { audit: Audit; definition?: TimingDefinition }) {
  useI18n()
  const selectedIds = new Set(audit.selection.map(selection => selection.action_id).filter(Boolean))
  const candidates = audit.candidates.filter(candidate => selectedIds.has(candidate.id))
  if (!candidates.length) return null
  return <details className="mt-3"><summary className="cursor-pointer py-2 text-xs text-accent-700">{systemText('preInvestment.timingTrainingAudit.selectedParameters')}</summary><div className="space-y-3">{candidates.map(candidate => <article key={candidate.id} className="rounded-lg bg-slate-50 p-3"><h3 className="text-xs font-semibold text-slate-800">{candidate.label}</h3>{candidate.parameters?.length ? <dl className="mt-2 space-y-2">{candidate.parameters.map((parameter, index) => <div key={index} className="flex flex-wrap justify-between gap-2 text-xs"><dt className="break-words text-slate-600">{definition?.nodes.find(node => node.id === parameter.node)?.label || parameter.node} · {parameter.parameter}</dt><dd className="break-all font-medium text-slate-800">{String(parameter.value)}</dd></div>)}</dl> : <p className="mt-2 text-xs text-slate-600">{systemText('preInvestment.timingTrainingAudit.noParameterOverridesDefaultsFromTheFrozen')}</p>}</article>)}</div></details>
}

export default function TimingTrainingAudit({ audit, definition }: { audit?: Audit; definition?: TimingDefinition }) {
  useI18n()
  if (!audit) return null
  return <details className="rounded-xl border border-slate-200 p-3"><summary className="cursor-pointer text-sm font-medium text-slate-700">{systemText('preInvestment.timingTrainingAudit.trainingSelectionAndFreezeAudit')}</summary><p className="mt-3 text-xs leading-5 text-slate-600">{trainingModeLabels[audit.mode]}{systemText('preInvestment.timingTrainingAudit.freezeDate') + " "}{audit.freeze_date}{systemText('preInvestment.timingTrainingAudit.trainingCutoff') + " "}{audit.fit_end_date}{systemText('preInvestment.timingTrainingAudit.embargo') + " "}{audit.embargo_bars} {" " + systemText('preInvestment.timingTrainingAudit.tradingDaysWithAtLeast') + " "}{audit.min_trades} {" " + systemText('preInvestment.timingTrainingAudit.completedSignalsNoOutOfSampleRetraining')}</p><div className="mt-3 space-y-2" aria-label={systemText('preInvestment.timingTrainingAudit.trainingSelectedPlans')}>{audit.selection.map((selection, index) => <article key={`${selection.state}:${index}`} className="rounded-lg bg-slate-50 p-3 text-xs"><div className="flex flex-wrap justify-between gap-2"><span className="font-medium text-slate-800">{systemText('preInvestment.timingTrainingAudit.status') + " "}{selection.state}</span><strong className="text-accent-700">{selection.action_label || (selection.action_id === null ? systemText('preInvestment.timingTrainingAudit.noTradeUnselected') : selection.action_id)}</strong></div><p className="mt-2 text-slate-600">{systemText('preInvestment.timingTrainingAudit.completedSignals') + " "}{timingNumber(selection.sample_count, 0)} {" " + systemText('preInvestment.timingTrainingAudit.trainingUtility') + " "}{timingNumber(selection.utility, 4)}</p></article>)}</div>{!audit.selection.length && <p className="mt-3 text-xs text-amber-800">{systemText('preInvestment.timingTrainingAudit.noAvailableFrozenSelectionsCheckTrainingSamples')}</p>}
    <SelectedParameters audit={audit} definition={definition} />
    {!!audit.candidates.length && <details className="mt-3"><summary className="cursor-pointer py-2 text-xs text-accent-700">{systemText('preInvestment.timingTrainingAudit.viewCandidateTrainingComparison')}</summary><div className="max-h-80 overflow-auto rounded-lg border border-slate-200"><table aria-label={systemText('preInvestment.timingTrainingAudit.candidateTrainingStatistics')} className="w-full text-left text-xs [&_td]:whitespace-nowrap [&_td]:border-t [&_td]:p-3 [&_th]:whitespace-nowrap [&_th]:bg-slate-50 [&_th]:p-3"><thead><tr><th scope="col">{systemText('preInvestment.timingTrainingAudit.variant')}</th><th scope="col">{systemText('preInvestment.timingTrainingAudit.status')}</th><th scope="col">{systemText('preInvestment.timingTrainingAudit.sampleCount')}</th><th scope="col">{systemText('preInvestment.timingTrainingAudit.meanReturn')}</th><th scope="col">{systemText('preInvestment.timingTrainingAudit.winRate')}</th><th scope="col">{systemText('preInvestment.timingTrainingAudit.stopLossRate')}</th><th scope="col">{systemText('preInvestment.timingTrainingAudit.utility')}</th></tr></thead><tbody>{audit.candidates.flatMap(candidate => candidate.states.map((state, index) => <tr key={`${candidate.id}:${index}`}><td>{candidate.label}</td><td>{state.state}</td><td>{timingNumber(state.sample_count, 0)}</td><td>{timingPercent(state.mean_return)}</td><td>{timingPercent(state.win_rate)}</td><td>{timingPercent(state.stop_rate)}</td><td>{timingNumber(state.utility, 4)}</td></tr>))}</tbody></table></div></details>}{!!audit.warnings.length && <div className="mt-3 space-y-1 text-xs leading-5 text-amber-800">{audit.warnings.map((warning, index) => <p key={index}>{warning}</p>)}</div>}
  </details>
}
