import { timingNumber, timingPercent, type TimingDefinition, type TimingTrainingAudit as Audit } from '../../services/timingResearch'
import { trainingModeLabels } from './TimingTrainingEditor'

function SelectedParameters({ audit, definition }: { audit: Audit; definition?: TimingDefinition }) {
  const selectedIds = new Set(audit.selection.map(selection => selection.action_id).filter(Boolean))
  const candidates = audit.candidates.filter(candidate => selectedIds.has(candidate.id))
  if (!candidates.length) return null
  return <details className="mt-3"><summary className="cursor-pointer py-2 text-xs text-indigo-700">已选参数</summary><div className="space-y-3">{candidates.map(candidate => <article key={candidate.id} className="rounded-lg bg-slate-50 p-3"><h3 className="text-xs font-semibold text-slate-800">{candidate.label}</h3>{candidate.parameters?.length ? <dl className="mt-2 space-y-2">{candidate.parameters.map((parameter, index) => <div key={index} className="flex flex-wrap justify-between gap-2 text-xs"><dt className="break-words text-slate-500">{definition?.nodes.find(node => node.id === parameter.node)?.label || parameter.node} · {parameter.parameter}</dt><dd className="break-all font-medium text-slate-800">{String(parameter.value)}</dd></div>)}</dl> : <p className="mt-2 text-xs text-slate-500">未覆盖参数，使用冻结定义中的默认参数。</p>}</article>)}</div></details>
}

export default function TimingTrainingAudit({ audit, definition }: { audit?: Audit; definition?: TimingDefinition }) {
  if (!audit) return null
  return <details className="rounded-xl border border-slate-200 p-3"><summary className="cursor-pointer text-sm font-medium text-slate-700">训练选择与冻结审计</summary><p className="mt-3 text-xs leading-5 text-slate-600">{trainingModeLabels[audit.mode]}。冻结日 {audit.freeze_date}，训练截止 {audit.fit_end_date}；隔离 {audit.embargo_bars} 个交易日，至少 {audit.min_trades} 个已完成信号。样本外不重训，效用是训练选择依据，不是收益预测。</p><div className="mt-3 space-y-2" aria-label="训练选中方案">{audit.selection.map((selection, index) => <article key={`${selection.state}:${index}`} className="rounded-lg bg-slate-50 p-3 text-xs"><div className="flex flex-wrap justify-between gap-2"><span className="font-medium text-slate-800">状态 {selection.state}</span><strong className="text-indigo-700">{selection.action_label || (selection.action_id === null ? '不交易 / 未选中' : selection.action_id)}</strong></div><p className="mt-2 text-slate-500">已完成信号 {timingNumber(selection.sample_count, 0)} · 训练效用 {timingNumber(selection.utility, 4)}</p></article>)}</div>{!audit.selection.length && <p className="mt-3 text-xs text-amber-800">没有可用的冻结选择，请检查训练样本与约束。</p>}
    <SelectedParameters audit={audit} definition={definition} />
    {!!audit.candidates.length && <details className="mt-3"><summary className="cursor-pointer py-2 text-xs text-indigo-700">查看候选方案训练对比</summary><div className="max-h-80 overflow-auto rounded-lg border border-slate-200"><table aria-label="候选训练统计" className="w-full text-left text-xs [&_td]:whitespace-nowrap [&_td]:border-t [&_td]:p-3 [&_th]:whitespace-nowrap [&_th]:bg-slate-50 [&_th]:p-3"><thead><tr><th>方案</th><th>状态</th><th>样本数</th><th>平均收益</th><th>胜率</th><th>止损率</th><th>效用</th></tr></thead><tbody>{audit.candidates.flatMap(candidate => candidate.states.map((state, index) => <tr key={`${candidate.id}:${index}`}><td>{candidate.label}</td><td>{state.state}</td><td>{timingNumber(state.sample_count, 0)}</td><td>{timingPercent(state.mean_return)}</td><td>{timingPercent(state.win_rate)}</td><td>{timingPercent(state.stop_rate)}</td><td>{timingNumber(state.utility, 4)}</td></tr>))}</tbody></table></div></details>}{!!audit.warnings.length && <div className="mt-3 space-y-1 text-xs leading-5 text-amber-800">{audit.warnings.map((warning, index) => <p key={index}>{warning}</p>)}</div>}
  </details>
}
