import { useState } from 'react'
import { Button, Card } from '../ui'
import { Field, NumberInput } from '../risk-models/ResearchUI'
import type { ImplementationCandidate, ImplementationCatalog, ImplementationProduct, SourceOption } from '../../services/implementation'
import { operationKey } from '../../services/implementation'
import { amount, control, percent, useImplementationText } from './shared'

export function initialCandidate(source: SourceOption, today: string): ImplementationCandidate {
  const prior = new Date(`${today}T12:00:00`); prior.setFullYear(prior.getFullYear()-1)
  return {name: source.name, source: {kind:source.kind, id:source.id, content_hash:source.content_hash}, as_of:today, start_date:prior.toISOString().slice(0,10),
    products: source.assets.flatMap(asset=>asset.products.map((p,i)=>productDefaults(p.kind,p.product_id,asset.id,i===0?source.target[asset.id]:0))),
    state: {valuation_at:today, knowledge_cutoff:today, confirmed_investable_value:0, settled_cash:0, restricted_cash:0, receivables:0, payables:0,
      elapsed_months:0, cutoff_phase:'after_model_month_end', transition_cost_in_balance:false, evidence:'', reconciliation:[], cash_events:[]},
    annual_additional_fee:0, annual_fee_source:'', return_basis_confirmed:false, horizon_stationarity_acknowledged:false,
    future_weight_rule:'frozen_scalar_proxy', paths:2000, search_seed:42, validation_seed:314159, min_validation_r2:0, scenario_release_ids:[]}
}
function productDefaults(kind: ImplementationProduct['kind'], id: string, asset: string, weight=0): ImplementationProduct {
  return {kind, product_id:id, asset_class_id:asset, weight, max_weight:1, current_value:0,
    buy_rate:null, sell_rate:null, fee_source:'', fee_valid_until:null, fee_basis:'unknown', holding_days:null, channel:'', nav_includes_management_fee:null, settlement_date:null}
}

export default function CandidateFields({candidate, source, catalog, onChange}: {candidate: ImplementationCandidate; source: SourceOption; catalog: ImplementationCatalog; onChange: (next: ImplementationCandidate)=>void}) {
  const t=useImplementationText(), [tab,setTab]=useState<'products'|'funding'>('products'), [flowPage,setFlowPage]=useState(0)
  const patch=(value: Partial<ImplementationCandidate>)=>onChange({...candidate,...value})
  const state=(value: Partial<ImplementationCandidate['state']>)=>patch({state:{...candidate.state,...value}})
  const product=(index:number, value:Partial<ImplementationProduct>)=>patch({products:candidate.products.map((p,i)=>i===index?{...p,...value}:p)})
  const flows=source.funding?.occurrences.filter(row=>row.month<=candidate.state.elapsed_months)??[]
  return <div className="space-y-4">
    <div className="flex flex-wrap gap-2" aria-label={t('inputSteps')}><Button aria-pressed={tab==='products'} onClick={()=>setTab('products')}>{t('productsAndFees')}</Button><Button aria-pressed={tab==='funding'} onClick={()=>setTab('funding')}>{t('fundingAndPayments')}</Button></div>
    {tab==='products'?<>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Field label={t('name')}><input className={control} value={candidate.name} onChange={e=>patch({name:e.target.value})}/></Field>
        <Field label={t('asOf')}><input className={control} type="date" value={candidate.as_of} onChange={e=>patch({as_of:e.target.value,state:{...candidate.state,knowledge_cutoff:e.target.value}})}/></Field>
        <Field label={t('startDate')}><input className={control} type="date" value={candidate.start_date} onChange={e=>patch({start_date:e.target.value})}/></Field></div>
      {source.kind==='saa_policy'&&source.strategic_universe_id&&<Field label={t('mapping')}><select className={control} value={candidate.source.implementation_mapping_id??''} onChange={e=>{
        const mapping=catalog.mappings.find(m=>m.id===e.target.value)
        const products=mapping?mapping.definition.assignments.flatMap(a=>(mapping.source_snapshot.assets.find(x=>x.id===a.proxy_asset_id)?.products??[]).map((p,i)=>productDefaults(p.kind,p.product_id,a.strategic_asset_id,i===0?source.target[a.strategic_asset_id]:0))):initialCandidate(source,catalog.today).products
        patch({source:{...candidate.source,implementation_mapping_id:e.target.value||null},products})
      }}><option value="">{t('frozenMapping')}</option>{catalog.mappings.filter(m=>m.definition.strategic_universe_id===source.strategic_universe_id).map(m=><option key={m.id} value={m.id}>{m.name} · {m.definition.valid_until}</option>)}</select></Field>}
      <p className="text-sm leading-6 text-slate-600">{t('budgetHelp')} {Object.entries(source.target).map(([key,value])=>`${key} ${percent(value)}`).join(' · ')}</p>
      {candidate.products.length===0&&<p role="status" className="text-sm text-amber-900">{t('mappingRequired')}</p>}
      <Card><div className="divide-y divide-slate-200">{candidate.products.map((p,i)=><section key={`${p.kind}:${p.product_id}`} className="space-y-3 py-4 first:pt-0 last:pb-0" aria-label={p.product_id}>
        <div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">{p.product_id} <span className="text-sm font-normal text-slate-600">{p.asset_class_id}</span></h2>{p.kind==='cash'&&<Button onClick={()=>patch({products:candidate.products.filter((_,j)=>j!==i)})}>{t('removeCash')}</Button>}</div>
        <div className="grid gap-3 sm:grid-cols-3"><Field label={t('weight')}><NumberInput className={control} value={p.weight*100} min={0} max={100} onValueChange={n=>product(i,{weight:n/100})}/></Field><Field label={t('maximumWeight')}><NumberInput className={control} value={p.max_weight*100} min={0} max={100} onValueChange={n=>product(i,{max_weight:n/100})}/></Field><Field label={t('currentValue')}><NumberInput className={control} value={p.current_value} min={0} onValueChange={n=>product(i,{current_value:n})}/></Field></div>
        {p.kind!=='cash'&&<details><summary className="cursor-pointer py-1 text-sm font-medium text-accent-700">{t('feesAndSettlement')}{p.buy_rate==null||p.sell_rate==null?` · ${t('required')}`:''}</summary>
          <div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
            <Field label={t('buyRate')}><input type="number" min="0" max="20" step="0.001" className={control} value={p.buy_rate==null?'':p.buy_rate*100} onChange={e=>product(i,{buy_rate:e.target.value===''?null:Number(e.target.value)/100,fee_basis:'each_side_notional'})}/></Field>
            <Field label={t('sellRate')}><input type="number" min="0" max="20" step="0.001" className={control} value={p.sell_rate==null?'':p.sell_rate*100} onChange={e=>product(i,{sell_rate:e.target.value===''?null:Number(e.target.value)/100,fee_basis:'each_side_notional'})}/></Field>
            <Field label={t('feeExpiry')}><input type="date" className={control} value={p.fee_valid_until??''} onChange={e=>product(i,{fee_valid_until:e.target.value||null})}/></Field>
            <Field label={t('feeSource')}><input className={control} value={p.fee_source} onChange={e=>product(i,{fee_source:e.target.value})}/></Field>
            <Field label={t('navFees')}><select className={control} value={p.nav_includes_management_fee==null?'':String(p.nav_includes_management_fee)} onChange={e=>product(i,{nav_includes_management_fee:e.target.value===''?null:e.target.value==='true'})}><option value="">{t('unknown')}</option><option value="true">{t('included')}</option><option value="false">{t('notIncluded')}</option></select></Field>
            <Field label={t('sellSettlement')}><input type="date" className={control} value={p.settlement_date??''} onChange={e=>product(i,{settlement_date:e.target.value||null})}/></Field>
            <Field label={t('settlementTerms')}><input className={control} value={p.settlement_terms_source??''} onChange={e=>product(i,{settlement_terms_source:e.target.value})}/></Field>
            {p.kind==='fund'&&<><Field label={t('holdingDays')}><input type="number" min="0" className={control} value={p.holding_days??''} onChange={e=>product(i,{holding_days:e.target.value===''?null:Number(e.target.value)})}/></Field><Field label={t('channel')}><input className={control} value={p.channel} onChange={e=>product(i,{channel:e.target.value})}/></Field></>}
          </div><label className="mt-3 flex items-start gap-2 text-sm leading-6"><input className="mt-1" type="checkbox" checked={p.same_month_settlement_confirmed??false} onChange={e=>product(i,{same_month_settlement_confirmed:e.target.checked})}/>{t('sameMonthSettlement')}</label><p className="mt-2 text-xs leading-5 text-slate-600">{t('feeHelp')}</p></details>}
      </section>)}</div></Card>
      {!candidate.products.some(p=>p.kind==='cash')&&source.assets.some(a=>a.role==='liquidity')&&<Button onClick={()=>patch({products:[...candidate.products,productDefaults('cash','CASH',source.assets.find(a=>a.role==='liquidity')!.id)]})}>{t('addCash')}</Button>}
      <label className="flex items-start gap-2 text-sm leading-6"><input className="mt-1" type="checkbox" checked={candidate.return_basis_confirmed} onChange={e=>patch({return_basis_confirmed:e.target.checked})}/>{t('basisConfirmation')}</label>
      <details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-medium">{t('publishedScenarios')}</summary><p className="mt-3 text-sm leading-6 text-slate-600">{t('scenarioHelp')}</p>
        {catalog.scenario_options?.scenarios.length ? <div className="mt-3 space-y-3"><Field label={t('exposureModel')}><select className={control} value={candidate.scenario_exposure_release_id??''} onChange={e=>patch({scenario_exposure_release_id:e.target.value||null})}><option value="">{t('selectExposure')}</option>{catalog.scenario_options.exposures.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></Field>
          {catalog.scenario_options.scenarios.map(row=><label key={row.id} className="flex items-start gap-2 text-sm leading-6"><input type="checkbox" className="mt-1" checked={candidate.scenario_release_ids.includes(row.id)} disabled={!candidate.scenario_release_ids.includes(row.id)&&candidate.scenario_release_ids.length>=5} onChange={e=>patch({scenario_release_ids:e.target.checked?[...candidate.scenario_release_ids,row.id]:candidate.scenario_release_ids.filter(id=>id!==row.id)})}/>{row.name}</label>)}</div>:<p className="mt-3 text-sm text-slate-600">{t('noScenarios')}</p>}
      </details>
      <Button tone="primary" onClick={()=>setTab('funding')}>{t('nextFunding')}</Button>
    </>:<>
      <p className="text-sm leading-6 text-slate-600">{t('balanceHelp')}</p>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Field label={t('valuationDate')}><input type="date" className={control} value={candidate.state.valuation_at} onChange={e=>state({valuation_at:e.target.value})}/></Field>
        {(['confirmed_investable_value','settled_cash','restricted_cash','receivables','payables'] as const).map(key=><Field key={key} label={t(key)}><NumberInput className={control} min={0} value={candidate.state[key]} onValueChange={n=>state({[key]:n})}/></Field>)}
        <Field label={t('balanceEvidence')}><input className={control} value={candidate.state.evidence} onChange={e=>state({evidence:e.target.value})}/></Field>
        <Field label={t('elapsedMonths')}><NumberInput className={control} min={0} max={source.funding?.months??360} value={candidate.state.elapsed_months} onValueChange={n=>{state({elapsed_months:n,reconciliation:candidate.state.reconciliation.filter(x=>source.funding?.occurrences.some(r=>r.occurrence_id===x.occurrence_id&&r.month<=n))});setFlowPage(0)}}/></Field>
        <Field label={t('futureRule')}><select className={control} value={candidate.future_weight_rule} onChange={e=>patch({future_weight_rule:e.target.value as ImplementationCandidate['future_weight_rule']})}><option value="frozen_scalar_proxy">{t('scalarRule')}</option><option value="buy_and_hold">{t('buyHoldRule')}</option><option value="monthly_rebalance">{t('monthlyRule')}</option></select></Field>
      </div>
      {source.funding&&<p className="text-sm text-slate-600">{t('originalPlan',{origin:source.funding.origin,months:source.funding.months})} · {t('remainingMonths',{count:Math.max(0,source.funding.months-candidate.state.elapsed_months)})}</p>}
      <label className="flex items-start gap-2 text-sm leading-6"><input type="checkbox" className="mt-1" checked={candidate.state.transition_cost_in_balance} onChange={e=>state({transition_cost_in_balance:e.target.checked})}/>{t('costAlreadyIncluded')}</label>
      <div className="grid gap-3 sm:grid-cols-2"><Field label={t('additionalAnnualFee')}><NumberInput className={control} min={0} max={10} value={candidate.annual_additional_fee*100} onValueChange={n=>patch({annual_additional_fee:n/100})}/></Field><Field label={t('annualFeeSource')}><input className={control} value={candidate.annual_fee_source} onChange={e=>patch({annual_fee_source:e.target.value})}/></Field></div>
      <label className="flex items-start gap-2 text-sm leading-6"><input type="checkbox" className="mt-1" checked={candidate.horizon_stationarity_acknowledged} onChange={e=>patch({horizon_stationarity_acknowledged:e.target.checked})}/>{t('stationarityConfirmation')}</label>
      {candidate.future_weight_rule!=='frozen_scalar_proxy'&&<label className="flex items-start gap-2 text-sm leading-6"><input className="mt-1" type="checkbox" checked={candidate.future_fee_assumption==='constant_declared_rates_sensitivity'} onChange={e=>patch({future_fee_assumption:e.target.checked?'constant_declared_rates_sensitivity':'unknown'})}/>{t('futureFeeConfirmation')}</label>}
      {flows.length>0&&<Card><h2 className="text-lg font-semibold">{t('reconciliation')}</h2><p className="mt-2 text-sm text-slate-600">{t('reconciliationHelp')}</p><div className="divide-y divide-slate-200">{flows.slice(flowPage*10,(flowPage+1)*10).map(flow=>{
        const row=candidate.state.reconciliation.find(x=>x.occurrence_id===flow.occurrence_id)??{occurrence_id:flow.occurrence_id,status:'unknown' as const,paid_amount:0,evidence:''}
        const change=(value:Partial<typeof row>)=>state({reconciliation:[...candidate.state.reconciliation.filter(x=>x.occurrence_id!==flow.occurrence_id),{...row,...value}]})
        return <div key={flow.occurrence_id} className="space-y-2 py-3"><h3 className="text-sm font-medium">{flow.due_at} · {flow.name}</h3><p className="text-sm tabular-nums text-slate-600">{t('plannedAmount')}: {amount(flow.nominal_amount??flow.amount,6)}</p><Button onClick={()=>change({paid_amount:flow.nominal_amount??flow.amount})}>{t('fillPlannedAmount')}</Button><div className="grid gap-3 sm:grid-cols-3"><Field label={t('paymentStatus')}><select className={control} value={row.status} onChange={e=>change({status:e.target.value as typeof row.status})}>{['unknown','paid','partial','unpaid'].map(s=><option key={s} value={s}>{t(s)}</option>)}</select></Field><Field label={t('paidAmount')}><NumberInput className={control} min={0} value={row.paid_amount} onValueChange={n=>change({paid_amount:n})}/></Field><Field label={t('paymentEvidence')}><input className={control} value={row.evidence} onChange={e=>change({evidence:e.target.value})}/></Field></div></div>
      })}</div><div className="mt-3 flex flex-wrap gap-2"><Button disabled={flowPage===0} onClick={()=>setFlowPage(n=>n-1)}>{t('previous')}</Button><Button disabled={(flowPage+1)*10>=flows.length} onClick={()=>setFlowPage(n=>n+1)}>{t('next')}</Button><span className="self-center text-sm text-slate-600">{flowPage+1} / {Math.ceil(flows.length/10)}</span></div></Card>}
      <Card><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-semibold">{t('cashCalendar')}</h2><Button onClick={()=>state({cash_events:[...candidate.state.cash_events,{id:operationKey(),date:null,kind:'payment',amount:0,evidence:''}]})}>{t('addCashEvent')}</Button></div><p className="mt-2 text-sm text-slate-600">{t('cashEventHelp')}</p>
        <div className="divide-y divide-slate-200">{candidate.state.cash_events.map((event,i)=>{const update=(value:Partial<typeof event>)=>state({cash_events:candidate.state.cash_events.map((x,j)=>j===i?{...x,...value}:x)});return <div key={event.id} className="grid gap-3 py-3 sm:grid-cols-2 xl:grid-cols-3"><Field label={t('eventDate')}><input type="date" className={control} value={event.date??''} onChange={e=>update({date:e.target.value||null})}/></Field><Field label={t('eventKind')}><select className={control} value={event.kind} onChange={e=>update({kind:e.target.value as typeof event.kind})}><option value="payment">{t('payment')}</option><option value="receipt">{t('receipt')}</option></select></Field><Field label={t('eventAmount')}><NumberInput className={control} min={0} value={event.amount} onValueChange={n=>update({amount:n})}/></Field><Field label={t('paymentEvidence')}><input className={control} value={event.evidence} onChange={e=>update({evidence:e.target.value})}/></Field><Button onClick={()=>state({cash_events:candidate.state.cash_events.filter((_,j)=>i!==j)})}>{t('removeEvent')}</Button></div>})}</div>
      </Card>
      <details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-medium">{t('simulationSettings')}</summary><div className="mt-3 grid gap-3 sm:grid-cols-3">{(['paths','search_seed','validation_seed'] as const).map(key=><Field key={key} label={t(key)}><NumberInput className={control} value={candidate[key]} onValueChange={n=>patch({[key]:n})}/></Field>)}</div></details>
    </>}
  </div>
}
