// Generated by scripts/export_risk_scale_contracts.py. Do not edit.
// Backend/OpenAPI is the only contract source. Decimal values are not display percentages.

export type ActivateRequest = { "confirm": true; "expected_revision": number }
export type Capabilities = { "trust_mode"?: "single_local_trusted_workspace"; "ready": boolean; "execution": Record<string, unknown>; "algorithms": Array<Record<string, unknown>>; "limits": Record<string, unknown>; "reference": Record<string, unknown>; "templates": Array<Record<string, unknown>> }
export type CatalogResponse = { "items": Array<Summary>; "drafts": Array<DraftView>; "total": number; "next_offset": number | null }
export type ClassifyRequest = { "volatility": number | null; "authorized_level"?: number }
export type ClassifyResponse = { "status": string; "level_code": string | null; "cap_satisfied": boolean | null; "authorized_cap": number; "flags": Array<string> }
export type CompareRequest = { "left_id": string; "right_id": string }
export type CompareResponse = { "compatible": boolean; "left": VersionView; "right": VersionView; "boundary_differences": Array<number> | null; "differences": Array<string> }
export type ConfirmReferenceInput = { "confirm": true; "request": ReferenceInputRequest; "preview_hash": string; "idempotency_key": string; "acknowledged_warnings"?: Array<string> }
export type ConfirmRequest = { "confirm": true; "request": PreviewRequest; "preview_hash": string; "idempotency_key": string; "acknowledged_warnings"?: Array<string> }
export type ConstraintProfile = { "asset_limits"?: Record<string, RiskScaleAssetLimit>; "group_limits"?: Array<GroupLimit>; "allow_short"?: false; "allow_leverage"?: false; "gross_exposure"?: 1 }
export type DefaultBinding = { "key": string; "revision": number; "version_id"?: string | null; "content_hash"?: string | null; "eligibility"?: Eligibility | null }
export type DefaultsResponse = { "items": Array<DefaultBinding> }
export type DeleteResponse = { "deleted": true; "id": string }
export type DraftUpdate = { "name": string; "scheme_id": string; "editable_definition"?: Record<string, unknown>; "expected_revision": number }
export type DraftView = { "name": string; "scheme_id": string; "editable_definition"?: Record<string, unknown>; "id": string; "revision": number; "created_at": string; "updated_at": string }
export type DraftWrite = { "name": string; "scheme_id": string; "editable_definition"?: Record<string, unknown> }
export type Eligibility = { "eligible": boolean; "blockers"?: Array<Problem> }
export type ErrorResponse = { "detail": Problem }
export type ExplicitConfirm = { "confirm": true }
export type FrontierPoint = { "node_id": number; "expected_return": number | null; "volatility": number | null; "weights": Array<number> | null; "status": string }
export type FrozenRef = { "id": string; "content_hash": string }
export type GroupLimit = { "id": string; "assets": Array<string>; "lo"?: number; "hi"?: number }
export type Level = { "level_code": "C1" | "C2" | "C3" | "C4" | "C5"; "lower_bound": number; "lower_inclusive": boolean; "upper_bound": number; "upper_inclusive"?: true; "authorized_volatility_cap": number; "calibration_status": string; "representative_node_id": number | null; "representative_weights": Array<number> | null; "expected_return": Metric; "volatility": Metric; "historical_es": Metric; "historical_mdd": Metric }
export type Metric = { "value"?: number | null; "status": string; "reason"?: string | null; "unit"?: string }
export type PreviewRequest = { "definition": RiskScaleDefinition; "draft_id"?: string | null; "draft_revision"?: number | null }
export type PreviewResponse = { "request_echo": PreviewRequest; "resolved_refs": Record<string, FrozenRef>; "data_fingerprints": Record<string, string>; "result": ScaleResult; "mathematical_status": string; "publication_eligibility": Eligibility; "default_eligibility": Eligibility; "warnings": Array<Problem>; "limitations": Array<string>; "execution_audit": Record<string, unknown>; "preview_hash": string }
export type Problem = { "code": string; "message": string; "field"?: string | null; "suggested_action"?: string }
export type ProxyComponent = { "kind": "index" | "etf" | "fund"; "series_id": string; "field": "close" | "close_hfq" | "adj_nav"; "weight": number }
export type ReferenceAsset = { "id": string; "name": string; "asset_type": "cash" | "market"; "rationale"?: string; "cash_return": number | null; "components": Array<ProxyComponent>; "rebalance": "daily" | "monthly" | "quarterly" | "yearly" | "buy_and_hold" | null }
export type ReferenceInputRequest = { "name": string; "currency"?: "CNY"; "as_of": string; "calendar"?: "SSE"; "frequency"?: "daily"; "periods_per_year"?: 252; "return_basis"?: "selected_index_and_adjusted_product_total_return"; "fee_basis"?: "source_embedded_no_additional_fee"; "fx_basis"?: "same_currency_no_conversion"; "assets": Array<ReferenceAsset> }
export type ReferencePreview = { "preview_hash": string; "definition": Record<string, unknown>; "ordered_asset_ids": Array<string>; "quality": Record<string, unknown>; "warnings": Array<Problem>; "moments"?: Record<string, unknown> | null; "provenance": Record<string, unknown> }
export type ReferenceVersion = { "preview_hash": string; "definition": Record<string, unknown>; "ordered_asset_ids": Array<string>; "quality": Record<string, unknown>; "warnings": Array<Problem>; "moments"?: Record<string, unknown> | null; "provenance": Record<string, unknown>; "id": string; "content_hash": string; "created_at": string; "artifact_type": string; "immutable"?: true }
export type RetireRequest = { "confirm": true; "expected_revision": number; "reason": string; "clear_default"?: boolean; "replacement_id"?: string | null }
export type RevisionRequest = { "expected_revision": number }
export type RiskScaleAssetLimit = { "min_weight"?: number; "max_weight"?: number }
export type RiskScaleDefinition = { "name": string; "description"?: string; "scheme_id": string; "base_currency"?: "CNY" | "USD" | "HKD"; "risk_basis_id"?: "annualized-periodic-volatility-v1"; "research_as_of": string; "review_due_at"?: string | null; "valid_until"?: string | null; "reference_input_ref": FrozenRef; "constraint_profile"?: ConstraintProfile; "segmentation"?: Segmentation; "purpose"?: string }
export type ScaleResult = { "parameter_evidence"?: Record<string, unknown>; "ordered_asset_ids": Array<string>; "frontier": Array<FrontierPoint>; "levels": Array<Level>; "applied_boundaries": Array<number>; "algorithm_id": "frontier_shape_dp_v2" | "equal_volatility_v1" | "equal_arclength_v1" | "equal_return_v1" | "manual_volatility_bands_v1"; "algorithm_version": string; "fallback_reason"?: string | null; "stability"?: Record<string, unknown>; "diagnostics"?: Record<string, unknown> }
export type Segmentation = { "algorithm_id"?: "frontier_shape_dp_v2" | "equal_volatility_v1" | "equal_arclength_v1" | "equal_return_v1" | "manual_volatility_bands_v1"; "manual_caps"?: Array<number> | null; "adjusted_caps"?: Array<number> | null; "rationale"?: string }
export type SourceCatalog = { "items": Array<Record<string, unknown>>; "total": number; "offset": number; "limit": number; "problems"?: Array<Problem> }
export type StudyOption = { "id": string; "name": string; "content_hash": string; "version_number": number; "base_currency": string; "risk_basis_id": "annualized-periodic-volatility-v1"; "research_as_of": string; "valid_until"?: string | null }
export type StudyOptionsResponse = { "as_of": string; "items": Array<StudyOption> }
export type Summary = { "id": string; "name": string; "content_hash": string; "created_at": string; "artifact_type": string; "scheme_id"?: string | null; "version_number"?: number | null; "base_currency"?: string | null; "risk_basis_id"?: string | null; "method"?: string | null; "review_due_at"?: string | null; "review_status"?: "none" | "scheduled" | "upcoming" | "due" | null }
export type VersionView = { "id": string; "name": string; "artifact_type"?: "risk_scale"; "content_hash": string; "scheme_id": string; "version_number": number; "created_at": string; "immutable"?: true; "preview": PreviewResponse; "current_eligibility": Eligibility; "current_default_eligibility": Eligibility; "retired": boolean; "review_due_at"?: string | null; "review_status"?: "none" | "scheduled" | "upcoming" | "due" }

export const riskScaleAlgorithmIds = ["frontier_shape_dp_v2", "equal_volatility_v1", "equal_arclength_v1", "equal_return_v1", "manual_volatility_bands_v1"] as const
export type RiskScaleAlgorithmId = typeof riskScaleAlgorithmIds[number]
export function isRiskScaleAlgorithmId(value: unknown): value is RiskScaleAlgorithmId {
  return typeof value === "string" && riskScaleAlgorithmIds.some(id => id === value)
}
