import { researchMessage } from '../../i18n/researchMessages'
import { systemText, useI18n } from '../../i18n/runtime'
import CrossModelResults from '../strategic-allocation/CrossModelResults'
import { useMemo } from 'react'
import ReactECharts from 'echarts-for-react'
import type { TaaPreview, TaaScenarioResult } from '../../services/tacticalAllocation'
import { buttonClass, numberText, percentText, sectionClass } from '../risk-models/ResearchUI'

export function TaaPerformance({ result, busy, onSelect }: { result: TaaPreview; busy: boolean; onSelect: (id: string) => void }) {
  const { version: i18nVersion } = useI18n()
  const selected = result.candidates.find(item => item.id === result.selected_id)
  const option = useMemo(() => ({
    animation: false,
    aria: { enabled: true, description: systemText('preInvestment.taaResults.saaAndTacticalNavAfterCostsTraining') },
    tooltip: { trigger: 'axis' },
    legend: { data: [systemText('preInvestment.taaResults.saaBaseline'), systemText('preInvestment.taaResults.tacticalPlan')], top: 0 },
    grid: { left: 52, right: 24, top: 48, bottom: 35 },
    xAxis: { type: 'category', boundaryGap: false, data: result.chart.map(item => item.date) },
    yAxis: { type: 'value', scale: true },
    series: (['train', 'validation'] as const).flatMap(segment => [
      { id: `baseline-${segment}`, name: systemText('preInvestment.taaResults.saaBaseline'), type: 'line', showSymbol: false, connectNulls: false, data: result.chart.map(item => item.segment === segment ? item.baseline : null), itemStyle: { color: '#64748b' } },
      { id: `taa-${segment}`, name: systemText('preInvestment.taaResults.tacticalPlan'), type: 'line', showSymbol: false, connectNulls: false, data: result.chart.map(item => item.segment === segment ? item.taa : null), itemStyle: { color: '#0f766e' }, ...(segment === 'train' ? { markLine: { silent: true, symbol: 'none', data: [{ xAxis: result.chart.filter(item => item.segment === 'train').slice(-1)[0]?.date ?? result.request.train_end_date, label: { formatter: systemText('preInvestment.taaResults.trainingEnd'), position: 'insideEndTop' } }] } } : {}) },
    ]),
  }), [result, i18nVersion])
  return <section className={`${sectionClass} space-y-5`} aria-label={systemText('preInvestment.taaResults.saaAndTacticalPlanComparison')}>
    <div><h2 className="text-lg font-semibold text-slate-950">{systemText('preInvestment.taaResults.isThisDeviationWorthwhile')}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{result.data.start_date} — {result.data.end_date} {" " + systemText('preInvestment.taaResults.training') + " "}{result.data.train_observations} {" " + systemText('preInvestment.taaResults.periodsIndependentValidation') + " "}{result.data.validation_observations} {" " + systemText('preInvestment.taaResults.periodsCandidatesAreSelectedOnTrainingData')}</p></div>
    {selected && <div className="grid grid-cols-2 gap-4 lg:grid-cols-3">{[
      [systemText('preInvestment.taaResults.validationTacticalNetReturn'), percentText(selected.validation.total_return)],
      [systemText('preInvestment.taaResults.validationSaaNetReturn'), percentText(selected.validation.baseline_return)],
      [systemText('preInvestment.taaResults.validationRelativeNetExcessReturn'), percentText(selected.validation.excess_return)],
      [systemText('preInvestment.taaResults.validationMaximumDrawdown'), percentText(selected.validation.max_drawdown)],
      [systemText('preInvestment.taaResults.validationActiveRisk'), percentText(selected.validation.tracking_error)],
      [systemText('preInvestment.taaResults.validationTransactionCosts'), percentText(selected.validation.cost)],
    ].map(([label, value]) => <div key={label} className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-600">{label}</p><p className="mt-2 text-xl font-semibold tabular-nums text-slate-950">{value}</p></div>)}</div>}
    {selected?.holding_budget_breaches && <p role="status" className="text-sm text-amber-800">{systemText('preInvestment.taaResults.actualHoldingBudgetBreachesTraining') + " "}{selected.holding_budget_breaches.train} {" " + systemText('preInvestment.taaResults.periodsValidation') + " "}{selected.holding_budget_breaches.validation} {" " + systemText('preInvestment.taaResults.periodsCheckPreTradeAndPeriodEnd')}</p>}
    {selected && <p className="text-xs leading-5 text-slate-600">{systemText('preInvestment.taaResults.validationTacticalAnnualVolatility')}{percentText(selected.validation.annual_volatility)} {" " + systemText('preInvestment.taaResults.cumulativeTurnover')}{percentText(selected.validation.turnover)}。</p>}
    {result.policy_check && <div role="status" className={`rounded-lg p-3 text-xs leading-5 ${result.policy_check.within_limits ? 'bg-slate-50 text-slate-700' : 'bg-rose-50 text-rose-900'}`}><strong>{systemText('preInvestment.taaResults.forwardLookingPolicyRiskChecks')}</strong>{systemText('preInvestment.taaResults.targetPortfolioExpectedVolatility') + " "}{percentText(result.policy_check.expected_volatility)} {" " + systemText('preInvestment.taaResults.policyLimit') + " "}{percentText(result.policy_check.max_volatility)}{systemText('preInvestment.taaResults.forwardLookingActiveRiskRelativeToSaa') + " "}{percentText(result.policy_check.expected_tracking_error)} {" " + systemText('preInvestment.taaResults.currentLimit') + " "}{percentText(result.policy_check.requested_tracking_error_limit)} {" " + systemText('preInvestment.taaResults.policyLimit') + " "}{percentText(result.policy_check.max_tracking_error)}。{result.policy_check.within_limits ? systemText('preInvestment.taaResults.researchDateRiskChecksPassed') : result.policy_check.violations.map(researchMessage).join('; ')}{result.policy_check.current_application_eligible === false && " " + systemText('preInvestment.taaResults.thePolicyIsPastReviewOrCurrently')}{result.policy_check.benchmark_check && systemText('preInvestment.taaResults.activeRiskRelativeToAuthorizedBenchmarkIs', { p0: result.policy_check.benchmark_check.name, p1: percentText(result.policy_check.benchmark_check.tracking_error), p2: percentText(result.policy_check.benchmark_check.max_tracking_error) })}</div>}
    {result.policy_check?.cross_model_results && <CrossModelResults common={result.policy_check.risk_evaluation_mode === 'compatible_all_models'} rows={result.policy_check.cross_model_results} />}
    {result.policy_check?.goal_diagnostic_scope && <p className="text-xs leading-5 text-amber-800">{systemText('preInvestment.taaResults.fundingSuccessProbabilityWasCalculatedWhenSaa')}</p>}
    <p className="text-xs text-slate-600">{systemText('preInvestment.taaResults.trainingAndValidationEachStartAt1')}</p><ReactECharts option={option} style={{ height: 300, width: '100%' }} notMerge />
    <div className="space-y-3 md:hidden"><h3 className="text-sm font-semibold">{systemText('preInvestment.taaResults.candidateComparison')}</h3>{result.candidates.map(item => <article key={item.id} className={`rounded-lg border p-3 ${item.id === result.selected_id ? 'border-accent-300 bg-accent-50/50' : 'border-slate-200'}`}><div className="flex justify-between gap-2"><h4 className="text-sm font-semibold">{item.strength === 0 ? systemText('preInvestment.taaResults.keepSaa') : systemText('preInvestment.taaResults.deviation', { p0: numberText(item.strength, 2) })}</h4><span className="text-xs text-accent-800">{item.id === result.selected_id ? systemText('preInvestment.taaResults.selected') : ''}</span></div><dl className="mt-3 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-600">{systemText('preInvestment.taaResults.trainingNetExcessReturn')}</dt><dd className="mt-1 tabular-nums">{percentText(item.train.excess_return)}</dd></div><div><dt className="text-slate-600">{systemText('preInvestment.taaResults.validationNetExcessReturn')}</dt><dd className="mt-1 tabular-nums">{percentText(item.validation.excess_return)}</dd></div><div><dt className="text-slate-600">{systemText('preInvestment.taaResults.validationDrawdown')}</dt><dd className="mt-1 tabular-nums">{percentText(item.validation.max_drawdown)}</dd></div><div><dt className="text-slate-600">{systemText('preInvestment.taaResults.validationTurnover')}</dt><dd className="mt-1 tabular-nums">{percentText(item.validation.turnover)}</dd></div></dl>{!item.feasible ? <p className="mt-3 text-xs text-amber-800">{systemText('preInvestment.taaResults.constraintBreach')}</p> : item.id !== result.selected_id ? <button type="button" className={`${buttonClass} mt-3 w-full`} disabled={busy} onClick={() => onSelect(item.id)} aria-label={systemText('preInvestment.taaResults.select', { p0: item.strength === 0 ? systemText('preInvestment.taaResults.keepSaa') : systemText('preInvestment.taaResults.deviation', { p0: item.strength }) })}>{systemText('preInvestment.taaResults.adoptAndReview')}</button> : item.validation_feasible === false ? <p className="mt-3 text-xs text-amber-800">{systemText('preInvestment.taaResults.validationLimitBreachedReviewRequired')}</p> : null}</article>)}</div>
    <div className="hidden overflow-auto md:block"><table className="w-full min-w-[740px] text-sm"><caption className="mb-3 text-left font-semibold text-slate-900">{systemText('preInvestment.taaResults.candidateComparisonKeepingSaaIsAlsoAn')}</caption><thead className="bg-slate-50 text-xs text-slate-600"><tr><th scope="col" className="p-3 text-left">{systemText('preInvestment.taaResults.deviationStrength')}</th><th scope="col" className="p-3 text-right">{systemText('preInvestment.taaResults.trainingNetExcessReturn')}</th><th scope="col" className="p-3 text-right">{systemText('preInvestment.taaResults.trainingScore')}</th><th scope="col" className="p-3 text-right">{systemText('preInvestment.taaResults.validationNetExcessReturn')}</th><th scope="col" className="p-3 text-right">{systemText('preInvestment.taaResults.validationDrawdown')}</th><th scope="col" className="p-3 text-right">{systemText('preInvestment.taaResults.validationTurnover')}</th><th scope="col" className="p-3 text-left">{systemText('preInvestment.taaResults.actions')}</th></tr></thead><tbody className="divide-y divide-slate-100">{result.candidates.map(item => <tr key={item.id} className={item.id === result.selected_id ? 'bg-accent-50/60' : ''}><th scope="row" className="p-3 text-left font-medium">{item.strength === 0 ? systemText('preInvestment.taaResults.keepSaa') : systemText('preInvestment.taaResults.text', { p0: numberText(item.strength, 2) })}{item.id === result.selected_id && <span className="ml-2 text-xs text-accent-800">{systemText('preInvestment.taaResults.selected')}</span>}</th><td className="p-3 text-right tabular-nums">{percentText(item.train.excess_return)}</td><td className="p-3 text-right tabular-nums">{numberText(item.train.score, 4)}</td><td className="p-3 text-right tabular-nums">{percentText(item.validation.excess_return)}</td><td className="p-3 text-right tabular-nums">{percentText(item.validation.max_drawdown)}</td><td className="p-3 text-right tabular-nums">{percentText(item.validation.turnover)}</td><td className="p-3">{!item.feasible ? <span className="text-xs text-amber-800">{systemText('preInvestment.taaResults.constraintBreach')}</span> : item.id !== result.selected_id ? <button type="button" className={buttonClass} disabled={busy} onClick={() => onSelect(item.id)} aria-label={systemText('preInvestment.taaResults.select', { p0: item.strength === 0 ? systemText('preInvestment.taaResults.keepSaa') : systemText('preInvestment.taaResults.deviation', { p0: item.strength }) })}>{systemText('preInvestment.taaResults.adoptAndReview')}</button> : <span className={`text-xs ${item.validation_feasible === false ? 'text-amber-800' : 'text-accent-800'}`}>{item.validation_feasible === false ? systemText('preInvestment.taaResults.validationLimitBreachedReviewRequired') : systemText('preInvestment.taaResults.currentCandidate')}</span>}</td></tr>)}</tbody></table></div>
    <p className="text-xs leading-5 text-slate-600">{systemText('preInvestment.taaResults.relativeNetExcessReturnTacticalTerminalNav')}</p>
  </section>
}

const differenceText = (value: number) => systemText('preInvestment.taaResults.percentagePoints', { p0: value > 0 ? '+' : '', p1: (value * 100).toFixed(2) })

export function TaaScenarioView({ result, names }: { result: TaaScenarioResult; names: Record<string, string> }) {
  useI18n()
  return <section className={`${sectionClass} space-y-4`} aria-label={systemText('preInvestment.taaResults.scenarioSimulationResults')}><h3 className="text-lg font-semibold">{result.name}</h3><div className="grid gap-4 sm:grid-cols-3">{[[systemText('preInvestment.taaResults.saaImpact'), result.baseline_return], [systemText('preInvestment.taaResults.tacticalPlanImpact'), result.taa_return], [systemText('preInvestment.taaResults.returnDifferenceTaaSaa'), result.excess_return]].map(([label, value]) => <div key={String(label)} className="rounded-lg bg-slate-50 p-4"><p className="text-xs text-slate-600">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{label === systemText('preInvestment.taaResults.returnDifferenceTaaSaa') ? differenceText(value as number) : percentText(value as number)}</p></div>)}</div><div className="overflow-auto"><table className="w-full text-sm"><caption className="mb-2 text-left font-medium">{systemText('preInvestment.taaResults.reconcileAssetContributionsCostsAndNetReturns')}</caption><thead className="text-left text-xs text-slate-600"><tr><th scope="col" className="p-2">{systemText('preInvestment.taaResults.asset')}</th><th scope="col" className="p-2 text-right">{systemText('preInvestment.taaResults.saaContribution')}</th><th scope="col" className="p-2 text-right">{systemText('preInvestment.taaResults.tacticalContribution')}</th><th scope="col" className="p-2 text-right">{systemText('preInvestment.taaResults.difference')}</th></tr></thead><tbody className="divide-y divide-slate-100">{result.contributions.map(item => <tr key={item.asset_id}><td className="p-2">{names[item.asset_id] ?? item.asset_id}</td><td className="p-2 text-right tabular-nums">{percentText(item.baseline)}</td><td className="p-2 text-right tabular-nums">{percentText(item.taa)}</td><td className="p-2 text-right tabular-nums">{differenceText(item.excess)}</td></tr>)}{result.cost && <tr className="border-t border-slate-200"><th scope="row" className="p-2 text-left font-medium">{systemText('preInvestment.taaResults.transactionCostsDeducted')}</th><td className="p-2 text-right">{percentText(-result.cost.baseline)}</td><td className="p-2 text-right">{percentText(-result.cost.taa)}</td><td className="p-2 text-right">{differenceText(result.cost.baseline - result.cost.taa)}</td></tr>}<tr className="border-t border-slate-200 font-semibold"><th scope="row" className="p-2 text-left">{systemText('preInvestment.taaResults.totalNetReturnAfterCosts')}</th><td className="p-2 text-right">{percentText(result.baseline_return)}</td><td className="p-2 text-right">{percentText(result.taa_return)}</td><td className="p-2 text-right">{differenceText(result.excess_return)}</td></tr></tbody></table></div><p className="text-xs text-slate-600">{systemText('preInvestment.taaResults.scenarioReturnDifferenceIsTaaMinusSaa')}</p>{result.warnings.map(item => <p key={item} className="text-xs leading-5 text-amber-800">{item}</p>)}</section>
}
