import { useMemo } from 'react'
import ReactECharts from 'echarts-for-react'
import type { TaaPreview, TaaScenarioResult } from '../../services/tacticalAllocation'
import { buttonClass, numberText, percentText, sectionClass } from '../risk-models/ResearchUI'

export function TaaPerformance({ result, busy, onSelect }: { result: TaaPreview; busy: boolean; onSelect: (id: string) => void }) {
  const selected = result.candidates.find(item => item.id === result.selected_id)
  const option = useMemo(() => ({
    animation: false,
    aria: { enabled: true, description: 'SAA 与战术方案的扣费净值；训练与验证分别从1开始，两段不连接。' },
    tooltip: { trigger: 'axis' },
    legend: { data: ['SAA 基准', '战术方案'], top: 0 },
    grid: { left: 52, right: 24, top: 48, bottom: 35 },
    xAxis: { type: 'category', boundaryGap: false, data: result.chart.map(item => item.date) },
    yAxis: { type: 'value', scale: true },
    series: (['train', 'validation'] as const).flatMap(segment => [
      { id: `baseline-${segment}`, name: 'SAA 基准', type: 'line', showSymbol: false, connectNulls: false, data: result.chart.map(item => item.segment === segment ? item.baseline : null), itemStyle: { color: '#64748b' } },
      { id: `taa-${segment}`, name: '战术方案', type: 'line', showSymbol: false, connectNulls: false, data: result.chart.map(item => item.segment === segment ? item.taa : null), itemStyle: { color: '#0f766e' }, ...(segment === 'train' ? { markLine: { silent: true, symbol: 'none', data: [{ xAxis: result.chart.filter(item => item.segment === 'train').slice(-1)[0]?.date ?? result.request.train_end_date, label: { formatter: '训练结束', position: 'insideEndTop' } }] } } : {}) },
    ]),
  }), [result])
  return <section className={`${sectionClass} space-y-5`} aria-label="SAA 与战术方案对照">
    <div><h2 className="text-lg font-semibold text-slate-950">这次偏离值得吗？</h2><p className="mt-1 text-sm leading-6 text-slate-600">{result.data.start_date} — {result.data.end_date} · 训练 {result.data.train_observations} 期，独立验证 {result.data.validation_observations} 期。候选只按训练数据选优，验证结果不参与排名。</p></div>
    {selected && <div className="grid grid-cols-2 gap-4 lg:grid-cols-3">{[
      ['验证期战术净收益', percentText(selected.validation.total_return)],
      ['验证期 SAA 净收益', percentText(selected.validation.baseline_return)],
      ['验证期相对净超额', percentText(selected.validation.excess_return)],
      ['验证期最大回撤', percentText(selected.validation.max_drawdown)],
      ['验证期主动风险', percentText(selected.validation.tracking_error)],
      ['验证期交易成本', percentText(selected.validation.cost)],
    ].map(([label, value]) => <div key={label} className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-600">{label}</p><p className="mt-2 text-xl font-semibold tabular-nums text-slate-950">{value}</p></div>)}</div>}
    {selected && <p className="text-xs leading-5 text-slate-600">验证期战术方案年化波动：{percentText(selected.validation.annual_volatility)} · 累计换手：{percentText(selected.validation.turnover)}。</p>}
    <p className="text-xs text-slate-600">训练与验证分别以 1 为起点；两段独立展示，不连接成一条持续投资净值。</p><ReactECharts option={option} style={{ height: 300, width: '100%' }} notMerge />
    <div className="space-y-3 md:hidden"><h3 className="text-sm font-semibold">候选对照</h3>{result.candidates.map(item => <article key={item.id} className={`rounded-lg border p-3 ${item.id === result.selected_id ? 'border-accent-300 bg-accent-50/50' : 'border-slate-200'}`}><div className="flex justify-between gap-2"><h4 className="text-sm font-semibold">{item.strength === 0 ? '保持 SAA' : `${numberText(item.strength, 2)} 倍偏离`}</h4><span className="text-xs text-accent-800">{item.id === result.selected_id ? '已选择' : ''}</span></div><dl className="mt-3 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-600">训练净超额</dt><dd className="mt-1 tabular-nums">{percentText(item.train.excess_return)}</dd></div><div><dt className="text-slate-600">验证净超额</dt><dd className="mt-1 tabular-nums">{percentText(item.validation.excess_return)}</dd></div><div><dt className="text-slate-600">验证回撤</dt><dd className="mt-1 tabular-nums">{percentText(item.validation.max_drawdown)}</dd></div><div><dt className="text-slate-600">验证换手</dt><dd className="mt-1 tabular-nums">{percentText(item.validation.turnover)}</dd></div></dl>{!item.feasible ? <p className="mt-3 text-xs text-amber-800">超出约束</p> : item.id !== result.selected_id ? <button type="button" className={`${buttonClass} mt-3 w-full`} disabled={busy} onClick={() => onSelect(item.id)} aria-label={`选择${item.strength === 0 ? '保持 SAA' : `${item.strength} 倍偏离`}`}>采用并复核</button> : item.validation_feasible === false ? <p className="mt-3 text-xs text-amber-800">验证超限 · 需复核</p> : null}</article>)}</div>
    <div className="hidden overflow-auto md:block"><table className="w-full min-w-[740px] text-sm"><caption className="mb-3 text-left font-semibold text-slate-900">候选对照：保持 SAA 也是一个方案</caption><thead className="bg-slate-50 text-xs text-slate-600"><tr><th scope="col" className="p-3 text-left">偏离强度</th><th scope="col" className="p-3 text-right">训练净超额</th><th scope="col" className="p-3 text-right">训练评分</th><th scope="col" className="p-3 text-right">验证净超额</th><th scope="col" className="p-3 text-right">验证回撤</th><th scope="col" className="p-3 text-right">验证换手</th><th scope="col" className="p-3 text-left">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{result.candidates.map(item => <tr key={item.id} className={item.id === result.selected_id ? 'bg-accent-50/60' : ''}><th scope="row" className="p-3 text-left font-medium">{item.strength === 0 ? '保持 SAA' : `${numberText(item.strength, 2)} 倍`}{item.id === result.selected_id && <span className="ml-2 text-xs text-accent-800">已选择</span>}</th><td className="p-3 text-right tabular-nums">{percentText(item.train.excess_return)}</td><td className="p-3 text-right tabular-nums">{numberText(item.train.score, 4)}</td><td className="p-3 text-right tabular-nums">{percentText(item.validation.excess_return)}</td><td className="p-3 text-right tabular-nums">{percentText(item.validation.max_drawdown)}</td><td className="p-3 text-right tabular-nums">{percentText(item.validation.turnover)}</td><td className="p-3">{!item.feasible ? <span className="text-xs text-amber-800">超出约束</span> : item.id !== result.selected_id ? <button type="button" className={buttonClass} disabled={busy} onClick={() => onSelect(item.id)} aria-label={`选择${item.strength === 0 ? '保持 SAA' : `${item.strength} 倍偏离`}`}>采用并复核</button> : <span className={`text-xs ${item.validation_feasible === false ? 'text-amber-800' : 'text-accent-800'}`}>{item.validation_feasible === false ? '验证超限 · 需复核' : '当前候选'}</span>}</td></tr>)}</tbody></table></div>
    <p className="text-xs leading-5 text-slate-600">相对净超额 = 战术方案期末净值 ÷ SAA 期末净值 − 1。强度只在本次候选集合内比较；验证区间不是重新调参的训练集，也不能证明未来最优。</p>
  </section>
}

const differenceText = (value: number) => `${value > 0 ? '+' : ''}${(value * 100).toFixed(2)} 个百分点`

export function TaaScenarioView({ result, names }: { result: TaaScenarioResult; names: Record<string, string> }) {
  return <section className={`${sectionClass} space-y-4`} aria-label="情景模拟结果"><h3 className="text-lg font-semibold">{result.name}</h3><div className="grid gap-4 sm:grid-cols-3">{[['SAA 影响', result.baseline_return], ['战术方案影响', result.taa_return], ['收益差（TAA − SAA）', result.excess_return]].map(([label, value]) => <div key={String(label)} className="rounded-lg bg-slate-50 p-4"><p className="text-xs text-slate-600">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{label === '收益差（TAA − SAA）' ? differenceText(value as number) : percentText(value as number)}</p></div>)}</div><div className="overflow-auto"><table className="w-full text-sm"><caption className="mb-2 text-left font-medium">资产贡献、成本与净收益对账</caption><thead className="text-left text-xs text-slate-600"><tr><th scope="col" className="p-2">资产</th><th scope="col" className="p-2 text-right">SAA 贡献</th><th scope="col" className="p-2 text-right">战术贡献</th><th scope="col" className="p-2 text-right">差异</th></tr></thead><tbody className="divide-y divide-slate-100">{result.contributions.map(item => <tr key={item.asset_id}><td className="p-2">{names[item.asset_id] ?? item.asset_id}</td><td className="p-2 text-right tabular-nums">{percentText(item.baseline)}</td><td className="p-2 text-right tabular-nums">{percentText(item.taa)}</td><td className="p-2 text-right tabular-nums">{differenceText(item.excess)}</td></tr>)}{result.cost && <tr className="border-t border-slate-200"><th scope="row" className="p-2 text-left font-medium">交易费用（扣除）</th><td className="p-2 text-right">{percentText(-result.cost.baseline)}</td><td className="p-2 text-right">{percentText(-result.cost.taa)}</td><td className="p-2 text-right">{differenceText(result.cost.baseline - result.cost.taa)}</td></tr>}<tr className="border-t border-slate-200 font-semibold"><th scope="row" className="p-2 text-left">扣费净收益合计</th><td className="p-2 text-right">{percentText(result.baseline_return)}</td><td className="p-2 text-right">{percentText(result.taa_return)}</td><td className="p-2 text-right">{differenceText(result.excess_return)}</td></tr></tbody></table></div><p className="text-xs text-slate-600">情景收益差为 TAA 减去 SAA 的百分点差，资产贡献扣除交易费用后与净收益对账。</p>{result.warnings.map(item => <p key={item} className="text-xs leading-5 text-amber-800">{item}</p>)}</section>
}
