import { systemText, useI18n } from '../../i18n/runtime'
import { useEffect, useRef, useState } from 'react'
import { useAllocationDraft } from '../../app/allocationJourney'
import { simulateTaaScenario, type TaaPreview, type TaaScenario, type TaaScenarioExperiment } from '../../services/tacticalAllocation'
import { buttonClass, Empty, Feedback, Field, inputClass, NumberInput, percentText, primaryClass, sectionClass } from '../risk-models/ResearchUI'
import { PortfolioRiskSection } from '../risk-models/PublishedRiskPanel'
import { TaaScenarioView } from './TaaResults'

const points = (value: number) => systemText('preInvestment.taaScenarioExperiments.percentagePoints', { p0: value > 0 ? '+' : '', p1: (value * 100).toFixed(2) })
export default function TaaScenarioExperiments({ preview, baselineId, experiments, onChange, onBacktest }: {
  preview: TaaPreview | null; baselineId: string; experiments: TaaScenarioExperiment[]
  onChange: (value: TaaScenarioExperiment[]) => void; onBacktest: () => void
}) {
  useI18n()
  const [draft, setDraft] = useAllocationDraft<TaaScenario>(`taa-scenario:${baselineId}`, { kind: 'shock', name: systemText('preInvestment.taaScenarioExperiments.customAssetShocks'), shocks: {} })
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [selected, setSelected] = useState<string | null>(null)
  const sequence = useRef(0)
  useEffect(() => { sequence.current += 1; setBusy(false); setError(''); return () => { sequence.current += 1 } }, [preview?.preview_hash])
  const names = Object.fromEntries((preview?.baseline.assets ?? []).map(asset => [asset.id, asset.name]))
  const range = preview ? { start: preview.data.start_date, end: [preview.data.end_date, preview.request.as_of].sort()[0] } : null
  const invalidHistory = draft.kind === 'historical' && (!range || !draft.start_date || !draft.end_date || draft.start_date < range.start || draft.end_date > range.end || draft.start_date >= draft.end_date)
  const active = experiments.find(item => item.scenario.name === selected)
  function update(patch: Partial<TaaScenario>) { sequence.current += 1; setBusy(false); setError(''); setDraft(previous => ({ ...previous, ...patch })) }
  function chooseKind(kind: TaaScenario['kind']) {
    update(kind === 'historical' ? { kind, name: systemText('preInvestment.taaScenarioExperiments.historicalPeriodReplay'), start_date: range?.start, end_date: range?.end } : { kind, name: systemText('preInvestment.taaScenarioExperiments.customAssetShocks'), shocks: Object.fromEntries(Object.keys(names).map(id => [id, 0])) })
  }
  async function run(scenario: TaaScenario) {
    if (!preview || busy) return
    const normalized = { ...scenario, name: scenario.name.trim(), ...(scenario.kind === 'shock' ? { shocks: Object.fromEntries(Object.keys(names).map(id => [id, scenario.shocks?.[id] ?? 0])) } : {}) }
    if (!normalized.name) { setError(systemText('preInvestment.taaScenarioExperiments.enterAScenarioName')); return }
    if (experiments.length >= 12 && !experiments.some(item => item.scenario.name === normalized.name)) { setError(systemText('preInvestment.taaScenarioExperiments.eachStudySupportsUpTo12Scenarios')); return }
    const token = ++sequence.current; setBusy(true); setError('')
    try {
      const result = await simulateTaaScenario({ preview_request: preview.request, candidate_id: preview.selected_id, scenario: normalized })
      if (token !== sequence.current) return
      onChange([...experiments.filter(item => item.scenario.name !== normalized.name), { scenario: normalized, result }]); setSelected(normalized.name)
    } catch (failure) { if (token === sequence.current) setError(failure instanceof Error ? failure.message : systemText('preInvestment.taaScenarioExperiments.scenarioSimulationDidNotComplete')) }
    finally { if (token === sequence.current) setBusy(false) }
  }
  return <div className="min-w-0 space-y-4">
    <section className={`${sectionClass} space-y-4`}><h2 className="text-lg font-semibold">{systemText('preInvestment.taaScenarioExperiments.whatIfMarketsDoNotBehaveAs')}</h2><p className="text-sm leading-6 text-slate-600">{systemText('preInvestment.taaScenarioExperiments.compareMultipleNamedExperimentsCompletedExperimentsAre')}</p><Feedback error={error} />
      <p className="text-sm leading-6 text-amber-800">{systemText('preInvestment.taaScenarioExperiments.appliesCurrentTargetsToSpecifiedShocksOr')}</p>
      {!preview ? <Empty title={systemText('preInvestment.taaScenarioExperiments.calculateAComparablePlanFirst')}><p>{systemText('preInvestment.taaScenarioExperiments.completeBacktestingAndCandidateSelectionThenSimulate')}</p><button type="button" className={`${buttonClass} mt-3`} onClick={onBacktest}>{systemText('preInvestment.taaScenarioExperiments.goToBacktestAndSelection')}</button></Empty> : <>
        <div className="grid gap-4 sm:grid-cols-2"><Field label={systemText('preInvestment.taaScenarioExperiments.scenarioMethod')}><select className={inputClass} value={draft.kind} onChange={event => chooseKind(event.target.value as TaaScenario['kind'])}><option value="shock">{systemText('preInvestment.taaScenarioExperiments.customAssetShocks')}</option><option value="historical">{systemText('preInvestment.taaScenarioExperiments.historicalPeriodReplay')}</option></select></Field><Field label={systemText('preInvestment.taaScenarioExperiments.scenarioName')}><input className={inputClass} value={draft.name} onChange={event => update({ name: event.target.value })} /></Field></div>
        {draft.kind === 'shock' ? <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{preview.baseline.assets.map(asset => <Field key={asset.id} label={systemText('preInvestment.taaScenarioExperiments.assumedChange', { p0: asset.name })}><NumberInput className={inputClass} value={draft.shocks?.[asset.id] ?? 0} onValueChange={value => update({ shocks: { ...draft.shocks, [asset.id]: value } })} /></Field>)}</div><p className="text-xs text-slate-600">{systemText('preInvestment.taaScenarioExperiments.0ExplicitlyAssumesNoChangeForThis')}</p></> : <><p className="text-xs text-slate-600">{systemText('preInvestment.taaScenarioExperiments.availableHistoricalRange')}{range?.start} — {range?.end}{systemText('preInvestment.taaScenarioExperiments.theEndDateMustNotExceedThe')}</p><div className="grid gap-4 sm:grid-cols-2"><Field label={systemText('preInvestment.taaScenarioExperiments.historicalScenarioStart')}><input type="date" className={inputClass} min={range?.start} max={draft.end_date} value={draft.start_date ?? ''} onChange={event => update({ start_date: event.target.value })} /></Field><Field label={systemText('preInvestment.taaScenarioExperiments.historicalScenarioEnd')}><input type="date" className={inputClass} min={draft.start_date} max={range?.end} value={draft.end_date ?? ''} onChange={event => update({ end_date: event.target.value })} /></Field></div>{invalidHistory && <p role="status" className="text-sm text-amber-900">{systemText('preInvestment.taaScenarioExperiments.historicalDatesAreOutsideTheAvailableRange')}<button type="button" className="ml-2 min-h-9 underline" onClick={() => update({ start_date: range?.start, end_date: range?.end })}>{systemText('preInvestment.taaScenarioExperiments.useTheCurrentAvailableRange')}</button></p>}</>}
        <button type="button" className={primaryClass} disabled={busy || invalidHistory || !draft.name.trim() || (draft.kind === 'shock' && Object.values(draft.shocks ?? {}).some(value => !Number.isFinite(value)))} onClick={() => void run({ ...draft, ...(draft.kind === 'shock' ? { shocks: Object.fromEntries(Object.entries(draft.shocks ?? {}).map(([id, value]) => [id, value / 100])) } : {}) })}>{busy ? systemText('preInvestment.taaScenarioExperiments.simulating') : experiments.some(item => item.scenario.name === draft.name.trim()) ? systemText('preInvestment.taaScenarioExperiments.recalculateScenarioWithThisName') : systemText('preInvestment.taaScenarioExperiments.calculateScenarioImpact')}</button>
      </>}
    </section>
    <section className={`${sectionClass} space-y-3`} aria-label={systemText('preInvestment.taaScenarioExperiments.scenarioExperimentComparison')}><h2 className="text-base font-semibold">{systemText('preInvestment.taaScenarioExperiments.retainedScenarios') + " "}{experiments.length}/12</h2>{!experiments.length ? <p className="text-sm text-slate-600">{systemText('preInvestment.taaScenarioExperiments.yourFirstCompletedExperimentWillAppearHere')}</p> : <div className="grid gap-3 lg:grid-cols-2">{experiments.map(item => <article key={item.scenario.name} className="min-w-0 rounded-lg border border-slate-200 p-3"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="min-w-0 break-words text-sm font-semibold">{item.scenario.name}</h3><span className="text-xs text-slate-600">{item.result ? systemText('preInvestment.taaScenarioExperiments.savedWithTheCurrentVersion') : systemText('preInvestment.taaScenarioExperiments.conditionsChangedRecalculationRequired')}</span></div><p className="mt-1 text-xs leading-5 text-slate-600">{item.scenario.kind === 'historical' ? `${item.scenario.start_date} — ${item.scenario.end_date}` : Object.entries(item.scenario.shocks ?? {}).map(([id, value]) => `${names[id] ?? id} ${percentText(value)}`).join('；')}</p>{item.result && <dl className="mt-3 grid grid-cols-3 gap-2 text-xs"><div><dt>SAA</dt><dd className="mt-1 font-semibold">{percentText(item.result.baseline_return)}</dd></div><div><dt>TAA</dt><dd className="mt-1 font-semibold">{percentText(item.result.taa_return)}</dd></div><div><dt>{systemText('preInvestment.taaScenarioExperiments.returnDifference')}</dt><dd className="mt-1 font-semibold">{points(item.result.excess_return)}</dd></div></dl>}<div className="mt-3 flex flex-wrap gap-2">{item.result ? <button type="button" className={buttonClass} onClick={() => setSelected(item.scenario.name)}>{systemText('preInvestment.taaScenarioExperiments.viewDetails')}</button> : <button type="button" className={buttonClass} disabled={!preview || busy} onClick={() => void run(item.scenario)}>{systemText('preInvestment.taaScenarioExperiments.recalculateScenario')}</button>}<button type="button" className={buttonClass} disabled={busy} aria-label={systemText('preInvestment.taaScenarioExperiments.removeScenario', { p0: item.scenario.name })} onClick={() => { onChange(experiments.filter(other => other !== item)); if (selected === item.scenario.name) setSelected(null) }}>{systemText('preInvestment.taaScenarioExperiments.remove')}</button></div></article>)}</div>}</section>
    {active?.result && <TaaScenarioView result={active.result} names={names} />}
    {preview && <details className={sectionClass}><summary className="cursor-pointer text-sm font-medium">{systemText('preInvestment.taaScenarioExperiments.advancedMacroStressTestsWithPublishedRisk')}</summary><div className="mt-4"><PortfolioRiskSection context={systemText('preInvestment.taaScenarioExperiments.selectASavedProductPortfolioAndTest')} /></div></details>}
  </div>
}
