import { researchMessage } from '../../i18n/researchMessages'
import { systemText, useI18n } from '../../i18n/runtime'
import type { TaaWalkForwardConfig, TaaWalkForwardResult } from '../../services/tacticalAllocation'
import { Field, inputClass, NumberInput, percentText, sectionClass } from '../risk-models/ResearchUI'

export default function TaaWalkForward({ value, result, disabled, onChange }: {
  value?: TaaWalkForwardConfig | null; result?: TaaWalkForwardResult; disabled: boolean
  onChange: (value: TaaWalkForwardConfig | null) => void
}) {
  useI18n()
  return <section className={`${sectionClass} space-y-4`} aria-label={systemText('preInvestment.taaWalkForward.multiPeriodOutOfSampleValidation')}>
    <div><h2 className="text-lg font-semibold">{systemText('preInvestment.taaWalkForward.doesItRemainEffectiveAcrossPeriods')}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{systemText('preInvestment.taaWalkForward.addRollingOrExpandingTrainingWithSequential')}</p></div>
    <label className="flex items-center gap-3 text-sm font-medium"><input type="checkbox" checked={Boolean(value)} disabled={disabled} onChange={e => onChange(e.target.checked ? { window_mode: 'rolling', training_periods: 126, validation_periods: 63 } : null)} />{systemText('preInvestment.taaWalkForward.runMultiPeriodOutOfSampleValidation')}</label>
    {value && <div className="grid gap-4 sm:grid-cols-3">
      <Field label={systemText('preInvestment.taaWalkForward.trainingWindowMode')}><select className={inputClass} value={value.window_mode} disabled={disabled} onChange={e => onChange({ ...value, window_mode: e.target.value as TaaWalkForwardConfig['window_mode'] })}><option value="rolling">{systemText('preInvestment.taaWalkForward.rollingMostRecentTrainingWindow')}</option><option value="expanding">{systemText('preInvestment.taaWalkForward.expandingAllKnownHistory')}</option></select></Field>
      <Field label={systemText('preInvestment.taaWalkForward.initialTrainingPeriods')} hint={systemText('preInvestment.taaWalkForward.atLeast20CommonReturnObservationsTrend')}><NumberInput className={inputClass} value={value.training_periods} min={20} max={2500} disabled={disabled} onValueChange={number => onChange({ ...value, training_periods: number })} /></Field>
      <Field label={systemText('preInvestment.taaWalkForward.validationPeriodsPerFold')} hint={systemText('preInvestment.taaWalkForward.atLeast20PeriodsWithUpTo')}><NumberInput className={inputClass} value={value.validation_periods} min={20} max={1000} disabled={disabled} onValueChange={number => onChange({ ...value, validation_periods: number })} /></Field>
    </div>}
    {value && !result && <p className="text-xs leading-5 text-slate-600">{systemText('preInvestment.taaWalkForward.afterSetupSelectRunBacktestAndCompare')}</p>}
    {result && <>
      <p role="status" className="text-sm text-slate-700">{systemText('preInvestment.taaWalkForward.completed') + " "}{result.completed_folds} {" " + systemText('preInvestment.taaWalkForward.foldsBlocked') + " "}{result.blocked_folds} {" " + systemText('preInvestment.taaWalkForward.foldsTrailingObservationsShorterThanAValidation') + " "}{result.excluded_tail_observations} {" " + systemText('preInvestment.taaWalkForward.periods')}</p>
      <div className="overflow-x-auto"><table aria-label={systemText('preInvestment.taaWalkForward.outOfSampleResultsByFold')} className="w-full min-w-[760px] text-sm"><thead><tr>{[systemText('preInvestment.taaWalkForward.fold'), systemText('preInvestment.taaWalkForward.actualTrainingPeriod'), systemText('preInvestment.taaWalkForward.validationPeriod'), systemText('preInvestment.taaWalkForward.strength'), systemText('preInvestment.taaWalkForward.validationNetExcessReturn'), systemText('preInvestment.taaWalkForward.trackingError'), systemText('preInvestment.taaWalkForward.turnover'), systemText('preInvestment.taaWalkForward.eligibility')].map((label, i) => <th key={label} scope="col" className={`whitespace-nowrap p-2 ${i >= 3 && i <= 6 ? 'text-right' : 'text-left'}`}>{label}</th>)}</tr></thead><tbody>{result.folds.map(fold => <tr key={fold.fold} className="border-t border-slate-200"><th scope="row" className="p-2 text-left font-medium">{fold.fold}</th><td className="p-2 text-xs leading-5">{fold.train_start}<br />{fold.train_end ?? systemText('preInvestment.taaWalkForward.noMatureSamples')}{fold.purged_training_periods > 0 && <span className="block text-amber-800">{systemText('preInvestment.taaWalkForward.tailObservationsExcluded') + " "}{fold.purged_training_periods} {" " + systemText('preInvestment.taaWalkForward.periods2')}</span>}</td><td className="p-2 text-xs leading-5">{fold.validation_start}<br />{fold.validation_end}</td><td className="p-2 text-right tabular-nums">{fold.strength ?? '—'}</td><td className="p-2 text-right tabular-nums">{percentText(fold.validation?.excess_return)}</td><td className="p-2 text-right tabular-nums">{percentText(fold.validation?.tracking_error)}</td><td className="p-2 text-right tabular-nums">{percentText(fold.validation?.turnover)}</td><td className="max-w-64 p-2 text-xs leading-5">{fold.status === 'blocked' ? fold.reasons.map(researchMessage).join('; ') : fold.validation_feasible ? systemText('preInvestment.taaWalkForward.validationWithinLimits') : fold.baseline_fallback_exemption ? systemText('preInvestment.taaWalkForward.saaRetainedBaselineTurnoverExemption') : systemText('preInvestment.taaWalkForward.validationRiskOrTurnoverLimitBreached')}</td></tr>)}</tbody></table></div>
      {result.warnings.map(warning => <p key={warning} className="text-xs leading-5 text-slate-600">{warning}</p>)}
    </>}
  </section>
}
