import { Field, inputClass, NumberInput, sectionClass } from '../risk-models/ResearchUI'
import { percentInputValue, type CmaDraft } from '../../services/strategicAllocation'
/** Standalone strategy research has no implied product history or proxy returns. */
export default function ForwardAssumptions({ value, onChange }: { value: CmaDraft; onChange: (value: CmaDraft) => void }) {
  return <section className={`${sectionClass} space-y-5`} aria-label="独立战略前瞻假设">
    <h2 className="text-lg font-semibold">填写前瞻预期与风险</h2>
    <p className="text-sm text-slate-600">资产角色与流动性来自已确认战略范围。本路径不读取或制造历史净值；预期、波动和相关性须有明确研究依据。</p>
    <div className="grid gap-3 sm:grid-cols-2"><Field label="假设版本名称"><input className={inputClass} value={value.name} onChange={e => onChange({ ...value, name: e.target.value })} /></Field><Field label="假设研究日"><input type="date" className={inputClass} value={value.as_of} onChange={e => onChange({ ...value, as_of: e.target.value })} /></Field></div>
    <Field label="预测来源与主要假设"><textarea className={inputClass} value={value.source} onChange={e => onChange({ ...value, source: e.target.value })} /></Field>
    <p className="text-sm text-slate-600">{value.currency} · {value.horizon_years}年 · 年化算术总收益；不是几何复合收益或历史业绩。</p>
    <div className="divide-y divide-slate-200">{value.assets.map((asset, i) => <fieldset key={asset.id} className="min-w-0 py-4"><legend className="text-sm font-semibold">{asset.id}</legend><div className="grid gap-3 sm:grid-cols-3">{([['annual_return', '预期年收益（%）'], ['annual_volatility', '年化波动（%）'], ['mean_uncertainty', '均值不确定半宽（百分点）']] as const).map(([key, label]) => <Field key={key} label={`${asset.id}${label}`}><NumberInput className={`${inputClass} tabular-nums`} value={percentInputValue(asset[key])} onValueChange={n => onChange({ ...value, assets: value.assets.map((a, index) => index === i ? { ...a, [key]: n / 100 } : a) })} /></Field>)}</div></fieldset>)}</div>
    <div className="overflow-x-auto"><table aria-label="战略资产相关矩阵" className="w-full text-sm"><caption className="p-2 text-left text-slate-600">服务端校验完整矩阵，不自动修正无效相关性。</caption><thead><tr><th scope="col" className="p-2 text-left">战略资产</th>{value.assets.map(a => <th scope="col" className="p-2 text-right" key={a.id}>{a.id}</th>)}</tr></thead><tbody>{value.assets.map((a, row) => <tr key={a.id} className="border-b border-slate-200"><th scope="row" className="p-2 text-left">{a.id}</th>{value.assets.map((b, col) => <td key={b.id} className="min-w-24 p-2 text-right tabular-nums">{col > row ? <NumberInput aria-label={`${a.id}与${b.id}相关系数`} className={`${inputClass} text-right tabular-nums`} value={value.correlation[row][col]} min={-1} max={1} onValueChange={n => onChange({ ...value, correlation: value.correlation.map((values, i) => values.map((old, j) => (i === row && j === col) || (i === col && j === row) ? n : old)) })} /> : Number.isFinite(value.correlation[row][col]) ? value.correlation[row][col] : '—'}</td>)}</tr>)}</tbody></table></div>
    <label className="flex min-h-10 items-start gap-2 text-sm leading-6"><input type="checkbox" className="mt-1.5" checked={value.basis_confirmed} onChange={e => onChange({ ...value, basis_confirmed: e.target.checked })} />我已确认同币种、年化算术总收益、风险口径与依据；未映射资产仍须保留完整假设。</label>
  </section>
}
