import type { ReactNode } from 'react'
import { act, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import * as api from '../services/riskModels'
import { impactFixture, riskCatalogFixture, riskFactor, riskPreviewFixture, riskReleaseFixture, riskRunFixture, scenarioPreviewFixture, scenarioReleaseFixture } from '../test/publishedRiskFixtures'
import PublishedRiskPanel from '../components/risk-models/PublishedRiskPanel'
import RiskModelCenter from './RiskModelCenter'
import PublishedScenarioCenter from './PublishedScenarioCenter'
import RiskApplicationWorkspace from './RiskApplicationWorkspace'

vi.mock('echarts-for-react', () => ({ default: () => <div data-testid="risk-chart" /> }))
vi.mock('./ScenarioAlgorithmCenter', () => ({ default: () => <div data-testid="advanced-experiments" /> }))
vi.mock('../services/riskModels', async importOriginal => {
  const actual = await importOriginal<typeof api>()
  return { ...actual, riskCatalog: vi.fn(), riskReleases: vi.fn(), getRiskRun: vi.fn(), scenarioReleases: vi.fn(), riskPortfolios: vi.fn(), runRiskImpact: vi.fn(), previewRiskModel: vi.fn(), publishRiskPreview: vi.fn(), previewCashflow: vi.fn(), publishCashflowPreview: vi.fn(), previewScenario: vi.fn(), publishScenario: vi.fn(), getRiskImpact: vi.fn() }
})
const mount = (node: ReactNode, url = '/') => render(<MemoryRouter initialEntries={[url]}>{node}</MemoryRouter>)
const copy = <T,>(value: T): T => structuredClone(value)
const productKey = 'fund:000001.OF'

beforeEach(() => {
  vi.clearAllMocks()
  vi.mocked(api.riskCatalog).mockResolvedValue(copy(riskCatalogFixture))
  vi.mocked(api.riskReleases).mockImplementation(async domain => domain === 'product' ? [copy(riskReleaseFixture)] : [])
  vi.mocked(api.getRiskRun).mockResolvedValue(copy(riskRunFixture))
  vi.mocked(api.scenarioReleases).mockResolvedValue([copy(scenarioReleaseFixture)])
  vi.mocked(api.riskPortfolios).mockResolvedValue([])
  vi.mocked(api.runRiskImpact).mockResolvedValue(copy(impactFixture))
  vi.mocked(api.previewRiskModel).mockResolvedValue(copy(riskPreviewFixture))
  vi.mocked(api.publishRiskPreview).mockResolvedValue(copy(riskReleaseFixture))
  vi.mocked(api.previewScenario).mockImplementation(async definition => ({ ...copy(scenarioPreviewFixture), name: definition.name, definition }))
  vi.mocked(api.publishScenario).mockResolvedValue(copy(scenarioReleaseFixture))
  vi.mocked(api.getRiskImpact).mockResolvedValue(copy(impactFixture))
})

async function chooseScenario(user: ReturnType<typeof userEvent.setup>) {
  await user.selectOptions(await screen.findByRole('combobox', { name: '选择已发布情景' }), scenarioReleaseFixture.id)
  await user.click(screen.getByRole('checkbox', { name: /未设置冲击的已建模因子保持不变/ }))
}

describe('产品消费已发布风险成果', () => {
  it('打开页面只读取本地发布结果，敏感性直接显示而不训练', async () => {
    mount(<PublishedRiskPanel productKey={productKey} />)
    expect(await screen.findByText('0.7%')).toBeInTheDocument()
    expect(screen.getByText('已发布结果 · 只读')).toBeInTheDocument()
    expect(api.riskReleases).toHaveBeenCalledWith('product', expect.objectContaining({ product_key: productKey }), expect.any(AbortSignal))
    expect(api.getRiskRun).toHaveBeenCalledWith('product', riskRunFixture.id, expect.any(AbortSignal))
    expect(api.previewRiskModel).not.toHaveBeenCalled()
    expect(api.runRiskImpact).not.toHaveBeenCalled()
  })
  it('无成果给出带产品身份的研究入口，空状态也可刷新', async () => {
    vi.mocked(api.riskReleases).mockResolvedValue([])
    const user = userEvent.setup()
    mount(<PublishedRiskPanel productKey={productKey} productName="测试基金甲" />)
    const link = await screen.findByRole('link', { name: '到风险模型中心研究' })
    expect(link.getAttribute('href')).toContain('product_key=fund%3A000001.OF')
    await user.click(screen.getByRole('button', { name: '刷新成果目录' }))
    await waitFor(() => expect(api.riskReleases).toHaveBeenCalledTimes(2))
    expect(api.previewRiskModel).not.toHaveBeenCalled()
  })
  it('失效的显式版本不会被另一份活跃成果悄悄替换', async () => {
    mount(<PublishedRiskPanel productKey={productKey} />, '/?exposure_release_id=missing-release')
    expect(await screen.findByText(/指定风险成果在当前对象或日期下不可用/)).toBeInTheDocument()
    expect(api.getRiskRun).not.toHaveBeenCalled()
    expect(screen.getByRole('button', { name: '计算情景影响' })).toBeDisabled()
  })
  it('停用或过期的成果不能计算，仍可查看历史只读研究', async () => {
    vi.mocked(api.riskReleases).mockResolvedValue([{ ...riskReleaseFixture, status: 'expired' }])
    const user = userEvent.setup()
    mount(<PublishedRiskPanel productKey={productKey} />, `/?exposure_release_id=${riskReleaseFixture.id}`)
    await chooseScenario(user)
    expect(screen.getByRole('button', { name: '计算情景影响' })).toBeDisabled()
    expect(api.runRiskImpact).not.toHaveBeenCalled()
  })
  it('冲击频率或因子契约不匹配时就地解释并阻断', async () => {
    vi.mocked(api.scenarioReleases).mockResolvedValue([{ ...scenarioReleaseFixture, frequency: 'daily' }])
    const user = userEvent.setup()
    mount(<PublishedRiskPanel productKey={productKey} />)
    await chooseScenario(user)
    expect(screen.getByText(/周期不匹配。/)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '计算情景影响' })).toBeDisabled()
  })
  it('用户确认后使用精确发布ID计算，改变参数后清除旧结果', async () => {
    const user = userEvent.setup()
    mount(<PublishedRiskPanel productKey={productKey} />)
    await chooseScenario(user)
    await user.click(screen.getByRole('button', { name: '计算情景影响' }))
    expect(await screen.findByRole('region', { name: '本次压测结果' })).toBeInTheDocument()
    expect(api.runRiskImpact).toHaveBeenCalledWith(expect.objectContaining({ scenario_release_id: scenarioReleaseFixture.id, exposure_release_id: riskReleaseFixture.id, target: { kind: 'product', product_key: productKey }, hold_other_factors_constant: true }))
    expect(api.previewRiskModel).not.toHaveBeenCalled()
    await user.clear(screen.getByRole('spinbutton', { name: /假设本金/ }))
    await user.type(screen.getByRole('spinbutton', { name: /假设本金/ }), '20000')
    expect(screen.queryByRole('region', { name: '本次压测结果' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: '计算情景影响' })).toBeDisabled()
  })
  it('产品切换后忽略旧对象迟到的压测结果', async () => {
    let finish!: (value: api.RiskImpact) => void
    vi.mocked(api.runRiskImpact).mockImplementation(() => new Promise(resolve => { finish = resolve }))
    const user = userEvent.setup()
    const view = mount(<PublishedRiskPanel productKey={productKey} />)
    await chooseScenario(user)
    await user.click(screen.getByRole('button', { name: '计算情景影响' }))
    await waitFor(() => expect(api.runRiskImpact).toHaveBeenCalledTimes(1))
    view.rerender(<MemoryRouter><PublishedRiskPanel productKey="fund:000002.OF" /></MemoryRouter>)
    await act(async () => { finish(copy(impactFixture)) })
    expect(screen.queryByRole('region', { name: '本次压测结果' })).not.toBeInTheDocument()
  })
  it('组合只传不可变快照ID，不从浏览器提交权重', async () => {
    const user = userEvent.setup()
    mount(<PublishedRiskPanel portfolioRunId="run-saved-portfolio" />)
    await chooseScenario(user)
    await user.click(screen.getByRole('button', { name: '计算情景影响' }))
    await waitFor(() => expect(api.runRiskImpact).toHaveBeenCalled())
    const request = vi.mocked(api.runRiskImpact).mock.calls[0][0]
    expect(request.target).toEqual({ kind: 'portfolio_run', portfolio_run_id: 'run-saved-portfolio' })
    expect(request).not.toHaveProperty('weights')
    expect(api.riskPortfolios).not.toHaveBeenCalled()
  })
  it('两个组合用相同冻结口径并列对比，不复制或修改权重', async () => {
    vi.mocked(api.riskPortfolios).mockResolvedValue([{ id: 'run-other', name: '对照组合', as_of: '2026-08-31', created_at: '2026-09-01' }])
    vi.mocked(api.runRiskImpact).mockResolvedValueOnce({ ...copy(impactFixture), id: 'impact-primary', target: { kind: 'portfolio_run', name: '当前组合' } })
      .mockResolvedValueOnce({ ...copy(impactFixture), id: 'impact-other', target: { kind: 'portfolio_run', name: '对照组合' } })
    const user = userEvent.setup()
    mount(<PublishedRiskPanel portfolioRunId="run-current" />)
    await user.click(await screen.findByRole('checkbox', { name: '对比另一个已保存组合' }))
    await user.selectOptions(await screen.findByRole('combobox', { name: /选择对照组合快照/ }), 'run-other')
    await chooseScenario(user)
    await user.click(screen.getByRole('button', { name: '计算并对比' }))
    expect(await screen.findByRole('region', { name: '组合情景对比结果' })).toBeInTheDocument()
    const requests = vi.mocked(api.runRiskImpact).mock.calls.map(([request]) => request)
    expect(requests.map(request => request.target)).toEqual([{ kind: 'portfolio_run', portfolio_run_id: 'run-current' }, { kind: 'portfolio_run', portfolio_run_id: 'run-other' }])
    expect(requests.map(({ target: _target, ...shared }) => shared)[0]).toEqual(requests.map(({ target: _target, ...shared }) => shared)[1])
    expect(api.previewRiskModel).not.toHaveBeenCalled()
    await user.click(screen.getByRole('checkbox', { name: '对比另一个已保存组合' }))
    expect(screen.queryByRole('region', { name: '组合情景对比结果' })).not.toBeInTheDocument()
  })
  it('对照组合失败时不展示不完整的对比结论', async () => {
    vi.mocked(api.riskPortfolios).mockResolvedValue([{ id: 'run-other', name: '对照组合', as_of: '2026-08-31', created_at: '2026-09-01' }])
    vi.mocked(api.runRiskImpact).mockResolvedValueOnce(copy(impactFixture)).mockRejectedValueOnce(new Error('对照组合缺少非零持仓暴露'))
    const user = userEvent.setup()
    mount(<PublishedRiskPanel portfolioRunId="run-current" />)
    await user.click(await screen.findByRole('checkbox', { name: '对比另一个已保存组合' }))
    await user.selectOptions(await screen.findByRole('combobox', { name: /选择对照组合快照/ }), 'run-other')
    await chooseScenario(user)
    await user.click(screen.getByRole('button', { name: '计算并对比' }))
    expect(await screen.findByRole('alert')).toHaveTextContent('对照组合缺少非零持仓暴露')
    expect(screen.queryByRole('region', { name: '组合情景对比结果' })).not.toBeInTheDocument()
    expect(screen.queryByRole('region', { name: '本次压测结果' })).not.toBeInTheDocument()
  })
  it('投后入口明确选择研究组合，不携带演示权重', async () => {
    mount(<RiskApplicationWorkspace />, '/?target_type=portfolio_run')
    expect(await screen.findByRole('combobox', { name: /选择已保存的产品组合快照/ })).toBeInTheDocument()
    expect(screen.queryByRole('combobox', { name: '选择产品' })).not.toBeInTheDocument()
    expect(api.riskPortfolios).toHaveBeenCalledTimes(1)
    expect(api.runRiskImpact).not.toHaveBeenCalled()
    expect(api.previewRiskModel).not.toHaveBeenCalled()
  })
  it('旧版已保存结果按ID兼容读取，即使模型后来停用也不重新计算', async () => {
    mount(<RiskApplicationWorkspace />, `/?impact_id=${impactFixture.id}`)
    expect(await screen.findByRole('region', { name: '本次压测结果' })).toBeInTheDocument()
    expect(api.getRiskImpact).toHaveBeenCalledWith(impactFixture.id, expect.any(AbortSignal))
    expect(api.runRiskImpact).not.toHaveBeenCalled()
    expect(api.riskReleases).not.toHaveBeenCalled()
  })
})

describe('风险研究中心', () => {
  it('产品身份可带入，计算预览不保存，确认发布后才形成成果', async () => {
    const user = userEvent.setup()
    mount(<RiskModelCenter />, '/settings/risk-models?product_key=fund%3A000001.OF&product_name=测试基金甲')
    expect(await screen.findByRole('button', { name: '移除研究对象测试基金甲' })).toBeInTheDocument()
    await user.type(screen.getByRole('textbox', { name: '研究名称' }), '测试研究')
    await user.click(screen.getByRole('checkbox', { name: new RegExp(riskFactor.name) }))
    await user.click(screen.getByRole('button', { name: '计算敏感度' }))
    expect(await screen.findByRole('region', { name: '敏感性研究结果' })).toBeInTheDocument()
    expect(screen.getByText('当前预览 · 未保存')).toBeInTheDocument()
    expect(screen.getByText(/只有确认发布后才会写入磁盘/)).toBeInTheDocument()
    expect(api.previewRiskModel).toHaveBeenCalledWith('product', expect.objectContaining({ name: '测试研究', targets: [{ kind: 'fund', product_id: '000001.OF', name: '测试基金甲' }] }))
    expect(api.publishRiskPreview).not.toHaveBeenCalled()
    await user.click(screen.getByRole('button', { name: '确认并发布' }))
    await user.click(screen.getByRole('checkbox', { name: /我已查看验证及数据来源/ }))
    await user.click(screen.getByRole('button', { name: '确认发布成果' }))
    await waitFor(() => expect(api.publishRiskPreview).toHaveBeenCalledWith('product', expect.objectContaining({ name: '测试研究' }), riskPreviewFixture.preview_hash, 30, ''))
    expect(screen.getByRole('button', { name: '已发布' })).toBeDisabled()
    const link = screen.getByRole('link', { name: '到测试基金甲查看' })
    const destination = new URL(link.getAttribute('href')!, 'http://localhost')
    expect(destination.pathname).toBe('/product-research/products/000001.OF')
    expect(destination.searchParams.get('kind')).toBe('fund')
    expect(destination.searchParams.get('tab')).toBe('risk')
    expect(destination.searchParams.get('exposure_release_id')).toBe(riskReleaseFixture.id)
  })
  it('同一运行的多份发布记录按所选发布ID展示和跳转，不猜测最新记录', async () => {
    const user = userEvent.setup()
    const previous = { ...copy(riskReleaseFixture), id: 'release-previous', status: 'retired' }
    vi.mocked(api.riskReleases).mockResolvedValue([copy(riskReleaseFixture), previous])
    mount(<RiskModelCenter />)
    const buttons = await screen.findAllByRole('button', { name: '查看成果' })
    await user.click(buttons[1])
    const link = await screen.findByRole('link', { name: '到测试基金甲查看' })
    expect(new URL(link.getAttribute('href')!, 'http://localhost').searchParams.get('exposure_release_id')).toBe('release-previous')
    expect(screen.getByText('发布版本：release-previous')).toBeInTheDocument()
    expect(api.previewRiskModel).not.toHaveBeenCalled()
    await user.click(buttons[0])
    await waitFor(() => expect(new URL(screen.getByRole('link', { name: '到测试基金甲查看' }).getAttribute('href')!, 'http://localhost').searchParams.get('exposure_release_id')).toBe(riskReleaseFixture.id))
  })
  it('参数改变后旧研究结果不能继续发布', async () => {
    const user = userEvent.setup()
    mount(<RiskModelCenter />, '/?product_key=fund%3A000001.OF')
    await user.type(await screen.findByRole('textbox', { name: '研究名称' }), '测试')
    await user.click(screen.getByRole('checkbox', { name: new RegExp(riskFactor.name) }))
    await user.click(screen.getByRole('button', { name: '计算敏感度' }))
    await user.click(await screen.findByRole('button', { name: '调整研究设置' }))
    await user.type(screen.getByRole('textbox', { name: '研究名称' }), '已修改')
    await user.click(screen.getByRole('button', { name: /3.*发布成果/ }))
    expect(screen.getByText('当前没有可发布的结果')).toBeInTheDocument()
    expect(api.publishRiskPreview).not.toHaveBeenCalled()
  })
})

describe('三个入口的情景工作台', () => {
  it('直接市场冲击可预览发布，旧高级实验不会默认加载', async () => {
    const user = userEvent.setup()
    mount(<PublishedScenarioCenter />)
    await screen.findByText('可复用的情景版本')
    expect(screen.queryByTestId('advanced-experiments')).not.toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: '新建情景' }))
    await user.type(screen.getByRole('textbox', { name: '情景名称' }), '股市下跌')
    await user.click(screen.getByRole('button', { name: '下一步：设置变化' }))
    await user.click(screen.getByRole('checkbox', { name: new RegExp(riskFactor.name) }))
    const shock = screen.getByRole('spinbutton', { name: `第1期${riskFactor.name}变化` })
    await user.clear(shock); await user.type(shock, '-10')
    await user.click(screen.getByRole('button', { name: '预览冲击路径' }))
    expect(await screen.findByText('股市下跌 · 市场风险因子路径')).toBeInTheDocument()
    expect(api.previewScenario).toHaveBeenCalledWith(expect.objectContaining({ entry: 'market', input_ids: [riskFactor.id], rows: [[-10]], shock_basis: 'period_change' }))
    expect(screen.getByText(/当前预览不会写入磁盘/)).toBeInTheDocument()
    expect(api.publishScenario).not.toHaveBeenCalled()
    await user.click(screen.getByRole('checkbox', { name: /我已核对单位/ }))
    await user.click(screen.getByRole('button', { name: '确认发布情景' }))
    await waitFor(() => expect(api.publishScenario).toHaveBeenCalledWith(expect.objectContaining({ name: '股市下跌', rows: [[-10]] }), scenarioPreviewFixture.preview_hash, 90, ''))
    expect(screen.getByRole('link', { name: '应用到产品或组合' })).toHaveAttribute('href', expect.stringContaining(scenarioReleaseFixture.id))
  })
  it.each(['发生一件大事', '经济指标变化'])('%s 没有已发布模型时解释缺少哪段，不使用内置假系数', async entry => {
    const user = userEvent.setup()
    mount(<PublishedScenarioCenter />)
    await screen.findByText('可复用的情景版本')
    await user.click(screen.getByRole('button', { name: '新建情景' }))
    await user.type(screen.getByRole('textbox', { name: '情景名称' }), '宏观假设')
    await user.click(screen.getByRole('radio', { name: new RegExp(entry) }))
    await user.click(screen.getByRole('button', { name: '下一步：设置变化' }))
    expect(screen.getByText('先补齐这条传导链')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '预览冲击路径' })).toBeDisabled()
    expect(screen.getByRole('button', { name: '去研究传导模型' })).toBeEnabled()
    expect(api.previewScenario).not.toHaveBeenCalled()
  })
})
