import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Badge, Button, Card } from '../components/ui'
import { Field } from '../components/risk-models/ResearchUI'
import { RiskScaleInputSummary } from '../components/risk-scales/RiskScaleInputSummary'
import { RiskScaleResults } from '../components/risk-scales/RiskScaleResults'
import { controlClass, ErrorNotice, linkClass, Loading, Problems, TaskHeader, useRiskTask, useRiskText } from '../components/risk-scales/shared'
import { metadata, riskScales, type DefaultBinding, type VersionView } from '../services/riskScales'

export default function RiskScaleVersionView() {
  const { versionId = '' } = useParams(), { t } = useRiskText(), task = useRiskTask()
  const [version, setVersion] = useState<VersionView | null>(null), [binding, setBinding] = useState<DefaultBinding | null>(null)
  const [governance, setGovernance] = useState<'activate' | 'retire' | null>(null), [confirmed, setConfirmed] = useState(false), [clearDefault, setClearDefault] = useState(false), [reason, setReason] = useState(''), [notice, setNotice] = useState('')
  const reload = () => { setGovernance(null); setConfirmed(false); void task.run(async signal => { const [item, defaults] = await Promise.all([riskScales.version(versionId, signal), riskScales.defaults(signal)]); return { item, defaults } }, ({ item, defaults }) => { setVersion(item); const definition = item.preview.request_echo.definition; setBinding(defaults.items.find(item => item.key === `${definition.base_currency}:${definition.risk_basis_id}`) ?? null) }) }
  useEffect(() => { setVersion(null); reload(); return task.invalidate }, [versionId])
  const isDefault = binding?.version_id === versionId
  const act = () => { void task.run(signal => governance === 'activate' ? riskScales.activate(versionId, { confirm: true, expected_revision: binding?.revision ?? 0 }, signal) : riskScales.retire(versionId, { confirm: true, expected_revision: binding?.revision ?? 0, reason, clear_default: clearDefault }, signal), () => { setNotice(governance === 'activate' ? 'defaultChanged' : 'retiredNotice'); reload() }) }
  return <div className="min-w-0 space-y-3 text-slate-900"><TaskHeader title={version ? `${version.name} · v${version.version_number}` : t('version')}><Badge>{t('readonly')}</Badge>{version && <Link className={linkClass} to={`/settings/risk-scales/new?from=${encodeURIComponent(version.id)}`}>{t('copyInputs')}</Link>}</TaskHeader><ErrorNotice error={task.error} retry={reload} />{task.busy && <Loading />}{notice && <p role="status" className="text-sm text-emerald-800">{t(notice)}</p>}
    {version && <><Card className="!p-4 space-y-3"><div className="flex flex-wrap gap-2">{isDefault && <Badge>{t('default')}</Badge>}<Badge tone={version.retired ? 'warning' : 'neutral'}>{t(version.retired ? 'retired' : 'published')}</Badge>{version.review_status === 'upcoming' && <Badge tone="warning">{t('reviewUpcoming')}</Badge>}{version.review_status === 'due' && <Badge tone="danger">{t('reviewDue')}</Badge>}</div>{version.review_due_at && version.review_status !== 'none' && <p className="text-sm text-slate-700">{t('reviewReminder', { date: String(version.review_due_at) })}</p>}<p className="text-sm text-slate-600">{t('readonlyHint')}</p><Problems items={version.current_eligibility.blockers} /><RiskScaleResults preview={version.preview} /><details><summary className="min-h-10 cursor-pointer py-2 text-sm font-medium">{t('frozenInputs')}</summary><RiskScaleInputSummary definition={version.preview.request_echo.definition} assetNames={metadata(version.preview.result.diagnostics?.asset_names) as Record<string, string>} /></details></Card>
    <Card className="!p-4 space-y-2"><h2 className="text-base font-semibold">{t('versionActions')}</h2><div className="flex flex-wrap gap-2"><Button disabled={task.busy || isDefault || version.retired || !version.current_eligibility.eligible || !version.current_default_eligibility.eligible} onClick={() => { setGovernance('activate'); setConfirmed(false) }}>{t('activate')}</Button><Button disabled={task.busy || version.retired} onClick={() => { setGovernance('retire'); setConfirmed(false); setClearDefault(false); setReason('') }}>{t('retire')}</Button></div>{isDefault && <p className="text-sm text-slate-600">{t('alreadyDefault')}</p>}{version.retired && <p className="text-sm text-slate-600">{t('retiredNotice')}</p>}<Problems items={version.current_default_eligibility.blockers} />
    {governance && <section className="space-y-3 border-t border-slate-200 pt-4" aria-label={t('governanceConfirmation')}><h3 className="font-semibold">{t(governance === 'activate' ? 'activateConfirm' : 'retireConfirm')}</h3><p className="text-sm text-slate-600">{t('defaultImpact')}</p>{governance === 'retire' && <><Field label={t('retireReason')} required><textarea required className={controlClass} value={reason} onChange={event => { setReason(event.target.value); setConfirmed(false) }} /></Field>{isDefault && <label className="flex min-h-10 items-start gap-2 text-sm"><input type="checkbox" className="mt-1" checked={clearDefault} onChange={event => { setClearDefault(event.target.checked); setConfirmed(false) }} />{t('clearDefault')}</label>}</>}<label className="flex min-h-10 items-start gap-2 text-sm"><input type="checkbox" className="mt-1" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />{t('confirmGovernance')}</label>{(!confirmed || governance === 'retire' && (reason.trim().length < 5 || isDefault && !clearDefault)) && <p className="text-xs text-amber-900">{t('governanceRequired')}</p>}<div className="flex flex-wrap gap-2"><Button tone={governance === 'retire' ? 'danger' : 'primary'} disabled={task.busy || !confirmed || governance === 'retire' && (reason.trim().length < 5 || Boolean(isDefault && !clearDefault)) || governance === 'activate' && !version.current_default_eligibility.eligible} onClick={act}>{t('confirmAction')}</Button><Button onClick={() => { setGovernance(null); setConfirmed(false) }}>{t('cancel')}</Button></div></section>}
    </Card></>}
  </div>
}
