import type { RiskCatalog, RiskImpact, RiskModelFields, RiskRelease, RiskRun, RiskVariable, ScenarioDraft, ScenarioPreview, ScenarioRelease } from '../services/riskModels'

// Offline UI fixtures, never installed as market data or published production research.
export const riskAudit = { execution_backend: 'numba_njit_fixed_signature', nopython: true, object_mode: 0, python_fallback: 0, request_time_compilation: 0, kernel_signatures: { exposure_kernel: ['(Array(float64, 2, C),)'] } }
export const researchDay = new Date().toISOString().slice(0, 10)
export const riskFactor: RiskVariable = { id: 'cn-equity-csi300', name: '沪深300价格收益', roles: ['market'], unit: 'return', unit_label: '%', frequency: 'daily', transform: 'price_return', reference_move: '+1%', contract_hash: 'fixture-factor-contract', basis: 'price_index', market: 'CN', currency: 'CNY', revision: 1, availability: { available: true, reason: '离线测试数据' } }
export const macroVariable: RiskVariable = { ...riskFactor, id: 'cn-cpi-yoy', name: 'CPI同比增速变化', roles: ['macro'], unit: 'pp', unit_label: '个百分点', frequency: 'monthly', transform: 'difference', contract_hash: 'fixture-macro-contract', reference_move: '+1个百分点' }
export const riskCatalogFixture: RiskCatalog = { domain: 'product', variables: [riskFactor, macroVariable], frequencies: [{ id: 'monthly', name: '月频' }, { id: 'daily', name: '日频' }, { id: 'quarterly', name: '季频' }], event_templates: [{ id: 'custom', name: '自定义事件', description: '不提供预设系数' }], storage: { logical_path: 'data/risk_models', managed_data_disk: true } }
export const riskFields: RiskModelFields = { name: '基金风险研究', stage: 'product', method: 'ols', inputs: [riskFactor.id], outputs: [], targets: [{ kind: 'fund', product_id: '000001.OF', name: '测试基金甲' }], frequency: 'monthly', start_date: '2019-01-01', end_date: researchDay, validation_start: '2025-01-01', as_of: researchDay, lags: 0, min_train: 36, min_validation: 12, minimum_validation_r2: 0, refit_after_validation: true }
export const riskRunFixture: RiskRun = { id: 'research-run-fixture', name: riskFields.name, stage: 'product', method: 'ols', model: riskFields, as_of: researchDay, data_as_of: researchDay, frequency: 'monthly', inputs: [riskFactor], outputs: [], targets: [{ kind: 'fund', product_id: '000001.OF', key: 'fund:000001.OF', name: '测试基金甲' }], target_keys: ['fund:000001.OF'], rows: [{ target_id: 'fund:000001.OF', name: '测试基金甲', unit: 'return', train_observations: 60, validation_observations: 16, training_r2: 0.82, validation_r2: 0.75, status: 0, status_label: '通过', betas: [0.7], reference_responses: [0.7] }], coefficients: [[0.7, 0]], publishable: true, blockers: [], execution: riskAudit, limitations: ['这是离线测试，不代表真实产品。'], created_at: `${researchDay}T01:01:00Z`, content_hash: 'fixture-run-hash' }
export const riskPreviewFixture: RiskRun = { ...riskRunFixture, id: 'transient-risk-preview', preview_hash: '1111111111111111111111111111111111111111111111111111111111111111', transient: true, content_hash: '1111111111111111111111111111111111111111111111111111111111111111' }
export const riskReleaseFixture: RiskRelease = { id: 'research-release-exposure', name: riskFields.name, stage: 'product', run_id: riskRunFixture.id, run_hash: riskRunFixture.content_hash, method: 'ols', as_of: researchDay, data_as_of: researchDay, frequency: 'monthly', inputs: [riskFactor], outputs: [], targets: riskRunFixture.targets, target_keys: riskRunFixture.target_keys, effective_at: `${researchDay}T01:02:00Z`, expires_at: '2099-12-31T00:00:00Z', created_at: `${researchDay}T01:02:00Z`, status: 'active', usage: 'research_only', note: 'fixture' }
export const scenarioDraftFixture: ScenarioDraft = { name: '市场下跌假设', description: '', entry: 'market', frequency: 'monthly', event_template: 'custom', event_model_release_id: null, macro_model_release_id: null, input_ids: [riskFactor.id], rows: [[-10]], shock_basis: 'period_change' }
export const scenarioPreviewFixture: ScenarioPreview = { id: 'transient-scenario-preview', preview_hash: '2222222222222222222222222222222222222222222222222222222222222222', transient: true, name: scenarioDraftFixture.name, entry: 'market', definition: scenarioDraftFixture, definition_hash: 'fixture-definition-hash', frequency: 'monthly', input_variables: [riskFactor], factors: [riskFactor], path: [[-0.1]], horizon: 1, lineage: [], limitations: ['确定性假设不是预测。'], execution: riskAudit }
export const scenarioReleaseFixture: ScenarioRelease = { id: 'research-release-scenario', name: scenarioDraftFixture.name, entry: 'market', preview_id: scenarioPreviewFixture.id, frequency: 'monthly', factors: [riskFactor], horizon: 1, lineage: [], status: 'active', effective_at: `${researchDay}T01:02:00Z`, expires_at: '2099-12-31T00:00:00Z', created_at: `${researchDay}T01:02:00Z`, note: 'fixture' }
export const impactFixture: RiskImpact = { id: 'research-impact-fixture', name: '测试基金甲 · 市场下跌假设', request: { scenario_release_id: scenarioReleaseFixture.id, exposure_release_id: riskReleaseFixture.id, target: { kind: 'product', product_key: 'fund:000001.OF' }, as_of: researchDay, holding_policy: 'buy_and_hold', hold_other_factors_constant: true, notional: 1000000, usage: 'research' }, as_of: researchDay, created_at: `${researchDay}T01:03:00Z`, content_hash: 'fixture-impact-hash', target: { kind: 'product', name: '测试基金甲' }, summary: { terminal_return: -0.07, terminal_nav: 0.93, max_drawdown: 0.07, pnl_amount: -70000, asset_reconciliation_error: 0, factor_reconciliation_error: 0 }, path: [{ step: 1, return: -0.07, nav: 0.93, drawdown: 0.07 }], by_asset: [{ ...riskRunFixture.targets[0], weight: 1, contribution: -0.07 }], by_factor: [{ id: riskFactor.id, name: riskFactor.name, contribution: -0.07 }], lineage: [], limitations: ['不包含模型外风险。'], execution: riskAudit, assumed_unchanged_factors: [], frequency: 'monthly', transient: true }
