#!/usr/bin/env python3
"""Deterministic Pydantic -> TypeScript contracts; --check refuses drift."""
from __future__ import annotations
import argparse
import json
from pathlib import Path
from pydantic import BaseModel
from pydantic.json_schema import models_json_schema
from backend.strategic_allocation import risk_scale_contracts, reference_contracts

TARGET = Path(__file__).resolve().parents[1] / 'frontend/src/services/riskScaleContract.generated.ts'


def render_type(schema):
    if '$ref' in schema:
        return schema['$ref'].split('/')[-1]
    if 'const' in schema:
        return json.dumps(schema['const'], ensure_ascii=False)
    if 'enum' in schema:
        return ' | '.join(json.dumps(x, ensure_ascii=False) for x in schema['enum'])
    if 'anyOf' in schema or 'oneOf' in schema:
        return ' | '.join(render_type(x) for x in schema.get('anyOf', schema.get('oneOf')))
    kind = schema.get('type')
    if kind in ('number', 'integer'):
        return 'number'
    if kind in ('string', 'boolean', 'null'):
        return kind
    if kind == 'array':
        return 'Array<' + render_type(schema.get('items', {})) + '>'
    if kind == 'object':
        if 'properties' in schema:
            return '{ ' + '; '.join(json.dumps(k) + ('' if k in schema.get('required', []) else '?') + ': ' + render_type(v)
                                   for k,v in schema['properties'].items()) + ' }'
        value = schema.get('additionalProperties', {})
        return 'Record<string, ' + (render_type(value) if isinstance(value, dict) else 'unknown') + '>'
    return 'unknown'


def generate():
    classes = sorted({v for module in (risk_scale_contracts, reference_contracts) for v in vars(module).values()
                      if isinstance(v, type) and issubclass(v, BaseModel) and v.__module__ == module.__name__}, key=lambda x:x.__name__)
    _, schema = models_json_schema([(x, 'validation') for x in classes], ref_template='#/$defs/{model}')
    output = ['// Generated by scripts/export_risk_scale_contracts.py. Do not edit.',
              '// Backend/OpenAPI is the only contract source. Decimal values are not display percentages.', '']
    for name, definition in sorted(schema['$defs'].items()):
        output.append(f'export type {name} = {render_type(definition)}')
    ids = schema['$defs']['Segmentation']['properties']['algorithm_id']['enum']
    output.extend(['', 'export const riskScaleAlgorithmIds = ' + json.dumps(ids) + ' as const',
        'export type RiskScaleAlgorithmId = typeof riskScaleAlgorithmIds[number]',
        'export function isRiskScaleAlgorithmId(value: unknown): value is RiskScaleAlgorithmId {',
        '  return typeof value === "string" && riskScaleAlgorithmIds.some(id => id === value)', '}', ''])
    return '\n'.join(output)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != expected:
            raise SystemExit('Risk Scale generated contracts are stale; run export_risk_scale_contracts.py')
        print('Risk Scale contracts match Pydantic')
    else:
        TARGET.write_text(expected)
        print(TARGET)
