#!/usr/bin/env python3
"""Generate LTCMA request/lifecycle types using the project's existing schema renderer."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from pydantic import BaseModel, TypeAdapter
from pydantic.json_schema import models_json_schema

from scripts.export_risk_scale_contracts import render_type
from backend.strategic_allocation import cma_center_contracts, cma_model_contracts
from backend.strategic_allocation.contracts import CmaRequest, PolicyRequest

TARGET = Path(__file__).resolve().parents[1] / "frontend/src/services/ltcmaContract.generated.ts"


def generate():
    classes = {CmaRequest, PolicyRequest}
    for module in (cma_center_contracts, cma_model_contracts):
        classes.update(value for value in vars(module).values() if isinstance(value, type)
                       and issubclass(value, BaseModel) and value.__module__ == module.__name__)
    _, schema = models_json_schema([(x, "validation") for x in sorted(classes, key=lambda x: x.__name__)],
                                   ref_template="#/$defs/{model}")
    result = ["// Generated by scripts/export_ltcma_contracts.py. Do not edit.",
              "// Backend contracts are authoritative; rates use decimals.", ""]
    for name, definition in sorted(schema["$defs"].items()):
        result.append(f"export type {name} = {render_type(definition)}")
    methods = ["manual", *TypeAdapter(cma_model_contracts.CmaModelRequest).json_schema()["discriminator"]["mapping"]]
    result.extend(["", "export const cmaMethodIds = " + json.dumps(methods) + " as const",
                   "export type CmaMethodId = typeof cmaMethodIds[number]", ""])
    return "\n".join(result)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != expected:
            raise SystemExit("LTCMA contracts are stale; run export_ltcma_contracts.py")
        print("LTCMA contracts match Pydantic")
    else:
        TARGET.write_text(expected)
        print(TARGET)
