#!/usr/bin/env python3
"""Generate mandate input types using the existing schema renderer; --check detects drift."""
import argparse
from pathlib import Path

from pydantic.json_schema import models_json_schema
from backend.strategic_allocation.contracts import MandateRequest, MandateStudyRequest
from scripts.export_risk_scale_contracts import render_type

TARGET = Path(__file__).resolve().parents[1] / 'frontend/src/services/mandateContract.generated.ts'


def generate():
    _, schema = models_json_schema([(MandateRequest, 'validation'), (MandateStudyRequest, 'validation')], ref_template='#/$defs/{model}')
    lines = ['// Generated by scripts/export_mandate_contracts.py. Do not edit.',
             '// Input decimals and immutable references follow the backend contract.', '']
    lines.extend(f'export type {name} = {render_type(definition)}' for name, definition in sorted(schema['$defs'].items()))
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != expected:
            raise SystemExit('Mandate contracts are stale; run export_mandate_contracts.py')
        print('Mandate contracts match Pydantic')
    else:
        TARGET.write_text(expected)
        print(TARGET)
