import { test,expect } from '@playwright/test'

test('real source → products and costs → validation → finalize → export and copy',async({page,request},testInfo)=>{
  const body=await(await request.get('/api/test/implementation-candidate')).json()
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto(`/pre-investment/product-allocation-timing?source=${body.source.id}`)
  await expect(page.getByRole('heading',{name:'产品实施',exact:true})).toBeVisible()
  for(const product of body.products){
    const section=page.getByRole('region',{name:product.product_id,exact:true})
    await section.getByText('费用与到账信息',{exact:false}).click()
    await section.getByLabel('买入每边费率（%）',{exact:true}).fill(String(product.buy_rate*100))
    await section.getByLabel('卖出每边费率（%）',{exact:true}).fill(String(product.sell_rate*100))
    await section.getByLabel('费率复核日',{exact:true}).fill(product.fee_valid_until)
    await section.getByLabel('费率依据与范围',{exact:true}).fill(product.fee_source)
    await section.getByRole('combobox',{name:'净值是否已含管理费',exact:true}).selectOption('true')
  }
  await page.getByLabel(/我已确认 CMA/).check()
  await page.getByRole('button',{name:'下一步：核对资金',exact:true}).click()
  await page.getByLabel('确认的可投资总价值',{exact:true}).fill('100000')
  await page.getByLabel('可支付现金',{exact:true}).fill('100000')
  await page.getByLabel('余额确认依据',{exact:true}).fill('离线浏览器已确认余额')
  await page.getByLabel(/我接受将冻结 CMA/).check()
  await page.getByRole('button',{name:'检查当前方案',exact:true}).click()
  await expect(page.getByRole('heading',{name:'产品组合的实际风险',exact:true})).toBeVisible({timeout:30000})
  await page.screenshot({path:testInfo.outputPath('funding-and-report.png'),fullPage:true})
  await page.getByRole('button',{name:'保存研究包并去验证',exact:true}).click()
  await expect(page.getByRole('heading',{name:'研究验证',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'锁定候选并独立验证',exact:true}).click()
  await expect(page.getByText('已完成锁定候选验证',{exact:true})).toBeVisible({timeout:30000})
  await page.getByRole('button',{name:'核对报告并定稿',exact:true}).click()
  await page.getByLabel('研究负责人',{exact:true}).fill('离线研究员')
  await page.getByLabel('下次复核日期',{exact:true}).fill(body.products[0].fee_valid_until)
  await page.getByLabel('定稿理由与限制',{exact:true}).fill('验证来源、费用和资金，保留实施证据限制')
  await page.getByLabel(/我已核对报告并接受/).check()
  await page.getByRole('button',{name:'确认研究定稿',exact:true}).click()
  await expect(page.getByText(/此版本已锁定/)).toBeVisible({timeout:30000})
  const href=await page.getByRole('link',{name:'导出完整研究包'}).getAttribute('href')
  const exported=await request.get(href!);expect(exported.ok()).toBeTruthy();expect(exported.headers()['content-type']).toContain('application/zip')
  await page.screenshot({path:testInfo.outputPath('finalized.png'),fullPage:true})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBeTruthy()
  const originalId=new URL(page.url()).searchParams.get('package')!
  const original=await(await request.get(`/api/pre-investment/packages/${originalId}`)).json()
  await page.getByRole('link',{name:'复制重研',exact:true}).click()
  await expect(page.getByRole('button',{name:'保存研究包并去验证',exact:true})).toBeEnabled()
  const copyResponse=page.waitForResponse(response=>response.url().endsWith('/api/pre-investment/packages')&&response.request().method()==='POST')
  await page.getByRole('button',{name:'保存研究包并去验证',exact:true}).click()
  const copied=await(await copyResponse).json()
  expect(copied.copied_from_id).toBe(original.package.id)
  await expect(page.getByRole('heading',{name:'研究验证',exact:true})).toBeVisible()
  await page.goto(`/pre-investment/product-allocation-timing?package=${copied.scheme_id}`)
  await page.getByLabel('方案名称',{exact:true}).fill('复制后重新打开并编辑')
  const editResponse=page.waitForResponse(response=>response.url().endsWith(`/api/pre-investment/packages/${copied.scheme_id}`)&&response.request().method()==='PUT')
  await page.getByRole('button',{name:'保存研究包并去验证',exact:true}).click()
  const edited=await(await editResponse).json()
  expect(edited.copied_from_id).toBe(original.package.id)
  const history=await(await request.get(`/api/pre-investment/packages/${copied.scheme_id}`)).json()
  expect(history.history.every((item:{copied_from_id:string})=>item.copied_from_id===original.package.id)).toBeTruthy()
  expect(errors).toEqual([])
})
