import { test, expect, type Page } from '@playwright/test'
import { spawn, type ChildProcess } from 'node:child_process'
import { createServer } from 'node:net'
import path from 'node:path'

let backend: ChildProcess | undefined
let apiRoot = ''
let logs = ''
test.beforeAll(async ({ request }) => {
  test.setTimeout(120_000)
  const socket = createServer()
  await new Promise<void>((resolve, reject) => { socket.once('error', reject); socket.listen(0, '127.0.0.1', resolve) })
  const address = socket.address()
  if (!address || typeof address === 'string') throw new Error('No test port available')
  const port = address.port
  await new Promise<void>(resolve => socket.close(() => resolve()))
  apiRoot = `http://127.0.0.1:${port}`
  backend = spawn(process.env.INDICATOR_TEST_PYTHON || 'python3', ['-m', 'uvicorn', 'indicator_formula_app:app', '--app-dir', 'tests', '--host', '127.0.0.1', '--port', String(port)], {
    cwd: path.resolve(process.cwd(), '../backend'), env: { ...process.env, ALL_PROXY: '', HTTP_PROXY: '', HTTPS_PROXY: '', NO_PROXY: '127.0.0.1,localhost' }, stdio: ['ignore', 'pipe', 'pipe'],
  })
  backend.stdout?.on('data', data => { logs = (logs + String(data)).slice(-8000) })
  backend.stderr?.on('data', data => { logs = (logs + String(data)).slice(-8000) })
  backend.on('error', error => { logs += error.message })
  await expect.poll(async () => {
    if (backend?.exitCode != null) throw new Error(logs)
    try { return (await request.get(`${apiRoot}/ready`, { timeout: 1000 })).ok() } catch { return false }
  }, { timeout: 100_000, message: 'Isolated real indicator API did not start' }).toBe(true)
})
// Drain proxied requests before Playwright closes the page or stops the fixture API.
test.afterEach(async ({ page }) => { await page.unrouteAll({ behavior: 'wait' }) })
test.afterAll(async () => {
  if (!backend || backend.exitCode !== null) return
  const stopped = new Promise<void>(resolve => backend?.once('exit', () => resolve()))
  backend.kill('SIGTERM')
  await Promise.race([stopped, new Promise<void>(resolve => setTimeout(resolve, 10_000))])
  if (backend.exitCode === null) backend.kill('SIGKILL')
})
async function routeApi(page: Page) {
  await page.route('**/api/custom-indicators**', async route => {
    const url = new URL(route.request().url())
    const response = await route.fetch({ url: `${apiRoot}${url.pathname}${url.search}`, timeout: 90_000 })
    await route.fulfill({ response })
  })
}
async function enterCanvas(page: Page) {
  await page.goto('/settings/indicators-models')
  await page.getByRole('button', { name: /5 日滚动年化夏普比率 时序 内置/ }).click()
  const resolved = page.waitForResponse(response => response.url().endsWith('/graph/resolve') && response.request().postDataJSON().source_kind === 'formula')
  await page.getByRole('tab', { name: '画布构建' }).click()
  const response = await resolved
  expect(response.status()).toBe(200)
  const body = await response.json()
  expect(body.valid, JSON.stringify(body.diagnostics)).toBe(true)
  expect(body.compile_status).toBe('not_requested')
  await expect(page.getByRole('button', { name: '应用到指标' })).toBeEnabled()
  return body
}

test('真实接口：画布编辑、保护旧结果、公式往返、保存和独立布局', async ({ page }, testInfo) => {
  test.setTimeout(120_000)
  const pageErrors: string[] = []
  page.on('pageerror', error => pageErrors.push(error.message))
  await routeApi(page)
  const restored = await enterCanvas(page)
  const rolling = restored.graph.nodes.find((node: { operator_id?: string }) => node.operator_id === 'rolling_apply')
  expect(rolling).toBeTruthy()
  const mobile = (page.viewportSize()?.width || 0) < 768
  if (!mobile) {
    const bounds = await page.getByTestId('indicator-graph-flow').boundingBox()
    expect(bounds!.height).toBeGreaterThanOrEqual(550)
    expect(bounds!.width).toBeGreaterThan(500)
    await expect(page.locator('#indicator-panel-library')).toBeHidden()
  }
  await page.getByRole('button', { name: '全屏编辑' }).click()
  await expect(page.getByRole('dialog', { name: '指标画布全屏编辑' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('canvas-fullscreen.png'), fullPage: false })
  const node = mobile ? page.locator(`[data-node-id="${rolling.id}"]`).getByRole('button').first() : page.locator(`.react-flow__node[data-id="${rolling.id}"]`)
  await node.click()
  const windowInput = page.getByRole('spinbutton', { name: /窗口.*常量/ })
  await expect(windowInput).toHaveValue('5')
  await windowInput.fill('15')
  await expect(page.getByText('尚未应用', { exact: true })).toBeVisible()
  const checkedPromise = page.waitForResponse(response => response.url().endsWith('/graph/resolve') && response.request().postDataJSON().source_kind === 'graph')
  await page.getByRole('button', { name: '检查画布', exact: true }).click()
  const checked = await (await checkedPromise).json()
  expect(checked.valid, JSON.stringify(checked.diagnostics)).toBe(true)
  expect(checked.expressions.value).toContain('rolling_apply(')
  expect(checked.expressions.value).toContain('std(returns, 1)')
  expect(checked.expressions.value).toMatch(/, 15(?:\.0)?, observation_dates, annual_risk_free_rate_decimal\)$/)
  await expect(page.getByText('尚未应用', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: '指标画布全屏编辑' })).toBeHidden()
  await expect(page.getByRole('button', { name: '全屏编辑' })).toBeFocused()
  const headerSave = page.getByRole('button', { name: '复制为新指标', exact: true }).first()
  await expect(headerSave).toBeDisabled()
  await page.getByRole('button', { name: '应用到指标', exact: true }).click()
  await expect(page.getByText('尚未应用', { exact: true })).toBeHidden()
  await page.getByRole('tab', { name: '高级公式模式' }).click()
  const source = await page.getByRole('textbox', { name: /公式源码/ }).inputValue()
  expect(source).toContain(String.raw`\operatorname{rolling_apply}`)
  expect(source).toContain(',15')
  await page.getByRole('tab', { name: '画布构建' }).click()
  await expect(page.getByRole('button', { name: '应用到指标' })).toBeEnabled()
  const savedPromise = page.waitForResponse(response => new URL(response.url()).pathname === '/api/custom-indicators' && response.request().method() === 'POST')
  await headerSave.click()
  const savedResponse = await savedPromise
  expect(savedResponse.status()).toBeLessThan(300)
  const saved = await savedResponse.json()
  await expect(page.getByText(/已另存为新指标/)).toBeVisible()
  const initialState = await (await page.request.get(`${apiRoot}/api/custom-indicators/${saved.id}/editor-state?revision=${saved.revision}`)).json()
  expect(initialState.editor_revision).toBeGreaterThan(0)
  await page.getByRole('button', { name: '全屏编辑' }).click()
  await page.getByRole('button', { name: '自动排布', exact: true }).click()
  if (mobile) await page.getByTestId('indicator-graph-mobile').getByRole('button', { name: /^右移/ }).first().click()
  else {
    const targetNode = page.locator('.react-flow__node').first()
    const bounds = await targetNode.boundingBox()
    await page.mouse.move(bounds!.x + 60, bounds!.y + 20)
    await page.mouse.down()
    await page.mouse.move(bounds!.x + 100, bounds!.y + 70, { steps: 6 })
    await page.mouse.up()
  }
  await expect(page.getByText('尚未应用', { exact: true })).toBeHidden()
  const layoutResponsePromise = page.waitForResponse(response => response.url().includes('/editor-state') && response.request().method() === 'PUT')
  await page.getByRole('button', { name: '保存布局', exact: true }).click()
  const layoutResponse = await layoutResponsePromise
  expect(layoutResponse.status()).toBe(200)
  const layout = await layoutResponse.json()
  expect(layout.editor_revision).toBe(initialState.editor_revision + 1)
  const reloaded = await (await page.request.get(`${apiRoot}/api/custom-indicators/${saved.id}`)).json()
  expect(reloaded.revision).toBe(saved.revision)
  await page.keyboard.press('Escape')
  const previewTab = mobile ? page.getByRole('tab', { name: '预览', exact: true }) : page.getByRole('tab', { name: /校验与预览/ })
  await previewTab.click()
  await expect(page.getByRole('region', { name: '指标定义校验' })).toBeVisible()
  await expect(page.getByText('层级计算 DAG', { exact: true })).toHaveCount(0)
  await expect(page.getByTestId('indicator-graph-canvas')).toBeHidden()
  await page.reload()
  await page.getByRole('button', { name: new RegExp(`${saved.name} 时序 v${saved.revision}`) }).click()
  const statePromise = page.waitForResponse(response => response.url().includes(`/${saved.id}/editor-state`) && response.request().method() === 'GET')
  await page.getByRole('tab', { name: '画布构建' }).click()
  const persisted = await (await statePromise).json()
  expect(persisted.editor_revision).toBe(layout.editor_revision)
  expect(persisted.state.positions).toEqual(layout.state.positions)
  await expect(page.getByRole('button', { name: '应用到指标' })).toBeEnabled()
  await expect(page.getByText('尚未应用', { exact: true })).toBeHidden()
  expect(pageErrors).toEqual([])
})

test('多通道共享计算、下拉选择上游、原生资源拖放与端口连线', async ({ page }) => {
  test.setTimeout(60_000)
  page.setDefaultTimeout(10_000)
  await routeApi(page)
  const original = await enterCanvas(page)
  const mean = original.graph.nodes.find((node: { operator_id?: string }) => node.operator_id === 'mean')
  const rolling = original.graph.nodes.find((node: { operator_id?: string }) => node.operator_id === 'rolling_apply')
  await page.getByTestId('indicator-graph-canvas').getByRole('button', { name: '添加输出通道', exact: true }).click()
  await page.getByRole('combobox', { name: '结果来源', exact: true }).selectOption(rolling.id)
  await page.getByRole('textbox', { name: '通道名称', exact: true }).fill('共享滚动夏普')
  await page.getByRole('textbox', { name: '通道标识', exact: true }).fill('shared_sharpe')
  await page.getByRole('textbox', { name: '通道标识', exact: true }).press('Tab')
  await page.getByRole('button', { name: '收起', exact: true }).click()
  const applyResponse = page.waitForResponse(response => response.url().endsWith('/graph/resolve') && response.request().postDataJSON().source_kind === 'graph')
  await page.getByRole('button', { name: '应用到指标', exact: true }).click()
  const applied = await (await applyResponse).json()
  expect(applied.valid, JSON.stringify(applied.diagnostics)).toBe(true)
  expect(applied.expressions.shared_sharpe).toBe(applied.expressions.value)
  expect(applied.graph.nodes.filter((node: { operator_id?: string }) => node.operator_id === 'rolling_apply')).toHaveLength(1)
  const mobile = (page.viewportSize()?.width || 0) < 768
  if (!mobile) {
    await page.getByRole('button', { name: '全屏编辑', exact: true }).click()
    await page.getByRole('button', { name: '添加步骤', exact: true }).click()
    await page.getByRole('searchbox', { name: '搜索画布资源' }).fill('returns')
    const resource = page.getByRole('complementary', { name: '画布资源库' }).getByRole('button', { name: /^复权净值普通收益率/ })
    const countBeforeDrag = await page.locator('.react-flow__node').count()
    await resource.dragTo(page.getByTestId('indicator-graph-flow'), { targetPosition: { x: 100, y: 100 } })
    await expect(page.getByRole('combobox', { name: '输入数据', exact: true })).toBeVisible()
    await expect(page.locator('.react-flow__node')).toHaveCount(countBeforeDrag + 1)
    await page.getByRole('button', { name: '收起', exact: true }).click()
    await page.getByRole('button', { name: '自动排布', exact: true }).click()
    const knownIds = new Set(original.graph.nodes.map((node: { id: string }) => node.id))
    const allIds = await page.locator('.react-flow__node').evaluateAll(elements => elements.map(element => element.getAttribute('data-id')))
    const insertedId = allIds.find(id => id && !knownIds.has(id) && !id.startsWith('output_'))
    expect(insertedId).toBeTruthy()
    const source = page.locator(`.react-flow__node[data-id="${insertedId}"] .react-flow__handle.source`)
    const dataParameter = Object.entries(mean.arguments).find(([, binding]) => original.graph.nodes.some((node: { id: string; kind: string }) => node.id === (binding as { node_id: string }).node_id && node.kind === 'variable'))?.[0]
    const target = page.locator(`.react-flow__node[data-id="${mean.id}"] .react-flow__handle.target[data-handleid="${dataParameter}"]`)
    const start = await source.boundingBox(), end = await target.boundingBox()
    await page.mouse.move(start!.x + start!.width / 2, start!.y + start!.height / 2)
    await page.mouse.down()
    await page.mouse.move(end!.x + end!.width / 2, end!.y + end!.height / 2, { steps: 12 })
    await page.mouse.up()
    const connectedResponse = page.waitForResponse(response => response.url().endsWith('/graph/resolve') && response.request().postDataJSON().source_kind === 'graph')
    await page.getByRole('button', { name: '应用到指标', exact: true }).click()
    const connected = await (await connectedResponse).json()
    expect(connected.valid, JSON.stringify(connected.diagnostics)).toBe(true)
    const connectedInputs = connected.graph.nodes.find((node: { id: string }) => node.id === mean.id).arguments
    expect(Object.values(connectedInputs).some(binding => (binding as { source: string; node_id?: string }).source === 'node' && (binding as { node_id?: string }).node_id === insertedId)).toBe(true)
    await page.keyboard.press('Escape')
  }
  const validated = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators/validate'))
  await (mobile ? page.getByRole('tab', { name: '预览', exact: true }) : page.getByRole('tab', { name: /校验与预览/ })).click()
  const checked = await (await validated).json()
  expect(checked.valid, JSON.stringify(checked.diagnostics)).toBe(true)
  expect(Object.keys(checked.dag.roots)).toEqual(['value', 'shared_sharpe'])
})

test('中文画布：节点、参数、上游选项和数据依赖不泄露类型代码', async ({ page }, testInfo) => {
  test.setTimeout(60_000)
  page.setDefaultTimeout(10_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await routeApi(page)
  await page.goto('/settings/indicators-models')
  await page.getByRole('button', { name: /Sortino 比率 标量 内置/ }).click()
  const restoredPromise = page.waitForResponse(response => response.url().endsWith('/graph/resolve') && response.request().postDataJSON().source_kind === 'formula')
  await page.getByRole('tab', { name: '画布构建' }).click()
  const restored = await (await restoredPromise).json()
  expect(restored.valid).toBe(true)
  const compare = restored.graph.nodes.find((node: { operator_id?: string }) => node.operator_id === 'less_than')
  expect(compare).toBeTruthy()
  const rawCode = /\b(?:returns|risk_free_rate_per_observation|periods_per_year|scalar|series|vector|matrix|mask|time)\b|<T>|<A,B>/i
  const canvas = page.getByTestId('indicator-graph-canvas')
  await expect(canvas).not.toContainText(rawCode)
  expect((await canvas.locator('[title]').evaluateAll(elements => elements.map(element => element.getAttribute('title')).join(' ')))).not.toMatch(rawCode)
  const disclosure = page.locator('details').filter({ has: page.getByText('查看生成公式与数据依赖', { exact: true }) })
  await disclosure.locator('summary').click()
  await expect(disclosure).toContainText('复权净值普通收益率')
  await expect(disclosure).toContainText('单观察期无风险收益率')
  await expect(disclosure).toContainText('年化因子')
  await expect(disclosure).not.toContainText(rawCode)
  await expect(disclosure.locator('.katex')).toBeVisible()
  await disclosure.screenshot({ path: testInfo.outputPath('canvas-chinese-dependencies.png') })
  const mobile = (page.viewportSize()?.width || 0) < 768
  await (mobile ? page.locator(`[data-node-id="${compare.id}"]`).getByRole('button').first() : page.locator(`.react-flow__node[data-id="${compare.id}"]`)).click()
  const inspector = page.getByRole('complementary', { name: '画布属性' })
  await expect(inspector).toContainText('单个数值、时间序列、一维数组、矩阵（二维数据）')
  await expect(inspector).toContainText('时间条件序列（是／否）')
  await expect(inspector).toContainText('对齐维度：时间')
  await expect(inspector).not.toContainText(rawCode)
  const upstream = Object.values(compare.arguments).find(binding => (binding as { source: string }).source === 'node') as { node_id: string }
  await expect(inspector.getByRole('combobox', { name: '输入 A输入来源' })).toHaveValue(upstream.node_id)
  await inspector.screenshot({ path: testInfo.outputPath('canvas-chinese-inspector.png') })
  await page.getByRole('button', { name: '收起', exact: true }).click()
  // Presentation changes must not alter the executable formula or dependencies.
  const checkedPromise = page.waitForResponse(response => response.url().endsWith('/graph/resolve') && response.request().postDataJSON().source_kind === 'graph')
  await page.getByRole('button', { name: '检查画布', exact: true }).click()
  const checkedResponse = await checkedPromise
  const checked = await checkedResponse.json()
  expect(checked.valid, JSON.stringify(checked.diagnostics)).toBe(true)
  // The DSL can spell the same power as power(x, 2) or x ** 2. Compare
  // untouched graph bindings and mathematical notation, not source spelling.
  expect(checkedResponse.request().postDataJSON().graph.nodes).toEqual(restored.graph.nodes)
  expect(checked.display_latex).toEqual(restored.display_latex)
  expect(checked.dependencies).toEqual(restored.dependencies)
  expect(checked.node_types[compare.id].dtype).toBe('bool')
  expect(errors).toEqual([])
})

test('独立常量节点、分类外观、参数同步及精简工具栏', async ({ page }, testInfo) => {
  test.setTimeout(60_000)
  page.setDefaultTimeout(10_000)
  await routeApi(page)
  const original = await enterCanvas(page)
  const rolling = original.graph.nodes.find((node: { operator_id?: string }) => node.operator_id === 'rolling_apply')
  const literal = original.graph.nodes.find((node: { id: string; kind: string; value?: number }) => node.kind === 'constant' && node.value === 5 && Object.values(rolling.arguments).some(binding => (binding as { node_id: string }).node_id === node.id))
  expect(literal).toBeTruthy()
  expect(original.graph.nodes.filter((node: { kind: string; value?: number }) => node.kind === 'constant' && node.value === 5)).toHaveLength(1)
  const legend = page.getByLabel('节点类型图例')
  for (const label of ['输入变量', '固定常量', '计算算子', '指标输出']) await expect(legend).toContainText(label)
  // Only the canvas output node remains, not a duplicate footer shortcut.
  await expect(page.getByRole('button', { name: '最终结果', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '保存布局', exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: '全屏编辑' }).click()
  const mobile = (page.viewportSize()?.width || 0) < 768
  const canvas = mobile ? page.getByTestId('indicator-graph-mobile') : page.getByTestId('indicator-graph-flow')
  for (const kind of ['variable', 'constant', 'operator', 'output']) await expect(canvas.locator(`[data-node-kind="${kind}"]`).first()).toBeVisible()
  const constantElement = mobile ? canvas.locator(`[data-node-id="${literal.id}"]`).getByRole('button').first() : canvas.locator(`.react-flow__node[data-id="${literal.id}"]`)
  await constantElement.click()
  await page.getByRole('spinbutton', { name: '常量值', exact: true }).fill('15')
  await page.getByRole('button', { name: '收起', exact: true }).click()
  const rollingElement = mobile ? canvas.locator(`[data-node-id="${rolling.id}"]`).getByRole('button').first() : canvas.locator(`.react-flow__node[data-id="${rolling.id}"]`)
  await rollingElement.click()
  await expect(page.getByRole('spinbutton', { name: /窗口.*常量/ })).toHaveValue('15')
  await page.getByRole('button', { name: '收起', exact: true }).click()
  const responsePromise = page.waitForResponse(response => response.url().endsWith('/graph/resolve') && response.request().postDataJSON().source_kind === 'graph')
  await page.getByRole('button', { name: '检查画布', exact: true }).click()
  const result = await (await responsePromise).json()
  expect(result.valid, JSON.stringify(result.diagnostics)).toBe(true)
  expect(result.expressions.value).toContain('rolling_apply(')
  expect(result.expressions.value).toContain('std(returns, 1)')
  expect(result.expressions.value).toMatch(/, 15(?:\.0)?, observation_dates, annual_risk_free_rate_decimal\)$/)
  await page.screenshot({ path: testInfo.outputPath('typed-constant-nodes.png'), fullPage: false })
})

test('资源增删和撤销，窄屏不横向溢出', async ({ page }, testInfo) => {
  test.setTimeout(120_000)
  await routeApi(page)
  await enterCanvas(page)
  await page.getByRole('button', { name: '添加常量', exact: true }).click()
  await page.getByRole('spinbutton', { name: '常量值', exact: true }).fill('2')
  await expect(page.getByText('尚未应用', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '删除步骤', exact: true }).click()
  await expect(page.getByText('尚未应用', { exact: true })).toBeHidden()
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await expect(page.getByText('尚未应用', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '重做', exact: true }).click()
  await expect(page.getByText('尚未应用', { exact: true })).toBeHidden()
  await page.getByRole('button', { name: '添加步骤', exact: true }).click()
  await page.getByRole('searchbox', { name: '搜索画布资源' }).fill('收益率')
  await expect(page.getByRole('complementary', { name: '画布资源库' })).toBeVisible()
  const horizontalOverflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)
  expect(horizontalOverflow).toBeLessThanOrEqual(2)
  await page.screenshot({ path: testInfo.outputPath('canvas-resources.png'), fullPage: true })
})
