import { test, expect } from '@playwright/test'
import { spawn, type ChildProcess } from 'node:child_process'
import { createServer } from 'node:net'
import path from 'node:path'

let backend: ChildProcess | undefined
let api = ''
let logs = ''
test.beforeAll(async ({ request }) => {
  test.setTimeout(150_000)
  const socket = createServer()
  await new Promise<void>((resolve, reject) => { socket.once('error', reject); socket.listen(0, '127.0.0.1', resolve) })
  const address = socket.address()
  if (!address || typeof address === 'string') throw new Error('No test port')
  const port = address.port
  await new Promise<void>(resolve => socket.close(() => resolve()))
  api = `http://127.0.0.1:${port}`
  backend = spawn(process.env.INDICATOR_TEST_PYTHON || 'python3', ['-m', 'uvicorn', 'indicator_primitives_app:app', '--app-dir', 'tests', '--host', '127.0.0.1', '--port', String(port)], {
    cwd: path.resolve(process.cwd(), '../backend'), env: { ...process.env, PYTHONPATH: [path.resolve(process.cwd(), '..'), path.resolve(process.cwd(), '../backend')].join(path.delimiter), ALL_PROXY: '', HTTP_PROXY: '', HTTPS_PROXY: '', NO_PROXY: '127.0.0.1,localhost', OPENBLAS_NUM_THREADS: '1', OMP_NUM_THREADS: '1', NUMBA_NUM_THREADS: '1' }, stdio: ['ignore', 'pipe', 'pipe'],
  })
  backend.stdout?.on('data', data => { logs = (logs + String(data)).slice(-8000) })
  backend.stderr?.on('data', data => { logs = (logs + String(data)).slice(-8000) })
  await expect.poll(async () => {
    if (backend?.exitCode != null) throw new Error(logs)
    try { return (await request.get(`${api}/ready`, { timeout: 1000 })).ok() } catch { return false }
  }, { timeout: 130_000 }).toBe(true)
})
test.afterAll(async () => {
  if (!backend || backend.exitCode !== null) return
  backend.kill('SIGTERM')
  await new Promise<void>(resolve => { const timer = setTimeout(() => { backend?.kill('SIGKILL'); resolve() }, 5000); backend?.once('exit', () => { clearTimeout(timer); resolve() }) })
})
test.beforeEach(async ({ page }) => {
  page.on('dialog', dialog => dialog.accept())
  await page.route('**/api/**', async route => {
    const url = new URL(route.request().url())
    if (url.pathname.startsWith('/api/custom-indicators')) await route.fulfill({ response: await route.fetch({ url: `${api}${url.pathname}${url.search}`, timeout: 90_000 }) })
    else if (url.pathname === '/api/instruments/search') await route.fulfill({ json: { items: [{ code: '510050.SH', ts_code: '510050.SH', name: '上证50ETF', instrument_type: 'etf' }], total: 1 } })
    else await route.fulfill({ status: 503, json: { detail: 'Isolated fixture' } })
  })
})

test('独立日期指标：数学公式、画布往返、保存预览和导出', async ({ page }, info) => {
  test.setTimeout(150_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/settings/indicators-models')
  await page.getByRole('button', { name: '新建指标', exact: true }).click()
  await expect(page.getByRole('button', { name: /添加结果|使用此计算/ })).toHaveCount(0)
  await page.getByLabel('名称', { exact: true }).fill('原语构建起点日期')
  await page.getByRole('tab', { name: '高级公式模式' }).click()
  await page.locator('#indicator-expression').fill('value_at(observation_dates, interval_start(last_drawdown_interval(drawdown_series(adjusted_nav))))')
  const checked = page.waitForResponse(response => response.url().endsWith('/validate'))
  await page.getByRole('button', { name: '解析并校验公式', exact: true }).click()
  const validation = await (await checked).json()
  expect(validation.valid, JSON.stringify(validation)).toBe(true)
  expect(validation.display_latex).not.toMatch(/value_at|interval_start|last_drawdown_interval/)
  await expect(page.getByTestId('formula-preview').locator('.katex')).toBeVisible()
  const resolving = page.waitForResponse(response => response.url().endsWith('/graph/resolve'))
  await page.getByRole('tab', { name: /画布/ }).click()
  const graph = await (await resolving).json()
  expect(graph.valid, JSON.stringify(graph)).toBe(true)
  expect(graph.graph.outputs).toHaveLength(1)
  await expect(page.getByTestId('indicator-graph-canvas')).toBeVisible()
  await page.getByRole('tab', { name: '高级公式模式' }).click()
  const savedResponse = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '保存新指标', exact: true }).first().click()
  const saved = await (await savedResponse).json()
  expect(saved.result_kind).toBe('scalar')
  expect(saved.display_format).toBe('date')
  expect(saved.scalar_outputs).toBeUndefined()
  const preview = page.locator('#workspace-tab-preview')
  if (await preview.isVisible()) await preview.click()
  else await page.locator('#indicator-tab-preview').click()
  await page.getByLabel('搜索产品', { exact: true }).fill('510050')
  await page.getByLabel('搜索产品', { exact: true }).press('Enter')
  await page.getByRole('button', { name: '添加', exact: true }).click()
  await page.getByLabel('计算周期', { exact: true }).selectOption('ALL')
  const evaluated = page.waitForResponse(response => response.url().endsWith('/evaluate'))
  await page.getByRole('button', { name: '预览指标', exact: true }).click()
  const result = await (await evaluated).json()
  expect(result.results[0].value).toBe('2026-01-08')
  await expect(page.locator('#preview-results-title')).toBeVisible()
  await expect(page.getByText('2026-01-08', { exact: true }).first()).toBeVisible()
  const downloading = page.waitForEvent('download', { timeout: 30_000 })
  await page.getByRole('button', { name: '下载 Excel 计算逻辑' }).click()
  const download = await downloading
  expect(await download.failure()).toBeNull()
  await page.screenshot({ path: info.outputPath('independent-date-preview.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  expect(errors).toEqual([])
})

test('统一算子目录与共享拟合：不生成多结果指标', async ({ request, page }) => {
  test.setTimeout(150_000)
  const meta = await (await request.get(`${api}/api/custom-indicators/meta`)).json()
  const names = meta.operators.map((item: { name: string }) => item.name)
  expect(names).toContain('linear_fit')
  for (const name of ['linear_slope', 'linear_intercept', 'total_return', 'annualized_return', 'drawdown_analysis', 'interval_depth', 'date_at']) expect(names).not.toContain(name)
  const definitions = []
  for (const [name, expression] of [['拟合斜率示例', 'fit_slope(linear_fit(adjusted_nav))'], ['拟合截距示例', 'fit_intercept(linear_fit(adjusted_nav))']]) {
    const response = await request.post(`${api}/api/custom-indicators`, { data: { name, expression, dsl_version: meta.dsl_version, direction: 'neutral' } })
    expect(response.ok(), await response.text()).toBe(true)
    definitions.push(await response.json())
  }
  const prepared = await request.post(`${api}/api/custom-indicators/prepare`, { data: { indicator_ids: definitions.map(item => item.id) } })
  const preparation = await prepared.json()
  expect(prepared.ok(), JSON.stringify(preparation)).toBe(true)
  expect(preparation.plans[0].operator_call_sites.linear_fit).toBe(1)
  const response = await request.post(`${api}/api/custom-indicators/evaluate`, { data: { indicator_refs: preparation.indicator_refs, targets: [{ kind: 'etf', product_id: '510050.SH' }], period: 'ALL' } })
  const result = await response.json()
  expect(response.ok(), JSON.stringify(result)).toBe(true)
  expect(result.results).toHaveLength(2)
  for (const item of result.results) { expect(typeof item.value).toBe('number'); expect(item.outputs).toBeUndefined() }
  expect(result.execution.python_fallback).toBe(0)
  await page.goto('/settings/indicators-models')
  await page.getByRole('button', { name: /^拟合斜率示例/ }).click()
  await page.getByRole('button', { name: '浏览公式构建资源', exact: true }).click()
  await expect(page.getByRole('dialog', { name: /编辑.*拟合斜率示例/ })).toBeVisible()
  await expect(page.getByRole('group', { name: '线性拟合结果 · 计算中间结果（需提取字段）', exact: true })).toBeVisible()
  await expect(page.getByRole('combobox', { name: '线性拟合结果 嵌套算子', exact: true })).toHaveValue('linear_fit')
})

test('保留时序参数：默认值、画布、临时覆盖和导出不受标量重构影响', async ({ page, request }, info) => {
  test.setTimeout(150_000)
  page.setDefaultTimeout(20_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const created = await request.post(`${api}/api/custom-indicators`, { data: {
    name: '浏览器可调均线', result_kind: 'time_series', axis_anchor: 'adjusted_nav',
    series_outputs: [{ id: 'ma', label: '净值均线', expression: 'mean(rolling_window(adjusted_nav, 5))', output_measure: 'auto', unit: '', display_format: 'number', precision: 4 }],
    dsl_version: '2.4.0', operator_registry_version: '2.4.0', context_kind: 'single_product',
  } })
  expect(created.ok(), await created.text()).toBe(true)
  const original = await created.json()
  await page.goto('/settings/indicators-models')
  await page.getByRole('button', { name: /^浏览器可调均线/ }).click()
  await page.getByRole('button', { name: '识别可调输入' }).click()
  await page.getByRole('button', { name: '开放为参数' }).click()
  await expect(page.getByLabel('默认值', { exact: true })).toHaveValue('5')
  await page.getByLabel('默认值', { exact: true }).fill('7')
  await page.getByRole('button', { name: '应用参数设置' }).click()
  const validating = page.waitForResponse(response => response.url().endsWith('/validate'))
  await page.getByRole('button', { name: '解析并校验全部通道' }).click()
  const validation = await (await validating).json()
  expect(validation.valid, JSON.stringify(validation.diagnostics)).toBe(true)
  const saving = page.waitForResponse(response => response.url().endsWith(`/api/custom-indicators/${original.id}`) && response.request().method() === 'PUT')
  await page.getByRole('button', { name: '保存修改', exact: true }).first().click()
  const saved = await (await saving).json()
  expect(saved.parameter_schema[0].default).toBe(7)
  expect(saved.parameter_contract_version).toBe('1.0')
  const resolving = page.waitForResponse(response => response.url().endsWith('/graph/resolve'))
  await page.getByRole('tab', { name: /画布/ }).click()
  await resolving
  const canvasNodes = page.locator('.react-flow__node')
  await expect(canvasNodes.filter({ hasText: '滚动窗口' })).toHaveCount(1)
  await expect(canvasNodes.filter({ hasText: '全元素算术平均值' })).toHaveCount(1)
  const preview = page.locator('#workspace-tab-preview')
  if (await preview.isVisible()) await preview.click()
  else await page.locator('#indicator-tab-preview').click()
  await page.getByLabel('搜索产品', { exact: true }).fill('510050')
  await page.getByLabel('搜索产品', { exact: true }).press('Enter')
  await page.getByRole('button', { name: '添加', exact: true }).click()
  await page.locator('#indicator-panel-preview select:has(option[value="ALL"])').selectOption('ALL')
  const calculating = page.waitForResponse(response => response.url().endsWith('/evaluate-series'))
  await page.getByRole('button', { name: '预览指标', exact: true }).click()
  const initial = await (await calculating).json()
  expect(initial.results[0].parameters).toEqual({ window_1: 7 })
  expect(initial.execution.request_time_compilation).toBe(0)
  await page.locator('summary').filter({ hasText: '本次计算参数' }).click()
  await page.getByLabel('窗口期数', { exact: true }).fill('3')
  await page.getByRole('button', { name: '应用参数', exact: true }).click()
  const recalculating = page.waitForResponse(response => response.url().endsWith('/evaluate-series'))
  await page.getByRole('button', { name: '预览指标', exact: true }).click()
  const overridden = await (await recalculating).json()
  expect(overridden.results[0].parameters).toEqual({ window_1: 3 })
  expect(overridden.results[0].parameter_hash).not.toBe(initial.results[0].parameter_hash)
  expect(overridden.execution.compiled_plan_ids).toEqual(initial.execution.compiled_plan_ids)
  expect(overridden.execution.python_fallback).toBe(0)
  const exporting = page.waitForRequest(request => request.url().includes('/export-excel'))
  const downloading = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载 Excel 计算逻辑' }).click()
  expect((await exporting).postDataJSON().parameters).toEqual({ window_1: 3 })
  expect(await (await downloading).failure()).toBeNull()
  await page.getByRole('button', { name: '恢复默认', exact: true }).click()
  await expect(page.getByLabel('窗口期数', { exact: true })).toHaveValue('7')
  const unchanged = await (await request.get(`${api}/api/custom-indicators/${original.id}`)).json()
  expect(unchanged.revision).toBe(saved.revision)
  expect(unchanged.parameter_schema[0].default).toBe(7)
  await page.screenshot({ path: info.outputPath('series-parameters-retained.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  expect(errors).toEqual([])
})

test('通用区间滚动：自定义回撤、搜索、画布、窗口参数与完整计算证据', async ({ page, request }, info) => {
  test.setTimeout(150_000)
  page.setDefaultTimeout(15_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const created = await request.post(`${api}/api/custom-indicators`, { data: {
    name: '浏览器区间回撤', expression: '-min_value(drawdown_series(adjusted_nav))',
    dsl_version: '2.4.0', operator_registry_version: '2.4.0', direction: 'lower_better',
  } })
  expect(created.ok(), await created.text()).toBe(true)
  const original = await created.json()
  expect(original.rolling_series_compatibility.supported).toBe(true)
  await page.goto('/settings/indicators-models')
  await page.getByRole('button', { name: /^浏览器区间回撤/ }).click()
  await page.getByRole('button', { name: '生成滚动时序指标', exact: true }).click()
  const panel = page.getByRole('region', { name: '标量指标滚动派生' })
  const sourcePicker = panel.getByRole('combobox', { name: '滚动来源标量指标' })
  // The sidebar leaves little room at tablet width. A source selector must
  // retain usable width rather than being squeezed behind adjacent controls.
  expect((await sourcePicker.boundingBox())!.width).toBeGreaterThan(160)
  await sourcePicker.click()
  await page.getByLabel('搜索滚动来源标量指标').fill('浏览器区间回撤')
  await page.getByRole('option', { name: /浏览器区间回撤/ }).click()
  await panel.getByLabel('滚动观察数', { exact: true }).fill('2.5')
  await expect(panel.getByRole('button', { name: '生成滚动公式' })).toBeDisabled()
  await panel.getByLabel('滚动观察数', { exact: true }).fill('3')
  const deriving = page.waitForResponse(response => response.url().endsWith('/derive-rolling-series'))
  await panel.getByRole('button', { name: '生成滚动公式' }).click()
  const derived = await (await deriving).json()
  expect(derived.validation.valid, JSON.stringify(derived)).toBe(true)
  expect(derived.definition.expression).toContain('rolling_apply(')
  expect(derived.definition.expression).toContain('drawdown_series(adjusted_nav)')
  await page.getByRole('button', { name: '识别可调输入' }).click()
  await page.getByRole('button', { name: '开放为参数', exact: true }).click()
  await expect(page.getByLabel('默认值', { exact: true })).toHaveValue('3')
  await page.getByLabel('默认值', { exact: true }).fill('4')
  await page.getByRole('button', { name: '应用参数设置' }).click()
  const saving = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '保存新指标', exact: true }).first().click()
  const saved = await (await saving).json()
  expect(saved.parameter_schema[0].default).toBe(4)
  await expect(page.getByText(`已保存为版本 ${saved.revision}。`, { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: /画布/ }).click()
  // Assert the current rendered graph, not a superseded/aborted resolve
  // response from the editor's restoration effect.
  const canvasNodes = page.locator('.react-flow__node')
  await expect(canvasNodes.filter({ hasText: '滚动计算' })).toHaveCount(1)
  await expect(canvasNodes.filter({ hasText: '回撤序列' })).toHaveCount(1)
  await expect(canvasNodes.filter({ hasText: '全元素最小值' })).toHaveCount(1)
  await expect(page.getByRole('region', { name: '指标画布编辑器' })).toContainText('每个窗口')
  await page.screenshot({ path: info.outputPath('whole-interval-graph.png'), fullPage: true })
  const preview = page.locator('#workspace-tab-preview')
  if (await preview.isVisible()) await preview.click()
  else await page.locator('#indicator-tab-preview').click()
  await page.getByLabel('搜索产品', { exact: true }).fill('510050')
  await page.getByLabel('搜索产品', { exact: true }).press('Enter')
  await page.getByRole('button', { name: '添加', exact: true }).click()
  await page.locator('#indicator-panel-preview select:has(option[value="ALL"])').selectOption('ALL')
  const calculating = page.waitForResponse(response => response.url().endsWith('/evaluate-series'))
  await page.getByRole('button', { name: '预览指标', exact: true }).click()
  const initial = await (await calculating).json()
  expect(initial.results[0].status, JSON.stringify(initial)).toBe('ok')
  expect(initial.results[0].channels[0].values.some((value: number | null) => value !== null)).toBe(true)
  expect(initial.execution.request_time_compilation).toBe(0)
  await page.locator('summary').filter({ hasText: '本次计算参数' }).click()
  await page.getByLabel('窗口期数', { exact: true }).fill('5')
  await page.getByRole('button', { name: '应用参数', exact: true }).click()
  const recalculating = page.waitForResponse(response => response.url().endsWith('/evaluate-series'))
  await page.getByRole('button', { name: '预览指标', exact: true }).click()
  const updated = await (await recalculating).json()
  expect(updated.results[0].lookback_observations).toBe(5)
  expect(updated.execution.compiled_plan_ids).toEqual(initial.execution.compiled_plan_ids)
  expect(updated.execution.python_fallback).toBe(0)
  const exporting = page.waitForResponse(response => response.url().endsWith('/export-excel'))
  const downloading = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载 Excel 计算逻辑' }).click()
  expect((await exporting).ok()).toBe(true)
  expect(await (await downloading).failure()).toBeNull()
  const unchanged = await (await request.get(`${api}/api/custom-indicators/${original.id}`)).json()
  expect(unchanged.revision).toBe(original.revision)
  expect(unchanged.expression).toBe(original.expression)
  await page.getByRole('button', { name: '恢复默认', exact: true }).click()
  await expect(page.getByLabel('窗口期数', { exact: true })).toHaveValue('4')
  await page.screenshot({ path: info.outputPath('whole-interval-preview.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  expect(errors).toEqual([])
})

test('内置时序迁移：v3目录、KDJ短窗口、画布与Excel', async ({ page, request }, info) => {
  test.setTimeout(150_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const catalog = await (await request.get(`${api}/api/custom-indicators`)).json()
  const builtins = catalog.items.filter((item: { source: string; result_kind: string }) => item.source === 'built_in' && item.result_kind === 'time_series')
  expect(builtins).toHaveLength(5)
  for (const definition of builtins) {
    expect(definition.revision).toBe(3)
    for (const channel of definition.series_outputs) {
      expect(channel.expression).toContain('rolling_apply(')
      expect(channel.expression).not.toContain('rolling_window(')
    }
    const validated = await request.post(`${api}/api/custom-indicators/validate`, { data: definition })
    expect(validated.ok(), await validated.text()).toBe(true)
    expect((await validated.json()).valid).toBe(true)
  }
  const calculated = await request.post(`${api}/api/custom-indicators/evaluate-series`, { data: {
    indicator_instances: builtins.map((item: { id: string }) => ({ indicator_id: item.id })),
    target: { kind: 'etf', product_id: '510050.SH' }, period: 'ALL',
  } })
  const all = await calculated.json()
  expect(all.summary.ok, JSON.stringify(all)).toBe(5)
  expect(all.execution.request_time_compilation).toBe(0)
  expect(all.execution.python_fallback).toBe(0)
  await page.goto('/settings/indicators-models')
  await page.getByRole('button', { name: /^KDJ/ }).click()
  await page.getByRole('tab', { name: /画布/ }).click()
  const canvasNodes = page.locator('.react-flow__node')
  await expect(canvasNodes.filter({ hasText: '滚动计算' })).toHaveCount(2)
  await expect(canvasNodes.filter({ hasText: '有限值判断' })).toHaveCount(2)
  await page.screenshot({ path: info.outputPath('builtin-v3-kdj-graph.png'), fullPage: true })
  const preview = page.locator('#workspace-tab-preview')
  if (await preview.isVisible()) await preview.click()
  else await page.locator('#indicator-tab-preview').click()
  await page.getByLabel('搜索产品', { exact: true }).fill('510050')
  await page.getByLabel('搜索产品', { exact: true }).press('Enter')
  await page.getByRole('button', { name: '添加', exact: true }).click()
  await page.locator('#indicator-panel-preview select:has(option[value="ALL"])').selectOption('ALL')
  const calculating = page.waitForResponse(response => response.url().endsWith('/evaluate-series'))
  await page.getByRole('button', { name: '预览指标', exact: true }).click()
  const result = await (await calculating).json()
  // Studio previews use an inline draft; version identity is verified on the
  // catalogue/reference execution above, then compare every displayed value.
  const canonical = all.results.find((item: { indicator_id: string }) => item.indicator_id === 'builtin-kdj-series')
  expect(canonical.indicator_revision).toBe(3)
  expect(result.results[0].channels).toEqual(canonical.channels)
  expect(result.results[0].channels.map((item: { id: string }) => item.id)).toEqual(['k', 'd', 'j'])
  expect(typeof result.results[0].channels[0].values[0]).toBe('number')
  expect(result.execution.request_time_compilation).toBe(0)
  const downloading = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载 Excel 计算逻辑' }).click()
  expect(await (await downloading).failure()).toBeNull()
  await page.screenshot({ path: info.outputPath('builtin-v3-kdj-preview.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  expect(errors).toEqual([])
})
