import { expect, test } from '@playwright/test'
import { auditTextContrast } from './helpers/contrast'

test('多组 API 独立保存，仅明确选用的配置生效，切换时不串密钥', async ({ page }) => {
  const profiles = [{ id: 'company', name: '公司 API', provider: 'openai-compatible', model: 'model-a', base_url: 'https://company.example/v1', configured: true, api_key_masked: '••••1234' }]
  let active: string | null = 'company'
  let failSave = false
  const writes: Array<Record<string, unknown>> = []
  const state = () => ({ profiles, active_profile_id: active, configured: !!active })
  await page.route('**/api/**', async route => {
    const path = new URL(route.request().url()).pathname
    if (!path.startsWith('/api/settings/llm')) return route.fulfill({ json: { items: [] } })
    if (route.request().method() === 'GET') return route.fulfill({ json: state() })
    const body = route.request().postDataJSON(); writes.push(body)
    if (failSave) { failSave = false; return route.fulfill({ status: 503, json: { detail: '暂时无法保存，请重试。' } }) }
    const { api_key: _secret, ...publicFields } = body
    if (path.endsWith('/active')) active = body.profile_id
    else if (path.endsWith('/profiles')) profiles.push({ ...publicFields, id: 'backup', configured: !!body.api_key, api_key_masked: '••••5678' })
    else Object.assign(profiles.find(p => path.endsWith('/' + p.id))!, publicFields)
    return route.fulfill({ json: state() })
  })
  await page.goto('/settings/llm-api')
  await expect(page.getByRole('heading', { name: 'LLM API 配置' })).toBeVisible()
  await expect(page.getByText('未选中的 API 不会被调用。', { exact: false })).toBeVisible()
  const key = page.getByLabel('API Key（留空保留此配置的密钥）', { exact: true })
  const company = page.getByLabel('API 公司 API', { exact: true })
  const editCompany = company.getByRole('button', { name: '编辑', exact: true })
  await expect(key).toHaveCount(0)
  await page.screenshot({ path: test.info().outputPath('llm-list.png'), fullPage: true })
  await editCompany.click()
  await expect(page.getByLabel('配置名称', { exact: true })).toBeFocused()
  await page.getByLabel('配置名称', { exact: true }).fill('未保存的名称')
  await key.fill('discarded-secret')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await expect(key).toHaveCount(0)
  await expect(editCompany).toBeFocused()
  expect(writes).toHaveLength(0)
  await editCompany.click()
  await expect(page.getByLabel('配置名称', { exact: true })).toHaveValue('公司 API')
  await expect(key).toHaveValue('')
  const effort = page.getByRole('combobox', { name: '思考等级', exact: true })
  const timeout = page.getByLabel('单次模型请求超时（秒）', { exact: true })
  const window = page.getByLabel('上下文窗口（tokens）', { exact: true })
  await expect(window).toHaveValue('')
  await expect(effort).toHaveValue('default')
  await expect(timeout).toHaveValue('60')
  await expect(window).toHaveValue('')
  await page.getByRole('button', { name: '新增 API', exact: true }).click()
  await expect(key).toHaveAttribute('placeholder', '填写 API Key')
  await page.getByLabel('配置名称', { exact: true }).fill('备用 API')
  await page.getByLabel('模型', { exact: true }).fill('deepseek-v4.1-flash')
  await page.getByLabel('API Base URL', { exact: true }).fill('https://opencode.ai/zen/go/v1')
  await effort.selectOption('max')
  await timeout.fill('600')
  await window.fill('131072')
  await key.fill('fixture-key-5678')
  await page.getByRole('button', { name: '保存配置', exact: true }).click()
  await expect(page.getByText('备用 API', { exact: true })).toBeVisible()
  expect(writes.at(-1)).toMatchObject({ reasoning_effort: 'max', timeout_seconds: 600, context_window_tokens: 131072 })
  await expect(page.getByLabel('API 备用 API', { exact: true })).toContainText('最高（max）')
  expect(active).toBe('company')
  await expect(key).toHaveCount(0)
  await page.getByRole('button', { name: '设为使用', exact: true }).click()
  await expect(page.getByLabel('API 备用 API', { exact: true })).toContainText('正在使用')
  expect(active).toBe('backup')
  await expect(key).toHaveCount(0)
  await company.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(key).toHaveValue('')
  await expect(key).toHaveAttribute('placeholder', '••••1234')
  await expect(effort).toHaveValue('default')
  await expect(timeout).toHaveValue('60')
  await expect(window).toHaveValue('')
  await effort.selectOption('high')
  await page.getByLabel('模型', { exact: true }).fill('model-a-updated')
  failSave = true
  await page.getByRole('button', { name: '保存配置', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('暂时无法保存')
  await expect(page.getByLabel('模型', { exact: true })).toHaveValue('model-a-updated')
  await page.getByRole('button', { name: '保存配置', exact: true }).click()
  await expect(page.getByText('openai-compatible · model-a-updated')).toBeVisible()
  expect(writes.at(-1)).not.toHaveProperty('api_key')
  expect(writes.at(-1)).toMatchObject({ reasoning_effort: 'high', timeout_seconds: 60 })
  expect(active).toBe('backup')
  await page.getByRole('button', { name: '停止使用 API', exact: true }).click()
  await expect(page.getByText('正在使用', { exact: true })).toHaveCount(0)
  await page.getByLabel('API 备用 API', { exact: true }).getByRole('button', { name: '编辑', exact: true }).click()
  await expect(effort).toHaveValue('max')
  await expect(timeout).toHaveValue('600')
  await expect(window).toHaveValue('131072')
  await effort.selectOption('default')
  await page.getByRole('button', { name: '保存配置', exact: true }).click()
  await expect(page.getByLabel('API 备用 API', { exact: true })).toContainText('服务默认')
  expect(writes.at(-1)).toMatchObject({ reasoning_effort: 'default', timeout_seconds: 600 })
  await page.getByLabel('API 备用 API', { exact: true }).getByRole('button', { name: '编辑', exact: true }).click()
  await effort.selectOption('max')
  await page.getByRole('button', { name: '保存配置', exact: true }).click()
  await expect(page.getByLabel('API 备用 API', { exact: true })).toContainText('最高（max）')
  expect(active).toBeNull()
  await page.reload()
  await expect(page.getByText('备用 API', { exact: true })).toBeVisible()
  await expect(page.getByText('正在使用', { exact: true })).toHaveCount(0)
  await expect(key).toHaveCount(0)
  await page.getByLabel('API 备用 API', { exact: true }).getByRole('button', { name: '编辑', exact: true }).click()
  await expect(effort).toHaveValue('max')
  await expect(timeout).toHaveValue('600')
  await expect(window).toHaveValue('131072')
  if (page.viewportSize()!.width < 640) {
    expect((await page.getByLabel('API 公司 API', { exact: true }).locator(':scope > div').first().boundingBox())!.width).toBeGreaterThan(200)
  }
  await expect.poll(async () => (await page.evaluate(auditTextContrast)).filter(f => !f.text.includes('PIT'))).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('llm-profiles.png'), fullPage: true })
  await window.fill('')
  await page.getByRole('button', { name: '保存配置', exact: true }).click()
  expect(writes.at(-1)).toMatchObject({ context_window_tokens: 0 })
  await page.getByRole('button', { name: '新增 API', exact: true }).click()
  await expect(page.getByLabel('配置名称', { exact: true })).toHaveValue('')
  await expect(key).toHaveValue('')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByRole('button', { name: '新增 API', exact: true })).toBeFocused()
  await expect(key).toHaveCount(0)
})
