import { test, expect, type Page } from '@playwright/test'
import { spawn, type ChildProcess } from 'node:child_process'
import { createServer } from 'node:net'
import { readFile } from 'node:fs/promises'
import path from 'node:path'

let backend: ChildProcess | undefined
let apiRoot = ''
let logs = ''
const settingsPath = '/settings/language-terminology'
const termKey = 'variables.periods_per_year.label'

test.beforeAll(async ({ request }) => {
  test.setTimeout(120_000)
  const socket = createServer()
  await new Promise<void>((resolve, reject) => { socket.once('error', reject); socket.listen(0, '127.0.0.1', resolve) })
  const address = socket.address()
  if (!address || typeof address === 'string') throw new Error('No port available')
  await new Promise<void>(resolve => socket.close(() => resolve()))
  apiRoot = `http://127.0.0.1:${address.port}`
  backend = spawn(process.env.INDICATOR_TEST_PYTHON || 'python3', ['-m', 'uvicorn', 'localization_app:app', '--app-dir', 'tests', '--host', '127.0.0.1', '--port', String(address.port)], {
    cwd: path.resolve(process.cwd(), '../backend'), env: { ...process.env, ALL_PROXY: '', HTTP_PROXY: '', HTTPS_PROXY: '', NO_PROXY: '127.0.0.1,localhost' }, stdio: ['ignore', 'pipe', 'pipe'],
  })
  backend.stdout?.on('data', chunk => { logs = (logs + String(chunk)).slice(-6000) })
  backend.stderr?.on('data', chunk => { logs = (logs + String(chunk)).slice(-6000) })
  backend.on('error', error => { logs += error.message })
  await expect.poll(async () => {
    if (backend?.exitCode != null) throw new Error(logs)
    try { return (await request.get(`${apiRoot}/ready`, { timeout: 1000 })).ok() } catch { return false }
  }, { timeout: 100_000 }).toBe(true)
})
test.afterEach(async ({ page }) => {
  // Drain in-flight proxy handlers before Playwright disposes the request context.
  await page.unrouteAll({ behavior: 'wait' })
})
test.afterAll(async () => {
  if (!backend || backend.exitCode !== null) return
  const stopped = new Promise<void>(resolve => backend?.once('exit', () => resolve()))
  backend.kill('SIGTERM')
  await Promise.race([stopped, new Promise<void>(resolve => setTimeout(resolve, 10_000))])
  if (backend.exitCode === null) backend.kill('SIGKILL')
})
async function routeApi(page: Page) {
  await page.route('**/api/**', async route => {
    const url = new URL(route.request().url())
    if (!url.pathname.startsWith('/api/i18n') && !url.pathname.startsWith('/api/custom-indicators')) {
      // Unrelated page-shell APIs remain explicitly unavailable in this fixture.
      await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: 'Outside localization test fixture' }) })
      return
    }
    const response = await route.fetch({ url: `${apiRoot}${url.pathname}${url.search}`, timeout: 90_000 })
    await route.fulfill({ response })
  })
}
test.beforeEach(async ({ page, request }) => {
  const current = await (await request.get(`${apiRoot}/api/i18n/settings`)).json()
  await request.post(`${apiRoot}/api/i18n/business/restore`, { data: { expected_revision: current.revision, target_revision: 0 } })
  await request.put(`${apiRoot}/api/i18n/preferences`, { data: { expected_revision: current.preferences_revision, default_locale: 'zh-CN' } })
  page.setDefaultTimeout(15_000)
  await routeApi(page)
})

async function businessTable(page: Page, key = termKey) {
  await page.getByRole('tab', { name: '业务翻译（可自定义）', exact: true }).click()
  await page.getByRole('searchbox', { name: '搜索词条' }).fill(key)
  const row = page.locator(`tr[data-entry-key="${key}"]`)
  await expect(row).toBeVisible()
  return row
}

test('系统只读、业务覆盖、跨页面实时生效与中英文切换不改计算', async ({ page }, testInfo) => {
  test.setTimeout(90_000)
  const pageErrors: string[] = []
  page.on('pageerror', error => pageErrors.push(error.message))
  await page.goto(settingsPath)
  const settings = page.getByTestId('language-terminology')
  await expect(settings.getByRole('heading', { name: '语言与术语' })).toBeVisible()
  await expect(settings.getByRole('grid', { name: '系统翻译（内置只读）' })).toBeVisible()
  await expect(settings.getByRole('textbox', { name: /自定义译文/ })).toHaveCount(0)
  await expect(settings.getByRole('button', { name: '导入业务覆盖' })).toHaveCount(0)
  const state = await (await page.request.get(`${apiRoot}/api/i18n/settings`)).json()
  const rejected = await page.request.patch(`${apiRoot}/api/i18n/business`, { data: { expected_revision: state.revision, changes: [{ key: 'common.save', locale: 'zh-CN', value: '错误覆盖' }] } })
  expect(rejected.status()).toBe(403)
  const row = await businessTable(page)
  await row.getByRole('gridcell', { name: `${termKey} zh-CN` }).dblclick()
  await page.getByRole('textbox', { name: `编辑译文 ${termKey} zh-CN` }).fill('每年观察期数')
  await page.getByRole('textbox', { name: `编辑译文 ${termKey} zh-CN` }).press('Enter')
  const saveResponse = page.waitForResponse(response => response.url().endsWith('/api/i18n/business') && response.request().method() === 'PATCH')
  await page.getByRole('button', { name: '保存业务翻译', exact: true }).click()
  expect((await saveResponse).status()).toBe(200)
  await expect(page.getByText(/业务翻译已保存/)).toBeVisible()
  await expect(row.getByRole('gridcell', { name: `${termKey} zh-CN` })).toContainText('每年观察期数')
  await settings.screenshot({ path: testInfo.outputPath('language-business-settings.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(2)

  await page.waitForLoadState('networkidle')
  await page.goto('/settings/indicators-models')
  await page.getByRole('button', { name: /5 日滚动年化夏普比率 时序 内置/ }).click()
  const restoredPromise = page.waitForResponse(response => response.url().endsWith('/graph/resolve') && response.request().postDataJSON().source_kind === 'formula')
  await page.getByRole('tab', { name: '画布构建', exact: true }).click()
  const restored = await (await restoredPromise).json()
  expect(restored.valid).toBe(true)
  const canvas = page.getByTestId('indicator-graph-canvas')
  await expect(canvas).toContainText('每年观察期数')
  await expect(canvas).not.toContainText('年化因子')
  const variable = restored.graph.nodes.find((node: { variable_id?: string }) => node.variable_id === 'periods_per_year')
  expect(variable).toBeTruthy()
  const mobile = (page.viewportSize()?.width || 0) < 768
  const node = mobile ? page.locator(`[data-node-id="${variable.id}"]`).getByRole('button').first() : page.locator(`.react-flow__node[data-id="${variable.id}"]`)
  await node.click()
  await page.getByRole('textbox', { name: '步骤备注', exact: true }).fill('用户自定义 returns 原文')
  await page.getByRole('button', { name: '收起', exact: true }).click()
  await page.getByRole('navigation', { name: '主导航', exact: true }).getByRole('combobox', { name: '当前浏览器语言' }).selectOption('en-US')
  await expect(page.getByRole('navigation', { name: 'Main navigation', exact: true })).toBeVisible()
  await expect(page.getByRole('tab', { name: 'Visual builder', exact: true })).toBeVisible()
  await expect(canvas).toContainText('Time series')
  await expect(canvas).toContainText('用户自定义 returns 原文')
  await expect(page.getByText('Not applied', { exact: true })).toHaveCount(0)
  const checkedPromise = page.waitForResponse(response => response.url().endsWith('/graph/resolve') && response.request().postDataJSON().source_kind === 'graph')
  await page.getByRole('button', { name: 'Check graph', exact: true }).click()
  const checkedResponse = await checkedPromise
  const checked = await checkedResponse.json()
  expect(checked.valid).toBe(true)
  expect(checked.definition_fingerprint).toBe(restored.definition_fingerprint)
  expect(checkedResponse.request().postDataJSON().graph.nodes.find((item: { id: string }) => item.id === variable.id).variable_id).toBe('periods_per_year')
  await page.waitForLoadState('networkidle')
  await page.goto(settingsPath)
  await expect(settings.getByRole('heading', { name: 'Language and terminology' })).toBeVisible()
  await page.waitForLoadState('networkidle')
  await page.reload()
  await expect(settings.getByRole('heading', { name: 'Language and terminology' })).toBeVisible()
  await page.waitForLoadState('networkidle')
  expect(pageErrors).toEqual([])
})

test('业务翻译导入预览、导出和历史恢复，系统表不会被导入修改', async ({ page }, testInfo) => {
  test.setTimeout(60_000)
  await page.goto(settingsPath)
  await businessTable(page)
  const packageData = { format_version: 1, scope: 'business', entries: [{ key: termKey, locale: 'zh-CN', value: '导入的年化期数' }] }
  const before = await (await page.request.get(`${apiRoot}/api/i18n/settings`)).json()
  await page.getByLabel('导入业务覆盖', { exact: true }).setInputFiles({ name: 'translations.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(packageData)) })
  const preview = page.getByRole('region', { name: '确认导入差异' })
  await expect(preview).toContainText('导入的年化期数')
  const uncommitted = await (await page.request.get(`${apiRoot}/api/i18n/settings`)).json()
  expect(uncommitted.revision).toBe(before.revision)
  const appliedPromise = page.waitForResponse(response => response.url().endsWith('/business/import/apply'))
  await preview.getByRole('button', { name: '确认并应用导入' }).click()
  expect((await appliedPromise).status()).toBe(200)
  await expect(page.getByText(/业务翻译已保存/)).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出业务覆盖', exact: true }).click()
  const download = await downloadPromise
  const exported = JSON.parse(await readFile((await download.path())!, 'utf8'))
  expect(exported.scope).toBe('business')
  expect(exported.entries).toContainEqual(packageData.entries[0])
  expect(exported.entries.every((item: { key: string }) => !item.key.startsWith('common.') && !item.key.startsWith('navigation.'))).toBe(true)
  await page.getByRole('tab', { name: '修改历史', exact: true }).click()
  const initial = page.locator('tbody tr').filter({ has: page.getByText('初始版本', { exact: true }) })
  await expect(initial).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await initial.getByRole('button', { name: '恢复此版本' }).click()
  await expect(page.getByText(/业务翻译已保存/)).toBeVisible()
  const restored = await (await page.request.get(`${apiRoot}/api/i18n/settings`)).json()
  expect(restored.revision).toBeGreaterThan(before.revision)
  expect(restored.overrides).toEqual({})
  await page.getByTestId('language-terminology').screenshot({ path: testInfo.outputPath('language-history.png') })
})

test('翻译矩阵支持跨语言搜索、清除筛选和列排序', async ({ page }) => {
  test.setTimeout(60_000)
  await page.goto(settingsPath)
  const settings = page.getByTestId('language-terminology')
  await settings.getByRole('tab', { name: '业务翻译（可自定义）', exact: true }).click()
  const codeHeader = settings.getByRole('columnheader', { name: /系统代码/ })
  await expect(codeHeader).toHaveAttribute('aria-sort', 'ascending')
  const descending = page.waitForResponse(response => response.url().includes('/api/i18n/matrix?') && response.url().includes('sort_by=code') && response.url().includes('sort_dir=desc'))
  await codeHeader.getByRole('button', { name: /降序排序/ }).click()
  expect((await descending).status()).toBe(200)
  await expect(codeHeader).toHaveAttribute('aria-sort', 'descending')
  const englishHeader = settings.getByRole('columnheader', { name: /English/ })
  const englishSort = page.waitForResponse(response => response.url().includes('/api/i18n/matrix?') && response.url().includes('sort_by=en-US') && response.url().includes('sort_dir=asc'))
  await englishHeader.getByRole('button', { name: /升序排序/ }).click()
  expect((await englishSort).status()).toBe(200)
  await expect(englishHeader).toHaveAttribute('aria-sort', 'ascending')
  const search = settings.getByRole('searchbox', { name: '搜索词条' })
  await search.fill('Asset')
  await expect(page.locator('tr[data-entry-key="axes.asset"]')).toBeVisible()
  await expect(page.locator('tr[data-entry-key="axes.time"]')).toHaveCount(0)
  await settings.getByRole('button', { name: '清除筛选', exact: true }).click()
  await expect(search).toHaveValue('')
})

test('代码首列、多语言矩阵、粘贴、新增日语、回退与停用保留译文', async ({ page }, testInfo) => {
  test.setTimeout(90_000)
  await page.goto(settingsPath)
  const settings = page.getByTestId('language-terminology')
  await businessTable(page, 'axes.asset')
  await settings.getByRole('combobox', { name: '模块', exact: true }).selectOption('axes')
  const asset = page.locator('tr[data-entry-key="axes.asset"]')
  await expect(asset.getByRole('rowheader')).toHaveText('asset')
  await expect(asset.getByRole('gridcell', { name: 'axes.asset en-US' })).toContainText('Asset')
  await settings.getByRole('button', { name: '＋ 添加语言', exact: true }).click()
  const manager = settings.getByRole('region', { name: '管理语言列' })
  await manager.getByRole('textbox', { name: '语言代码', exact: true }).fill('JA-jp')
  await manager.getByRole('textbox', { name: '语言名称', exact: true }).fill('日本語')
  await manager.getByRole('combobox', { name: '缺少译文时回退到', exact: true }).selectOption('en-US')
  const languagesSaved = page.waitForResponse(response => response.url().endsWith('/api/i18n/languages') && response.request().method() === 'PUT')
  await manager.getByRole('button', { name: '保存', exact: true }).click()
  expect((await languagesSaved).status()).toBe(200)
  const japanese = asset.getByRole('gridcell', { name: 'axes.asset ja-JP' })
  await expect(japanese).toContainText('未翻译')
  await expect(japanese).toContainText('Asset')
  // The code column remains frozen while language columns scroll.
  const gridScroll = page.getByTestId('translation-matrix-scroll')
  const before = await asset.getByRole('rowheader').boundingBox()
  await gridScroll.evaluate(element => { element.scrollLeft = 240 })
  const after = await asset.getByRole('rowheader').boundingBox()
  expect(Math.abs(before!.x - after!.x)).toBeLessThanOrEqual(2)
  await gridScroll.evaluate(element => { element.scrollLeft = 0 })
  const zh = asset.getByRole('gridcell', { name: 'axes.asset zh-CN' })
  await zh.focus()
  // Same plain-text clipboard payload used by Excel's rectangular copy.
  await zh.evaluate(element => { const data = new DataTransfer(); data.setData('text/plain', '资产类别\tAsset class\t資産'); element.dispatchEvent(new ClipboardEvent('paste', { bubbles: true, clipboardData: data })) })
  await expect(settings.getByRole('region', { name: '修改预览' })).toContainText('資産')
  const saved = page.waitForResponse(response => response.url().endsWith('/api/i18n/business') && response.request().method() === 'PATCH')
  await settings.getByRole('button', { name: '保存业务翻译', exact: true }).click()
  expect((await saved).status()).toBe(200)
  await expect(asset.getByRole('gridcell', { name: 'axes.asset ja-JP' })).toContainText('資産')
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(2)
  await settings.screenshot({ path: testInfo.outputPath('language-matrix-three-columns.png') })
  await settings.getByRole('combobox', { name: '当前浏览器语言', exact: true }).selectOption('ja-JP')
  await expect(page.locator('html')).toHaveAttribute('lang', 'ja-JP')
  await expect(settings.getByRole('heading', { name: 'Language and terminology' })).toBeVisible()
  const navLanguage = page.getByRole('navigation', { name: 'Main navigation', exact: true }).getByRole('combobox', { name: 'Language for this browser' })
  await expect(navLanguage).toHaveValue('ja-JP')
  await page.waitForLoadState('networkidle')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('lang', 'ja-JP')
  await settings.getByRole('combobox', { name: 'Language for this browser', exact: true }).selectOption('zh-CN')
  await businessTable(page, 'axes.asset')
  await expect(asset.getByRole('gridcell', { name: 'axes.asset ja-JP' })).toContainText('資産')
  await settings.getByRole('button', { name: '管理语言列', exact: true }).click()
  const row = manager.locator('div.grid').filter({ has: page.locator('code', { hasText: /^ja-JP$/ }) })
  await row.getByRole('checkbox').uncheck()
  const disabled = page.waitForResponse(response => response.url().endsWith('/api/i18n/languages') && response.request().method() === 'PUT')
  await manager.getByRole('button', { name: '保存', exact: true }).click()
  expect((await disabled).status()).toBe(200)
  await expect(settings.getByRole('combobox', { name: '当前浏览器语言', exact: true }).locator('option[value="ja-JP"]')).toHaveCount(0)
  await expect(asset.getByRole('gridcell', { name: 'axes.asset ja-JP' })).toContainText('資産')
  const current = await (await page.request.get(`${apiRoot}/api/i18n/settings`)).json()
  expect(current.overrides['ja-JP']['axes.asset']).toBe('資産')
  const bundle = await page.request.get(`${apiRoot}/api/i18n/bundle?locale=ja-JP`)
  expect(bundle.status()).toBe(422)
})

test('离线内置语言包可用，浏览器偏好不会被工作区默认语言覆盖', async ({ page }) => {
  test.setTimeout(60_000)
  await page.goto(settingsPath)
  const settings = page.getByTestId('language-terminology')
  await settings.getByRole('combobox', { name: '当前浏览器语言', exact: true }).selectOption('en-US')
  await expect(settings.getByRole('heading', { name: 'Language and terminology' })).toBeVisible()
  const state = await (await page.request.get(`${apiRoot}/api/i18n/settings`)).json()
  await page.request.put(`${apiRoot}/api/i18n/preferences`, { data: { expected_revision: state.preferences_revision, default_locale: 'zh-CN' } })
  await page.reload()
  await expect(settings.getByRole('heading', { name: 'Language and terminology' })).toBeVisible()
  await page.route('**/api/i18n/**', route => route.abort())
  await page.reload()
  await expect(settings.getByRole('heading', { name: 'Language and terminology' })).toBeVisible()
  await expect(settings.getByText(/Translation service is unavailable/)).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Main navigation', exact: true })).toBeVisible()
})
