import { test, expect, type Page, type TestInfo } from '@playwright/test'
import { auditTextContrast } from './helpers/contrast'

const api = 'http://127.0.0.1:8128'
type Fixture = { today: string; allocation: string; manual_id: string; historical_id: string; bl_id: string; scenario_id: string; mandate_id: string; universe_id: string; regime_id: string }
let fixture: Fixture
async function layout(page: Page, info: TestInfo, name: string) {
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
  // Measure settled CSS states, not the transient disabled-to-enabled transition.
  await page.evaluate(async () => { await Promise.all(document.getAnimations().filter(animation => animation.effect?.getComputedTiming().iterations !== Infinity).map(animation => animation.finished.catch(() => undefined))) })
  expect(await page.evaluate(auditTextContrast)).toEqual([])
  await page.screenshot({ path: info.outputPath(`${name}.png`), fullPage: true })
}
async function preview(page: Page) {
  await page.getByRole('checkbox', { name: /我已核对资产范围/ }).check()
  const result = page.waitForResponse(response => response.url().includes('/cma/preview') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '计算预览', exact: true }).click()
  const response = await result
  expect(response.ok(), await response.text()).toBe(true)
  const value = await response.json()
  expect(value.execution.python_fallback).toBe(0)
  expect(value.execution.request_time_compilation).toBe(0)
  if (value.model_result) expect(value.model_result.execution.python_fallback).toBe(0)
  await expect(page.getByRole('table', { name: '收益与风险假设', exact: true })).toBeVisible()
  return value
}
async function publish(page: Page) {
  await page.getByRole('checkbox', { name: /我已阅读结果和限制/ }).check()
  const result = page.waitForResponse(response => new URL(response.url()).pathname.endsWith('/cma') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '确认保存版本', exact: true }).click()
  const response = await result
  expect(response.ok(), await response.text()).toBe(true)
  const value = await response.json()
  await expect(page).toHaveURL(new RegExp(`/ltcma/${value.id}`))
  await expect(page.getByRole('button', { name: '用于 SAA', exact: true })).toBeVisible()
  return value
}

test.beforeEach(async ({ page, request }) => {
  fixture = await (await request.get(`${api}/fixture/ltcma`)).json()
  await page.route('**/api/**', async route => {
    const url = new URL(route.request().url())
    const response = await route.fetch({ url: `${api}${url.pathname}${url.search}`, timeout: 60000 })
    await route.fulfill({ response })
  })
})

test.afterEach(async ({ page }) => { await page.unrouteAll({ behavior: 'wait' }) })

test('manual copy, immutable publication, exact SAA handoff and retirement', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/pre-investment/ltcma')
  await expect(page.locator(`a[href="/pre-investment/ltcma/${fixture.manual_id}"]`)).toBeVisible()
  await layout(page, info, 'list')
  await page.goto(`/pre-investment/ltcma/new?copy=${fixture.manual_id}&mandate=${fixture.mandate_id}`)
  await expect(page.getByLabel('名称', { exact: true })).toHaveValue('离线基础 LTCMA')
  await page.getByLabel('名称', { exact: true }).fill(`浏览器手动版本 ${info.project.name}`)
  await layout(page, info, 'manual-input')
  const calculated = await preview(page)
  expect(calculated.definition).not.toHaveProperty('mandate_id')
  expect(calculated.definition.implementation_mapping_id).toBeNull()
  await layout(page, info, 'manual-results')
  const saved = await publish(page)
  await page.reload()
  await expect(page.getByRole('heading', { name: saved.name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: '用于 SAA', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`cma=${saved.id}`))
  await expect(page.getByRole('button', { name: '比较符合目标的政策候选' })).toBeEnabled()
  await page.getByRole('button', { name: '比较符合目标的政策候选' }).click()
  await expect(page.getByRole('table', { name: '长期政策候选比较' })).toBeVisible()
  await expect(page.getByRole('button', { name: '比较符合目标的政策候选' })).toBeEnabled()
  await layout(page, info, 'saa-selection')
  await page.goto(`/pre-investment/ltcma/${saved.id}`)
  await page.getByRole('button', { name: '停止新引用', exact: true }).click()
  await page.getByLabel('停止引用的原因（至少 5 字）', { exact: true }).fill('离线浏览器验证停止新引用')
  await page.getByRole('checkbox', { name: '确认停止此版本的新引用', exact: true }).check()
  await page.getByRole('button', { name: '确认停止此版本的新引用', exact: true }).click()
  await expect(page.getByRole('button', { name: '用于 SAA', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('table', { name: '收益与风险假设', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '用于 SAA', exact: true })).toBeDisabled()
  expect(errors).toEqual([])
})

test('historical and NIW use real saved evidence and independently frozen results', async ({ page }, info) => {
  await page.goto(`/pre-investment/ltcma/new?copy=${fixture.manual_id}`)
  await page.getByLabel('名称', { exact: true }).fill(`浏览器历史 ${info.project.name}`)
  await page.getByLabel('生成方法', { exact: true }).selectOption('historical_statistics')
  await page.getByLabel('历史取样窗口', { exact: true }).selectOption('common_since_inception')
  const history = await preview(page)
  expect(history.model_result.model_audit.evidence.observations).toBe(300)
  expect(history.model_result.model_audit.uncertainty_status).toBe('estimated_iid')
  await expect(page.getByRole('columnheader', { name: '均值模型标准误', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: '样本窗口与预测期限', exact: true })).toBeVisible()
  await layout(page, info, 'historical-results')
  const historicalVersion = await publish(page)
  await page.goto(`/pre-investment/ltcma/new?copy=${historicalVersion.id}`)
  await page.getByLabel('生成方法', { exact: true }).selectOption('bayesian_niw')
  await page.getByLabel('历史取样窗口', { exact: true }).selectOption('common_since_inception')
  await page.getByLabel('先验 LTCMA 版本', { exact: true }).selectOption(fixture.manual_id)
  await page.getByLabel('均值先验等效日观察数', { exact: true }).fill('20')
  await page.getByLabel('风险先验等效日观察数', { exact: true }).fill('20')
  await layout(page, info, 'niw-input')
  const niw = await preview(page)
  expect(niw.model_result.model_audit.niw_posterior.kappa).toBe(320)
  expect(niw.model_result.posterior_mean_covariance).toHaveLength(2)
  await publish(page)
})

test('BL, explicit scenarios and historical regimes remain separate methods', async ({ page }, info) => {
  for (const [id, method] of [[fixture.bl_id, 'black_litterman'], [fixture.scenario_id, 'scenario_mixture']] as const) {
    await page.goto(`/pre-investment/ltcma/new?copy=${id}`)
    await expect(page.getByLabel('生成方法', { exact: true })).toHaveValue(method)
    const value = await preview(page)
    expect(value.model_result.method).toBe(method)
    await layout(page, info, `${method}-results`)
  }
  await page.goto(`/pre-investment/ltcma/new?copy=${fixture.manual_id}`)
  await page.getByLabel('生成方法', { exact: true }).selectOption('historical_regime_occupancy')
  await page.getByLabel('历史取样窗口', { exact: true }).selectOption('common_since_inception')
  await page.getByLabel('已保存的事后状态研究', { exact: true }).selectOption(fixture.regime_id)
  const regime = await preview(page)
  expect(regime.model_result.model_audit.detected_probabilities).toEqual([.5, .5])
  expect(regime.model_result.model_audit.counts).toEqual([150, 150])
  expect(regime.model_result.model_audit.annualization_method).toBe('historical_occupancy_iid_annualization')
  const stateTable = page.getByRole('table', { name: '历史状态与应用概率', exact: true })
  await expect(stateTable).toBeVisible()
  await expect(stateTable.getByRole('columnheader', { name: '历史占用率', exact: true })).toBeVisible()
  await expect(stateTable.getByRole('columnheader', { name: '本次应用概率', exact: true })).toBeVisible()
  await expect(stateTable.getByText('50.00%', { exact: true })).toHaveCount(4)
  await expect(page.getByRole('table', { name: '历史状态转移诊断', exact: true })).toBeVisible()
  expect(regime.model_result.model_audit.transition_diagnostics.forecast_used).toBe(false)
  await layout(page, info, 'regime-results')
  await publish(page)
})

test('basket views and explicit mean ellipsoid survive publication and policy restoration', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(`/pre-investment/ltcma/new?copy=${fixture.bl_id}&mandate=${fixture.mandate_id}`)
  await page.getByLabel('名称', { exact: true }).fill(`篮子与椭球 ${info.project.name}`)
  await page.getByRole('button', { name: '添加观点', exact: true }).click()
  await page.getByRole('combobox', { name: '观点1类型', exact: true }).selectOption('basket')
  await page.getByRole('combobox', { name: '观点1篮子口径', exact: true }).selectOption('absolute')
  await page.getByLabel('观点1 · 股票系数', { exact: true }).fill('0.5')
  await page.getByLabel('观点1 · 债券系数', { exact: true }).fill('0.5')
  await page.getByLabel('观点1年化总收益（%）', { exact: true }).fill('5')
  await page.getByLabel('观点1标准差（百分点）', { exact: true }).fill('2')
  await page.getByLabel('观点1观察日', { exact: true }).fill(fixture.today)
  await page.getByLabel('观点1可得日', { exact: true }).fill(fixture.today)
  await page.getByLabel('观点1依据', { exact: true }).fill('离线浏览器明确提供的篮子收益观点')
  await layout(page, info, 'basket-input')
  const calculated = await preview(page)
  expect(calculated.model_result.definition.views[0].kind).toBe('basket')
  expect(calculated.model_result.model_audit.view_return_contributions).toHaveLength(1)
  await expect(page.getByRole('table', { name: '观点影响与均值更新贡献', exact: true })).toBeVisible()
  await expect(page.getByText('隐含市场 Sharpe', { exact: true })).toBeVisible()
  await layout(page, info, 'basket-diagnostics')
  const savedCma = await publish(page)
  await page.getByRole('button', { name: '用于 SAA', exact: true }).click()
  await page.getByText('联合约束与候选搜索设置', { exact: true }).click()
  await page.getByRole('combobox', { name: '均值稳健方式', exact: true }).selectOption('ellipsoidal')
  const compare = page.getByRole('button', { name: '比较符合目标的政策候选', exact: true })
  await expect(compare).toBeDisabled()
  await page.getByRole('combobox', { name: '模型覆盖水平', exact: true }).selectOption('95')
  const response = page.waitForResponse(r => r.url().endsWith('/policy/preview') && r.request().method() === 'POST')
  await compare.click()
  const result = await response
  expect(result.ok(), await result.text()).toBe(true)
  const policyPreview = await result.json()
  expect(policyPreview.uncertainty_model.mean_covariance).toEqual(savedCma.model_result.posterior_mean_covariance)
  expect(policyPreview.covariance).toEqual(savedCma.effective_covariance)
  expect(policyPreview.uncertainty_model.kappa).toBeCloseTo(2.44774683, 7)
  expect(policyPreview.uncertainty_model.execution.request_time_compilation).toBe(0)
  await expect(page.getByRole('region', { name: '已冻结的均值稳健口径', exact: true })).toBeVisible()
  await layout(page, info, 'ellipse-results')
  await page.getByRole('combobox', { name: '模型覆盖水平', exact: true }).selectOption('90')
  await expect(page.getByRole('table', { name: '长期政策候选比较' })).toHaveCount(0)
  await page.getByRole('combobox', { name: '模型覆盖水平', exact: true }).selectOption('95')
  await compare.click()
  const candidates = page.getByRole('table', { name: '长期政策候选比较' })
  await candidates.getByRole('row').filter({ hasText: '椭球稳健效用' }).getByRole('button', { name: '复核此候选' }).click()
  await page.getByLabel('采纳理由与复核关注点', { exact: false }).fill('冻结均值协方差与联合覆盖前提，离线检验不是收益保证')
  const published = page.waitForResponse(r => r.url().endsWith('/policies') && r.request().method() === 'POST')
  await page.getByRole('button', { name: '确认采用此长期政策', exact: true }).click()
  const publication = await published
  expect(publication.ok(), await publication.text()).toBe(true)
  const baseline = await publication.json()
  await page.goto(`/pre-investment/saa/policy?baseline=${baseline.id}`)
  await expect(page.getByRole('region', { name: '已冻结的均值稳健口径', exact: true })).toContainText('95%')
  await layout(page, info, 'ellipse-frozen-policy')
  expect(errors).toEqual([])
})

test('incomplete draft, reload, edit and explicit delete', async ({ page }, info) => {
  await page.goto('/pre-investment/ltcma/new')
  const name = `未完成草稿 ${info.project.name}`
  await page.getByLabel('名称', { exact: true }).fill(name)
  await page.getByLabel('资产范围', { exact: true }).selectOption(`allocation:${fixture.allocation}`)
  await expect(page.getByRole('button', { name: '计算预览', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '保存草稿', exact: true }).click()
  await expect(page.getByText('草稿已保存，可从列表继续编辑。', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: '返回 LTCMA 列表', exact: true }).click()
  await page.getByRole('button', { name: '草稿', exact: true }).click()
  await page.getByRole('heading', { name, exact: true }).locator('..').locator('..').getByRole('link', { name: '继续编辑' }).click()
  await expect(page.getByLabel('名称', { exact: true })).toHaveValue(name)
  await expect(page.getByLabel('股票 · 预期年收益（%）', { exact: true })).toHaveValue('')
  await page.reload()
  await expect(page.getByLabel('名称', { exact: true })).toHaveValue(name)
  await page.getByRole('link', { name: '返回 LTCMA 列表', exact: true }).click()
  await page.getByRole('button', { name: '草稿', exact: true }).click()
  await page.getByRole('heading', { name, exact: true }).locator('..').locator('..').getByRole('button', { name: '删除草稿' }).click()
  await page.getByRole('button', { name: '确认删除', exact: true }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toHaveCount(0)
})

test('errors, empty results and keyboard-visible retry', async ({ page }, info) => {
  await page.route('**/api/strategic-allocation/cma?*', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: { message: '离线测试：目录暂时不可用' } }) }))
  await page.goto('/pre-investment/ltcma')
  await expect(page.getByRole('alert')).toContainText('目录暂时不可用')
  await layout(page, info, 'error-state')
  await page.unroute('**/api/strategic-allocation/cma?*')
  await page.getByRole('button', { name: '重试', exact: true }).click()
  await expect(page.locator(`a[href="/pre-investment/ltcma/${fixture.manual_id}"]`)).toBeVisible()
  await page.getByLabel('搜索名称', { exact: true }).fill('不存在的合成测试版本')
  await expect(page.getByText('没有匹配的 LTCMA', { exact: true })).toBeVisible()
  await layout(page, info, 'empty-state')
})
