import { test, expect, type Page, type TestInfo } from '@playwright/test'
import { auditTextContrast } from './helpers/contrast'

const api = 'http://127.0.0.1:8126'
async function connect(page: Page, locale = 'zh-CN') {
  await page.addInitScript(language => localStorage.setItem('fund-research.i18n.locale', language), locale)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  return errors
}
async function layout(page: Page, info: TestInfo, name: string, heading: string) {
  await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBeTruthy()
  const contrast = await page.getByRole('heading', { name: heading, exact: true }).locator('..').locator('p').evaluate(element => {
    const color = getComputedStyle(element).color.match(/[\d.]+/g)!.slice(0, 3).map(Number).map(x => {
      const v = x / 255; return v <= .04045 ? v / 12.92 : ((v + .055) / 1.055) ** 2.4
    })
    return 1.05 / (.2126 * color[0] + .7152 * color[1] + .0722 * color[2] + .05)
  })
  expect(contrast).toBeGreaterThanOrEqual(4.5)
  await expect.poll(() => page.evaluate(auditTextContrast)).toEqual([])
  await page.screenshot({ path: info.outputPath(`${name}.png`), fullPage: true })
}

test('两步目标流程只收集目标、风险等级和现金，并展示双有效前沿', async ({ page, request }, info) => {
  const errors = await connect(page)
  const fixture = await (await request.get(`${api}/fixture`)).json()
  await page.clock.setFixedTime(new Date(`${fixture.today}T12:00:00Z`))
  await page.goto('/pre-investment/objectives')
  await expect(page.getByRole('heading', { name: '投资目标与约束', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '添加投资目标与约束', exact: true }).first().click()
  await expect(page).toHaveURL(/\/pre-investment\/objectives\/new/)
  await expect(page.getByRole('heading', { name: '添加投资目标与约束', exact: true })).toBeVisible()
  await expect(page.getByRole('navigation', { name: '投资目标步骤' }).getByRole('button')).toHaveCount(2)
  await expect(page.getByLabel('目标研究日', { exact: false })).toBeEnabled() // fixture explicitly closes PIT
  await expect(page.getByLabel('目标研究日', { exact: false })).toHaveValue(fixture.today)
  await page.getByLabel('目标名称', { exact: true }).fill(`精简目标-${info.project.name}`)
  await page.getByRole('combobox', { name: '投资目标类型', exact: false }).selectOption('funding_goal')
  await page.getByLabel(/期末目标金额/).fill('1000000')
  await layout(page, info, '01-objective', '添加投资目标与约束')

  await expect(page.getByRole('combobox', { name: /风险标尺版本/ })).toHaveValue('')
  const yesterday = new Date(`${fixture.today}T12:00:00Z`)
  yesterday.setUTCDate(yesterday.getUTCDate() - 1)
  const researchDate = page.getByLabel('目标研究日', { exact: false })
  await researchDate.fill(yesterday.toISOString().slice(0, 10))
  await expect(page.getByRole('button', { name: '2. 结果与确认', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '我已核对资金和现金流，确认按新研究日使用', exact: true }).click()
  await researchDate.fill(fixture.today)
  await expect(page.getByRole('button', { name: '2. 结果与确认', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '我已核对资金和现金流，确认按新研究日使用', exact: true }).click()
  await page.getByRole('combobox', { name: /风险标尺版本/ }).selectOption(fixture.scale.id)
  await expect(page.getByLabel(/^计价币种/)).toHaveValue('CNY')
  await page.getByRole('button', { name: /^C3 / }).click()
  await page.getByLabel(/最低现金占比/).fill('10')
  await expect(page.getByRole('checkbox', { name: /期末与期间目标需要本金和现金流计划/ })).toBeChecked()
  await page.getByLabel(/总资金（CNY）/).fill('1000000')
  const objectiveType = page.getByRole('combobox', { name: '投资目标类型', exact: false })
  await objectiveType.selectOption('absolute_return')
  await expect(page.getByLabel(/总资金（CNY）/)).toHaveValue('1000000')
  await objectiveType.selectOption('funding_goal')
  await page.getByLabel(/期末目标金额/).fill('1000000')
  await expect(page.getByLabel(/最高预期年波动/)).toHaveCount(0)
  await expect(page.getByLabel(/风险厌恶/)).toHaveCount(0)
  await expect(page.getByLabel(/政策来源/)).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: /CMA/ })).toHaveCount(0)
  await layout(page, info, '02-risk-cash', '添加投资目标与约束')

  await page.getByRole('button', { name: '下一步：结果与确认', exact: true }).click()
  const pending = page.waitForResponse(r => r.url().endsWith('/mandates/preview') && r.request().method() === 'POST')
  await page.getByRole('button', { name: '运行目标诊断', exact: true }).click()
  const response = await pending
  expect(response.status()).toBe(200)
  const diagnosis = await response.json()
  expect(diagnosis.request.cma_id).toBeNull()
  expect(diagnosis.definition.risk_authorization.selected_max_level).toBe(3)
  expect(diagnosis.reference_diagnosis.reference_frontier).toHaveLength(101)
  expect(diagnosis.reference_diagnosis.constrained_frontier).toHaveLength(101)
  expect(diagnosis.reference_diagnosis.risk_boundaries).toEqual(fixture.scale.preview.result.applied_boundaries)
  expect(diagnosis.reference_diagnosis.cash_constraint.requested_min_cash_weight).toBeCloseTo(.1)
  await expect(page.getByRole('heading', { name: '参考前沿与当前约束前沿', exact: true })).toBeVisible()
  await expect(page.getByText(/C1–C5 始终来自所选风险等级配置/)).toBeVisible()
  await expect(page.getByText('10.00%', { exact: true }).first()).toBeVisible()
  await layout(page, info, '03-dual-frontiers', '添加投资目标与约束')

  await page.getByRole('checkbox', { name: /我已核对输入、最终授权上限/ }).check()
  const confirmed = page.waitForResponse(r => r.url().endsWith('/mandates/confirm') && r.request().method() === 'POST')
  await page.getByRole('button', { name: '保存新目标版本', exact: true }).click()
  const savedResponse = await confirmed
  expect(savedResponse.status()).toBe(201)
  const saved = await savedResponse.json()
  expect(saved.definition.boundary_policy.source).toBe('investment_objectives_model_convention_v1')
  expect(saved.definition.effective_cash_reserve_weight).toBeGreaterThanOrEqual(.1)
  await expect(page.getByText('只读版本', { exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: /下一步：确定投资范围/ })).toBeVisible()

  // A saved view may load before the global PIT setting recovers.
  let pitUnavailable = true
  await page.route(`**/api/strategic-allocation/mandates/${saved.id}`, route =>
    route.fulfill({ status: 503, json: { detail: { message: '保存版本暂时不可读' } } }))
  await page.route('**/api/pit/settings', route => route.fulfill(pitUnavailable
    ? { status: 503, json: { detail: 'Offline PIT recovery fixture' } }
    : { json: { settings: { active_release_id: null }, available_releases: [],
      effective: { no_pit: false, as_of: fixture.today, run_mode: 'RESEARCH', label: 'Recovered PIT' } } }))
  await page.reload()
  await expect(page.getByRole('alert').filter({ hasText: '保存版本暂时不可读' })).toBeVisible()
  pitUnavailable = false
  const menu = page.getByRole('button', { name: '菜单', exact: true })
  if (await menu.isVisible()) await menu.click()
  await page.locator('[data-testid=pit-badge]:visible').click()
  await page.getByRole('button', { name: '重试读取 PIT 口径', exact: true }).click()
  await expect(page.locator('[data-testid=pit-badge]:visible')).toContainText(`PIT 打开：${fixture.today}`)
  await page.getByRole('button', { name: '关闭口径切换', exact: true }).click()
  if (await menu.isVisible()) await menu.click()
  await expect(page).toHaveURL(new RegExp(`view=${saved.id}`))
  await expect(page.getByLabel('目标名称', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '运行目标诊断', exact: true })).toHaveCount(0)
  await page.unroute(`**/api/strategic-allocation/mandates/${saved.id}`)
  await page.getByRole('button', { name: '重试', exact: true }).click()
  await expect(page.getByText('只读版本', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '运行目标诊断', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '保存新目标版本', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '1. 目标与约束', exact: true }).click()
  await expect(page.getByLabel('目标名称', { exact: true })).toBeDisabled()
  await expect(page.getByLabel('目标研究日', { exact: false })).toHaveValue(saved.definition.as_of)
  await page.getByRole('button', { name: '2. 结果与确认', exact: true }).click()
  await layout(page, info, 'saved-after-pit-recovery', '已保存投资目标与约束')
  const unchanged = await (await request.get(`${api}/api/strategic-allocation/mandates/${saved.id}`)).json()
  expect(unchanged.content_hash).toBe(saved.content_hash)
  await page.unroute('**/api/pit/settings')

  // Published objectives are managed from a list, matching Risk Scale Center.
  await page.getByRole('link', { name: '返回投资目标列表', exact: true }).click()
  const row = page.getByRole('row', { name: new RegExp(`精简目标-${info.project.name}`) })
  await expect(row).toBeVisible()
  await page.evaluate(() => sessionStorage.setItem('allocation-journey:v1', JSON.stringify({ mandateId: 'another-objective', baselineId: 'old-policy', taaRunId: 'old-taa' })))
  await row.getByRole('link', { name: `精简目标-${info.project.name}`, exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`view=${saved.id}`))
  await expect(page.getByText('只读版本', { exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: /下一步：确定投资范围/ })).toHaveAttribute('href', `/pre-investment/product-pool?mandate=${saved.id}`)
  const poolVersion = { id: 'handoff-version', pool_id: 'handoff-pool', pool_name: 'Handoff pool', version: 1,
    effective_from: '2020-01-01', effective_to: null, evaluation_plans: [], members: [], investable_count: 1,
    member_counts: { approved: 1, pending: 0, watch: 0, rejected: 0 }, immutable: true, created_at: fixture.today }
  const snapshot = { id: 'handoff-universe', name: 'Handoff scope', research_date: fixture.today,
    version_ids: ['handoff-version'], groups: [], product_count: 1, immutable: true }
  await page.route('**/api/product-pool-versions?*', route => route.fulfill({ json: { items: [poolVersion], total: 1 } }))
  await page.route('**/api/investable-universe-snapshots**', route => route.fulfill({ json: snapshot }))
  await page.getByRole('link', { name: /下一步：确定投资范围/ }).click()
  await page.getByRole('checkbox', { name: /Handoff pool/ }).check()
  await page.getByRole('button', { name: '生成锁定快照', exact: true }).click()
  await expect(page.getByText('可投资域快照已锁定', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '进入手动构建大类', exact: true }).click()
  await expect(page).toHaveURL(/asset-classes\?universe=handoff-universe/)
  const journey = await page.evaluate(() => JSON.parse(sessionStorage.getItem('allocation-journey:v1')!))
  expect(journey.mandateId).toBe(saved.id)
  expect(journey.baselineId).toBeUndefined()
  expect(journey.taaRunId).toBeUndefined()
  // Reuse the fixture's existing classification; the SAA URL deliberately carries no mandate.
  await page.goto('/pre-investment/saa/policy?alloc=' + encodeURIComponent('浏览器离线股债'))
  await expect(page.getByRole('combobox', { name: '投资目标版本', exact: true })).toHaveValue(saved.id)
  await page.goto('/pre-investment/objectives')
  await row.getByRole('link', { name: '修改', exact: true }).click()
  await expect(page.getByRole('heading', { name: '修改投资目标与约束', exact: true })).toBeVisible()
  const modifiedName = `精简目标-${info.project.name}-修改`
  await page.getByLabel('目标名称', { exact: true }).fill(modifiedName)
  await page.getByRole('button', { name: '2. 结果与确认', exact: true }).click()
  await page.getByRole('button', { name: '运行目标诊断', exact: true }).click()
  await expect(page.getByText('当前约束下可实现', { exact: true })).toBeVisible()
  await page.getByRole('checkbox', { name: /我已核对输入、最终授权上限/ }).check()
  const replacement = page.waitForResponse(r => r.url().endsWith('/mandates/confirm') && r.request().method() === 'POST')
  await page.getByRole('button', { name: '保存修改后的版本', exact: true }).click()
  expect((await replacement).status()).toBe(201)
  await expect(page.getByRole('heading', { name: '已保存投资目标与约束', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '返回投资目标列表', exact: true }).click()
  await expect(page.getByText(`精简目标-${info.project.name}`, { exact: true })).toHaveCount(0)
  const activeRow = page.getByRole('row', { name: new RegExp(modifiedName) })
  await activeRow.getByRole('button', { name: '删除', exact: true }).click()
  await page.getByRole('button', { name: '确认删除', exact: true }).click()
  await expect(page.getByText(modifiedName, { exact: true })).toHaveCount(0)
  expect(errors).toEqual([])
})

test('相对基准直接使用风险等级代表组合，不要求用户手填基准', async ({ page, request }, info) => {
  const errors = await connect(page)
  const fixture = await (await request.get(`${api}/fixture`)).json()
  await page.clock.setFixedTime(new Date(`${fixture.today}T12:00:00Z`))
  await page.goto('/pre-investment/objectives')
  await page.getByRole('link', { name: '添加投资目标与约束', exact: true }).first().click()
  await page.getByLabel('目标名称', { exact: true }).fill(`相对目标-${info.project.name}`)
  await page.getByRole('combobox', { name: '投资目标类型', exact: false }).selectOption('benchmark_relative')
  await page.getByLabel(/目标年超额收益/).fill('0.5')
  await expect(page.getByLabel(/基准名称/)).toHaveCount(0)
  await expect(page.getByLabel(/基准大类方案/)).toHaveCount(0)
  await page.getByRole('combobox', { name: /风险标尺版本/ }).selectOption(fixture.scale.id)
  await page.getByRole('button', { name: /^C3 / }).click()
  await page.getByRole('button', { name: '下一步：结果与确认', exact: true }).click()
  const pending = page.waitForResponse(r => r.url().endsWith('/mandates/preview'))
  await page.getByRole('button', { name: '运行目标诊断', exact: true }).click()
  const diagnosis = await (await pending).json()
  expect(diagnosis.definition.benchmark.source).toBe('risk_scale_reference')
  expect(diagnosis.definition.benchmark.target_excess_return).toBeCloseTo(.005)
  expect(Object.values(diagnosis.definition.benchmark.weights).reduce((a: number, b: any) => a + Number(b), 0)).toBeCloseTo(1)
  await layout(page, info, 'relative-benchmark', '添加投资目标与约束')
  expect(errors).toEqual([])
})

test('编辑已保存绝对收益目标保留现金保护和独立资金验证', async ({ page, request }, info) => {
  const errors = await connect(page)
  const fixture = await (await request.get(`${api}/fixture`)).json()
  const protection = { mode: 'payments_and_terminal_floor', terminal_floor: { amount: 800000, amount_basis: 'nominal' } }
  const study = { definition: { schema_version: '2.0', name: `现金保护-${info.project.name}`,
    as_of: fixture.today, horizon_years: 10, objective_kind: 'absolute_return', target_return: 0,
    max_volatility: null, cash_budget: { total_capital: 1000000, balance_as_of: fixture.today }, cash_protection: protection,
    risk_authorization: { mode: 'manual_level', authorized_max_level: 3, selected_max_level: 3,
      risk_scale_ref: { id: fixture.scale.id, content_hash: fixture.scale.content_hash } } } }
  const initial = await request.post(`${api}/api/strategic-allocation/mandates/preview`, { data: study })
  expect(initial.status()).toBe(200)
  const savedResponse = await request.post(`${api}/api/strategic-allocation/mandates/confirm`, {
    data: { request: study, preview_hash: (await initial.json()).preview_hash, acknowledge_limits: true } })
  expect(savedResponse.status()).toBe(201)
  const saved = await savedResponse.json()
  await page.goto(`/pre-investment/objectives/new?editFrom=${saved.id}`)
  await expect(page.getByLabel(/^期末至少保有/)).toHaveValue('800000')
  await page.getByRole('combobox', { name: /^现金保护条件/ }).selectOption('payments_only')
  await page.getByRole('button', { name: '添加投入或支付', exact: true }).click()
  await page.getByLabel('现金流 1 · 目标名称', { exact: true }).fill('Recurring payment')
  await page.getByLabel(/^现金流 1 · 金额/).fill('1000')
  await page.getByRole('combobox', { name: /^现金流 1 · 频率/ }).selectOption('3')
  await page.getByRole('combobox', { name: /^现金流 1 · 开始月/ }).selectOption('25')
  await page.getByLabel('投资期限（年）', { exact: true }).fill('1')
  await expect(page.getByRole('button', { name: '2. 结果与确认', exact: true })).toBeDisabled()
  await expect(page.getByRole('combobox', { name: /^现金流 1 · 频率/ })).toHaveValue('3')
  await page.getByLabel('投资期限（年）', { exact: true }).fill('12')
  await expect(page.getByLabel(/^现金流 1 · 结束月/)).toHaveValue(/第142月/)

  await page.getByLabel('目标名称', { exact: true }).fill(`现金保护保留-${info.project.name}`)
  await page.getByRole('button', { name: '2. 结果与确认', exact: true }).click()
  const previewed = page.waitForResponse(r => r.url().endsWith('/mandates/preview'))
  await page.getByRole('button', { name: '运行目标诊断', exact: true }).click()
  const preview = await (await previewed).json()
  expect(preview.definition.cash_protection).toEqual({ mode: 'payments_only', terminal_floor: null })
  expect(preview.definition.cash_budget.flows[0].last_month).toBe(142)
  expect(preview.definition.cash_budget.flows[0].first_month).toBe(25)
  expect(preview.reference_diagnosis.validation.candidate_frozen_before_validation).toBe(true)
  await page.getByRole('checkbox', { name: /我已核对输入/ }).check()
  const confirmed = page.waitForResponse(r => r.url().endsWith('/mandates/confirm'))
  await page.getByRole('button', { name: '保存修改后的版本', exact: true }).click()
  const replacement = await (await confirmed).json()
  expect(replacement.definition.cash_protection).toEqual({ mode: 'payments_only', terminal_floor: null })
  expect(replacement.supersedes_mandate_id).toBe(saved.id)
  await expect(page.getByText('只读版本', { exact: true })).toBeVisible()
  await layout(page, info, 'cash-protection-preserved', '已保存投资目标与约束')
  expect(errors).toEqual([])
})

test('英语页面在无PIT时研究日可编辑，字段顺序和移动端布局可用', async ({ page }, info) => {
  const errors = await connect(page, 'en-US')
  await page.goto('/pre-investment/objectives')
  await expect(page.getByRole('heading', { name: 'Investment objectives and constraints', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Add investment objective', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Add investment objective', exact: true })).toBeVisible()
  await expect(page.getByLabel(/^Research date/)).toBeEnabled()
  await page.getByLabel('Name', { exact: true }).focus()
  await page.keyboard.type('English compact objective')
  await page.keyboard.press('Tab')
  await expect(page.getByLabel(/^Research date/)).toBeFocused()
  await expect(page.getByLabel(/^Base currency/)).toHaveAttribute('readonly')
  await expect(page.getByRole('navigation', { name: 'Objective workflow steps' }).getByRole('button')).toHaveCount(2)
  await layout(page, info, 'english-compact', 'Add investment objective')
  expect(errors).toEqual([])
})
