import { test, expect, type Page, type TestInfo } from '@playwright/test'
import { auditTextContrast } from './helpers/contrast'

const api = 'http://127.0.0.1:8129'
type Fixture = { allocation: string; manual_id: string; bl_id: string; scenario_id: string; mandate_id: string; common_ids: string[]; common_mandate_id: string; conflict_mandate_id: string }
let fixture: Fixture
async function layout(page: Page, info: TestInfo, name: string) {
  await page.evaluate(() => window.scrollTo(0, 0))
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1)
  await page.evaluate(async () => { await Promise.all(document.getAnimations().filter(animation => animation.effect?.getComputedTiming().iterations !== Infinity).map(animation => animation.finished.catch(() => undefined))) })
  expect(await page.evaluate(auditTextContrast)).toEqual([])
  await page.screenshot({ path: info.outputPath(`${name}.png`), fullPage: true })
}
async function add(page: Page, id: string) {
  await page.getByRole('combobox', { name: '添加已确认 CMA', exact: true }).selectOption(id)
  await expect(page.getByRole('combobox', { name: '添加已确认 CMA', exact: true })).toBeEnabled()
}
test.beforeEach(async ({ page, request }) => {
  fixture = await (await request.get(`${api}/fixture/ltcma`)).json()
  await page.route('**/api/**', async route => {
    const url = new URL(route.request().url())
    const response = await route.fetch({ url: `${api}${url.pathname}${url.search}`, timeout: 60000 })
    await route.fulfill({ response })
  })
})
test.afterEach(async ({ page }) => { await page.unrouteAll({ behavior: 'wait' }) })

test('frozen multi-CMA inputs, parameter-average SAA and immutable source history', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto(`/pre-investment/saa/policy?alloc=${encodeURIComponent(fixture.allocation)}&mandate=${fixture.mandate_id}`)
  await page.getByRole('combobox', { name: 'CMA 使用方式', exact: true }).selectOption('parameter_average')
  await add(page, fixture.manual_id); await add(page, fixture.bl_id)
  await page.getByRole('button', { name: '确认使用等权', exact: true }).click()
  await page.getByLabel('离线 BL LTCMA · 研究权重（%）', { exact: true }).fill('20')
  await expect(page.getByRole('button', { name: '核对权重并进入政策比较', exact: true })).toBeDisabled()
  await layout(page, info, 'invalid-weights')
  await page.getByRole('button', { name: '确认使用等权', exact: true }).click()
  await layout(page, info, 'frozen-selection')
  await page.reload()
  await expect(page.getByRole('combobox', { name: 'CMA 使用方式', exact: true })).toHaveValue('parameter_average')
  await expect(page.getByRole('button', { name: '核对权重并进入政策比较', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '核对权重并进入政策比较', exact: true }).click()
  const calculation = page.waitForResponse(response => response.url().includes('/policy/preview') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '比较符合目标的政策候选', exact: true }).click()
  const response = await calculation; expect(response.ok(), await response.text()).toBe(true)
  const preview = await response.json()
  expect(preview.request.mode).toBe('parameter_average')
  expect(preview.request.cma_refs).toHaveLength(2)
  expect(preview.multi_cma.aggregation_semantics).toBe('parameter_average')
  expect(preview.execution.python_fallback).toBe(0)
  expect(preview.execution.request_time_compilation).toBe(0)
  await expect(page.getByRole('table', { name: '原 CMA 交叉评估', exact: true }).first()).toBeVisible()
  await layout(page, info, 'cross-model-results')
  await page.getByRole('button', { name: '复核此候选', exact: true }).first().click()
  await page.getByLabel('采纳理由与复核关注点', { exact: false }).fill('明确采用参数平均，持续复核原模型风险差异。')
  await layout(page, info, 'adoption-review')
  const saved = page.waitForResponse(response => new URL(response.url()).pathname.endsWith('/policies') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '确认采用此长期政策', exact: true }).click()
  const publication = await saved; expect(publication.ok(), await publication.text()).toBe(true)
  const policy = await publication.json()
  expect(policy.policy.multi_cma.refs).toEqual(preview.request.cma_refs)
  await page.goto(`/pre-investment/saa/policy?baseline=${policy.id}`)
  const history = page.getByRole('region', { name: '冻结的融合来源与权重', exact: true })
  await expect(history).toContainText('离线基础 LTCMA')
  await expect(history).toContainText('离线 BL LTCMA')
  await layout(page, info, 'immutable-history')
  await page.getByRole('link', { name: '返回此政策的 TAA 研究', exact: true }).click()
  await expect(page.getByRole('heading', { name: '本次准备怎么配？', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: '回测与选优', exact: true }).click()
  const tactical = page.waitForResponse(response => new URL(response.url()).pathname === '/api/tactical-allocation/preview' && response.request().method() === 'POST')
  await page.getByRole('button', { name: '计算并比较方案', exact: true }).click()
  const tacticalResponse = await tactical; expect(tacticalResponse.ok(), await tacticalResponse.text()).toBe(true)
  const tacticalResult = await tacticalResponse.json()
  expect(tacticalResult.policy_check.cross_model_results).toHaveLength(2)
  expect(tacticalResult.policy_check.cross_model_results.every((row: { goal_check: unknown }) => row.goal_check === null)).toBe(true)
  await expect(page.getByRole('table', { name: '原 CMA 交叉评估', exact: true })).toBeVisible()
  await layout(page, info, 'taa-cross-model-results')
  expect(errors).toEqual([])
})

test('incompatible moment semantics remain a visible failure', async ({ page }, info) => {
  await page.goto(`/pre-investment/saa/policy?alloc=${encodeURIComponent(fixture.allocation)}&mandate=${fixture.mandate_id}`)
  await page.getByRole('combobox', { name: 'CMA 使用方式', exact: true }).selectOption('parameter_average')
  await add(page, fixture.manual_id); await add(page, fixture.scenario_id)
  await page.getByRole('button', { name: '确认使用等权', exact: true }).click()
  await page.getByRole('button', { name: '核对权重并进入政策比较', exact: true }).click()
  await page.getByRole('button', { name: '比较符合目标的政策候选', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText(/moment_semantics|矩|口径/)
  await expect(page.getByRole('table', { name: '长期政策候选比较', exact: true })).toHaveCount(0)
  await layout(page, info, 'incompatible-semantics')
})

async function commonSelection(page: Page, mandate: string) {
  await page.goto(`/pre-investment/saa/policy?alloc=${encodeURIComponent(fixture.allocation)}&mandate=${mandate}`)
  await page.getByRole('combobox', { name: 'CMA 使用方式', exact: true }).selectOption('compatible_all_models')
  for (const id of fixture.common_ids) await add(page, id)
  await expect(page.getByRole('button', { name: '确认使用等权', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '核对模型并进入共同配置', exact: true }).click()
}

test('continuous common allocation, individual anchor checks, immutable history and TAA gates', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await commonSelection(page, fixture.common_mandate_id)
  await page.getByRole('combobox', { name: '共同配置的选择目标', exact: true }).selectOption('maximin_return')
  const calculation = page.waitForResponse(response => response.url().includes('/policy/preview') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '比较符合目标的政策候选', exact: true }).click()
  const response = await calculation; expect(response.ok(), await response.text()).toBe(true)
  const preview = await response.json()
  expect(preview.request.cma_refs.every((ref: { weight: unknown }) => ref.weight === null)).toBe(true)
  expect(preview.compatibility.joint_solver.status).toBe('converged')
  expect(preview.candidates[0].weights['股票']).toBeCloseTo(.5, 7)
  expect(preview.candidates[0].all_models_pass).toBe(true)
  expect(preview.execution.python_fallback).toBe(0)
  expect(preview.execution.request_time_compilation).toBe(0)
  await expect(page.getByRole('region', { name: '共同配置求解结果', exact: true })).toBeVisible()
  await page.getByText('查看各模型单独求解及交叉检查', { exact: true }).click()
  await expect(page.getByRole('table', { name: '原 CMA 交叉评估', exact: true })).toHaveCount(3)
  await layout(page, info, 'common-anchors-and-joint')
  await page.getByRole('button', { name: '复核此候选', exact: true }).click()
  await page.getByLabel('采纳理由与复核关注点', { exact: false }).fill('逐一复核两种模型的共同收益和风险边界。')
  const saved = page.waitForResponse(response => new URL(response.url()).pathname.endsWith('/policies') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '确认采用此长期政策', exact: true }).click()
  const publication = await saved; expect(publication.ok(), await publication.text()).toBe(true)
  const policy = await publication.json(); expect(policy.policy.mode).toBe('compatible_all_models')
  await page.goto(`/pre-investment/saa/policy?baseline=${policy.id}`)
  await expect(page.getByRole('region', { name: '冻结的共同约束模型', exact: true })).toContainText('共同约束模型 2')
  await layout(page, info, 'common-history')
  await page.getByRole('link', { name: '返回此政策的 TAA 研究', exact: true }).click()
  await expect(page.getByRole('heading', { name: '本次准备怎么配？', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: '回测与选优', exact: true }).click()
  const tactical = page.waitForResponse(response => new URL(response.url()).pathname === '/api/tactical-allocation/preview' && response.request().method() === 'POST')
  await page.getByRole('button', { name: '计算并比较方案', exact: true }).click()
  const tacticalResponse = await tactical; expect(tacticalResponse.ok(), await tacticalResponse.text()).toBe(true)
  const result = await tacticalResponse.json()
  expect(result.policy_check.risk_evaluation_mode).toBe('compatible_all_models')
  expect(result.policy_check.within_limits).toBe(result.policy_check.cross_model_results.every((row: { within_limits: boolean }) => row.within_limits))
  await expect(page.getByRole('table', { name: '原 CMA 交叉评估', exact: true })).toBeVisible()
  await layout(page, info, 'common-taa')
  expect(errors).toEqual([])
})

test('inconsistent model floors produce a proof and no adoption action', async ({ page }, info) => {
  await commonSelection(page, fixture.conflict_mandate_id)
  const calculation = page.waitForResponse(response => response.url().includes('/policy/preview') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '比较符合目标的政策候选', exact: true }).click()
  const response = await calculation; expect(response.ok(), await response.text()).toBe(true)
  const result = await response.json()
  expect(result.compatibility.joint_solver.status).toBe('infeasible')
  expect(result.compatibility.joint_solver.phase_one_lower_bound).toBeGreaterThan(0)
  await expect(page.getByText('已证明：这些约束无法同时满足。', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '复核此候选', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '4. 确认与交接', exact: true })).toBeDisabled()
  await layout(page, info, 'common-infeasible')
})
