import { test, expect } from '@playwright/test'
import { spawn, type ChildProcess } from 'node:child_process'
import { createServer } from 'node:net'
import path from 'node:path'

let backend: ChildProcess | undefined
let apiRoot = ''
let logs = ''

test.beforeAll(async ({ request }) => {
  test.setTimeout(120_000)
  const socket = createServer()
  await new Promise<void>((resolve, reject) => { socket.once('error', reject); socket.listen(0, '127.0.0.1', resolve) })
  const address = socket.address()
  if (!address || typeof address === 'string') throw new Error('Missing test port')
  const port = address.port
  await new Promise<void>(resolve => socket.close(() => resolve()))
  apiRoot = `http://127.0.0.1:${port}`
  backend = spawn(process.env.INDICATOR_TEST_PYTHON || 'python3', ['-m', 'uvicorn', 'scalar_outputs_app:app', '--app-dir', 'tests', '--host', '127.0.0.1', '--port', String(port)], {
    cwd: path.resolve(process.cwd(), '../backend'),
    env: { ...process.env, ALL_PROXY: '', HTTP_PROXY: '', HTTPS_PROXY: '', NO_PROXY: '127.0.0.1,localhost', OPENBLAS_NUM_THREADS: '1', OMP_NUM_THREADS: '1', NUMBA_NUM_THREADS: '1' },
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  backend.stdout?.on('data', data => { logs = (logs + String(data)).slice(-8000) })
  backend.stderr?.on('data', data => { logs = (logs + String(data)).slice(-8000) })
  backend.on('error', error => { logs += error.message })
  await expect.poll(async () => {
    if (backend?.exitCode !== null && backend?.exitCode !== undefined) throw new Error(logs)
    try { return (await request.get(`${apiRoot}/ready`, { timeout: 1000 })).ok() } catch { return false }
  }, { timeout: 100_000 }).toBe(true)
})

test.afterEach(async ({}, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus) {
    console.error('Isolated backend diagnostics:', logs)
    await testInfo.attach('isolated-backend', { body: logs, contentType: 'text/plain' })
  }
})

test.afterAll(async () => {
  if (!backend || backend.exitCode !== null) return
  const stopped = new Promise<void>(resolve => backend?.once('exit', () => resolve()))
  backend.kill('SIGTERM')
  await Promise.race([stopped, new Promise<void>(resolve => setTimeout(resolve, 10_000))])
  if (backend.exitCode === null) backend.kill('SIGKILL')
})

test('可变参数真实 API：开放、默认值、画布、覆盖计算和导出', async ({ page, request }, testInfo) => {
  test.setTimeout(150_000)
  page.setDefaultTimeout(20_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('dialog', dialog => dialog.accept())
  const created = await request.post(`${apiRoot}/api/custom-indicators`, { data: {
    name: '浏览器可调均线', description: '隔离数据参数验收', result_kind: 'time_series', axis_anchor: 'adjusted_nav',
    series_outputs: [{ id: 'ma', label: '净值均线', expression: 'rolling_mean(adjusted_nav, 5)', output_measure: 'auto', unit: '', display_format: 'number', precision: 4 }],
    dsl_version: '2.3.0', operator_registry_version: '2.3.0', context_kind: 'single_product',
  } })
  expect(created.ok(), await created.text()).toBe(true)
  const original = await created.json()
  await page.route('**/api/**', async route => {
    const url = new URL(route.request().url())
    if (url.pathname.startsWith('/api/custom-indicators')) {
      await route.fulfill({ response: await route.fetch({ url: `${apiRoot}${url.pathname}${url.search}`, timeout: 90_000 }) })
    } else if (url.pathname === '/api/instruments/search') {
      await route.fulfill({ json: { items: [{ code: '510050.SH', ts_code: '510050.SH', name: '上证50ETF', instrument_type: 'etf' }], total: 1, page: 1, page_size: 10, kind: 'etf' } })
    } else await route.fulfill({ status: 503, json: { detail: 'Isolated test' } })
  })
  await page.goto('/settings/indicators-models')
  await page.getByRole('button', { name: /^浏览器可调均线/ }).click()
  await page.getByRole('button', { name: '识别可调输入' }).click()
  await page.getByRole('button', { name: '开放为参数' }).click()
  await expect(page.getByLabel('默认值', { exact: true })).toHaveValue('5')
  await page.getByLabel('默认值', { exact: true }).fill('7')
  await page.getByRole('button', { name: '应用参数设置' }).click()
  const validating = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators/validate'))
  await page.getByRole('button', { name: '解析并校验全部通道' }).click()
  const validation = await (await validating).json()
  expect(validation.valid, JSON.stringify(validation.diagnostics)).toBe(true)
  const saving = page.waitForResponse(response => response.url().endsWith(`/api/custom-indicators/${original.id}`) && response.request().method() === 'PUT')
  await page.getByRole('button', { name: '保存修改', exact: true }).first().click()
  const saved = await (await saving).json()
  expect(saved.parameter_schema[0].default).toBe(7)
  expect(saved.parameter_contract_version).toBe('1.0')
  const graphResolving = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators/graph/resolve'))
  await page.getByRole('tab', { name: /画布/ }).click()
  const graph = await (await graphResolving).json()
  expect(graph.valid, JSON.stringify(graph.diagnostics)).toBe(true)
  expect(graph.graph.nodes.some((node: { kind: string }) => node.kind === 'parameter')).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('runtime-parameter-editor.png'), fullPage: true })
  const previewTab = page.locator('#workspace-tab-preview')
  if (await previewTab.isVisible()) await previewTab.click()
  else await page.locator('#indicator-tab-preview').click()
  await page.getByLabel('搜索产品', { exact: true }).fill('510050')
  await page.getByLabel('搜索产品', { exact: true }).press('Enter')
  await page.getByRole('button', { name: '添加', exact: true }).click()
  await page.locator('#indicator-panel-preview select:has(option[value="ALL"])').selectOption('ALL')
  const firstCalculation = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators/evaluate-series'))
  await page.getByRole('button', { name: '预览指标', exact: true }).click()
  const initial = await (await firstCalculation).json()
  expect(initial.results[0].parameters).toEqual({ window_1: 7 })
  expect(initial.execution.request_time_compilation).toBe(0)
  expect(initial.execution.python_fallback).toBe(0)
  await page.locator('summary').filter({ hasText: '本次计算参数' }).click()
  await page.getByLabel('窗口期数', { exact: true }).fill('3')
  await page.getByRole('button', { name: '应用参数', exact: true }).click()
  const overrideCalculation = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators/evaluate-series'))
  await page.getByRole('button', { name: '预览指标', exact: true }).click()
  const overridden = await (await overrideCalculation).json()
  expect(overridden.results[0].parameters).toEqual({ window_1: 3 })
  expect(overridden.results[0].parameter_hash).not.toBe(initial.results[0].parameter_hash)
  expect(overridden.execution.compiled_plan_ids).toEqual(initial.execution.compiled_plan_ids)
  const exportRequest = page.waitForRequest(request => request.url().includes('/export-excel'))
  const downloading = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载 Excel 计算逻辑' }).click()
  expect((await exportRequest).postDataJSON().parameters).toEqual({ window_1: 3 })
  const download = await downloading
  expect(await download.failure()).toBeNull()
  await download.saveAs(testInfo.outputPath('runtime-parameter.xlsx'))
  await page.screenshot({ path: testInfo.outputPath('runtime-parameter-preview.png'), fullPage: true })
  await page.getByRole('button', { name: '恢复默认', exact: true }).click()
  await expect(page.getByLabel('窗口期数', { exact: true })).toHaveValue('7')
  const unchanged = await (await request.get(`${apiRoot}/api/custom-indicators/${original.id}`)).json()
  expect(unchanged.revision).toBe(saved.revision)
  expect(unchanged.parameter_schema[0].default).toBe(7)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  expect(errors).toEqual([])
})


test('真实 API：添加结果、切换公式、保存版本、画布恢复、预览与 Excel', async ({ page, request }, testInfo) => {
  test.setTimeout(120_000)
  page.setDefaultTimeout(15_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('dialog', dialog => dialog.accept())
  const created = await request.post(`${apiRoot}/api/custom-indicators`, { data: {
    name: '浏览器多结果测试', description: '隔离测试数据', expression: 'mean(returns)',
    display_format: 'percent', precision: 2, direction: 'higher_better', unit: '%',
    dsl_version: '2.3.0', operator_registry_version: '2.3.0', context_kind: 'single_product',
  } })
  expect(created.ok(), await created.text()).toBe(true)
  const originalDefinition = await created.json()
  await page.route('**/api/**', async route => {
    const url = new URL(route.request().url())
    if (url.pathname.startsWith('/api/custom-indicators')) {
      const response = await route.fetch({ url: `${apiRoot}${url.pathname}${url.search}`, timeout: 90_000 })
      await route.fulfill({ response })
    } else if (url.pathname === '/api/instruments/search') {
      await route.fulfill({ json: { items: [{ code: '510050.SH', ts_code: '510050.SH', name: '上证50ETF', instrument_type: 'etf', management: null, found_date: null }], total: 1, page: 1, page_size: 10, kind: 'etf' } })
    } else {
      // Unrelated navigation/localization requests cannot reach real user data.
      await route.fulfill({ status: 503, json: { detail: 'Not part of this isolated test' } })
    }
  })
  await page.goto('/settings/indicators-models')
  await page.getByRole('button', { name: /^浏览器多结果测试/ }).click()
  await page.getByRole('tab', { name: '高级公式模式' }).click()
  const source = page.getByRole('textbox', { name: /公式源码/ })
  const originalFormula = await source.inputValue()
  await page.getByRole('button', { name: '＋添加结果' }).click()
  await expect(page.getByLabel('结果名称')).toBeFocused()
  await page.getByLabel('结果名称').fill('双倍平均值')
  await source.fill('mean(returns) * 2')
  await expect(page.getByLabel('评分方向')).toHaveValue('neutral')
  await page.getByRole('tab', { name: '浏览器多结果测试', exact: true }).click()
  await expect(source).toHaveValue(originalFormula)
  await page.getByRole('tab', { name: '双倍平均值', exact: true }).click()
  await expect(source).toHaveValue('mean(returns) * 2')
  const validationResponse = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators/validate'))
  await page.getByRole('button', { name: '解析并校验全部结果' }).click()
  const validation = await (await validationResponse).json()
  expect(validation.valid, JSON.stringify(validation.diagnostics)).toBe(true)
  expect(Object.keys(validation.dag.roots)).toHaveLength(2)
  const saving = page.waitForResponse(response => response.url().endsWith(`/api/custom-indicators/${originalDefinition.id}`) && response.request().method() === 'PUT')
  await page.getByRole('button', { name: '保存修改', exact: true }).first().click()
  const saved = await (await saving).json()
  expect(saved.revision).toBe(2)
  expect(saved.scalar_outputs.map((item: { label: string }) => item.label)).toEqual(['浏览器多结果测试', '双倍平均值'])
  const graphResponse = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators/graph/resolve'))
  await page.getByRole('tab', { name: /画布/ }).click()
  const graph = await (await graphResponse).json()
  expect(graph.valid, JSON.stringify(graph.diagnostics)).toBe(true)
  expect(graph.graph.outputs).toHaveLength(2)
  await expect(page.getByTestId('indicator-graph-canvas')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('scalar-outputs-canvas.png'), fullPage: true })
  const previewTab = page.locator('#workspace-tab-preview')
  if (await previewTab.isVisible()) await previewTab.click()
  else await page.locator('#indicator-tab-preview').click()
  await page.getByLabel('搜索产品', { exact: true }).fill('510050')
  await page.getByLabel('搜索产品', { exact: true }).press('Enter')
  await page.getByRole('button', { name: '添加', exact: true }).click()
  await page.locator('#indicator-panel-preview select:has(option[value="ALL"])').selectOption('ALL')
  const evaluationResponse = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators/evaluate'))
  await page.getByRole('button', { name: '预览指标', exact: true }).click()
  const evaluationHttp = await evaluationResponse
  const evaluated = await evaluationHttp.json()
  expect(evaluationHttp.ok(), JSON.stringify(evaluated)).toBe(true)
  expect(evaluated.results[0].outputs).toHaveLength(2)
  expect(evaluated.results[0].outputs[1].value).toBeCloseTo(evaluated.results[0].outputs[0].value * 2, 12)
  await expect(page.getByLabel('各结果数值', { exact: true })).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载 Excel 计算逻辑' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/\.xlsx$/)
  await download.saveAs(testInfo.outputPath('scalar-outputs.xlsx'))
  expect(await download.failure()).toBeNull()
  await page.screenshot({ path: testInfo.outputPath('scalar-outputs-preview.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  expect(errors).toEqual([])
})


test('统一构建：常规算子入口创建多结果，输入修改保持结果身份', async ({ page }, testInfo) => {
  test.setTimeout(120_000)
  page.on('dialog', dialog => dialog.accept())
  await page.route('**/api/**', async route => {
    const url = new URL(route.request().url())
    if (url.pathname.startsWith('/api/custom-indicators')) {
      const response = await route.fetch({ url: `${apiRoot}${url.pathname}${url.search}`, timeout: 90_000 })
      await route.fulfill({ response })
    } else await route.fulfill({ status: 503, json: { detail: 'Isolated test' } })
  })
  await page.goto('/settings/indicators-models')
  await page.getByRole('button', { name: '新建指标', exact: true }).click()
  await expect(page.getByRole('button', { name: '使用此计算', exact: true })).toHaveCount(0)
  expect(await page.getByTestId('indicator-calculation-editor').getByTestId('indicator-output-settings').count()).toBe(0)
  await page.getByRole('button', { name: '浏览公式构建资源', exact: true }).click()
  const catalog = page.getByRole('dialog', { name: '变量、算子与已有指标' })
  await catalog.getByLabel('资源类型').selectOption('operators')
  await catalog.getByRole('combobox', { name: '选择算子' }).click()
  await catalog.getByLabel('搜索选择算子').fill('最大回撤')
  await catalog.getByLabel('搜索选择算子').press('Enter')
  await catalog.getByRole('button', { name: '配置算子参数' }).click()
  const builder = page.getByRole('dialog', { name: '配置 最大回撤分析' })
  await expect(builder.getByRole('combobox', { name: / 变量$/ })).toHaveValue('adjusted_nav')
  const composed = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators/compose'))
  await builder.getByRole('button', { name: '应用计算' }).click()
  expect((await (await composed).json()).output_ports).toHaveLength(4)
  await page.getByLabel('名称', { exact: true }).fill('自定义回撤组合')
  const selected = page.getByTestId('indicator-output-settings')
  await expect(selected.getByRole('tab')).toHaveCount(4)
  await selected.getByRole('tab', { name: '最大回撤恢复期数' }).click()
  await selected.getByRole('button', { name: '删除结果' }).click()
  await selected.getByRole('tab', { name: '最大回撤', exact: true }).click()
  await selected.getByLabel('结果名称').fill('自定义回撤幅度')
  const saving = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '保存新指标', exact: true }).first().click()
  const response = await saving
  const saved = await response.json()
  expect(response.ok(), JSON.stringify(saved)).toBe(true)
  expect(saved.scalar_outputs).toHaveLength(3)
  expect(saved.source).toBe('custom')
  expect(saved.scalar_outputs.every((output: { expression: string }) => output.expression.includes('drawdown_analysis'))).toBe(true)
  await page.reload()
  await page.getByRole('button', { name: /^自定义回撤组合/ }).click()
  await expect(selected.getByRole('tab')).toHaveCount(3)
  await expect(selected.getByRole('tab', { name: '最大回撤恢复期数' })).toHaveCount(0)
  await page.getByRole('button', { name: '编辑计算输入' }).click()
  const editing = page.getByRole('dialog')
  const variable = editing.getByRole('combobox', { name: / 变量$/ })
  await expect(variable).toHaveValue('adjusted_nav')
  await variable.selectOption('market_close')
  await editing.getByRole('button', { name: '应用逻辑修改' }).click()
  await expect(selected.getByRole('tab')).toHaveCount(3)
  const updating = page.waitForResponse(response => response.request().method() === 'PUT' && response.url().includes('/api/custom-indicators/'))
  await page.getByRole('button', { name: '保存修改', exact: true }).click()
  const updatedResponse = await updating
  const updated = await updatedResponse.json()
  expect(updatedResponse.ok(), JSON.stringify(updated)).toBe(true)
  expect(updated.scalar_outputs.map((output: { id: string; label: string }) => [output.id, output.label])).toEqual(saved.scalar_outputs.map((output: { id: string; label: string }) => [output.id, output.label]))
  expect(updated.scalar_outputs.every((output: { expression: string }) => output.expression.includes('(market_close).'))).toBe(true)
  await selected.getByRole('button', { name: '＋添加结果' }).click()
  await selected.getByRole('button', { name: '最大回撤恢复期数', exact: true }).click()
  await expect(selected.getByRole('tab')).toHaveCount(4)
  await page.screenshot({ path: testInfo.outputPath('unified-output-authoring.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
})

test('最大回撤：共享输入、四结果、一次分析、画布往返与导出', async ({ page }, testInfo) => {
  test.setTimeout(120_000)
  page.setDefaultTimeout(20_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/api/**', async route => {
    const url = new URL(route.request().url())
    if (url.pathname.startsWith('/api/custom-indicators')) {
      const response = await route.fetch({ url: `${apiRoot}${url.pathname}${url.search}`, timeout: 90_000 })
      await route.fulfill({ response })
    } else if (url.pathname === '/api/instruments/search') {
      await route.fulfill({ json: { items: [{ code: '510050.SH', ts_code: '510050.SH', name: '上证50ETF', instrument_type: 'etf' }], total: 1, page: 1, page_size: 10, kind: 'etf' } })
    } else await route.fulfill({ status: 503, json: { detail: 'Isolated test' } })
  })
  await page.goto('/settings/indicators-models')
  await page.getByRole('button', { name: /^最大回撤分析/ }).click()
  await expect(page.getByRole('button', { name: /^市场归因/ })).toHaveCount(0)
  await expect(page.getByTestId('indicator-output-settings').getByRole('tab')).toHaveCount(4)
  await expect(page.getByRole('button', { name: '编辑计算输入' })).toBeVisible()
  await expect(page.getByRole('button', { name: '使用此计算' })).toHaveCount(0)
  expect(await page.getByTestId('indicator-calculation-editor').getByTestId('indicator-output-settings').count()).toBe(0)
  await page.getByRole('tab', { name: '最大回撤恢复期数', exact: true }).click()
  await expect(page.getByLabel('评分方向')).toHaveValue('neutral')
  await page.getByRole('tab', { name: '高级公式模式' }).click()
  const validationResponse = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators/validate'))
  await page.getByRole('button', { name: '解析并校验全部结果' }).click()
  const validation = await (await validationResponse).json()
  expect(validation.valid, JSON.stringify(validation.diagnostics)).toBe(true)
  expect(Object.keys(validation.dag.roots)).toHaveLength(4)
  expect(validation.dag.nodes.filter((node: { operator?: { id: string } }) => node.operator?.id === 'drawdown_analysis')).toHaveLength(1)
  await expect(page.getByTestId('formula-preview').locator('.katex')).toBeVisible()
  const resolving = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators/graph/resolve'))
  await page.getByRole('tab', { name: /画布/ }).click()
  const resolved = await (await resolving).json()
  expect(resolved.valid, JSON.stringify(resolved.diagnostics)).toBe(true)
  expect(resolved.graph.nodes.filter((node: { kind: string }) => node.kind === 'operator')).toHaveLength(1)
  expect(resolved.graph.outputs).toHaveLength(4)
  expect(resolved.graph.outputs.map((output: { port_id: string }) => output.port_id)).toEqual(['max_drawdown', 'decline_periods', 'recovery_periods', 'longest_underwater_periods'])
  await expect(page.getByTestId('indicator-graph-canvas')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('drawdown-shared-graph.png'), fullPage: true })
  const previewTab = page.locator('#workspace-tab-preview')
  if (await previewTab.isVisible()) await previewTab.click()
  else await page.locator('#indicator-tab-preview').click()
  await page.getByLabel('搜索产品', { exact: true }).fill('510050')
  await page.getByLabel('搜索产品', { exact: true }).press('Enter')
  await page.getByRole('button', { name: '添加', exact: true }).click()
  await page.getByLabel('计算周期', { exact: true }).selectOption('ALL')
  const evaluated = page.waitForResponse(response => response.url().endsWith('/api/custom-indicators/evaluate'))
  await page.getByRole('button', { name: '预览指标', exact: true }).click()
  const response = await evaluated
  const result = await response.json()
  expect(response.ok(), JSON.stringify(result)).toBe(true)
  expect(result.results[0].outputs).toHaveLength(4)
  expect(result.results[0].outputs[0].value).not.toBeNull()
  await expect(page.getByLabel('各结果数值', { exact: true })).toBeVisible()
  const downloading = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载 Excel 计算逻辑' }).click()
  const download = await downloading
  await download.saveAs(testInfo.outputPath('drawdown-shared-calculation.xlsx'))
  expect(await download.failure()).toBeNull()
  await page.screenshot({ path: testInfo.outputPath('builtin-drawdown-results.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  expect(errors).toEqual([])
})
