import type { RiskRun } from '../../services/riskModels'
import { frequencyLabels, numberText, sectionClass } from './ResearchUI'

export default function RiskRunView({ run, published = false, releaseId }: { run: RiskRun; published?: boolean; releaseId?: string }) {
  return <section className={`${sectionClass} space-y-4`} aria-label="敏感性研究结果">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{run.name}</h3><p className="mt-1 text-xs text-slate-600">数据截至 {run.data_as_of ?? run.as_of} · {frequencyLabels[run.frequency]} · {run.method === 'cashflow' ? '现金流定价' : '数据估计的系数'}</p></div><span className={`rounded-lg px-3 py-1 text-xs font-semibold ${run.publishable ? 'bg-accent-50 text-accent-900' : 'bg-amber-50 text-amber-900'}`}>{published ? '已发布结果 · 只读' : run.transient ? (run.publishable ? '当前预览 · 未保存' : '当前预览 · 不可发布') : run.publishable ? '验证通过，可发布研究成果' : '暂不可发布'}</span></div>
    {run.blockers.length > 0 && <div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{run.blockers.map(item => <p key={item}>{item}</p>)}</div>}
    {run.method === 'cashflow' && run.metrics ? <div className="grid gap-4 sm:grid-cols-3">{[['现金流价格', run.metrics.price], ['修正久期', run.metrics.modified_duration], ['凸度', run.metrics.convexity]].map(([label, value]) => <div key={String(label)}><div className="text-xs text-slate-600">{label}</div><div className="mt-1 text-xl font-semibold tabular-nums">{numberText(Number(value), 4)}</div></div>)}</div> : <>
      <p className="text-sm text-slate-600">下表回答：<strong className="font-medium text-slate-900">一个因子按表头幅度变化，产品或下游变量大约改变多少？</strong> 这是其余因子不变时的当期模型响应；滞后响应见原始系数，不是收益预测。</p>
      <div className="overflow-x-auto"><table className="w-full min-w-[480px] text-sm"><caption className="sr-only">单因子变化对应的只读敏感性</caption><thead className="border-b border-slate-200 text-left text-xs text-slate-600"><tr><th scope="col" className="p-2">研究对象</th>{run.inputs.map(input => <th scope="col" key={input.id} className="p-2 text-right"><div>{input.name}</div><div className="mt-1 font-normal">{input.reference_move}</div></th>)}</tr></thead><tbody className="divide-y divide-slate-100">{run.rows.map(row => <tr key={row.target_id}><th scope="row" className="p-3 text-left font-medium">{row.name}</th>{row.reference_responses.map((value, index) => <td key={run.inputs[index].id} className="p-3 text-right tabular-nums">{numberText(value)}{value == null ? '' : row.unit === 'return' ? '%' : row.unit === 'pp' ? ' 个百分点' : row.unit === 'points' ? ' 点' : ' bp'}</td>)}</tr>)}</tbody></table></div>
      <details className="border-t border-slate-100 pt-3"><summary className="cursor-pointer text-sm font-medium text-slate-700">验证样本与原始系数</summary><p className="mt-2 text-xs leading-5 text-slate-600">系数只读。R² 是模型解释程度，不是准确率，也不是因果证明。{run.deployment_fit === 'full_window_after_holdout_validation' ? '验证完成后已全样本重估；下表验证分数对应重估前的独立验证模型。' : '发布系数仅使用训练区间。'}</p><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[560px] text-xs"><thead className="text-left text-slate-600"><tr><th scope="col" className="p-2">对象</th><th scope="col" className="p-2">训练样本</th><th scope="col" className="p-2">验证样本</th><th scope="col" className="p-2">训练 R²</th><th scope="col" className="p-2">验证 R²</th><th scope="col" className="p-2">验证结论</th></tr></thead><tbody>{run.rows.map(row => <tr key={row.target_id} className="border-t border-slate-100"><td className="p-2">{row.name}</td><td className="p-2">{row.train_observations}</td><td className="p-2">{row.validation_observations}</td><td className="p-2">{numberText(row.training_r2)}</td><td className="p-2">{numberText(row.validation_r2)}</td><td className="p-2">{row.status_label}</td></tr>)}</tbody></table></div><div className="mt-3 space-y-2 text-xs text-slate-600">{run.rows.map(row => <p key={row.target_id} className="break-words"><span className="font-medium">{row.name}：</span>{row.betas.map((value, index) => `${run.inputs[index % run.inputs.length].name}${index >= run.inputs.length ? `（滞后${Math.floor(index / run.inputs.length)}期）` : ''} β=${numberText(value, 6)}`).join('；')}</p>)}</div></details>
    </>}
    {releaseId && <p className="break-all text-xs text-slate-600">发布版本：{releaseId}</p>}
    <details className="border-t border-slate-100 pt-3"><summary className="cursor-pointer text-sm font-medium text-slate-700">适用限制与结果来源</summary><div className="mt-2 space-y-2 text-xs leading-5 text-slate-600">{run.limitations.map(item => <p key={item}>{item}</p>)}<p className="break-all">{run.transient ? '预览' : '运行'}：{run.id} · 固定签名 NJIT · Python 回退：0</p><p className="break-all">内容校验：{run.content_hash}</p><p>{run.transient ? '当前计算结果尚未写入磁盘；只有确认发布后才会持久化。' : '已发布结果保存于统一数据磁盘；浏览页面不会重新训练。'}</p></div></details>
  </section>
}
