import { systemText, useI18n } from '../../i18n/runtime'
import type { RiskRun } from '../../services/riskModels'
import { frequencyLabels, numberText, sectionClass } from './ResearchUI'

export default function RiskRunView({ run, published = false, releaseId }: { run: RiskRun; published?: boolean; releaseId?: string }) {
  useI18n()
  return <section className={`${sectionClass} space-y-4`} aria-label={systemText('preInvestment.riskRunView.sensitivityResearchResults')}>
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{run.name}</h3><p className="mt-1 text-xs text-slate-600">{systemText('preInvestment.riskRunView.dataThrough') + " "}{run.data_as_of ?? run.as_of} · {frequencyLabels[run.frequency]} · {run.method === 'cashflow' ? systemText('preInvestment.riskRunView.cashFlowPricing') : systemText('preInvestment.riskRunView.dataEstimatedCoefficients')}</p></div><span className={`rounded-lg px-3 py-1 text-xs font-semibold ${run.publishable ? 'bg-accent-50 text-accent-900' : 'bg-amber-50 text-amber-900'}`}>{published ? systemText('preInvestment.riskRunView.publishedResultReadOnly') : run.transient ? (run.publishable ? systemText('preInvestment.riskRunView.currentPreviewUnsaved') : systemText('preInvestment.riskRunView.currentPreviewNotPublishable')) : run.publishable ? systemText('preInvestment.riskRunView.validationPassedResearchResultCanBePublished') : systemText('preInvestment.riskRunView.notYetPublishable')}</span></div>
    {run.blockers.length > 0 && <div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{run.blockers.map(item => <p key={item}>{item}</p>)}</div>}
    {run.method === 'cashflow' && run.metrics ? <div className="grid gap-4 sm:grid-cols-3">{[[systemText('preInvestment.riskRunView.cashFlowPrice'), run.metrics.price], [systemText('preInvestment.riskRunView.modifiedDuration'), run.metrics.modified_duration], [systemText('preInvestment.riskRunView.convexity'), run.metrics.convexity]].map(([label, value]) => <div key={String(label)}><div className="text-xs text-slate-600">{label}</div><div className="mt-1 text-xl font-semibold tabular-nums">{numberText(Number(value), 4)}</div></div>)}</div> : <>
      <p className="text-sm text-slate-600">{systemText('preInvestment.riskRunView.theTableAnswers')}<strong className="font-medium text-slate-900">{systemText('preInvestment.riskRunView.howMuchDoesTheProductOrDownstream')}</strong> {" " + systemText('preInvestment.riskRunView.thisIsTheCurrentModelResponseWith')}</p>
      <div className="overflow-x-auto"><table className="w-full min-w-[480px] text-sm"><caption className="sr-only">{systemText('preInvestment.riskRunView.readOnlySensitivityToSingleFactorChanges')}</caption><thead className="border-b border-slate-200 text-left text-xs text-slate-600"><tr><th scope="col" className="p-2">{systemText('preInvestment.riskRunView.researchTarget')}</th>{run.inputs.map(input => <th scope="col" key={input.id} className="p-2 text-right"><div>{input.name}</div><div className="mt-1 font-normal">{input.reference_move}</div></th>)}</tr></thead><tbody className="divide-y divide-slate-100">{run.rows.map(row => <tr key={row.target_id}><th scope="row" className="p-3 text-left font-medium">{row.name}</th>{row.reference_responses.map((value, index) => <td key={run.inputs[index].id} className="p-3 text-right tabular-nums">{numberText(value)}{value == null ? '' : row.unit === 'return' ? '%' : row.unit === 'pp' ? " " + systemText('preInvestment.riskRunView.percentagePoints') : row.unit === 'points' ? " " + systemText('preInvestment.riskRunView.points') : ' bp'}</td>)}</tr>)}</tbody></table></div>
      <details className="border-t border-slate-100 pt-3"><summary className="cursor-pointer text-sm font-medium text-slate-700">{systemText('preInvestment.riskRunView.validationSamplesAndRawCoefficients')}</summary><p className="mt-2 text-xs leading-5 text-slate-600">{systemText('preInvestment.riskRunView.coefficientsAreReadOnlyRMeasuresModel')}{run.deployment_fit === 'full_window_after_holdout_validation' ? systemText('preInvestment.riskRunView.theModelWasRefittedOnAllData') : systemText('preInvestment.riskRunView.publishedCoefficientsUseTrainingDataOnly')}</p><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[560px] text-xs"><thead className="text-left text-slate-600"><tr><th scope="col" className="p-2">{systemText('preInvestment.riskRunView.target')}</th><th scope="col" className="p-2">{systemText('preInvestment.riskRunView.trainingSamples')}</th><th scope="col" className="p-2">{systemText('preInvestment.riskRunView.validationSamples')}</th><th scope="col" className="p-2">{systemText('preInvestment.riskRunView.trainingR')}</th><th scope="col" className="p-2">{systemText('preInvestment.riskRunView.validationR')}</th><th scope="col" className="p-2">{systemText('preInvestment.riskRunView.validationConclusion')}</th></tr></thead><tbody>{run.rows.map(row => <tr key={row.target_id} className="border-t border-slate-100"><td className="p-2">{row.name}</td><td className="p-2">{row.train_observations}</td><td className="p-2">{row.validation_observations}</td><td className="p-2">{numberText(row.training_r2)}</td><td className="p-2">{numberText(row.validation_r2)}</td><td className="p-2">{row.status_label}</td></tr>)}</tbody></table></div><div className="mt-3 space-y-2 text-xs text-slate-600">{run.rows.map(row => <p key={row.target_id} className="break-words"><span className="font-medium">{row.name}：</span>{row.betas.map((value, index) => `${run.inputs[index % run.inputs.length].name}${index >= run.inputs.length ? systemText('preInvestment.riskRunView.lagPeriods', { p0: Math.floor(index / run.inputs.length) }) : ''} β=${numberText(value, 6)}`).join('；')}</p>)}</div></details>
    </>}
    {releaseId && <p className="break-all text-xs text-slate-600">{systemText('preInvestment.riskRunView.publishedVersion')}{releaseId}</p>}
    <details className="border-t border-slate-100 pt-3"><summary className="cursor-pointer text-sm font-medium text-slate-700">{systemText('preInvestment.riskRunView.applicabilityLimitsAndResultProvenance')}</summary><div className="mt-2 space-y-2 text-xs leading-5 text-slate-600">{run.limitations.map(item => <p key={item}>{item}</p>)}<p className="break-all">{run.transient ? systemText('preInvestment.riskRunView.preview') : systemText('preInvestment.riskRunView.run')}：{run.id} {" " + systemText('preInvestment.riskRunView.fixedSignatureNjitPythonFallbacks0')}</p><p className="break-all">{systemText('preInvestment.riskRunView.contentVerification')}{run.content_hash}</p><p>{run.transient ? systemText('preInvestment.riskRunView.thisCalculationIsNotSavedToDisk') : systemText('preInvestment.riskRunView.publishedResultsAreStoredOnTheShared')}</p></div></details>
  </section>
}
