"""Investment booking, ledger, valuation, PBOR, performance, and attribution contracts."""

from __future__ import annotations

from ..types import CategoryDefinition, TableDefinition, control_audit_fields, field, foreign_id, primary_id


CATEGORY = CategoryDefinition(
    category_id="accounting",
    label="投资核算与绩效",
    description="把外部事实转为 Booking、投资账、组合子账、估值、关账、PBOR、绩效和归因结果。",
    order=110,
)


def _internal_field(*args, **kwargs):
    kwargs["source_mappable"] = False
    return field(*args, **kwargs)


def _table(
    table_id: str,
    label: str,
    description: str,
    grain: str,
    primary_key: tuple[str, ...],
    fields: tuple,
    *,
    storage_engine: str = "sqlite",
    layer: str = "control",
    update_strategy: str = "append",
    partition_by: tuple[str, ...] = (),
    sort_by: tuple[str, ...] = (),
) -> TableDefinition:
    name = table_id.split(".", 1)[1]
    location = "data/platform.db" if storage_engine == "sqlite" else f"data/marts/v1/accounting/{name}/"
    return TableDefinition(
        table_id=table_id,
        category_id=CATEGORY.category_id,
        label=label,
        description=description,
        layer=layer,  # type: ignore[arg-type]
        storage_engine=storage_engine,  # type: ignore[arg-type]
        storage_location=location,
        delivery_phase="next",
        grain=grain,
        primary_key=primary_key,
        update_strategy=update_strategy,  # type: ignore[arg-type]
        fields=fields,
        source_mappable=False,
        partition_by=partition_by,
        sort_by=sort_by,
        pit_supported=True,
    )


TABLES = (
    _table(
        "accounting.policy_version",
        "投资核算政策版本",
        "冻结成本、收益确认、汇率、估值、现金流、费用、税费和凭证映射口径。",
        "每个核算政策版本一条记录",
        ("accounting_policy_version_id",),
        (
            primary_id("accounting_policy_version_id", "核算政策版本 ID", "不可变核算政策版本标识。"),
            _internal_field("accounting_policy_id", "核算政策 ID", "string", "跨版本稳定政策标识。", nullable=False),
            _internal_field("version", "版本号", "int64", "政策内递增版本号。", nullable=False),
            _internal_field("name", "政策名称", "string", "核算政策名称。", nullable=False),
            _internal_field("scope", "适用范围", "string", "主体投资账或组合管理子账。", nullable=False, enum_values=("OWNER_LEDGER", "PORTFOLIO_SUBLEDGER", "BOTH")),
            _internal_field("base_currency_policy", "本位币策略", "string", "主体或组合本位币确定方式。", nullable=False),
            _internal_field("cost_method", "成本方法", "string", "FIFO、移动平均或指定批次。", nullable=False, enum_values=("FIFO", "AVERAGE", "SPECIFIC")),
            _internal_field("trade_date_accounting", "交易日核算", "bool", "是否在交易日确认证券和应收应付。", nullable=False),
            _internal_field("settlement_date_accounting", "交收日核算", "bool", "是否在交收日确认现金。", nullable=False),
            _internal_field("fx_policy_json", "汇率规则", "json", "交易、估值和报表换算规则。", nullable=False),
            _internal_field("valuation_policy_json", "估值规则", "json", "价格来源、净值、缺失和陈旧数据处理。", nullable=False),
            _internal_field("income_policy_json", "收益确认规则", "json", "分红、利息和已实现损益确认规则。", nullable=False),
            _internal_field("fee_tax_policy_json", "费用税费规则", "json", "费用和税费确认与分摊规则。", nullable=False),
            _internal_field("cash_flow_policy_json", "现金流分类规则", "json", "外部现金流和内部交易分类规则。", nullable=False),
            _internal_field("effective_from", "生效起始", "date32", "政策开始生效日期。", nullable=False, role="effective_time"),
            _internal_field("effective_to", "生效结束", "date32", "政策结束日期。", role="effective_time"),
            _internal_field("content_hash", "政策哈希", "string", "完整政策内容哈希。", nullable=False, role="audit"),
            _internal_field("status", "状态", "string", "政策生命周期。", nullable=False, enum_values=("DRAFT", "PUBLISHED", "SUPERSEDED", "RETIRED")),
            _internal_field("published_at", "发布时间", "timestamp[us, UTC]", "政策版本发布时间。", role="audit"),
            *control_audit_fields(),
        ),
    ),
    _table(
        "accounting.ledger",
        "投资账簿",
        "定义资产主体投资账或组合管理子账及其本位币、政策和有效期。",
        "每个账簿的一段有效主数据记录",
        ("ledger_id", "valid_from"),
        (
            primary_id("ledger_id", "账簿 ID", "账簿稳定标识。"),
            foreign_id("workspace_id", "工作空间 ID", "portfolio.workspace.workspace_id", "所属工作空间。"),
            foreign_id("asset_owner_id", "资产主体 ID", "portfolio.asset_owner.asset_owner_id", "主体投资账所属资产主体。", nullable=True),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "组合管理子账所属组合。", nullable=True),
            _internal_field("ledger_type", "账簿类型", "string", "主体投资账或组合管理子账。", nullable=False, enum_values=("OWNER_INVESTMENT_LEDGER", "PORTFOLIO_SUBLEDGER")),
            _internal_field("ledger_code", "账簿代码", "string", "工作空间内唯一账簿代码。", nullable=False),
            _internal_field("name", "账簿名称", "string", "账簿名称。", nullable=False),
            _internal_field("base_currency", "本位币", "string", "账簿本位币。", nullable=False, unit="ISO-4217"),
            _internal_field("accounting_policy_version_id", "核算政策版本 ID", "string", "账簿采用的政策版本。", nullable=False, reference="accounting.policy_version.accounting_policy_version_id"),
            _internal_field("status", "账簿状态", "string", "账簿状态。", nullable=False, enum_values=("OPEN", "SUSPENDED", "CLOSED")),
            _internal_field("valid_from", "生效起始", "date32", "账簿版本开始日期。", nullable=False, role="primary_key"),
            _internal_field("valid_to", "生效结束", "date32", "账簿版本结束日期。", role="effective_time"),
            _internal_field("recorded_at", "记录时间", "timestamp[us, UTC]", "账簿版本记录时间。", nullable=False, role="audit"),
            *control_audit_fields(),
        ),
        update_strategy="scd2",
    ),
    _table(
        "accounting.account",
        "会计科目",
        "保存投资核算使用的资产、负债、权益、收入和费用科目及层级。",
        "每个账簿科目版本一条记录",
        ("ledger_id", "account_code", "valid_from"),
        (
            foreign_id("ledger_id", "账簿 ID", "accounting.ledger.ledger_id", "科目所属账簿。"),
            _internal_field("account_code", "科目代码", "string", "账簿内唯一科目代码。", nullable=False, role="primary_key"),
            _internal_field("name", "科目名称", "string", "会计科目名称。", nullable=False),
            _internal_field("account_type", "科目类型", "string", "资产、负债、权益、收入或费用。", nullable=False, enum_values=("ASSET", "LIABILITY", "EQUITY", "INCOME", "EXPENSE")),
            _internal_field("parent_account_code", "上级科目", "string", "父级科目代码。"),
            _internal_field("normal_balance", "正常余额方向", "string", "借方或贷方。", nullable=False, enum_values=("DEBIT", "CREDIT")),
            _internal_field("instrument_required", "要求标的维度", "bool", "凭证明细是否必须记录 instrument_id。", nullable=False),
            _internal_field("account_required", "要求外部账户维度", "bool", "凭证明细是否必须记录 external_account_id。", nullable=False),
            _internal_field("currency_required", "要求币种维度", "bool", "凭证明细是否必须记录交易币种。", nullable=False),
            _internal_field("valid_from", "生效起始", "date32", "科目版本开始日期。", nullable=False, role="primary_key"),
            _internal_field("valid_to", "生效结束", "date32", "科目版本结束日期。", role="effective_time"),
            _internal_field("status", "科目状态", "string", "科目状态。", nullable=False, enum_values=("ACTIVE", "INACTIVE")),
            *control_audit_fields(),
        ),
        update_strategy="scd2",
    ),
    _table(
        "accounting.booking_event",
        "Booking 事件",
        "把交易、现金、公司行动、估值和调整转化为可追溯、可冲销的统一核算事件。",
        "每个可记账业务事件的一条 Booking 记录",
        ("booking_event_id",),
        (
            primary_id("booking_event_id", "Booking ID", "统一记账事件稳定标识。"),
            foreign_id("workspace_id", "工作空间 ID", "portfolio.workspace.workspace_id", "所属工作空间。"),
            foreign_id("asset_owner_id", "资产主体 ID", "portfolio.asset_owner.asset_owner_id", "业务事件所属主体。"),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "业务事实所在账户。", nullable=True),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "业务事实分配组合。", nullable=True),
            _internal_field("source_event_type", "来源事件类型", "string", "成交、现金、公司行动、估值或人工调整。", nullable=False, enum_values=("TRADE_EXECUTION", "CASH_MOVEMENT", "CORPORATE_ACTION", "VALUATION", "MANUAL_ADJUSTMENT")),
            _internal_field("source_event_id", "来源事件 ID", "string", "产生 Booking 的原始事实 ID。", nullable=False),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "业务事件涉及标的。", nullable=True),
            _internal_field("business_type", "业务类型", "string", "标准化核算业务类型。", nullable=False),
            _internal_field("trade_date", "交易日期", "date32", "业务交易日期。", role="observation_time"),
            _internal_field("settlement_date", "交收日期", "date32", "业务交收日期。", role="observation_time"),
            _internal_field("accounting_date", "会计日期", "date32", "进入账簿期间的日期。", nullable=False, role="observation_time"),
            _internal_field("quantity", "数量", "decimal128(38, 10)", "业务事件涉及数量。", role="measure", unit="base_unit"),
            _internal_field("gross_amount", "总金额", "decimal128(38, 6)", "费用税费前金额。", role="measure", unit="currency"),
            _internal_field("fee_amount", "费用", "decimal128(38, 6)", "业务费用。", role="measure", unit="currency"),
            _internal_field("tax_amount", "税费", "decimal128(38, 6)", "业务税费。", role="measure", unit="currency"),
            _internal_field("net_amount", "净金额", "decimal128(38, 6)", "业务净金额。", role="measure", unit="currency"),
            _internal_field("currency", "交易币种", "string", "业务金额币种。", nullable=False, unit="ISO-4217"),
            _internal_field("base_currency_amount", "本位币金额", "decimal128(38, 6)", "按冻结汇率折算的本位币金额。", role="measure", unit="base_currency"),
            _internal_field("fx_rate", "核算汇率", "decimal128(38, 12)", "交易币种到本位币的冻结汇率。", role="measure", unit="base/transaction"),
            _internal_field("accounting_policy_version_id", "核算政策版本 ID", "string", "生成 Booking 使用的政策版本。", nullable=False, reference="accounting.policy_version.accounting_policy_version_id"),
            _internal_field("status", "Booking 状态", "string", "草稿、已入账、已冲销或作废。", nullable=False, enum_values=("DRAFT", "POSTED", "REVERSED", "VOID")),
            _internal_field("reversal_of_booking_id", "原 Booking ID", "string", "冲销对应原 Booking。", reference="accounting.booking_event.booking_event_id"),
            _internal_field("content_hash", "事件哈希", "string", "Booking 输入和政策内容哈希。", nullable=False, role="audit"),
            _internal_field("posted_at", "入账时间", "timestamp[us, UTC]", "Booking 完成入账的时间。", role="audit"),
            *control_audit_fields(),
        ),
    ),
    _table(
        "accounting.journal",
        "会计凭证",
        "一张借贷平衡凭证，可由一个或多个 Booking 事件生成并支持冲销。",
        "每张会计凭证一条记录",
        ("journal_id",),
        (
            primary_id("journal_id", "凭证 ID", "会计凭证稳定标识。"),
            foreign_id("ledger_id", "账簿 ID", "accounting.ledger.ledger_id", "凭证所属账簿。"),
            _internal_field("journal_number", "凭证号", "string", "账簿期间内唯一凭证号。", nullable=False),
            _internal_field("accounting_date", "会计日期", "date32", "凭证所属会计日期。", nullable=False, role="observation_time"),
            _internal_field("period_code", "会计期间", "string", "YYYY-MM 等期间代码。", nullable=False),
            _internal_field("journal_type", "凭证类型", "string", "交易、现金、公司行动、估值、费用、调整或冲销。", nullable=False, enum_values=("TRADE", "CASH", "CORPORATE_ACTION", "VALUATION", "FEE", "ADJUSTMENT", "REVERSAL")),
            _internal_field("description", "摘要", "string", "凭证摘要。", nullable=False),
            _internal_field("status", "凭证状态", "string", "草稿、已过账、已冲销或作废。", nullable=False, enum_values=("DRAFT", "POSTED", "REVERSED", "VOID")),
            _internal_field("total_debit", "借方合计", "decimal128(38, 6)", "本位币借方金额合计。", nullable=False, role="measure", unit="base_currency"),
            _internal_field("total_credit", "贷方合计", "decimal128(38, 6)", "本位币贷方金额合计。", nullable=False, role="measure", unit="base_currency"),
            _internal_field("balanced", "借贷平衡", "bool", "借方与贷方是否相等。", nullable=False),
            _internal_field("reversal_of_journal_id", "原凭证 ID", "string", "冲销凭证对应原凭证。", reference="accounting.journal.journal_id"),
            _internal_field("posted_at", "过账时间", "timestamp[us, UTC]", "凭证正式过账时间。", role="audit"),
            *control_audit_fields(),
        ),
    ),
    _table(
        "accounting.journal_booking_link",
        "凭证—Booking 关系",
        "保存凭证与 Booking 事件的多对多来源关系。",
        "每个凭证与 Booking 事件的一条关系",
        ("journal_id", "booking_event_id"),
        (
            foreign_id("journal_id", "凭证 ID", "accounting.journal.journal_id", "会计凭证。"),
            foreign_id("booking_event_id", "Booking ID", "accounting.booking_event.booking_event_id", "凭证来源 Booking。"),
            _internal_field("linked_at", "关联时间", "timestamp[us, UTC]", "关系建立时间。", nullable=False, role="audit"),
        ),
    ),
    _table(
        "accounting.journal_line",
        "凭证明细",
        "按会计科目、标的、账户、组合、币种和业务维度记录借贷金额。",
        "每张凭证中的每一行借贷明细",
        ("journal_line_id",),
        (
            primary_id("journal_line_id", "凭证明细 ID", "凭证明细稳定标识。"),
            foreign_id("journal_id", "凭证 ID", "accounting.journal.journal_id", "所属凭证。"),
            _internal_field("line_number", "行号", "int64", "凭证内行号。", nullable=False),
            foreign_id("ledger_id", "账簿 ID", "accounting.ledger.ledger_id", "明细所属账簿。"),
            _internal_field("account_code", "科目代码", "string", "入账科目代码。", nullable=False, reference="accounting.account.account_code"),
            foreign_id("asset_owner_id", "资产主体 ID", "portfolio.asset_owner.asset_owner_id", "明细主体维度。", nullable=True),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "明细组合维度。", nullable=True),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "明细外部账户维度。", nullable=True),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "明细投资标的维度。", nullable=True),
            _internal_field("debit_amount", "借方金额", "decimal128(38, 6)", "本位币借方金额。", nullable=False, role="measure", unit="base_currency"),
            _internal_field("credit_amount", "贷方金额", "decimal128(38, 6)", "本位币贷方金额。", nullable=False, role="measure", unit="base_currency"),
            _internal_field("transaction_currency", "交易币种", "string", "原业务币种。", unit="ISO-4217"),
            _internal_field("transaction_amount", "交易币种金额", "decimal128(38, 6)", "原币金额。", role="measure", unit="transaction_currency"),
            _internal_field("quantity", "数量", "decimal128(38, 10)", "涉及标的数量。", role="measure", unit="base_unit"),
            _internal_field("cost_lot_id", "成本批次 ID", "string", "涉及的持仓成本批次。", reference="operations.position_lot.position_lot_id"),
            _internal_field("description", "明细摘要", "string", "凭证明细说明。"),
            _internal_field("created_at", "创建时间", "timestamp[us, UTC]", "明细生成时间。", nullable=False, role="audit"),
        ),
    ),
    _table(
        "accounting.position_valuation",
        "持仓估值",
        "保存主体和组合持仓在估值时点的价格、数量、市值、成本和未实现损益。",
        "每个数据版本、估值时点、账簿、账户、组合和标的一条记录",
        ("data_release_id", "valuation_at", "ledger_id", "external_account_id", "portfolio_key", "instrument_id"),
        (
            foreign_id("data_release_id", "数据版本 ID", "governance.data_release.data_release_id", "估值使用的数据版本。"),
            _internal_field("valuation_at", "估值时点", "timestamp[us, UTC]", "持仓估值截止时点。", nullable=False, role="primary_key"),
            foreign_id("ledger_id", "账簿 ID", "accounting.ledger.ledger_id", "估值所属账簿。"),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "持仓所在账户。"),
            _internal_field("portfolio_key", "组合键", "string", "portfolio_id 或主体未分配持仓占位键。", nullable=False, role="primary_key"),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "估值所属组合。", nullable=True),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "被估值标的。"),
            _internal_field("quantity", "持仓数量", "decimal128(38, 10)", "估值时点总数量。", nullable=False, role="measure", unit="base_unit"),
            _internal_field("settled_quantity", "已交收数量", "decimal128(38, 10)", "已交收数量。", nullable=False, role="measure", unit="base_unit"),
            _internal_field("price", "估值价格", "decimal128(38, 10)", "采用的价格或净值。", nullable=False, role="measure", unit="currency/base_unit"),
            _internal_field("price_date", "价格日期", "date32", "估值价格对应日期。", nullable=False, role="observation_time"),
            _internal_field("price_source_table", "价格来源表", "string", "使用的内部行情或净值表。", nullable=False),
            _internal_field("market_value", "市场价值", "decimal128(38, 6)", "原币市场价值。", nullable=False, role="measure", unit="currency"),
            _internal_field("book_cost", "账面成本", "decimal128(38, 6)", "原币账面成本。", nullable=False, role="measure", unit="currency"),
            _internal_field("unrealized_pnl", "未实现损益", "decimal128(38, 6)", "原币未实现损益。", nullable=False, role="measure", unit="currency"),
            _internal_field("currency", "原币", "string", "估值原币。", nullable=False, unit="ISO-4217"),
            _internal_field("fx_rate", "折算汇率", "decimal128(38, 12)", "原币到账簿本位币汇率。", nullable=False, role="measure", unit="base/transaction"),
            _internal_field("base_market_value", "本位币市值", "decimal128(38, 6)", "折算后本位币市场价值。", nullable=False, role="measure", unit="base_currency"),
            _internal_field("base_book_cost", "本位币成本", "decimal128(38, 6)", "折算后本位币账面成本。", nullable=False, role="measure", unit="base_currency"),
            _internal_field("base_unrealized_pnl", "本位币未实现损益", "decimal128(38, 6)", "折算后本位币未实现损益。", nullable=False, role="measure", unit="base_currency"),
            _internal_field("valuation_status", "估值状态", "string", "正常、陈旧、估算或不可估值。", nullable=False, enum_values=("VALID", "STALE", "ESTIMATED", "UNAVAILABLE")),
            _internal_field("warning_codes", "警告代码", "list<string>", "估值警告。"),
            _internal_field("calculation_version", "估值版本", "string", "估值计算逻辑版本。", nullable=False, role="audit"),
            _internal_field("built_at", "构建时间", "timestamp[us, UTC]", "估值构建时间。", nullable=False, role="audit"),
        ),
        storage_engine="parquet",
        layer="mart",
        partition_by=("data_release_id", "valuation_at"),
        sort_by=("data_release_id", "valuation_at", "ledger_id", "external_account_id", "portfolio_key", "instrument_id"),
    ),
    _table(
        "accounting.close_period",
        "关账期间",
        "管理投资账和组合子账的开放、检查、关闭、重开和审批状态。",
        "每个账簿和会计期间一条记录",
        ("ledger_id", "period_code"),
        (
            foreign_id("ledger_id", "账簿 ID", "accounting.ledger.ledger_id", "关账账簿。"),
            _internal_field("period_code", "期间代码", "string", "YYYY-MM 或其他会计期间。", nullable=False, role="primary_key"),
            _internal_field("period_start", "期间开始", "date32", "会计期间开始日期。", nullable=False, role="observation_time"),
            _internal_field("period_end", "期间结束", "date32", "会计期间结束日期。", nullable=False, role="observation_time"),
            _internal_field("status", "期间状态", "string", "开放、检查中、已关闭或重开。", nullable=False, enum_values=("OPEN", "CHECKING", "CLOSED", "REOPENED")),
            _internal_field("cash_reconciled", "现金已对账", "bool", "现金对账是否通过。", nullable=False),
            _internal_field("positions_reconciled", "持仓已对账", "bool", "持仓对账是否通过。", nullable=False),
            _internal_field("transactions_reconciled", "交易已对账", "bool", "交易对账是否通过。", nullable=False),
            _internal_field("valuations_complete", "估值已完成", "bool", "期间估值是否完成。", nullable=False),
            _internal_field("unresolved_case_count", "未解决差异数", "int64", "阻断或警告差异数量。", nullable=False, role="measure", unit="count"),
            _internal_field("closed_at", "关账时间", "timestamp[us, UTC]", "期间正式关闭时间。", role="audit"),
            _internal_field("reopened_at", "重开时间", "timestamp[us, UTC]", "期间最近一次重开时间。", role="audit"),
            _internal_field("reason", "重开或关闭说明", "string", "关账说明。"),
            *control_audit_fields(),
        ),
        update_strategy="upsert",
    ),
    _table(
        "accounting.pbor_snapshot",
        "PBOR 快照",
        "冻结正式绩效期间的持仓、估值、现金流、交易、费用、汇率、基准、数据和算法版本。",
        "每个组合绩效期间的一份正式 PBOR 快照",
        ("pbor_snapshot_id",),
        (
            primary_id("pbor_snapshot_id", "PBOR 快照 ID", "不可变绩效账簿快照标识。"),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "快照对应真实组合。"),
            _internal_field("period_start", "期间开始", "date32", "绩效期间开始日期。", nullable=False, role="observation_time"),
            _internal_field("period_end", "期间结束", "date32", "绩效期间结束日期。", nullable=False, role="observation_time"),
            _internal_field("valuation_start_at", "期初估值时点", "timestamp[us, UTC]", "期初正式估值时点。", nullable=False, role="observation_time"),
            _internal_field("valuation_end_at", "期末估值时点", "timestamp[us, UTC]", "期末正式估值时点。", nullable=False, role="observation_time"),
            _internal_field("data_release_id", "数据版本 ID", "string", "PBOR 使用的数据发布版本。", nullable=False, reference="governance.data_release.data_release_id"),
            _internal_field("position_artifact_id", "持仓制品 ID", "string", "冻结持仓快照制品。", nullable=False, reference="research.artifact.artifact_id"),
            _internal_field("valuation_artifact_id", "估值制品 ID", "string", "冻结估值快照制品。", nullable=False, reference="research.artifact.artifact_id"),
            _internal_field("cash_flow_artifact_id", "现金流制品 ID", "string", "冻结外部现金流制品。", nullable=False, reference="research.artifact.artifact_id"),
            _internal_field("transaction_artifact_id", "交易制品 ID", "string", "冻结交易和费用制品。", nullable=False, reference="research.artifact.artifact_id"),
            _internal_field("benchmark_version", "基准版本", "string", "冻结的基准定义版本。", nullable=False),
            _internal_field("accounting_policy_version_id", "核算政策版本 ID", "string", "冻结核算政策版本。", nullable=False, reference="accounting.policy_version.accounting_policy_version_id"),
            _internal_field("content_hash", "快照哈希", "string", "全部 PBOR 输入和版本的内容哈希。", nullable=False, role="audit"),
            _internal_field("status", "快照状态", "string", "构建中、已冻结或已作废。", nullable=False, enum_values=("BUILDING", "FROZEN", "VOID")),
            _internal_field("frozen_at", "冻结时间", "timestamp[us, UTC]", "PBOR 正式冻结时间。", role="audit"),
            *control_audit_fields(),
        ),
    ),
    _table(
        "accounting.performance_period",
        "绩效期间",
        "定义组合正式绩效计算的期间、外部现金流政策、基准和 PBOR 输入。",
        "每个组合绩效期间一条记录",
        ("performance_period_id",),
        (
            primary_id("performance_period_id", "绩效期间 ID", "绩效期间稳定标识。"),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "绩效对应真实组合。"),
            _internal_field("period_start", "期间开始", "date32", "绩效期间开始日期。", nullable=False, role="observation_time"),
            _internal_field("period_end", "期间结束", "date32", "绩效期间结束日期。", nullable=False, role="observation_time"),
            _internal_field("period_type", "期间类型", "string", "日、月、季、年或自定义。", nullable=False, enum_values=("DAILY", "MONTHLY", "QUARTERLY", "ANNUAL", "CUSTOM")),
            _internal_field("pbor_snapshot_id", "PBOR 快照 ID", "string", "绩效计算使用的冻结 PBOR。", nullable=False, reference="accounting.pbor_snapshot.pbor_snapshot_id"),
            _internal_field("base_currency", "本位币", "string", "绩效计量币种。", nullable=False, unit="ISO-4217"),
            _internal_field("benchmark_instrument_id", "基准标的 ID", "string", "绩效比较基准。", reference="master.instrument.instrument_id"),
            _internal_field("external_flow_policy", "外部现金流政策", "string", "现金流时点和大额现金流处理。", nullable=False),
            _internal_field("status", "期间状态", "string", "待计算、已计算、已冻结或已重开。", nullable=False, enum_values=("PENDING", "CALCULATED", "FROZEN", "REOPENED")),
            _internal_field("calculated_at", "计算时间", "timestamp[us, UTC]", "绩效计算完成时间。", role="audit"),
            _internal_field("frozen_at", "冻结时间", "timestamp[us, UTC]", "绩效结果冻结时间。", role="audit"),
            *control_audit_fields(),
        ),
    ),
    _table(
        "accounting.performance_metric",
        "绩效指标结果",
        "保存组合 TWR、MWR/XIRR、基准收益、超额收益、风险和费用等正式绩效指标。",
        "每个绩效期间和指标版本一条记录",
        ("performance_period_id", "metric_code", "metric_version"),
        (
            foreign_id("performance_period_id", "绩效期间 ID", "accounting.performance_period.performance_period_id", "所属绩效期间。"),
            _internal_field("metric_code", "指标代码", "string", "TWR、MWR、XIRR、BENCHMARK_RETURN 等指标代码。", nullable=False, role="primary_key"),
            _internal_field("metric_version", "指标版本", "string", "计算公式和实现版本。", nullable=False, role="primary_key"),
            _internal_field("value", "指标值", "float64", "指标原始数值；不可用时为空。", role="measure"),
            _internal_field("unit", "单位", "string", "小数、金额、天数或其他单位。", nullable=False),
            _internal_field("status", "结果状态", "string", "可用、样本不足、缺失或失败。", nullable=False, enum_values=("AVAILABLE", "INSUFFICIENT", "MISSING", "FAILED")),
            _internal_field("reason_code", "不可用原因", "string", "稳定原因代码。"),
            _internal_field("input_hash", "输入哈希", "string", "PBOR 输入和参数哈希。", nullable=False, role="audit"),
            _internal_field("calculation_audit_json", "计算审计", "json", "引擎、内核、版本和无回退证据。", nullable=False, role="audit"),
            _internal_field("calculated_at", "计算时间", "timestamp[us, UTC]", "指标计算完成时间。", nullable=False, role="audit"),
        ),
    ),
    _table(
        "accounting.attribution_result",
        "收益归因结果",
        "分解 SAA、TAA、产品选择、择时、费用、现金拖累、汇率和执行对收益的贡献。",
        "每个绩效期间、归因层级、归因对象和归因版本一条记录",
        ("performance_period_id", "attribution_version", "level", "component_code", "target_key"),
        (
            foreign_id("performance_period_id", "绩效期间 ID", "accounting.performance_period.performance_period_id", "归因所属绩效期间。"),
            _internal_field("attribution_version", "归因版本", "string", "归因模型和实现版本。", nullable=False, role="primary_key"),
            _internal_field("level", "归因层级", "string", "总组合、大类、产品、因子、币种或费用。", nullable=False, role="primary_key", enum_values=("PORTFOLIO", "ASSET_CLASS", "INSTRUMENT", "FACTOR", "CURRENCY", "COST")),
            _internal_field("component_code", "归因成分", "string", "SAA、TAA、选择、择时、费用、现金、汇率、执行等。", nullable=False, role="primary_key"),
            _internal_field("target_key", "归因对象键", "string", "总组合、资产大类版本、instrument_id、因子或币种。", nullable=False, role="primary_key"),
            _internal_field("allocation_effect", "配置效应", "float64", "配置权重差异贡献。", role="measure", unit="decimal_return"),
            _internal_field("selection_effect", "选择效应", "float64", "产品或证券选择贡献。", role="measure", unit="decimal_return"),
            _internal_field("interaction_effect", "交互效应", "float64", "配置与选择交互贡献。", role="measure", unit="decimal_return"),
            _internal_field("timing_effect", "择时效应", "float64", "战术或产品择时贡献。", role="measure", unit="decimal_return"),
            _internal_field("cost_effect", "成本效应", "float64", "费用和交易成本贡献。", role="measure", unit="decimal_return"),
            _internal_field("currency_effect", "汇率效应", "float64", "币种变化贡献。", role="measure", unit="decimal_return"),
            _internal_field("total_contribution", "总贡献", "float64", "该对象对组合收益的总贡献。", nullable=False, role="measure", unit="decimal_return"),
            _internal_field("weight_average", "平均权重", "float64", "期间平均实际权重。", role="measure", unit="decimal"),
            _internal_field("benchmark_weight_average", "基准平均权重", "float64", "期间基准平均权重。", role="measure", unit="decimal"),
            _internal_field("status", "结果状态", "string", "可用、覆盖不足或失败。", nullable=False, enum_values=("AVAILABLE", "PARTIAL", "UNAVAILABLE", "FAILED")),
            _internal_field("coverage_ratio", "覆盖率", "float64", "归因覆盖的组合资产比例。", role="measure", unit="decimal"),
            _internal_field("warning_codes", "警告代码", "list<string>", "归因警告。"),
            _internal_field("input_hash", "输入哈希", "string", "PBOR、目标配置和基准输入哈希。", nullable=False, role="audit"),
            _internal_field("calculated_at", "计算时间", "timestamp[us, UTC]", "归因计算完成时间。", nullable=False, role="audit"),
        ),
    ),
    _table(
        "accounting.risk_attribution_result",
        "风险归因结果",
        "分解资产类别、产品、行业、风格、因子、币种、流动性和集中度风险贡献。",
        "每个绩效或风险时点、风险模型版本和归因对象一条记录",
        ("risk_run_id", "risk_model_version", "level", "target_key", "risk_measure"),
        (
            _internal_field("risk_run_id", "风险运行 ID", "string", "风险归因运行标识。", nullable=False, role="primary_key"),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "风险归因对应组合。"),
            _internal_field("as_of", "风险时点", "timestamp[us, UTC]", "风险归因截止时点。", nullable=False, role="observation_time"),
            _internal_field("risk_model_version", "风险模型版本", "string", "风险模型及实现版本。", nullable=False, role="primary_key"),
            _internal_field("level", "归因层级", "string", "资产大类、产品、行业、风格、因子、币种或流动性。", nullable=False, role="primary_key"),
            _internal_field("target_key", "归因对象键", "string", "具体归因对象。", nullable=False, role="primary_key"),
            _internal_field("risk_measure", "风险指标", "string", "波动率、VaR、ES、跟踪误差或其他风险。", nullable=False, role="primary_key"),
            _internal_field("marginal_risk", "边际风险", "float64", "边际风险贡献。", role="measure"),
            _internal_field("component_risk", "成分风险", "float64", "对象对总风险的绝对贡献。", role="measure"),
            _internal_field("component_ratio", "风险贡献占比", "float64", "对象风险贡献占总风险比例。", role="measure", unit="decimal"),
            _internal_field("exposure", "风险暴露", "float64", "对象暴露值。", role="measure"),
            _internal_field("status", "结果状态", "string", "可用、部分覆盖或失败。", nullable=False, enum_values=("AVAILABLE", "PARTIAL", "UNAVAILABLE", "FAILED")),
            _internal_field("coverage_ratio", "覆盖率", "float64", "风险归因覆盖比例。", role="measure", unit="decimal"),
            _internal_field("warning_codes", "警告代码", "list<string>", "风险归因警告。"),
            _internal_field("input_hash", "输入哈希", "string", "持仓、因子、协方差和参数输入哈希。", nullable=False, role="audit"),
            _internal_field("calculated_at", "计算时间", "timestamp[us, UTC]", "风险归因完成时间。", nullable=False, role="audit"),
        ),
    ),
    _table(
        "accounting.report_snapshot",
        "投资与组合报告快照",
        "登记资产主体投资报表、组合管理报表和内部研究报告的冻结输入与制品。",
        "每份报告快照一条记录",
        ("report_snapshot_id",),
        (
            primary_id("report_snapshot_id", "报告快照 ID", "不可变报告快照标识。"),
            foreign_id("workspace_id", "工作空间 ID", "portfolio.workspace.workspace_id", "报告所属工作空间。"),
            foreign_id("asset_owner_id", "资产主体 ID", "portfolio.asset_owner.asset_owner_id", "主体报告对应资产主体。", nullable=True),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "组合报告对应组合。", nullable=True),
            _internal_field("report_type", "报告类型", "string", "主体投资、组合管理、绩效、风险或研究报告。", nullable=False, enum_values=("OWNER_INVESTMENT", "PORTFOLIO_MANAGEMENT", "PERFORMANCE", "RISK", "RESEARCH")),
            _internal_field("period_start", "报告开始日", "date32", "报告期间开始日期。", role="observation_time"),
            _internal_field("period_end", "报告结束日", "date32", "报告期间结束日期。", nullable=False, role="observation_time"),
            _internal_field("as_of", "报告截止时间", "timestamp[us, UTC]", "报告数据截止时间。", nullable=False, role="observation_time"),
            _internal_field("input_versions_json", "输入版本", "json", "PBOR、数据、配置、指标和模型版本。", nullable=False),
            _internal_field("artifact_id", "报告制品 ID", "string", "生成的 HTML、Excel 或其他报告制品。", nullable=False, reference="research.artifact.artifact_id"),
            _internal_field("confidentiality", "保密级别", "string", "报告保密级别。", nullable=False, enum_values=("INTERNAL", "CONFIDENTIAL", "RESTRICTED")),
            _internal_field("content_hash", "报告哈希", "string", "报告输入和输出内容哈希。", nullable=False, role="audit"),
            _internal_field("frozen_at", "冻结时间", "timestamp[us, UTC]", "报告快照冻结时间。", nullable=False, role="audit"),
            *control_audit_fields(),
        ),
    ),
)
