"""Canonical public-fund disclosure, event, fee, and dealing-rule contracts."""

from __future__ import annotations

from ..types import (
    CategoryDefinition,
    TableDefinition,
    availability_fields,
    field,
    foreign_id,
    primary_id,
    source_lineage_fields,
)


CATEGORY = CategoryDefinition(
    category_id="fund",
    label="基金研究与披露",
    description="保存基金持仓、资产与行业配置、分红、费率和申购赎回规则，并保留披露时点。",
    order=40,
)


def _fund_table(
    table_id: str,
    label: str,
    description: str,
    grain: str,
    primary_key: tuple[str, ...],
    fields: tuple,
    *,
    partition_by: tuple[str, ...],
    sort_by: tuple[str, ...],
    delivery_phase: str = "next",
    update_strategy: str = "append",
) -> TableDefinition:
    name = table_id.split(".", 1)[1]
    return TableDefinition(
        table_id=table_id,
        category_id=CATEGORY.category_id,
        label=label,
        description=description,
        layer="canonical",
        storage_engine="parquet",
        storage_location=f"data/canonical/v1/fund/{name}/",
        delivery_phase=delivery_phase,  # type: ignore[arg-type]
        grain=grain,
        primary_key=primary_key,
        update_strategy=update_strategy,  # type: ignore[arg-type]
        fields=fields,
        source_mappable=True,
        partition_by=partition_by,
        sort_by=sort_by,
        pit_supported=True,
    )


TABLES = (
    _fund_table(
        "fund.adjustment_factor", "基金复权因子",
        "保存独立复权因子，不把因子当作净值；未知历史发布日期不能宣称严格 PIT。",
        "每个标的、因子日期、来源和修订版本一条记录",
        ("instrument_id", "factor_date", "source_id", "revision"),
        (
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "因子对应的标的。"),
            *availability_fields(observation_name="factor_date", observation_label="因子日期"),
            field("factor", "复权因子", "float64", "来源披露的复权因子。", nullable=False, role="measure", unit="multiple"),
            field("adjustment_basis", "复权口径", "string", "来源因子的基准口径。", nullable=False, enum_values=("SOURCE", "FORWARD", "BACKWARD", "UNKNOWN")),
            *source_lineage_fields(),
        ),
        partition_by=("factor_date",),
        sort_by=("instrument_id", "factor_date", "source_id", "revision"),
        delivery_phase="core",
    ),
    _fund_table(
        "fund.holding_disclosure",
        "基金持仓披露",
        "保存公开披露的股票、债券、基金、现金和衍生品持仓；未解析标的不得丢失原始代码。",
        "每只基金份额、报告期、持仓标的、数据源和修订版本一条记录",
        ("fund_instrument_id", "report_period_end", "holding_key", "source_id", "revision"),
        (
            foreign_id("fund_instrument_id", "基金标的 ID", "master.instrument.instrument_id", "披露持仓的基金份额或 ETF。", source_mappable=False),
            *availability_fields(
                observation_name="report_period_end",
                observation_label="报告期末",
                observation_description="持仓披露对应的报告期末。",
            ),
            field("announced_at", "公告时间", "timestamp[us, UTC]", "持仓报告正式公告时间。", role="available_time"),
            field("holding_key", "持仓键", "string", "已解析标的 ID 或来源标的代码形成的稳定持仓键。", nullable=False, role="primary_key", source_mappable=False),
            foreign_id("holding_instrument_id", "底层标的 ID", "master.instrument.instrument_id", "已解析的底层标的。", nullable=True, source_mappable=False),
            field("holding_external_code", "底层外部代码", "string", "来源中的底层标的代码；无法解析时仍保留。"),
            field("holding_name", "底层名称", "string", "来源披露的底层标的名称。"),
            field("holding_type", "持仓类型", "string", "底层资产类型。", nullable=False, enum_values=("STOCK", "BOND", "FUND", "CASH", "DERIVATIVE", "OTHER")),
            field("quantity", "持仓数量", "decimal128(38, 10)", "披露的持仓数量。", role="measure", unit="base_unit"),
            field("market_value", "持仓市值", "decimal128(38, 6)", "报告期末持仓市值。", role="measure", unit="currency"),
            field("portfolio_weight", "基金资产占比", "float64", "该持仓占基金净资产比例，小数制。", role="measure", unit="decimal"),
            field("floating_share_weight", "流通股占比", "float64", "股票持仓占对应流通股比例，小数制。", role="measure", unit="decimal"),
            field("rank", "持仓排名", "int64", "来源披露的持仓排序。", role="measure", unit="rank"),
            field("currency", "币种", "string", "持仓市值币种。", unit="ISO-4217"),
            field("coverage_scope", "披露范围", "string", "完整持仓、前十大或其他披露范围。", nullable=False, enum_values=("FULL", "TOP_N", "PARTIAL", "UNKNOWN")),
            *source_lineage_fields(),
        ),
        partition_by=("report_period_end",),
        sort_by=("fund_instrument_id", "report_period_end", "holding_key", "source_id", "revision"),
    ),
    _fund_table(
        "fund.asset_allocation_disclosure",
        "基金资产配置披露",
        "保存基金在股票、债券、现金、基金、衍生品等资产类别上的披露配置。",
        "每只基金份额、报告期、资产类别、数据源和修订版本一条记录",
        ("fund_instrument_id", "report_period_end", "asset_class_code", "source_id", "revision"),
        (
            foreign_id("fund_instrument_id", "基金标的 ID", "master.instrument.instrument_id", "披露资产配置的基金份额。", source_mappable=False),
            *availability_fields(
                observation_name="report_period_end",
                observation_label="报告期末",
                observation_description="资产配置披露对应的报告期末。",
            ),
            field("announced_at", "公告时间", "timestamp[us, UTC]", "报告正式公告时间。", role="available_time"),
            field("asset_class_code", "资产类别代码", "string", "平台统一资产类别代码。", nullable=False, role="primary_key"),
            field("asset_class_name", "资产类别名称", "string", "资产类别名称。", nullable=False),
            field("market_value", "市值", "decimal128(38, 6)", "报告期末资产类别市值。", role="measure", unit="currency"),
            field("portfolio_weight", "资产占比", "float64", "资产类别占基金净资产比例，小数制。", role="measure", unit="decimal"),
            field("currency", "币种", "string", "市值币种。", unit="ISO-4217"),
            *source_lineage_fields(),
        ),
        partition_by=("report_period_end",),
        sort_by=("fund_instrument_id", "report_period_end", "asset_class_code", "source_id", "revision"),
    ),
    _fund_table(
        "fund.industry_allocation_disclosure",
        "基金行业配置披露",
        "保存基金按申万、中信、GICS 等分类体系披露或归集的行业配置。",
        "每只基金份额、报告期、分类节点、数据源和修订版本一条记录",
        ("fund_instrument_id", "report_period_end", "scheme_id", "scheme_version", "node_id", "source_id", "revision"),
        (
            foreign_id("fund_instrument_id", "基金标的 ID", "master.instrument.instrument_id", "行业配置对应基金份额。", source_mappable=False),
            *availability_fields(
                observation_name="report_period_end",
                observation_label="报告期末",
                observation_description="行业配置对应的报告期末。",
            ),
            field("announced_at", "公告时间", "timestamp[us, UTC]", "报告正式公告时间。", role="available_time"),
            foreign_id("scheme_id", "分类体系 ID", "master.classification_scheme.scheme_id", "行业分类体系。", source_mappable=False),
            field("scheme_version", "分类体系版本", "string", "行业分类体系版本。", nullable=False, role="primary_key", source_mappable=False),
            foreign_id("node_id", "行业节点 ID", "master.classification_node.node_id", "行业分类节点。", source_mappable=False),
            field("market_value", "行业市值", "decimal128(38, 6)", "报告期末行业持仓市值。", role="measure", unit="currency"),
            field("portfolio_weight", "行业占比", "float64", "行业持仓占基金净资产比例，小数制。", role="measure", unit="decimal"),
            field("calculation_method", "生成方式", "string", "来源直接披露或由底层持仓归集。", nullable=False, enum_values=("DISCLOSED", "AGGREGATED", "ESTIMATED")),
            field("currency", "币种", "string", "行业市值币种。", unit="ISO-4217"),
            *source_lineage_fields(),
        ),
        partition_by=("report_period_end", "scheme_id"),
        sort_by=("fund_instrument_id", "report_period_end", "scheme_id", "node_id", "source_id", "revision"),
    ),
    _fund_table(
        "fund.dividend_event",
        "基金分红事件",
        "统一基金权益登记、除息、派息和单位分红记录。",
        "每个基金份额分红事件、数据源和修订版本一条记录",
        ("dividend_event_id", "source_id", "revision"),
        (
            primary_id("dividend_event_id", "分红事件 ID", "平台生成的稳定分红事件标识。"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "发生分红的基金份额。", source_mappable=False),
            *availability_fields(
                observation_name="record_date",
                observation_label="权益登记日",
                observation_description="分红权益登记日期。",
            ),
            field("announced_at", "公告时间", "timestamp[us, UTC]", "分红公告时间。", role="available_time"),
            field("ex_date", "除息日", "date32", "分红除息日期。", role="effective_time"),
            field("pay_date", "派息日", "date32", "现金实际支付日期。", role="effective_time"),
            field("cash_per_unit", "单位现金分红", "decimal128(38, 10)", "每个基础单位的现金分红。", role="measure", unit="currency/base_unit"),
            field("base_unit", "分红基础单位", "decimal128(38, 10)", "分红金额对应的基金份额单位。", role="measure", unit="share"),
            field("currency", "币种", "string", "分红币种。", nullable=False, unit="ISO-4217"),
            field("event_status", "事件状态", "string", "分红流程状态。", nullable=False, enum_values=("ANNOUNCED", "IMPLEMENTED", "CANCELLED", "UNKNOWN")),
            *source_lineage_fields(),
        ),
        partition_by=("record_date",),
        sort_by=("instrument_id", "record_date", "dividend_event_id", "source_id", "revision"),
    ),
    _fund_table(
        "fund.fee_schedule",
        "基金费率规则",
        "统一管理费、托管费、销售服务费、申购费和赎回费的有效期与分档。",
        "每个基金或份额、费率类型、费率档位和有效期一条记录",
        ("fee_schedule_id", "source_id", "revision"),
        (
            primary_id("fee_schedule_id", "费率规则 ID", "费率档位的稳定标识。"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "份额级费率对应标的；产品级费率可为空。", nullable=True, source_mappable=False),
            foreign_id("fund_product_id", "基金产品 ID", "master.fund_product.fund_product_id", "产品级费率对应基金产品。", nullable=True, source_mappable=False),
            field("fee_type", "费率类型", "string", "费用类型。", nullable=False, enum_values=("MANAGEMENT", "CUSTODY", "SALES_SERVICE", "SUBSCRIPTION", "PURCHASE", "REDEMPTION", "OTHER")),
            field("rate_decimal", "费率", "float64", "小数制费率，0.015 表示 1.5%。", role="measure", unit="decimal"),
            field("fixed_amount", "固定金额", "decimal128(38, 6)", "固定费用金额。", role="measure", unit="currency"),
            field("minimum_amount", "最低金额门槛", "decimal128(38, 6)", "该档适用的最低交易金额。", role="measure", unit="currency"),
            field("maximum_amount", "最高金额门槛", "decimal128(38, 6)", "该档适用的最高交易金额。", role="measure", unit="currency"),
            field("holding_days_from", "最短持有天数", "int64", "赎回费档位适用的最短持有天数。", role="measure", unit="day"),
            field("holding_days_to", "最长持有天数", "int64", "赎回费档位适用的最长持有天数。", role="measure", unit="day"),
            field("currency", "币种", "string", "固定费用和金额门槛的币种。", unit="ISO-4217"),
            field("effective_from", "生效起始", "date32", "费率规则生效日期。", nullable=False, role="effective_time"),
            field("effective_to", "生效结束", "date32", "费率规则失效日期。", role="effective_time"),
            field("available_at", "最早可得时间", "timestamp[us, UTC]", "费率规则最早可用于历史研究的时间。", role="available_time"),
            field("availability_status", "可得性状态", "string", "available_at 的精度。", nullable=False, role="available_time", enum_values=("EXACT", "DATE_ONLY", "ESTIMATED", "UNKNOWN")),
            *source_lineage_fields(),
        ),
        partition_by=("fee_type",),
        sort_by=("instrument_id", "fund_product_id", "fee_type", "effective_from", "source_id", "revision"),
        update_strategy="scd2",
    ),
    _fund_table(
        "fund.subscription_redemption_rule",
        "申购赎回规则",
        "统一申购、赎回、确认、交收、最低金额和限额规则。",
        "每个基金份额的一段有效申购赎回规则",
        ("dealing_rule_id", "source_id", "revision"),
        (
            primary_id("dealing_rule_id", "交易规则 ID", "申购赎回规则的稳定标识。"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "规则对应的基金份额。", source_mappable=False),
            field("purchase_open", "允许申购", "bool", "当前规则是否允许申购。", nullable=False),
            field("redemption_open", "允许赎回", "bool", "当前规则是否允许赎回。", nullable=False),
            field("minimum_purchase_amount", "最低申购金额", "decimal128(38, 6)", "首次或追加申购最低金额。", role="measure", unit="currency"),
            field("maximum_purchase_amount", "最高申购金额", "decimal128(38, 6)", "单笔或单日最高申购金额。", role="measure", unit="currency"),
            field("minimum_redemption_shares", "最低赎回份额", "decimal128(38, 10)", "单笔最低赎回份额。", role="measure", unit="share"),
            field("confirmation_days", "确认天数", "int64", "交易申请到份额确认的工作日数。", role="measure", unit="business_day"),
            field("settlement_days", "交收天数", "int64", "确认后资金或份额交收工作日数。", role="measure", unit="business_day"),
            field("currency", "币种", "string", "金额限额币种。", unit="ISO-4217"),
            field("effective_from", "生效起始", "date32", "规则开始生效日期。", nullable=False, role="effective_time"),
            field("effective_to", "生效结束", "date32", "规则结束日期。", role="effective_time"),
            field("available_at", "最早可得时间", "timestamp[us, UTC]", "规则最早可用于历史研究的时间。", role="available_time"),
            field("availability_status", "可得性状态", "string", "available_at 的精度。", nullable=False, role="available_time", enum_values=("EXACT", "DATE_ONLY", "ESTIMATED", "UNKNOWN")),
            *source_lineage_fields(),
        ),
        partition_by=("effective_from",),
        sort_by=("instrument_id", "effective_from", "source_id", "revision"),
        update_strategy="scd2",
    ),
)
