"""Data-source, mapping, scheduling, release, and quality contracts."""

from __future__ import annotations

from ..types import (
    CategoryDefinition,
    TableDefinition,
    control_audit_fields,
    field,
    foreign_id,
    primary_id,
)


CATEGORY = CategoryDefinition(
    category_id="governance",
    label="数据接入与治理",
    description="管理数据源、接口、字段映射、下载约束、定时任务、数据版本、质量和血缘。",
    order=10,
)


def _control_table(
    table_id: str,
    label: str,
    description: str,
    grain: str,
    primary_key: tuple[str, ...],
    fields: tuple,
    *,
    delivery_phase: str = "core",
    update_strategy: str = "upsert",
) -> TableDefinition:
    return TableDefinition(
        table_id=table_id,
        category_id=CATEGORY.category_id,
        label=label,
        description=description,
        layer="control",
        storage_engine="sqlite",
        storage_location="data/platform.db",
        delivery_phase=delivery_phase,  # type: ignore[arg-type]
        grain=grain,
        primary_key=primary_key,
        update_strategy=update_strategy,  # type: ignore[arg-type]
        fields=fields,
        source_mappable=False,
    )


TABLES = (
    _control_table(
        "governance.data_source",
        "数据源",
        "平台已配置的 API、文件或数据库来源；Tushare 将作为系统默认数据源。",
        "每个外部数据源一条记录",
        ("data_source_id",),
        (
            primary_id("data_source_id", "数据源 ID", "平台生成的稳定数据源标识。"),
            field("code", "数据源代码", "string", "系统内唯一代码，例如 tushare。", nullable=False, role="configuration", source_mappable=False),
            field("name", "数据源名称", "string", "用户可识别的数据源名称。", nullable=False, role="configuration", source_mappable=False),
            field("provider", "服务提供方", "string", "数据服务商或文件提供方。", role="configuration", source_mappable=False),
            field("source_type", "接入类型", "string", "数据接入方式。", nullable=False, role="configuration", enum_values=("API", "FILE", "DATABASE"), source_mappable=False),
            field("timezone", "默认时区", "string", "来源数据未带时区时采用的 IANA 时区。", nullable=False, role="configuration", source_mappable=False),
            field("default_currency", "默认币种", "string", "来源未明确币种时使用的 ISO 4217 币种。", role="configuration", unit="ISO-4217", source_mappable=False),
            field("credential_reference", "凭据引用", "string", "只保存受控凭据引用，不保存明文密钥。", role="configuration", source_mappable=False),
            field("config_json", "扩展配置", "json", "数据源级扩展参数。", role="configuration", source_mappable=False),
            field("enabled", "是否启用", "bool", "是否允许该数据源执行任务。", nullable=False, role="configuration", source_mappable=False),
            field("is_system_default", "系统默认", "bool", "是否为平台默认预置数据源。", nullable=False, role="configuration", source_mappable=False),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "governance.source_interface",
        "数据源接口",
        "定义数据源内可调用的接口、请求和返回格式，以及增量游标。",
        "每个数据源接口一条记录",
        ("interface_id",),
        (
            primary_id("interface_id", "接口 ID", "平台生成的稳定接口标识。"),
            foreign_id("data_source_id", "数据源 ID", "governance.data_source.data_source_id", "所属数据源。"),
            field("code", "接口代码", "string", "数据源内唯一接口代码。", nullable=False, role="configuration", source_mappable=False),
            field("name", "接口名称", "string", "接口的人类可读名称。", nullable=False, role="configuration", source_mappable=False),
            field("business_domain", "业务域", "string", "接口所属业务域，例如基金净值、指数行情。", nullable=False, role="configuration", source_mappable=False),
            field("endpoint", "接口地址", "string", "HTTP 地址、SDK 方法或文件入口。", nullable=False, role="configuration", source_mappable=False),
            field("http_method", "请求方法", "string", "HTTP 或逻辑调用方法。", nullable=False, role="configuration", enum_values=("GET", "POST", "SDK", "FILE"), source_mappable=False),
            field("request_format", "请求格式", "string", "请求参数的组织方式。", nullable=False, role="configuration", enum_values=("QUERY", "JSON", "FORM", "SDK", "FILE"), source_mappable=False),
            field("response_format", "返回格式", "string", "接口返回的数据格式。", nullable=False, role="configuration", enum_values=("JSON", "CSV", "XLSX", "PARQUET", "DATAFRAME"), source_mappable=False),
            field("records_path", "记录路径", "string", "JSON 返回中数据行所在路径；表格返回可为空。", role="configuration", source_mappable=False),
            field("primary_time_field", "主时间字段", "string", "用于增量范围和新鲜度判断的来源字段。", role="configuration", source_mappable=False),
            field("incremental_cursor_type", "增量游标类型", "string", "增量下载的推进方式。", nullable=False, role="configuration", enum_values=("NONE", "DATE", "DATETIME", "PAGE", "TOKEN"), source_mappable=False),
            field("incremental_cursor_field", "增量游标字段", "string", "来源响应中对应游标的字段。", role="configuration", source_mappable=False),
            field("request_template_json", "请求模板", "json", "固定参数、字段列表和分页模板。", role="configuration", source_mappable=False),
            field("supports_full", "支持全量", "bool", "是否支持全量抓取。", nullable=False, role="configuration", source_mappable=False),
            field("supports_incremental", "支持增量", "bool", "是否支持增量抓取。", nullable=False, role="configuration", source_mappable=False),
            field("enabled", "是否启用", "bool", "是否允许该接口被任务选择。", nullable=False, role="configuration", source_mappable=False),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "governance.dataset_mapping",
        "数据集映射",
        "把一个来源接口映射到一个固定的系统内部表，并锁定版本和转换流程。",
        "每个接口到目标表的映射版本一条记录",
        ("dataset_mapping_id",),
        (
            primary_id("dataset_mapping_id", "数据集映射 ID", "映射定义的稳定标识。"),
            foreign_id("interface_id", "接口 ID", "governance.source_interface.interface_id", "来源接口。"),
            field("target_table_id", "目标内部表", "string", "必须引用系统数据模型中的 table_id。", nullable=False, role="configuration", source_mappable=False),
            field("mapping_version", "映射版本", "string", "不可变映射版本。", nullable=False, role="configuration", source_mappable=False),
            field("status", "状态", "string", "映射生命周期。", nullable=False, role="configuration", enum_values=("DRAFT", "PUBLISHED", "RETIRED"), source_mappable=False),
            field("source_grain", "来源粒度", "string", "来源每行表示什么。", nullable=False, role="configuration", source_mappable=False),
            field("target_grain", "目标粒度", "string", "目标表每行表示什么。", nullable=False, role="configuration", source_mappable=False),
            field("row_filter_json", "行过滤", "json", "进入转换前的白名单过滤条件。", role="configuration", source_mappable=False),
            field("transform_pipeline_json", "转换流水线", "json", "受控转换器及其顺序，不允许任意代码。", role="configuration", source_mappable=False),
            field("effective_from", "生效时间", "timestamp[us, UTC]", "映射开始生效的时间。", role="effective_time", source_mappable=False),
            field("effective_to", "失效时间", "timestamp[us, UTC]", "映射停止生效的时间。", role="effective_time", source_mappable=False),
            field("published_at", "发布时间", "timestamp[us, UTC]", "映射被发布为可执行版本的时间。", role="audit", source_mappable=False),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "governance.field_mapping",
        "字段映射",
        "定义来源字段到内部标准字段的类型、单位、枚举和空值转换。",
        "每个数据集映射中的目标字段一条记录",
        ("field_mapping_id",),
        (
            primary_id("field_mapping_id", "字段映射 ID", "字段映射的稳定标识。"),
            foreign_id("dataset_mapping_id", "数据集映射 ID", "governance.dataset_mapping.dataset_mapping_id", "所属数据集映射。"),
            field("source_field_path", "来源字段路径", "string", "来源字段名或 JSONPath。", nullable=False, role="configuration", source_mappable=False),
            field("target_field_name", "目标字段", "string", "目标内部表中的字段名。", nullable=False, role="configuration", source_mappable=False),
            field("source_data_type", "来源类型", "string", "来源声明的数据类型。", role="configuration", source_mappable=False),
            field("target_data_type", "目标类型", "string", "由系统数据模型锁定的目标类型。", nullable=False, role="configuration", source_mappable=False),
            field("transform_id", "转换器", "string", "受控转换器标识，例如 yyyymmdd_to_date。", role="configuration", source_mappable=False),
            field("source_unit", "来源单位", "string", "来源字段单位。", role="configuration", source_mappable=False),
            field("target_unit", "目标单位", "string", "内部标准单位。", role="configuration", source_mappable=False),
            field("enum_mapping_json", "枚举映射", "json", "来源枚举到内部枚举的映射。", role="configuration", source_mappable=False),
            field("null_policy", "空值策略", "string", "空值如何处理。", nullable=False, role="configuration", enum_values=("PRESERVE", "REJECT", "DEFAULT", "DROP_ROW"), source_mappable=False),
            field("default_value", "默认值", "string", "空值策略为 DEFAULT 时使用的值。", role="configuration", source_mappable=False),
            field("required", "是否必映射", "bool", "该字段是否必须由来源提供或受控生成。", nullable=False, role="configuration", source_mappable=False),
            field("sequence", "执行顺序", "int64", "字段转换顺序。", nullable=False, role="configuration", source_mappable=False),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "governance.download_policy",
        "下载限制策略",
        "定义接口的限频、并发、分页、重试、超时和配额约束。",
        "每个接口的一套可执行下载约束",
        ("download_policy_id",),
        (
            primary_id("download_policy_id", "策略 ID", "下载策略的稳定标识。"),
            foreign_id("interface_id", "接口 ID", "governance.source_interface.interface_id", "受该策略控制的接口。"),
            field("max_requests_per_minute", "每分钟请求上限", "int64", "所有 worker 共享的每分钟调用上限。", role="configuration", unit="request/minute", source_mappable=False),
            field("min_request_interval_ms", "最小请求间隔", "int64", "任意两次请求之间的最小间隔。", role="configuration", unit="millisecond", source_mappable=False),
            field("max_rows_per_request", "单次最大行数", "int64", "接口单次响应的安全行数上限。", role="configuration", unit="row", source_mappable=False),
            field("max_concurrency", "最大并发数", "int64", "该接口允许的最大并发任务数。", nullable=False, role="configuration", unit="worker", source_mappable=False),
            field("max_retries", "最大重试次数", "int64", "可重试异常的最大次数。", nullable=False, role="configuration", unit="count", source_mappable=False),
            field("retry_backoff_seconds", "初始退避", "float64", "重试的初始退避秒数。", nullable=False, role="configuration", unit="second", source_mappable=False),
            field("rate_limit_wait_seconds", "限流等待", "float64", "触发限流后至少等待的秒数。", nullable=False, role="configuration", unit="second", source_mappable=False),
            field("request_timeout_seconds", "请求超时", "int64", "单次连接和读取超时。", nullable=False, role="configuration", unit="second", source_mappable=False),
            field("idle_timeout_seconds", "任务空闲超时", "int64", "任务无进度输出的最大持续时间。", nullable=False, role="configuration", unit="second", source_mappable=False),
            field("max_runtime_seconds", "任务最长时间", "int64", "任务绝对运行上限；0 表示不限制。", nullable=False, role="configuration", unit="second", source_mappable=False),
            field("chunk_strategy", "分片策略", "string", "全量或增量抓取的拆分方式。", nullable=False, role="configuration", enum_values=("NONE", "DATE", "CODE", "PAGE", "DATE_AND_CODE"), source_mappable=False),
            field("chunk_size", "分片大小", "int64", "分片天数、代码数或页大小。", role="configuration", source_mappable=False),
            field("daily_request_quota", "每日调用配额", "int64", "可选的每日总调用上限。", role="configuration", unit="request/day", source_mappable=False),
            field("enabled", "是否启用", "bool", "是否启用该策略。", nullable=False, role="configuration", source_mappable=False),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "governance.schedule",
        "定时下载任务",
        "定义下载频率、执行时间、目标数据、全量或增量模式。",
        "每个定时任务一条记录",
        ("schedule_id",),
        (
            primary_id("schedule_id", "任务计划 ID", "定时计划的稳定标识。"),
            field("name", "计划名称", "string", "用户可识别的计划名称。", nullable=False, role="configuration", source_mappable=False),
            field("timezone", "计划时区", "string", "解释执行时间的 IANA 时区。", nullable=False, role="configuration", source_mappable=False),
            field("schedule_type", "计划类型", "string", "触发方式。", nullable=False, role="configuration", enum_values=("CRON", "FIXED_INTERVAL", "MANUAL"), source_mappable=False),
            field("cron_expression", "Cron 表达式", "string", "计划类型为 CRON 时使用。", role="configuration", source_mappable=False),
            field("interval_seconds", "固定间隔", "int64", "固定间隔计划的秒数。", role="configuration", unit="second", source_mappable=False),
            field("run_time_local", "本地执行时间", "string", "每日或每周任务的 HH:mm 时间。", role="configuration", source_mappable=False),
            field("weekdays_json", "执行星期", "json", "每周任务的星期列表。", role="configuration", source_mappable=False),
            foreign_id("data_source_id", "数据源 ID", "governance.data_source.data_source_id", "执行所用数据源。"),
            field("interface_ids_json", "接口列表", "json", "需要执行的来源接口 ID。", nullable=False, role="configuration", source_mappable=False),
            field("target_table_ids_json", "目标表列表", "json", "需要更新的内部目标表 ID。", nullable=False, role="configuration", source_mappable=False),
            field("refresh_mode", "更新模式", "string", "全量或增量。", nullable=False, role="configuration", enum_values=("FULL", "INCREMENTAL"), source_mappable=False),
            field("enabled", "是否启用", "bool", "是否允许调度器触发。", nullable=False, role="configuration", source_mappable=False),
            field("next_run_at", "下次执行时间", "timestamp[us, UTC]", "调度器计算出的下一次执行时间。", role="audit", source_mappable=False),
            field("last_run_at", "上次执行时间", "timestamp[us, UTC]", "最近一次实际触发时间。", role="audit", source_mappable=False),
            *control_audit_fields(),
        ),
        delivery_phase="next",
    ),
    _control_table(
        "governance.ingestion_job",
        "采集任务",
        "记录一次手动、定时或重试的数据下载与转换执行。",
        "每次采集执行一条记录",
        ("ingestion_job_id",),
        (
            primary_id("ingestion_job_id", "采集任务 ID", "一次采集执行的稳定标识。"),
            foreign_id("schedule_id", "计划 ID", "governance.schedule.schedule_id", "触发该任务的计划；手动任务为空。", nullable=True),
            foreign_id("data_source_id", "数据源 ID", "governance.data_source.data_source_id", "本次任务的数据源。"),
            field("trigger_type", "触发类型", "string", "任务触发方式。", nullable=False, role="configuration", enum_values=("MANUAL", "SCHEDULED", "RETRY"), source_mappable=False),
            field("refresh_mode", "更新模式", "string", "本次执行为全量或增量。", nullable=False, role="configuration", enum_values=("FULL", "INCREMENTAL"), source_mappable=False),
            field("status", "任务状态", "string", "任务生命周期状态。", nullable=False, role="configuration", enum_values=("QUEUED", "RUNNING", "SUCCEEDED", "PARTIAL", "FAILED", "CANCELLED"), source_mappable=False),
            field("requested_at", "请求时间", "timestamp[us, UTC]", "任务进入队列的时间。", nullable=False, role="audit", source_mappable=False),
            field("started_at", "开始时间", "timestamp[us, UTC]", "任务实际开始时间。", role="audit", source_mappable=False),
            field("finished_at", "结束时间", "timestamp[us, UTC]", "任务结束时间。", role="audit", source_mappable=False),
            field("source_start", "来源起点", "string", "本次来源区间或游标起点。", role="configuration", source_mappable=False),
            field("source_end", "来源终点", "string", "本次来源区间或游标终点。", role="configuration", source_mappable=False),
            foreign_id("target_release_id", "目标数据版本", "governance.data_release.data_release_id", "本次任务构建的数据版本。", nullable=True),
            field("rows_received", "接收行数", "int64", "来源返回的总行数。", nullable=False, role="measure", unit="row", source_mappable=False),
            field("rows_accepted", "入库行数", "int64", "通过映射和校验的行数。", nullable=False, role="measure", unit="row", source_mappable=False),
            field("rows_rejected", "拒绝行数", "int64", "被映射或质量规则拒绝的行数。", nullable=False, role="measure", unit="row", source_mappable=False),
            field("request_count", "请求次数", "int64", "本次任务实际外部调用次数。", nullable=False, role="measure", unit="request", source_mappable=False),
            field("error_code", "错误代码", "string", "任务失败或部分成功的稳定错误代码。", role="audit", source_mappable=False),
            field("error_message", "错误说明", "string", "脱敏后的错误说明。", role="audit", source_mappable=False),
            field("configuration_snapshot_json", "执行配置快照", "json", "本次执行冻结的接口、映射和约束版本。", nullable=False, role="audit", source_mappable=False),
            *control_audit_fields(),
        ),
        update_strategy="append",
    ),
    _control_table(
        "governance.ingestion_batch",
        "采集批次",
        "记录一次接口分页、日期分片或代码分片请求及其原始制品。",
        "每次外部请求或可重放分片一条记录",
        ("ingestion_batch_id",),
        (
            primary_id("ingestion_batch_id", "采集批次 ID", "单次请求或分片的稳定标识。"),
            foreign_id("ingestion_job_id", "采集任务 ID", "governance.ingestion_job.ingestion_job_id", "所属采集任务。"),
            foreign_id("interface_id", "接口 ID", "governance.source_interface.interface_id", "实际调用的来源接口。"),
            field("sequence", "批次顺序", "int64", "任务内执行顺序。", nullable=False, role="audit", source_mappable=False),
            field("cursor_from", "游标起点", "string", "分页、日期或令牌游标起点。", role="configuration", source_mappable=False),
            field("cursor_to", "游标终点", "string", "分页、日期或令牌游标终点。", role="configuration", source_mappable=False),
            field("page_number", "页码", "int64", "分页接口的页码或 offset 序号。", role="configuration", source_mappable=False),
            field("status", "批次状态", "string", "批次执行状态。", nullable=False, role="configuration", enum_values=("RUNNING", "SUCCEEDED", "FAILED", "SKIPPED"), source_mappable=False),
            field("requested_at", "请求时间", "timestamp[us, UTC]", "外部请求发起时间。", nullable=False, role="audit", source_mappable=False),
            field("finished_at", "完成时间", "timestamp[us, UTC]", "外部请求完成时间。", role="audit", source_mappable=False),
            field("rows_received", "接收行数", "int64", "来源返回行数。", nullable=False, role="measure", unit="row", source_mappable=False),
            field("rows_accepted", "接受行数", "int64", "映射后接受行数。", nullable=False, role="measure", unit="row", source_mappable=False),
            field("rows_rejected", "拒绝行数", "int64", "映射或校验拒绝行数。", nullable=False, role="measure", unit="row", source_mappable=False),
            field("raw_artifact_uri", "原始制品地址", "string", "可重放 Raw 文件的内部地址。", role="audit", source_mappable=False),
            field("raw_checksum", "原始制品校验和", "string", "Raw 文件内容校验和。", role="audit", source_mappable=False),
            field("error_code", "错误代码", "string", "批次错误代码。", role="audit", source_mappable=False),
            field("error_message", "错误说明", "string", "脱敏后的错误说明。", role="audit", source_mappable=False),
            *control_audit_fields(),
        ),
        update_strategy="append",
    ),
    _control_table(
        "governance.data_release",
        "数据发布版本",
        "一个经过校验、不可变并可被研究任务锁定的数据版本。",
        "每个完整数据发布版本一条记录",
        ("data_release_id",),
        (
            primary_id("data_release_id", "数据版本 ID", "不可变数据发布版本标识。"),
            foreign_id("parent_release_id", "父版本 ID", "governance.data_release.data_release_id", "增量版本的直接父版本。", nullable=True),
            field("release_type", "发布类型", "string", "全量或增量版本。", nullable=False, role="configuration", enum_values=("FULL", "INCREMENTAL"), source_mappable=False),
            field("status", "发布状态", "string", "数据版本生命周期。", nullable=False, role="configuration", enum_values=("BUILDING", "VALIDATING", "PUBLISHED", "FAILED", "RETIRED"), source_mappable=False),
            field("schema_catalog_version", "数据模型版本", "string", "该版本使用的平台数据模型版本。", nullable=False, role="audit", source_mappable=False),
            field("created_at", "创建时间", "timestamp[us, UTC]", "候选版本创建时间。", nullable=False, role="audit", source_mappable=False),
            field("validated_at", "验收时间", "timestamp[us, UTC]", "完整质量验收通过时间。", role="audit", source_mappable=False),
            field("published_at", "发布时间", "timestamp[us, UTC]", "原子切换为可用版本的时间。", role="audit", source_mappable=False),
            field("manifest_uri", "Manifest 地址", "string", "版本清单地址。", role="audit", source_mappable=False),
            field("manifest_checksum", "Manifest 校验和", "string", "版本清单内容校验和。", role="audit", source_mappable=False),
            field("notes", "说明", "string", "版本说明和运维备注。", role="audit", source_mappable=False),
        ),
        update_strategy="append",
    ),
    _control_table(
        "governance.release_dataset",
        "版本数据集清单",
        "记录一个数据版本中每张内部表的物理位置、Schema 和校验和。",
        "每个数据版本中的每张表一条记录",
        ("data_release_id", "table_id"),
        (
            foreign_id("data_release_id", "数据版本 ID", "governance.data_release.data_release_id", "所属数据版本。"),
            field("table_id", "内部表 ID", "string", "系统数据模型中的 table_id。", nullable=False, role="primary_key", source_mappable=False),
            field("contract_version", "表合同版本", "string", "该表使用的字段合同版本。", nullable=False, role="audit", source_mappable=False),
            field("schema_hash", "Schema 哈希", "string", "字段顺序、类型和空值规则的哈希。", nullable=False, role="audit", source_mappable=False),
            field("physical_uri", "物理地址", "string", "Parquet 数据集或控制表的物理地址。", nullable=False, role="audit", source_mappable=False),
            field("storage_format", "存储格式", "string", "实际存储格式。", nullable=False, role="audit", enum_values=("PARQUET", "SQLITE"), source_mappable=False),
            field("row_count", "行数", "int64", "该版本表的总行数。", nullable=False, role="measure", unit="row", source_mappable=False),
            field("file_count", "文件数", "int64", "Parquet 数据集包含的文件数。", nullable=False, role="measure", unit="file", source_mappable=False),
            field("min_observation_date", "最早观测日", "date32", "表内最早业务日期。", role="observation_time", source_mappable=False),
            field("max_observation_date", "最晚观测日", "date32", "表内最晚业务日期。", role="observation_time", source_mappable=False),
            field("dataset_checksum", "数据集校验和", "string", "该版本数据集内容校验和。", nullable=False, role="audit", source_mappable=False),
            field("source_job_ids_json", "来源任务", "json", "构建该数据集的采集任务 ID。", nullable=False, role="audit", source_mappable=False),
            field("published_at", "发布时间", "timestamp[us, UTC]", "该数据集随版本发布的时间。", nullable=False, role="audit", source_mappable=False),
        ),
        update_strategy="append",
    ),
    _control_table(
        "governance.data_quality_result",
        "数据质量结果",
        "保存 Schema、完整性、唯一性、有效性、及时性、一致性和 PIT 检查结果。",
        "每次质量检查结果一条记录",
        ("quality_result_id",),
        (
            primary_id("quality_result_id", "质量结果 ID", "一次质量检查结果的稳定标识。"),
            foreign_id("data_release_id", "数据版本 ID", "governance.data_release.data_release_id", "被检查的数据版本。"),
            field("table_id", "内部表 ID", "string", "被检查的内部表。", nullable=False, role="configuration", source_mappable=False),
            field("check_code", "检查代码", "string", "稳定的质量规则代码。", nullable=False, role="configuration", source_mappable=False),
            field("check_name", "检查名称", "string", "质量规则名称。", nullable=False, role="configuration", source_mappable=False),
            field("dimension", "质量维度", "string", "规则所属质量维度。", nullable=False, role="configuration", enum_values=("SCHEMA", "COMPLETENESS", "UNIQUENESS", "VALIDITY", "TIMELINESS", "CONSISTENCY", "PIT"), source_mappable=False),
            field("severity", "严重级别", "string", "规则失败的影响级别。", nullable=False, role="configuration", enum_values=("INFO", "WARNING", "ERROR", "BLOCKER"), source_mappable=False),
            field("status", "检查状态", "string", "检查结果。", nullable=False, role="configuration", enum_values=("PASS", "WARN", "FAIL"), source_mappable=False),
            field("rows_checked", "检查行数", "int64", "实际参与检查的行数。", nullable=False, role="measure", unit="row", source_mappable=False),
            field("rows_failed", "失败行数", "int64", "违反规则的行数。", nullable=False, role="measure", unit="row", source_mappable=False),
            field("failure_ratio", "失败比例", "float64", "失败行数占检查行数的比例。", role="measure", unit="decimal", source_mappable=False),
            field("message", "结果说明", "string", "面向用户的结果说明。", nullable=False, role="audit", source_mappable=False),
            field("details_json", "检查详情", "json", "样本、阈值和诊断信息。", role="audit", source_mappable=False),
            field("checked_at", "检查时间", "timestamp[us, UTC]", "检查完成时间。", nullable=False, role="audit", source_mappable=False),
        ),
        update_strategy="append",
    ),
    _control_table(
        "governance.lineage_edge",
        "数据血缘",
        "记录来源接口、Raw 数据、内部表和研究派生数据之间的转换关系。",
        "每条上游到下游依赖关系一条记录",
        ("lineage_edge_id",),
        (
            primary_id("lineage_edge_id", "血缘边 ID", "一条血缘关系的稳定标识。"),
            foreign_id("data_release_id", "数据版本 ID", "governance.data_release.data_release_id", "该血缘关系所属的数据版本。"),
            field("upstream_type", "上游类型", "string", "上游对象类型。", nullable=False, role="configuration", enum_values=("SOURCE_INTERFACE", "RAW_DATASET", "CANONICAL_TABLE", "MART"), source_mappable=False),
            field("upstream_id", "上游对象", "string", "上游接口、文件或表标识。", nullable=False, role="configuration", source_mappable=False),
            field("downstream_type", "下游类型", "string", "下游对象类型。", nullable=False, role="configuration", enum_values=("RAW_DATASET", "CANONICAL_TABLE", "MART", "ARTIFACT"), source_mappable=False),
            field("downstream_id", "下游对象", "string", "下游文件、表或制品标识。", nullable=False, role="configuration", source_mappable=False),
            field("transform_version", "转换版本", "string", "产生下游对象的转换器版本。", nullable=False, role="audit", source_mappable=False),
            foreign_id("ingestion_job_id", "采集任务 ID", "governance.ingestion_job.ingestion_job_id", "执行本次转换的任务。", nullable=True),
            field("created_at", "记录时间", "timestamp[us, UTC]", "血缘关系写入时间。", nullable=False, role="audit", source_mappable=False),
        ),
        update_strategy="append",
    ),
)
