"""Canonical NAV, quote, scale, FX, rate, and status-event contracts."""

from __future__ import annotations

from ..types import (
    CategoryDefinition,
    TableDefinition,
    availability_fields,
    field,
    foreign_id,
    primary_id,
    source_lineage_fields,
)


CATEGORY = CategoryDefinition(
    category_id="market",
    label="行情、净值与估值",
    description="统一基金净值、交易行情、规模、汇率、利率和标的状态事件。",
    order=30,
)


def _fact_table(
    table_id: str,
    label: str,
    description: str,
    grain: str,
    primary_key: tuple[str, ...],
    fields: tuple,
    *,
    partition_by: tuple[str, ...],
    sort_by: tuple[str, ...],
    delivery_phase: str = "core",
) -> TableDefinition:
    name = table_id.split(".", 1)[1]
    return TableDefinition(
        table_id=table_id,
        category_id=CATEGORY.category_id,
        label=label,
        description=description,
        layer="canonical",
        storage_engine="parquet",
        storage_location=f"data/canonical/v1/market/{name}/",
        delivery_phase=delivery_phase,  # type: ignore[arg-type]
        grain=grain,
        primary_key=primary_key,
        update_strategy="append",
        fields=fields,
        source_mappable=True,
        partition_by=partition_by,
        sort_by=sort_by,
        pit_supported=True,
    )


TABLES = (
    _fact_table(
        "market.nav_daily",
        "基金日净值",
        "ETF 与场外基金共用的净值事实表，严格区分估值日期、公告时间和历史可得时间。",
        "每个基金份额、估值日、数据源和修订版本一条记录",
        ("instrument_id", "valuation_date", "source_id", "revision"),
        (
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "基金份额或 ETF 的内部标的 ID。", source_mappable=False),
            *availability_fields(
                observation_name="valuation_date",
                observation_label="估值日期",
                observation_description="该条净值对应的估值日期。",
            ),
            field("announced_at", "公告时间", "timestamp[us, UTC]", "净值正式公告时间；未知时为空。", role="available_time"),
            field("unit_nav", "单位净值", "float64", "每份基金单位净值。", role="measure", unit="currency/share"),
            field("accumulated_nav", "累计净值", "float64", "包含历史分红影响的累计净值。", role="measure", unit="currency/share"),
            field("adjusted_nav", "复权净值", "float64", "用于收益计算的复权净值。", role="measure", unit="nav_index"),
            field("accumulated_dividend", "累计分红", "float64", "截至估值日的累计单位分红。", role="measure", unit="currency/share"),
            field("net_assets", "净资产", "decimal128(38, 6)", "基金或份额披露的净资产。", role="measure", unit="currency"),
            field("total_assets", "资产总额", "decimal128(38, 6)", "基金或份额披露的资产总额。", role="measure", unit="currency"),
            field("currency", "币种", "string", "净值和资产金额币种。", nullable=False, unit="ISO-4217"),
            field("adjustment_method", "复权方法", "string", "adjusted_nav 的构造口径。", nullable=False, enum_values=("SOURCE", "DIVIDEND_REINVEST", "FACTOR", "NONE", "UNKNOWN")),
            field("is_retrospective_adjustment", "是否事后复权", "bool", "是否使用了当时尚不可得的后续调整信息。", nullable=False),
            *source_lineage_fields(),
        ),
        partition_by=("valuation_date",),
        sort_by=("instrument_id", "valuation_date", "source_id", "revision"),
    ),
    _fact_table(
        "market.quote_daily",
        "日行情",
        "统一 ETF、股票、债券、指数和期货的日频行情，不再按供应商或指数来源拆表。",
        "每个标的、交易日、行情类型、数据源和修订版本一条记录",
        ("instrument_id", "trade_date", "quote_type", "source_id", "revision"),
        (
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "行情对应的内部标的。", source_mappable=False),
            *availability_fields(
                observation_name="trade_date",
                observation_label="交易日期",
                observation_description="该条日行情对应的交易日期。",
            ),
            field("quote_type", "行情类型", "string", "区分交易价格、指数点位、结算价等。", nullable=False, enum_values=("TRADE_PRICE", "INDEX_LEVEL", "SETTLEMENT_PRICE", "NAV_REFERENCE")),
            field("open", "开盘值", "float64", "日内开盘价格或指数点位。", role="measure", unit="quote_unit"),
            field("high", "最高值", "float64", "日内最高价格或指数点位。", role="measure", unit="quote_unit"),
            field("low", "最低值", "float64", "日内最低价格或指数点位。", role="measure", unit="quote_unit"),
            field("close", "收盘值", "float64", "日内收盘价格或指数点位。", role="measure", unit="quote_unit"),
            field("previous_close", "前收盘值", "float64", "上一交易日收盘值。", role="measure", unit="quote_unit"),
            field("settlement_price", "结算价", "float64", "期货或适用资产的结算价格。", role="measure", unit="quote_unit"),
            field("change", "变动额", "float64", "收盘值相对前收盘值的变动额。", role="measure", unit="quote_unit"),
            field("return_decimal", "涨跌幅", "float64", "普通收益率，小数制，0.01 表示 1%。", role="measure", unit="decimal"),
            field("volume", "成交量", "float64", "按平台标准化基础单位计量的成交量。", role="measure", unit="base_unit"),
            field("turnover_amount", "成交额", "decimal128(38, 6)", "标准币种金额口径的成交额。", role="measure", unit="currency"),
            field("currency", "币种", "string", "价格和成交额币种；指数点位可为空。", unit="ISO-4217"),
            field("adjustment_basis", "行情复权口径", "string", "行情是否以及如何复权。", nullable=False, enum_values=("RAW", "FORWARD", "BACKWARD", "TOTAL_RETURN", "NOT_APPLICABLE")),
            *source_lineage_fields(),
        ),
        partition_by=("trade_date", "quote_type"),
        sort_by=("instrument_id", "trade_date", "quote_type", "source_id", "revision"),
    ),
    _fact_table(
        "market.fund_scale",
        "基金规模",
        "统一 ETF 份额规模和场外基金资产规模，保存公告与历史可得时点。",
        "每个基金份额、观测日、数据源和修订版本一条记录",
        ("instrument_id", "observation_date", "source_id", "revision"),
        (
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "规模对应基金份额或 ETF。", source_mappable=False),
            *availability_fields(),
            field("announced_at", "公告时间", "timestamp[us, UTC]", "规模信息正式公告时间。", role="available_time"),
            field("total_shares", "总份额", "decimal128(38, 6)", "基金或 ETF 总份额。", role="measure", unit="share"),
            field("net_assets", "净资产规模", "decimal128(38, 6)", "基金净资产规模。", role="measure", unit="currency"),
            field("total_assets", "资产总额", "decimal128(38, 6)", "基金资产总额。", role="measure", unit="currency"),
            field("market_value", "交易市值", "decimal128(38, 6)", "ETF 等交易品种按收盘价计算的市场价值。", role="measure", unit="currency"),
            field("currency", "币种", "string", "规模金额币种。", nullable=False, unit="ISO-4217"),
            *source_lineage_fields(),
        ),
        partition_by=("observation_date",),
        sort_by=("instrument_id", "observation_date", "source_id", "revision"),
    ),
    _fact_table(
        "market.fx_rate_daily",
        "日汇率",
        "统一跨币种研究、QDII、估值和组合换算使用的日汇率。",
        "每个基础币种、报价币种、日期、汇率类型、数据源和修订版本一条记录",
        ("base_currency", "quote_currency", "rate_date", "rate_type", "source_id", "revision"),
        (
            field("base_currency", "基础币种", "string", "汇率分子币种。", nullable=False, role="primary_key", unit="ISO-4217"),
            field("quote_currency", "报价币种", "string", "汇率分母币种。", nullable=False, role="primary_key", unit="ISO-4217"),
            *availability_fields(
                observation_name="rate_date",
                observation_label="汇率日期",
                observation_description="汇率适用的业务日期。",
            ),
            field("rate_type", "汇率类型", "string", "收盘、中间、定盘或即期汇率。", nullable=False, enum_values=("CLOSE", "MID", "FIXING", "SPOT")),
            field("rate", "汇率", "float64", "1 单位基础币种可兑换的报价币种数量。", nullable=False, role="measure", unit="quote/base"),
            field("inverse_rate", "倒数汇率", "float64", "1 单位报价币种可兑换的基础币种数量。", role="measure", unit="base/quote"),
            *source_lineage_fields(),
        ),
        partition_by=("rate_date",),
        sort_by=("base_currency", "quote_currency", "rate_date", "rate_type", "source_id", "revision"),
        delivery_phase="next",
    ),
    _fact_table(
        "market.rate_observation",
        "利率观察值",
        "统一 Shibor、LPR、回购、国债收益率和无风险利率等可直接使用的利率序列。",
        "每个利率序列、观测日、期限、数据源和修订版本一条记录",
        ("rate_series_id", "observation_date", "tenor_days", "source_id", "revision"),
        (
            field("rate_series_id", "利率序列 ID", "string", "平台稳定利率序列标识。", nullable=False, role="primary_key"),
            *availability_fields(),
            field("tenor_days", "期限天数", "int64", "标准化后的期限天数；隔夜为 1。", nullable=False, unit="day"),
            field("tenor_label", "期限标签", "string", "来源期限标签，例如 ON、1W、1Y。"),
            field("rate_decimal", "利率", "float64", "小数制利率，0.03 表示 3%。", nullable=False, role="measure", unit="decimal"),
            field("compounding", "复利方式", "string", "利率复利方式。", nullable=False, enum_values=("SIMPLE", "ANNUAL", "CONTINUOUS", "UNKNOWN")),
            field("day_count", "日计数规则", "string", "ACT/365、ACT/360 等日计数规则。"),
            field("currency", "币种", "string", "利率对应币种。", nullable=False, unit="ISO-4217"),
            *source_lineage_fields(),
        ),
        partition_by=("observation_date",),
        sort_by=("rate_series_id", "observation_date", "tenor_days", "source_id", "revision"),
        delivery_phase="next",
    ),
    _fact_table(
        "market.instrument_status_event",
        "标的状态事件",
        "统一上市、暂停、恢复、摘牌、申购开放、赎回开放等状态变化。",
        "每个标的状态变化事件一条记录",
        ("status_event_id",),
        (
            primary_id("status_event_id", "状态事件 ID", "状态事件的稳定标识。"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "发生状态变化的标的。", source_mappable=False),
            *availability_fields(
                observation_name="event_date",
                observation_label="事件日期",
                observation_description="状态实际生效的日期。",
            ),
            field("announced_at", "公告时间", "timestamp[us, UTC]", "事件正式公告时间。", role="available_time"),
            field("event_type", "事件类型", "string", "状态变化类型。", nullable=False, enum_values=("LISTING", "SUSPENSION", "RESUMPTION", "DELISTING", "SUBSCRIPTION_OPEN", "SUBSCRIPTION_CLOSE", "REDEMPTION_OPEN", "REDEMPTION_CLOSE", "TERMINATION", "OTHER")),
            field("status_before", "变更前状态", "string", "事件发生前的平台状态代码。"),
            field("status_after", "变更后状态", "string", "事件发生后的平台状态代码。", nullable=False),
            field("reason", "原因", "string", "状态变化原因。"),
            field("details_json", "事件详情", "json", "来源中的扩展事件信息。"),
            *source_lineage_fields(),
        ),
        partition_by=("event_date",),
        sort_by=("instrument_id", "event_date", "status_event_id"),
    ),
)
