"""Derived research marts built only from published canonical data releases."""

from __future__ import annotations

from ..types import CategoryDefinition, TableDefinition, field, foreign_id


CATEGORY = CategoryDefinition(
    category_id="marts",
    label="研究派生数据",
    description="保存可重复构建的产品快照、收益、指标、覆盖率和资产大类净值，不允许外部数据源直接写入。",
    order=70,
)


def _mart_table(
    table_id: str,
    label: str,
    description: str,
    grain: str,
    primary_key: tuple[str, ...],
    fields: tuple,
    *,
    partition_by: tuple[str, ...],
    sort_by: tuple[str, ...],
) -> TableDefinition:
    name = table_id.split(".", 1)[1]
    return TableDefinition(
        table_id=table_id,
        category_id=CATEGORY.category_id,
        label=label,
        description=description,
        layer="mart",
        storage_engine="parquet",
        storage_location=f"data/marts/v1/{name}/",
        delivery_phase="core",
        grain=grain,
        primary_key=primary_key,
        update_strategy="derived",
        fields=fields,
        source_mappable=False,
        partition_by=partition_by,
        sort_by=sort_by,
        pit_supported=True,
    )


TABLES = (
    _mart_table(
        "mart.instrument_current",
        "产品当前快照",
        "面向产品搜索、筛选和详情的当前统一视图，由主数据、净值、行情、规模和机构信息构建。",
        "每个标的和数据发布版本一条当前快照",
        ("data_release_id", "instrument_id"),
        (
            foreign_id("data_release_id", "数据版本 ID", "governance.data_release.data_release_id", "构建该快照的数据版本。"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "产品内部标的 ID。"),
            field("as_of", "快照截止时间", "timestamp[us, UTC]", "该快照的数据截止时间。", nullable=False, role="available_time", source_mappable=False),
            field("canonical_name", "产品名称", "string", "当前标准名称。", nullable=False, source_mappable=False),
            field("instrument_type", "产品类型", "string", "当前标的类型。", nullable=False, source_mappable=False),
            field("status_code", "产品状态", "string", "当前生命周期状态。", nullable=False, source_mappable=False),
            field("currency", "币种", "string", "产品计价币种。", nullable=False, unit="ISO-4217", source_mappable=False),
            field("fund_type", "基金类别", "string", "当前基金类别。", source_mappable=False),
            field("investment_type", "投资方式", "string", "当前投资方式。", source_mappable=False),
            field("management_company_id", "管理人机构 ID", "string", "当前管理人机构。", role="foreign_key", reference="master.organization.organization_id", source_mappable=False),
            field("latest_nav_date", "最新净值日", "date32", "最新有效净值日期。", role="observation_time", source_mappable=False),
            field("latest_adjusted_nav", "最新复权净值", "float64", "最新复权净值。", role="measure", unit="nav_index", source_mappable=False),
            field("latest_quote_date", "最新行情日", "date32", "最新有效行情日期。", role="observation_time", source_mappable=False),
            field("latest_close", "最新收盘值", "float64", "最新交易收盘价或指数点位。", role="measure", unit="quote_unit", source_mappable=False),
            field("latest_net_assets", "最新净资产规模", "decimal128(38, 6)", "最新可得净资产规模。", role="measure", unit="currency", source_mappable=False),
            field("data_status", "数据状态", "string", "当前产品数据是否完整、部分可用或不可用。", nullable=False, enum_values=("COMPLETE", "PARTIAL", "UNAVAILABLE"), source_mappable=False),
            field("warning_codes", "警告代码", "list<string>", "当前产品数据警告代码。", source_mappable=False),
            field("calculation_version", "构建版本", "string", "快照构建逻辑版本。", nullable=False, role="audit", source_mappable=False),
            field("built_at", "构建时间", "timestamp[us, UTC]", "快照构建完成时间。", nullable=False, role="audit", source_mappable=False),
        ),
        partition_by=("data_release_id", "instrument_type"),
        sort_by=("data_release_id", "instrument_type", "instrument_id"),
    ),
    _mart_table(
        "mart.daily_return",
        "标准日收益率",
        "按固定价格口径生成的普通或对数日收益率，供指标、分类、资产配置和回测共同使用。",
        "每个标的、收益日期、收益类型、价格口径和数据版本一条记录",
        ("data_release_id", "instrument_id", "return_date", "return_type", "price_basis"),
        (
            foreign_id("data_release_id", "数据版本 ID", "governance.data_release.data_release_id", "收益率使用的数据版本。"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "收益率对应标的。"),
            field("return_date", "收益日期", "date32", "该收益率对应的期末日期。", nullable=False, role="observation_time", source_mappable=False),
            field("period_start", "收益期初", "date32", "计算收益率使用的期初日期。", nullable=False, role="observation_time", source_mappable=False),
            field("return_type", "收益类型", "string", "普通收益或对数收益。", nullable=False, enum_values=("SIMPLE", "LOG"), source_mappable=False),
            field("price_basis", "价格口径", "string", "收益率使用的价格或净值口径。", nullable=False, enum_values=("ADJUSTED_NAV", "RAW_CLOSE", "TOTAL_RETURN", "SETTLEMENT"), source_mappable=False),
            field("return_value", "收益率", "float64", "小数制收益率。", nullable=False, role="measure", unit="decimal", source_mappable=False),
            field("available_at", "最早可得时间", "timestamp[us, UTC]", "该收益率最早可用于历史研究的时间。", role="available_time", source_mappable=False),
            field("status_code", "计算状态", "string", "成功、样本不足或来源不可用。", nullable=False, enum_values=("AVAILABLE", "INSUFFICIENT", "UNAVAILABLE", "INVALID"), source_mappable=False),
            field("source_table_id", "来源表", "string", "直接来源内部表。", nullable=False, role="audit", source_mappable=False),
            field("calculation_version", "计算版本", "string", "收益率构建逻辑版本。", nullable=False, role="audit", source_mappable=False),
            field("built_at", "构建时间", "timestamp[us, UTC]", "派生数据构建时间。", nullable=False, role="audit", source_mappable=False),
        ),
        partition_by=("data_release_id", "return_date"),
        sort_by=("data_release_id", "instrument_id", "return_date", "return_type", "price_basis"),
    ),
    _mart_table(
        "mart.instrument_metric_snapshot",
        "产品指标快照",
        "以长表保存内置和自定义产品指标结果，锁定指标版本、窗口、状态和数据版本。",
        "每个标的、指标版本、周期、截止时间和数据版本一条记录",
        ("data_release_id", "instrument_id", "metric_id", "metric_revision", "period_code", "as_of"),
        (
            foreign_id("data_release_id", "数据版本 ID", "governance.data_release.data_release_id", "指标输入使用的数据版本。"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "指标对应产品。"),
            field("metric_id", "指标 ID", "string", "内置或自定义指标稳定 ID。", nullable=False, role="primary_key", source_mappable=False),
            field("metric_revision", "指标修订", "int64", "指标不可变修订号。", nullable=False, role="primary_key", source_mappable=False),
            field("period_code", "评价周期", "string", "1M、1Y、成立以来等评价周期。", nullable=False, role="primary_key", source_mappable=False),
            field("as_of", "指标截止时间", "timestamp[us, UTC]", "指标运行冻结的截止时间。", nullable=False, role="primary_key", source_mappable=False),
            field("window_start", "窗口开始", "date32", "实际参与计算的窗口开始日。", role="observation_time", source_mappable=False),
            field("window_end", "窗口结束", "date32", "实际参与计算的窗口结束日。", role="observation_time", source_mappable=False),
            field("value", "指标值", "float64", "指标原始数值；不可用时为空。", role="measure", source_mappable=False),
            field("unit", "指标单位", "string", "锁定指标版本声明的单位。", nullable=False, source_mappable=False),
            field("status_code", "结果状态", "string", "结果是否可用。", nullable=False, enum_values=("AVAILABLE", "INSUFFICIENT_SAMPLE", "MISSING_DATA", "INAPPLICABLE", "FAILED"), source_mappable=False),
            field("reason_code", "不可用原因", "string", "不可用或失败的稳定原因代码。", source_mappable=False),
            field("observation_count", "观察数", "int64", "实际参与计算的有效观察数。", nullable=False, role="measure", unit="count", source_mappable=False),
            field("presentation_json", "展示合同", "json", "锁定的精度、缩放和格式化规则。", nullable=False, source_mappable=False),
            field("calculation_version", "计算版本", "string", "指标运行时和数值内核版本。", nullable=False, role="audit", source_mappable=False),
            field("built_at", "构建时间", "timestamp[us, UTC]", "指标结果生成时间。", nullable=False, role="audit", source_mappable=False),
        ),
        partition_by=("data_release_id", "as_of"),
        sort_by=("data_release_id", "metric_id", "metric_revision", "period_code", "instrument_id"),
    ),
    _mart_table(
        "mart.series_coverage",
        "序列覆盖率",
        "汇总每条净值、行情、指数、宏观和派生序列的起止日、观察数、缺失率、陈旧度与 PIT 能力。",
        "每个数据版本中的每条逻辑序列一条记录",
        ("data_release_id", "series_type", "series_id"),
        (
            foreign_id("data_release_id", "数据版本 ID", "governance.data_release.data_release_id", "覆盖率对应数据版本。"),
            field("series_type", "序列类型", "string", "净值、行情、指数、宏观、指标等类型。", nullable=False, role="primary_key", enum_values=("NAV", "QUOTE", "INDEX", "MACRO", "RATE", "FX", "METRIC"), source_mappable=False),
            field("series_id", "序列 ID", "string", "instrument_id、macro series_id 或其他逻辑序列 ID。", nullable=False, role="primary_key", source_mappable=False),
            field("source_table_id", "来源表", "string", "序列直接来源内部表。", nullable=False, source_mappable=False),
            field("first_date", "最早日期", "date32", "首个有效观察日期。", role="observation_time", source_mappable=False),
            field("latest_date", "最晚日期", "date32", "最后有效观察日期。", role="observation_time", source_mappable=False),
            field("observation_count", "观察数", "int64", "有效观察总数。", nullable=False, role="measure", unit="count", source_mappable=False),
            field("expected_count", "应有观察数", "int64", "按频率和日历推算的应有观察数。", role="measure", unit="count", source_mappable=False),
            field("missing_count", "缺失数", "int64", "应有但缺失的观察数。", role="measure", unit="count", source_mappable=False),
            field("coverage_ratio", "覆盖率", "float64", "有效观察占应有观察比例。", role="measure", unit="decimal", source_mappable=False),
            field("stale_days", "陈旧天数", "int64", "最新可用日距数据版本截止日的天数。", role="measure", unit="day", source_mappable=False),
            field("pit_supported", "支持 PIT", "bool", "是否有足够的历史可得时间信息。", nullable=False, source_mappable=False),
            field("quality_status", "质量状态", "string", "序列质量状态。", nullable=False, enum_values=("READY", "PARTIAL", "STALE", "MISSING", "INVALID"), source_mappable=False),
            field("warning_codes", "警告代码", "list<string>", "覆盖和质量警告。", source_mappable=False),
            field("built_at", "构建时间", "timestamp[us, UTC]", "覆盖率构建时间。", nullable=False, role="audit", source_mappable=False),
        ),
        partition_by=("data_release_id", "series_type"),
        sort_by=("data_release_id", "series_type", "series_id"),
    ),
    _mart_table(
        "mart.asset_class_nav",
        "资产大类净值",
        "保存资产大类版本基于底层产品、权重和已发布数据版本计算出的不可变净值序列。",
        "每个资产大类版本、估值日和数据版本一条记录",
        ("data_release_id", "asset_class_version_id", "valuation_date"),
        (
            foreign_id("data_release_id", "数据版本 ID", "governance.data_release.data_release_id", "计算使用的数据版本。"),
            field("asset_class_version_id", "资产大类版本 ID", "string", "资产大类不可变定义版本。", nullable=False, role="primary_key", source_mappable=False),
            field("asset_class_name", "资产大类名称", "string", "锁定版本中的大类名称。", nullable=False, source_mappable=False),
            field("valuation_date", "估值日期", "date32", "大类净值对应日期。", nullable=False, role="observation_time", source_mappable=False),
            field("nav", "大类净值", "float64", "以 1 为基准的资产大类净值。", nullable=False, role="measure", unit="nav_index", source_mappable=False),
            field("return_value", "大类收益率", "float64", "相邻有效日期的普通收益率。", role="measure", unit="decimal", source_mappable=False),
            field("available_at", "最早可得时间", "timestamp[us, UTC]", "底层数据与权重均已可得的最晚时间。", role="available_time", source_mappable=False),
            field("calculation_version", "计算版本", "string", "资产大类净值计算逻辑版本。", nullable=False, role="audit", source_mappable=False),
            field("definition_hash", "定义哈希", "string", "底层成员和权重定义哈希。", nullable=False, role="audit", source_mappable=False),
            field("built_at", "构建时间", "timestamp[us, UTC]", "大类净值构建时间。", nullable=False, role="audit", source_mappable=False),
        ),
        partition_by=("data_release_id", "valuation_date"),
        sort_by=("data_release_id", "asset_class_version_id", "valuation_date"),
    ),
)
