"""Canonical product, organization, identity, classification, and calendar contracts."""

from __future__ import annotations

from ..types import (
    CategoryDefinition,
    TableDefinition,
    field,
    foreign_id,
    primary_id,
    source_lineage_fields,
    validity_fields,
)


CATEGORY = CategoryDefinition(
    category_id="master",
    label="产品与参与方主数据",
    description="定义平台内部产品 ID、基金产品、外部代码、管理人、基金经理、分类、基准和交易日历。",
    order=20,
)


def _master_table(
    table_id: str,
    label: str,
    description: str,
    grain: str,
    primary_key: tuple[str, ...],
    fields: tuple,
    *,
    update_strategy: str = "scd2",
    delivery_phase: str = "core",
    partition_by: tuple[str, ...] = (),
    sort_by: tuple[str, ...] = (),
    pit_supported: bool = False,
    source_mappable: bool = True,
) -> TableDefinition:
    name = table_id.split(".", 1)[1]
    return TableDefinition(
        table_id=table_id,
        category_id=CATEGORY.category_id,
        label=label,
        description=description,
        layer="master",
        storage_engine="parquet",
        storage_location=f"data/canonical/v1/master/{name}/",
        delivery_phase=delivery_phase,  # type: ignore[arg-type]
        grain=grain,
        primary_key=primary_key,
        update_strategy=update_strategy,  # type: ignore[arg-type]
        fields=fields,
        source_mappable=source_mappable,
        partition_by=partition_by,
        sort_by=sort_by,
        pit_supported=pit_supported,
    )


TABLES = (
    _master_table(
        "master.exchange",
        "交易所",
        "统一交易所、市场、时区、币种和交易日历引用。",
        "每个交易所的每个有效版本一条记录",
        ("exchange_id", "valid_from"),
        (
            primary_id("exchange_id", "交易所 ID", "平台生成的稳定交易所标识。"),
            field("mic", "MIC 代码", "string", "ISO 10383 市场识别代码。", unit="ISO-10383"),
            field("exchange_code", "交易所代码", "string", "平台内部简码，例如 SSE、SZSE。", nullable=False),
            field("name", "交易所名称", "string", "交易所正式名称。", nullable=False),
            field("country_code", "国家或地区", "string", "ISO 3166-1 alpha-2 代码。", nullable=False, unit="ISO-3166-1"),
            field("timezone", "交易所时区", "string", "交易时点使用的 IANA 时区。", nullable=False),
            field("currency", "主要币种", "string", "主要交易币种。", nullable=False, unit="ISO-4217"),
            field("calendar_code", "交易日历代码", "string", "关联交易日历的内部代码。", nullable=False),
            field("active", "是否有效", "bool", "交易所当前是否有效。", nullable=False),
            *validity_fields(),
            *source_lineage_fields(),
        ),
        sort_by=("exchange_id", "valid_from"),
    ),
    _master_table(
        "master.organization",
        "机构",
        "统一基金管理人、托管人、指数公司、券商、银行和其他机构。",
        "每个机构的每个有效版本一条记录",
        ("organization_id", "valid_from"),
        (
            primary_id("organization_id", "机构 ID", "平台生成的稳定机构标识。"),
            field("organization_type", "机构类型", "string", "机构承担的主要业务角色。", nullable=False, enum_values=("FUND_MANAGER", "CUSTODIAN", "TRUSTEE", "INDEX_PROVIDER", "BROKER", "BANK", "DATA_PROVIDER", "OTHER")),
            field("legal_name", "法定名称", "string", "机构正式登记名称。", nullable=False),
            field("short_name", "简称", "string", "机构常用简称。"),
            field("country_code", "国家或地区", "string", "注册国家或地区。", unit="ISO-3166-1"),
            field("province", "省份", "string", "注册地址省份。"),
            field("city", "城市", "string", "注册地址城市。"),
            field("registration_number", "注册编号", "string", "统一社会信用代码或当地注册编号。"),
            field("website", "官网", "string", "机构官方网站。"),
            field("status_code", "状态", "string", "机构当前状态。", nullable=False, enum_values=("ACTIVE", "INACTIVE", "UNKNOWN")),
            *validity_fields(),
            *source_lineage_fields(),
        ),
        partition_by=("organization_type",),
        sort_by=("organization_type", "organization_id", "valid_from"),
    ),
    _master_table(
        "master.organization_identifier",
        "机构外部标识映射",
        "系统内部保存来源机构代码与 organization_id 的对照，由导入配置和身份解析维护；不是需要用户导入的业务数据。",
        "每个数据源命名空间中的每个机构外部代码一条有效期记录",
        ("source_id", "namespace", "external_code", "valid_from"),
        (
            foreign_id("source_id", "数据源", "governance.data_source.data_source_id", "外部标识所属数据源。"),
            field("namespace", "代码空间", "string", "外部代码类型，例如 ORG_CODE、CREDIT_CODE。", nullable=False),
            field("external_code", "外部机构代码", "string", "来源系统中的机构标识。", nullable=False),
            foreign_id("organization_id", "机构 ID", "master.organization.organization_id", "映射后的平台机构。", source_mappable=False),
            field("is_primary", "是否主标识", "bool", "是否为该来源的首选机构代码。", nullable=False),
            field("mapping_method", "映射方式", "string", "外部代码与内部 ID 的匹配方式。", nullable=False, enum_values=("EXACT", "MANUAL", "RULE", "FUZZY")),
            field("confidence", "映射置信度", "float64", "自动映射的置信度；人工确认可为 1。", nullable=False, unit="decimal"),
            *validity_fields(),
            field("source_record_hash", "来源记录哈希", "string", "原始映射记录的内容哈希。", nullable=False, role="audit", source_mappable=False),
            field("ingested_at", "采集时间", "timestamp[us, UTC]", "映射记录进入平台的时间。", nullable=False, role="audit", source_mappable=False),
        ),
        source_mappable=False,
        update_strategy="scd2",
        sort_by=("source_id", "namespace", "external_code", "valid_from"),
    ),
    _master_table(
        "master.person",
        "人员",
        "统一基金经理及后续研究中需要引用的自然人主数据。",
        "每个人员的每个有效版本一条记录",
        ("person_id", "valid_from"),
        (
            primary_id("person_id", "人员 ID", "平台生成的稳定人员标识。"),
            field("canonical_name", "标准姓名", "string", "平台统一姓名。", nullable=False),
            field("gender", "性别", "string", "来源披露的性别；未知时为空。", enum_values=("MALE", "FEMALE", "OTHER", "UNKNOWN")),
            field("birth_year", "出生年份", "int64", "来源披露的出生年份。", unit="year"),
            field("nationality", "国籍", "string", "来源披露的国籍或地区。"),
            field("education", "学历", "string", "来源披露的最高学历。"),
            field("profile_summary", "履历摘要", "string", "公开履历摘要。"),
            field("status_code", "状态", "string", "人员主数据状态。", nullable=False, enum_values=("ACTIVE", "INACTIVE", "UNKNOWN")),
            *validity_fields(),
            *source_lineage_fields(),
        ),
        partition_by=("status_code",),
        sort_by=("person_id", "valid_from"),
        delivery_phase="next",
    ),
    _master_table(
        "master.person_identifier",
        "人员外部标识映射",
        "系统内部保存已确认的来源人员标识与 person_id 的对照，由导入配置和身份解析维护；不要求用户单独导入对照表。",
        "每个来源人员标识的一条有效期记录",
        ("source_id", "namespace", "external_code", "valid_from"),
        (
            foreign_id("source_id", "数据源", "governance.data_source.data_source_id", "外部标识所属数据源。"),
            field("namespace", "代码空间", "string", "外部人员代码类型。", nullable=False),
            field("external_code", "外部人员代码", "string", "来源中的人员标识；无代码时可使用受控实体键。", nullable=False),
            foreign_id("person_id", "人员 ID", "master.person.person_id", "映射后的平台人员。", source_mappable=False),
            field("mapping_method", "映射方式", "string", "人员实体匹配方式。", nullable=False, enum_values=("EXACT", "MANUAL", "RULE", "FUZZY")),
            field("confidence", "映射置信度", "float64", "自动匹配置信度。", nullable=False, unit="decimal"),
            *validity_fields(),
            field("source_record_hash", "来源记录哈希", "string", "原始映射记录哈希。", nullable=False, role="audit", source_mappable=False),
            field("ingested_at", "采集时间", "timestamp[us, UTC]", "映射进入平台的时间。", nullable=False, role="audit", source_mappable=False),
        ),
        source_mappable=False,
        sort_by=("source_id", "namespace", "external_code", "valid_from"),
        delivery_phase="next",
    ),
    _master_table(
        "master.fund_product",
        "基金产品",
        "表示法律或合同层面的一只基金；A/C/E 等份额通过 instrument 关联。",
        "每只基金产品的每个有效版本一条记录",
        ("fund_product_id", "valid_from"),
        (
            primary_id("fund_product_id", "基金产品 ID", "平台生成的基金产品稳定标识。"),
            field("legal_name", "基金法定名称", "string", "基金正式名称。", nullable=False),
            field("short_name", "基金简称", "string", "基金常用简称。"),
            field("fund_structure", "基金结构", "string", "基金法律或交易结构。", nullable=False, enum_values=("OPEN_END", "CLOSED_END", "ETF", "LOF", "REIT", "OTHER")),
            field("fund_type", "基金类别", "string", "股票型、债券型、混合型、货币型等标准分类。"),
            field("investment_type", "投资方式", "string", "主动、被动、指数增强等投资方式。"),
            field("base_currency", "基础币种", "string", "基金主要计价币种。", nullable=False, unit="ISO-4217"),
            field("domicile", "注册地", "string", "基金注册国家或地区。", unit="ISO-3166-1"),
            foreign_id("management_company_id", "管理人机构", "master.organization.organization_id", "基金管理人。", nullable=True, source_mappable=False),
            foreign_id("custodian_organization_id", "托管机构", "master.organization.organization_id", "基金托管人。", nullable=True, source_mappable=False),
            foreign_id("trustee_organization_id", "受托机构", "master.organization.organization_id", "基金受托人。", nullable=True, source_mappable=False),
            field("inception_date", "成立日期", "date32", "基金成立日期。", role="effective_time"),
            field("maturity_date", "到期日期", "date32", "有期限基金的合同到期日期。", role="effective_time"),
            field("termination_date", "终止日期", "date32", "基金清算或终止日期。", role="effective_time"),
            field("status_code", "基金状态", "string", "基金生命周期状态。", nullable=False, enum_values=("ISSUING", "ACTIVE", "SUSPENDED", "TERMINATED", "UNKNOWN")),
            field("benchmark_description", "合同基准说明", "string", "合同文本中的业绩比较基准描述。"),
            field("qdii_flag", "是否 QDII", "bool", "是否通过 QDII 额度投资境外资产。"),
            *validity_fields(),
            *source_lineage_fields(),
        ),
        partition_by=("fund_structure",),
        sort_by=("fund_product_id", "valid_from"),
    ),
    _master_table(
        "master.instrument",
        "可投资标的",
        "平台统一标的主表；ETF、基金份额、股票、债券、指数、期货、外汇和现金均使用内部 instrument_id。",
        "每个可投资或可观察标的的每个有效版本一条记录",
        ("instrument_id", "valid_from"),
        (
            primary_id("instrument_id", "标的 ID", "平台生成的稳定标的标识，业务代码只使用该 ID。"),
            field("instrument_type", "标的类型", "string", "平台统一标的类型。", nullable=False, enum_values=("FUND_SHARE", "ETF", "STOCK", "BOND", "INDEX", "FUTURE", "FX", "CASH", "OTHER")),
            foreign_id("fund_product_id", "基金产品 ID", "master.fund_product.fund_product_id", "基金份额或 ETF 所属基金产品。", nullable=True, source_mappable=False),
            field("canonical_name", "标准名称", "string", "平台统一名称。", nullable=False),
            field("short_name", "简称", "string", "常用简称。"),
            field("share_class", "份额类别", "string", "基金 A、C、E、I 等份额类别。"),
            field("ticker", "交易代码", "string", "主要交易代码；不同来源的代码通过导入配置关联到同一标的，无需单独导入代码对照表。"),
            foreign_id("exchange_id", "交易所 ID", "master.exchange.exchange_id", "上市或报价交易所。", nullable=True, source_mappable=False),
            field("currency", "计价币种", "string", "净值或行情的计价币种。", nullable=False, unit="ISO-4217"),
            field("inception_date", "起始日期", "date32", "基金份额成立或标的开始日期。", role="effective_time"),
            field("listing_date", "上市日期", "date32", "交易所上市日期。", role="effective_time"),
            field("maturity_date", "到期日期", "date32", "标的到期日期。", role="effective_time"),
            field("termination_date", "终止日期", "date32", "摘牌、清盘或终止日期。", role="effective_time"),
            field("status_code", "标的状态", "string", "平台统一生命周期状态。", nullable=False, enum_values=("PENDING", "ACTIVE", "SUSPENDED", "DELISTED", "TERMINATED", "UNKNOWN")),
            field("tradable", "是否可交易", "bool", "是否属于可执行交易标的；指数等通常为否。", nullable=False),
            field("qdii_flag", "是否 QDII", "bool", "基金或 ETF 是否属于 QDII。"),
            field("lot_size", "最小交易单位", "float64", "交易所或销售渠道的最小数量单位。", unit="unit"),
            field("price_precision", "价格精度", "int64", "价格或净值的小数位数。", unit="decimal_place"),
            *validity_fields(),
            *source_lineage_fields(),
        ),
        partition_by=("instrument_type",),
        sort_by=("instrument_type", "instrument_id", "valid_from"),
    ),
    _master_table(
        "master.instrument_identifier",
        "标的外部代码映射",
        "系统内部保存来源标的代码与 instrument_id 的对照，由导入配置和身份解析维护；业务数据直接映射到产品、行情、净值等标准表。",
        "每个来源代码空间中的每个标的代码一条有效期记录",
        ("source_id", "namespace", "external_code", "valid_from"),
        (
            foreign_id("source_id", "数据源", "governance.data_source.data_source_id", "外部代码所属数据源。"),
            field("namespace", "代码空间", "string", "外部代码类型，例如 TS_CODE、WIND_CODE、ISIN。", nullable=False),
            field("external_code", "外部标的代码", "string", "来源系统中的标的标识。", nullable=False),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "映射后的平台标的。", source_mappable=False),
            field("is_primary", "是否主标识", "bool", "是否为该来源的首选代码。", nullable=False),
            field("mapping_method", "映射方式", "string", "外部代码与内部标的的匹配方式。", nullable=False, enum_values=("EXACT", "MANUAL", "RULE", "FUZZY")),
            field("confidence", "映射置信度", "float64", "自动映射置信度。", nullable=False, unit="decimal"),
            *validity_fields(),
            field("source_record_hash", "来源记录哈希", "string", "原始映射记录哈希。", nullable=False, role="audit", source_mappable=False),
            field("ingested_at", "采集时间", "timestamp[us, UTC]", "映射进入平台的时间。", nullable=False, role="audit", source_mappable=False),
        ),
        source_mappable=False,
        sort_by=("source_id", "namespace", "external_code", "valid_from"),
    ),
    _master_table(
        "master.fund_manager_tenure",
        "基金经理任职",
        "记录基金产品与基金经理的角色、任期、公告日和历史可得时间。",
        "每段基金经理任职关系一条记录",
        ("tenure_id",),
        (
            primary_id("tenure_id", "任职 ID", "任职关系的稳定标识。"),
            foreign_id("fund_product_id", "基金产品 ID", "master.fund_product.fund_product_id", "任职对应基金产品。", source_mappable=False),
            foreign_id("person_id", "人员 ID", "master.person.person_id", "任职基金经理。", source_mappable=False),
            field("role_code", "角色", "string", "基金经理在产品中的角色。", nullable=False, enum_values=("LEAD_MANAGER", "CO_MANAGER", "ASSISTANT", "OTHER")),
            field("begin_date", "任职开始", "date32", "任职生效日期。", nullable=False, role="effective_time"),
            field("end_date", "任职结束", "date32", "任职结束日期；为空表示仍在任。", role="effective_time"),
            field("announced_at", "公告时间", "timestamp[us, UTC]", "任职信息公告时间。", role="available_time"),
            field("available_at", "最早可得时间", "timestamp[us, UTC]", "历史研究中最早可使用的时间。", role="available_time"),
            field("is_primary", "是否主要经理", "bool", "是否为主要负责人。", nullable=False),
            *source_lineage_fields(),
        ),
        update_strategy="append",
        partition_by=("begin_date",),
        sort_by=("fund_product_id", "begin_date", "person_id"),
        pit_supported=True,
        delivery_phase="next",
    ),
    _master_table(
        "master.classification_scheme",
        "分类体系",
        "定义基金、资产、行业、风格或产品标签的版本化分类体系。",
        "每个分类体系版本一条记录",
        ("scheme_id", "version"),
        (
            primary_id("scheme_id", "分类体系 ID", "分类体系稳定标识。"),
            field("version", "版本", "string", "不可变分类体系版本。", nullable=False, role="primary_key"),
            field("code", "体系代码", "string", "平台内部分类体系代码。", nullable=False),
            field("name", "体系名称", "string", "分类体系名称。", nullable=False),
            field("provider", "提供方", "string", "平台、数据源或外部机构。"),
            field("description", "说明", "string", "分类边界和使用说明。"),
            field("status", "状态", "string", "分类体系生命周期。", nullable=False, enum_values=("DRAFT", "PUBLISHED", "RETIRED")),
            field("effective_from", "生效起始", "date32", "该版本开始生效日期。", nullable=False, role="effective_time"),
            field("effective_to", "生效结束", "date32", "该版本结束日期。", role="effective_time"),
            *source_lineage_fields(),
        ),
        update_strategy="append",
        sort_by=("scheme_id", "version"),
    ),
    _master_table(
        "master.classification_node",
        "分类节点",
        "保存分类体系中的层级节点和父子关系。",
        "每个分类体系版本中的每个分类节点一条记录",
        ("scheme_id", "scheme_version", "node_id"),
        (
            foreign_id("scheme_id", "分类体系 ID", "master.classification_scheme.scheme_id", "所属分类体系。", source_mappable=False),
            field("scheme_version", "体系版本", "string", "所属分类体系版本。", nullable=False, role="primary_key"),
            primary_id("node_id", "节点 ID", "分类节点稳定标识。"),
            foreign_id("parent_node_id", "父节点 ID", "master.classification_node.node_id", "父分类节点；根节点为空。", nullable=True, source_mappable=False),
            field("code", "节点代码", "string", "分类节点代码。", nullable=False),
            field("name", "节点名称", "string", "分类节点名称。", nullable=False),
            field("level", "层级", "int64", "分类树层级，从 1 开始。", nullable=False, unit="level"),
            field("sort_order", "排序", "int64", "同级展示顺序。", nullable=False),
            field("description", "说明", "string", "分类标准说明。"),
            *source_lineage_fields(),
        ),
        update_strategy="append",
        partition_by=("scheme_id", "scheme_version"),
        sort_by=("scheme_id", "scheme_version", "level", "sort_order", "node_id"),
    ),
    _master_table(
        "master.instrument_classification",
        "标的分类关系",
        "把标的映射到版本化分类节点，并保留有效期、可得时间和置信度。",
        "每个标的在一个分类体系中的一段有效分类关系",
        ("instrument_id", "scheme_id", "scheme_version", "node_id", "valid_from"),
        (
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "被分类的标的。", source_mappable=False),
            foreign_id("scheme_id", "分类体系 ID", "master.classification_scheme.scheme_id", "使用的分类体系。", source_mappable=False),
            field("scheme_version", "体系版本", "string", "使用的分类体系版本。", nullable=False, role="primary_key", source_mappable=False),
            foreign_id("node_id", "分类节点 ID", "master.classification_node.node_id", "标的所属分类节点。", source_mappable=False),
            field("confidence", "分类置信度", "float64", "规则或模型分类的置信度。", nullable=False, unit="decimal"),
            field("classification_method", "分类方式", "string", "分类产生方式。", nullable=False, enum_values=("SOURCE", "RULE", "MODEL", "MANUAL")),
            field("available_at", "最早可得时间", "timestamp[us, UTC]", "该分类结果最早可用于研究的时间。", role="available_time"),
            *validity_fields(),
            *source_lineage_fields(),
        ),
        partition_by=("scheme_id", "scheme_version"),
        sort_by=("scheme_id", "scheme_version", "instrument_id", "valid_from"),
        pit_supported=True,
    ),
    _master_table(
        "master.instrument_benchmark",
        "标的基准关系",
        "保存基金或组合标的与一个或多个基准成分的版本化关系。",
        "每个标的与每个基准成分的一段有效关系",
        ("instrument_id", "benchmark_component_id", "valid_from"),
        (
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "使用基准的基金或标的。", source_mappable=False),
            primary_id("benchmark_component_id", "基准成分 ID", "基准关系成分的稳定标识。"),
            foreign_id("benchmark_instrument_id", "基准标的 ID", "master.instrument.instrument_id", "已解析的指数或基准标的。", nullable=True, source_mappable=False),
            field("benchmark_name_text", "基准文本", "string", "无法完全结构化时保留的合同基准文本。"),
            field("relation_type", "基准关系", "string", "基准用途。", nullable=False, enum_values=("PRIMARY", "SECONDARY", "CONTRACT", "TRACKED_INDEX")),
            field("weight", "基准权重", "float64", "复合基准中的权重。", unit="decimal"),
            field("available_at", "最早可得时间", "timestamp[us, UTC]", "该基准关系最早可用时间。", role="available_time"),
            *validity_fields(),
            *source_lineage_fields(),
        ),
        sort_by=("instrument_id", "valid_from", "benchmark_component_id"),
        pit_supported=True,
    ),
    _master_table(
        "master.trading_calendar",
        "交易日历",
        "统一各交易所开放日、交易时段、前一开放日和结算日。",
        "每个交易日历代码和自然日一条记录",
        ("calendar_code", "calendar_date"),
        (
            field("calendar_code", "交易日历代码", "string", "平台内部交易日历代码。", nullable=False, role="primary_key"),
            foreign_id("exchange_id", "交易所 ID", "master.exchange.exchange_id", "日历对应交易所。", nullable=True, source_mappable=False),
            field("calendar_date", "自然日", "date32", "日历日期。", nullable=False, role="primary_key"),
            field("is_open", "是否开市", "bool", "该日期是否开放交易。", nullable=False),
            field("session_open_at", "开市时间", "timestamp[us, UTC]", "主要交易时段开始时间。", role="effective_time"),
            field("session_close_at", "收市时间", "timestamp[us, UTC]", "主要交易时段结束时间。", role="effective_time"),
            field("previous_open_date", "前一开放日", "date32", "该日之前最近开放交易日。"),
            field("settlement_date", "默认结算日", "date32", "采用默认规则时对应结算日期。"),
            field("holiday_name", "节假日名称", "string", "闭市节假日名称。"),
            *source_lineage_fields(),
        ),
        update_strategy="upsert",
        partition_by=("calendar_code",),
        sort_by=("calendar_code", "calendar_date"),
        pit_supported=True,
    ),
)
