"""External transaction, execution, allocation, settlement, position, and reconciliation contracts."""

from __future__ import annotations

from ..types import CategoryDefinition, TableDefinition, control_audit_fields, field, foreign_id, primary_id


CATEGORY = CategoryDefinition(
    category_id="operations",
    label="交易、持仓与对账",
    description="接收外部账户事实，形成交易需求、成交匹配、组合分摊、交收、持仓、现金和对账例外。",
    order=100,
)


def _internal_field(*args, **kwargs):
    kwargs["source_mappable"] = False
    return field(*args, **kwargs)


def _table(
    table_id: str,
    label: str,
    description: str,
    grain: str,
    primary_key: tuple[str, ...],
    fields: tuple,
    *,
    source_mappable: bool,
    update_strategy: str = "append",
) -> TableDefinition:
    return TableDefinition(
        table_id=table_id,
        category_id=CATEGORY.category_id,
        label=label,
        description=description,
        layer="canonical" if source_mappable else "control",
        storage_engine="sqlite",
        storage_location="data/platform.db",
        delivery_phase="next",
        grain=grain,
        primary_key=primary_key,
        update_strategy=update_strategy,  # type: ignore[arg-type]
        fields=fields,
        source_mappable=source_mappable,
        pit_supported=True,
    )


TABLES = (
    _table(
        "operations.import_batch",
        "外部文件导入批次",
        "登记 Excel、CSV、对账单、成交、确认、持仓和现金文件的原始来源与处理状态。",
        "每次外部文件导入一条记录",
        ("import_batch_id",),
        (
            primary_id("import_batch_id", "导入批次 ID", "外部文件导入稳定标识。"),
            foreign_id("workspace_id", "工作空间 ID", "portfolio.workspace.workspace_id", "导入所属工作空间。"),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "文件对应账户；多账户文件可为空。", nullable=True),
            _internal_field("data_source_id", "数据源 ID", "string", "文件或机构数据源。", reference="governance.data_source.data_source_id"),
            _internal_field("file_name", "文件名", "string", "原始文件名。", nullable=False),
            _internal_field("file_type", "文件类型", "string", "文件承载的数据类型。", nullable=False, enum_values=("TRANSACTION", "EXECUTION", "CONFIRMATION", "SETTLEMENT", "POSITION", "CASH", "MIXED")),
            _internal_field("storage_uri", "原始文件地址", "string", "不可变原始文件地址。", nullable=False),
            _internal_field("checksum", "文件校验和", "string", "原始文件内容校验和。", nullable=False, role="audit"),
            _internal_field("received_at", "接收时间", "timestamp[us, UTC]", "平台接收文件时间。", nullable=False, role="audit"),
            _internal_field("statement_start_date", "账单开始日", "date32", "文件覆盖的业务起始日期。", role="observation_time"),
            _internal_field("statement_end_date", "账单结束日", "date32", "文件覆盖的业务结束日期。", role="observation_time"),
            _internal_field("mapping_version", "映射版本", "string", "解析该文件使用的映射版本。", nullable=False),
            _internal_field("row_count", "原始行数", "int64", "文件原始数据行数。", nullable=False, role="measure", unit="row"),
            _internal_field("accepted_rows", "接受行数", "int64", "成功标准化的行数。", nullable=False, role="measure", unit="row"),
            _internal_field("rejected_rows", "拒绝行数", "int64", "进入异常池的行数。", nullable=False, role="measure", unit="row"),
            _internal_field("status", "导入状态", "string", "批次处理状态。", nullable=False, enum_values=("RECEIVED", "PROCESSING", "SUCCEEDED", "PARTIAL", "FAILED", "REVERSED")),
            _internal_field("error_summary", "错误摘要", "string", "导入失败或部分成功说明。"),
            *control_audit_fields(),
        ),
        source_mappable=False,
    ),
    _table(
        "operations.external_transaction",
        "外部账户交易流水",
        "标准化银行、券商、销售机构和托管系统的账户级业务流水，保留原始行号和外部标识。",
        "每个外部账户业务流水事件、数据源和修订版本一条记录",
        ("external_transaction_id", "source_id", "revision"),
        (
            primary_id("external_transaction_id", "外部交易 ID", "平台生成的稳定外部事实标识。"),
            foreign_id("import_batch_id", "导入批次 ID", "operations.import_batch.import_batch_id", "来源文件导入批次。", nullable=True),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "流水所在真实账户。", source_mappable=False),
            field("source_transaction_id", "来源交易 ID", "string", "外部机构交易或流水标识。", nullable=False),
            field("source_row_number", "来源行号", "int64", "原始文件行号或接口记录序号。", role="audit"),
            field("business_type", "业务类型", "string", "外部业务事件类型。", nullable=False, enum_values=("BUY", "SELL", "SUBSCRIPTION", "REDEMPTION", "DIVIDEND", "INTEREST", "FEE", "TAX", "DEPOSIT", "WITHDRAWAL", "TRANSFER", "CORPORATE_ACTION", "OTHER")),
            field("trade_date", "交易日期", "date32", "指令或成交所属交易日期。", role="observation_time"),
            field("confirmation_date", "确认日期", "date32", "基金份额或交易确认日期。", role="observation_time"),
            field("settlement_date", "交收日期", "date32", "资金或证券实际交收日期。", role="observation_time"),
            field("booking_date", "记账日期", "date32", "业务事实应进入账簿的日期。", nullable=False, role="observation_time"),
            field("available_at", "最早可得时间", "timestamp[us, UTC]", "平台或机构最早可提供该流水的时间。", role="available_time"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "已解析交易标的。", nullable=True, source_mappable=False),
            field("instrument_external_code", "外部标的代码", "string", "来源中的标的代码。"),
            field("quantity", "数量", "decimal128(38, 10)", "交易、申赎或变动数量。", role="measure", unit="base_unit"),
            field("price", "价格或净值", "decimal128(38, 10)", "成交价格或确认净值。", role="measure", unit="currency/base_unit"),
            field("gross_amount", "交易总额", "decimal128(38, 6)", "费用税费前交易金额。", role="measure", unit="currency"),
            field("fee_amount", "费用", "decimal128(38, 6)", "交易或申赎费用。", role="measure", unit="currency"),
            field("tax_amount", "税费", "decimal128(38, 6)", "税金和政府费用。", role="measure", unit="currency"),
            field("net_amount", "净金额", "decimal128(38, 6)", "账户实际收付净金额。", nullable=False, role="measure", unit="currency"),
            field("currency", "币种", "string", "金额和价格币种。", nullable=False, unit="ISO-4217"),
            field("cash_flow_class", "现金流属性", "string", "外部资金流、内部交易或收益费用。", nullable=False, enum_values=("EXTERNAL_FLOW", "INTERNAL_TRADE", "INCOME", "EXPENSE", "TRANSFER")),
            field("status", "业务状态", "string", "待确认、已确认、已结算、取消或冲销。", nullable=False, enum_values=("PENDING", "CONFIRMED", "SETTLED", "CANCELLED", "REVERSED")),
            field("reversal_of_transaction_id", "原交易 ID", "string", "冲销记录对应的原外部交易。", reference="operations.external_transaction.external_transaction_id"),
            field("description", "摘要", "string", "来源流水摘要。"),
            _internal_field("source_id", "数据源 ID", "string", "来源数据源。", nullable=False, role="primary_key", reference="governance.data_source.data_source_id"),
            _internal_field("source_record_hash", "来源记录哈希", "string", "原始记录哈希。", nullable=False, role="audit"),
            _internal_field("revision", "修订序号", "int64", "同一来源交易的修订序号。", nullable=False, role="primary_key"),
            _internal_field("ingested_at", "采集时间", "timestamp[us, UTC]", "平台取得该记录的时间。", nullable=False, role="audit"),
        ),
        source_mappable=True,
    ),
    _table(
        "operations.trade_requirement",
        "组合交易需求",
        "根据真实持仓、现金和生效目标配置计算组合级买卖或申赎需求，不代表真实委托。",
        "每次测算中每个组合和标的一条交易需求",
        ("trade_requirement_id",),
        (
            primary_id("trade_requirement_id", "交易需求 ID", "组合级需求稳定标识。"),
            _internal_field("calculation_run_id", "测算运行 ID", "string", "同一次再平衡测算标识。", nullable=False),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "产生需求的真实组合。"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "需要买卖或申赎的产品。"),
            _internal_field("decision_date", "决策日期", "date32", "需求测算决策日期。", nullable=False, role="observation_time"),
            _internal_field("target_binding_id", "目标绑定 ID", "string", "测算使用的生效目标版本。", reference="portfolio.target_binding.target_binding_id"),
            _internal_field("current_quantity", "当前数量", "decimal128(38, 10)", "测算时已核对数量。", nullable=False, role="measure", unit="base_unit"),
            _internal_field("current_value", "当前市值", "decimal128(38, 6)", "测算时当前市值。", nullable=False, role="measure", unit="currency"),
            _internal_field("target_weight", "目标权重", "float64", "目标配置权重。", nullable=False, role="measure", unit="decimal"),
            _internal_field("target_value", "目标市值", "decimal128(38, 6)", "目标权重对应市值。", nullable=False, role="measure", unit="currency"),
            _internal_field("required_quantity", "需求数量", "decimal128(38, 10)", "正数买入/申购，负数卖出/赎回。", nullable=False, role="measure", unit="base_unit"),
            _internal_field("required_amount", "需求金额", "decimal128(38, 6)", "预计交易净额。", nullable=False, role="measure", unit="currency"),
            _internal_field("currency", "币种", "string", "测算金额币种。", nullable=False, unit="ISO-4217"),
            _internal_field("reason_code", "触发原因", "string", "周期、偏离、现金流或风险事件。", nullable=False, enum_values=("PERIODIC", "DRIFT", "CASH_FLOW", "RISK_EVENT", "MANUAL")),
            _internal_field("pretrade_status", "前置检查状态", "string", "需求是否通过交易前检查。", nullable=False, enum_values=("PENDING", "PASSED", "BLOCKED", "WARNING")),
            _internal_field("constraint_messages_json", "约束说明", "json", "现金、流动性、限额和产品状态检查结果。", nullable=False),
            *control_audit_fields(),
        ),
        source_mappable=False,
    ),
    _table(
        "operations.trade_plan_version",
        "合并交易计划版本",
        "合并或冲抵同一资产主体多个组合的交易需求，保存原始需求和预分摊版本。",
        "每个交易计划版本一条记录",
        ("trade_plan_version_id",),
        (
            primary_id("trade_plan_version_id", "交易计划版本 ID", "不可变交易计划版本标识。"),
            _internal_field("trade_plan_id", "交易计划 ID", "string", "跨版本稳定交易计划标识。", nullable=False),
            _internal_field("version", "版本号", "int64", "交易计划递增版本。", nullable=False),
            foreign_id("asset_owner_id", "资产主体 ID", "portfolio.asset_owner.asset_owner_id", "交易计划所属资产主体。"),
            _internal_field("decision_date", "决策日期", "date32", "计划决策日期。", nullable=False, role="observation_time"),
            _internal_field("execution_window_start", "执行窗口开始", "timestamp[us, UTC]", "计划允许的最早执行时间。", role="effective_time"),
            _internal_field("execution_window_end", "执行窗口结束", "timestamp[us, UTC]", "计划允许的最晚执行时间。", role="effective_time"),
            _internal_field("aggregation_policy_json", "合并规则", "json", "需求合并、冲抵和舍入规则。", nullable=False),
            _internal_field("preallocation_policy_json", "预分摊规则", "json", "成交前组合预分摊规则。", nullable=False),
            _internal_field("status", "计划状态", "string", "草稿、冻结、已发送外部、已完成或取消。", nullable=False, enum_values=("DRAFT", "FROZEN", "EXTERNAL_SENT", "PARTIAL", "COMPLETED", "CANCELLED")),
            _internal_field("content_hash", "计划哈希", "string", "需求、规则和预分摊内容哈希。", nullable=False, role="audit"),
            _internal_field("frozen_at", "冻结时间", "timestamp[us, UTC]", "计划不再修改的时间。", role="audit"),
            *control_audit_fields(),
        ),
        source_mappable=False,
    ),
    _table(
        "operations.trade_plan_line",
        "合并交易计划明细",
        "保存按外部账户和产品汇总后的交易方向、数量、金额及来源需求。",
        "每个交易计划版本中的每个账户和标的一条明细",
        ("trade_plan_version_id", "external_account_id", "instrument_id"),
        (
            foreign_id("trade_plan_version_id", "交易计划版本 ID", "operations.trade_plan_version.trade_plan_version_id", "所属交易计划版本。"),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "计划执行账户。"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "计划交易标的。"),
            _internal_field("side", "方向", "string", "买入、卖出、申购或赎回。", nullable=False, enum_values=("BUY", "SELL", "SUBSCRIBE", "REDEEM")),
            _internal_field("planned_quantity", "计划数量", "decimal128(38, 10)", "计划执行数量。", role="measure", unit="base_unit"),
            _internal_field("planned_amount", "计划金额", "decimal128(38, 6)", "计划执行金额。", role="measure", unit="currency"),
            _internal_field("currency", "币种", "string", "计划金额币种。", nullable=False, unit="ISO-4217"),
            _internal_field("requirement_ids_json", "来源需求", "json", "构成该计划明细的组合交易需求 ID。", nullable=False),
            _internal_field("preallocation_json", "预分摊", "json", "计划执行前的组合分摊比例。", nullable=False),
            _internal_field("execution_status", "执行状态", "string", "计划明细执行状态。", nullable=False, enum_values=("PENDING", "PARTIAL", "COMPLETED", "CANCELLED")),
            *control_audit_fields(),
        ),
        source_mappable=False,
    ),
    _table(
        "operations.trade_execution",
        "外部成交",
        "标准化券商成交、基金确认或其他实际执行事实。",
        "每个外部成交或确认记录、数据源和修订版本一条记录",
        ("trade_execution_id", "source_id", "revision"),
        (
            primary_id("trade_execution_id", "成交 ID", "平台生成的稳定成交标识。"),
            foreign_id("import_batch_id", "导入批次 ID", "operations.import_batch.import_batch_id", "成交来源文件。", nullable=True),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "成交所在账户。", source_mappable=False),
            field("source_execution_id", "来源成交 ID", "string", "外部机构成交或确认编号。", nullable=False),
            field("source_order_id", "来源委托 ID", "string", "外部机构委托编号。"),
            field("execution_type", "执行类型", "string", "交易所成交或场外基金确认。", nullable=False, enum_values=("EXCHANGE_TRADE", "FUND_CONFIRMATION", "TRANSFER", "OTHER")),
            field("trade_date", "交易日期", "date32", "成交或申请日期。", nullable=False, role="observation_time"),
            field("execution_at", "成交时间", "timestamp[us, UTC]", "实际成交时点。", role="observation_time"),
            field("confirmation_date", "确认日期", "date32", "份额或成交确认日期。", role="observation_time"),
            field("settlement_date", "交收日期", "date32", "预计或实际交收日期。", role="observation_time"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "已解析成交标的。", nullable=True, source_mappable=False),
            field("instrument_external_code", "外部标的代码", "string", "来源中的标的代码。"),
            field("side", "方向", "string", "买卖或申赎方向。", nullable=False, enum_values=("BUY", "SELL", "SUBSCRIBE", "REDEEM")),
            field("quantity", "成交数量", "decimal128(38, 10)", "实际成交或确认份额。", nullable=False, role="measure", unit="base_unit"),
            field("price", "成交价格", "decimal128(38, 10)", "成交价格或确认净值。", role="measure", unit="currency/base_unit"),
            field("gross_amount", "成交总额", "decimal128(38, 6)", "费用税费前成交金额。", role="measure", unit="currency"),
            field("fee_amount", "费用", "decimal128(38, 6)", "实际执行费用。", role="measure", unit="currency"),
            field("tax_amount", "税费", "decimal128(38, 6)", "实际税费。", role="measure", unit="currency"),
            field("net_amount", "净金额", "decimal128(38, 6)", "账户实际收付净额。", nullable=False, role="measure", unit="currency"),
            field("currency", "币种", "string", "成交金额币种。", nullable=False, unit="ISO-4217"),
            field("status", "成交状态", "string", "成交生命周期状态。", nullable=False, enum_values=("PENDING", "CONFIRMED", "SETTLED", "CANCELLED", "REVERSED")),
            _internal_field("source_id", "数据源 ID", "string", "成交来源。", nullable=False, role="primary_key", reference="governance.data_source.data_source_id"),
            _internal_field("source_record_hash", "来源记录哈希", "string", "原始成交记录哈希。", nullable=False, role="audit"),
            _internal_field("revision", "修订序号", "int64", "同一来源成交修订序号。", nullable=False, role="primary_key"),
            _internal_field("ingested_at", "采集时间", "timestamp[us, UTC]", "平台取得成交记录的时间。", nullable=False, role="audit"),
        ),
        source_mappable=True,
    ),
    _table(
        "operations.execution_match",
        "成交匹配",
        "把实际外部成交匹配到交易计划明细、账户流水或待认领池。",
        "每个成交与计划明细的一条匹配关系",
        ("execution_match_id",),
        (
            primary_id("execution_match_id", "匹配 ID", "成交匹配稳定标识。"),
            foreign_id("trade_execution_id", "成交 ID", "operations.trade_execution.trade_execution_id", "被匹配的实际成交。"),
            foreign_id("trade_plan_version_id", "交易计划版本 ID", "operations.trade_plan_version.trade_plan_version_id", "匹配的交易计划版本。", nullable=True),
            foreign_id("external_transaction_id", "外部交易 ID", "operations.external_transaction.external_transaction_id", "匹配的账户流水。", nullable=True),
            _internal_field("match_method", "匹配方式", "string", "外部 ID、规则、金额日期或人工匹配。", nullable=False, enum_values=("EXTERNAL_ID", "RULE", "DATE_AMOUNT", "MANUAL", "UNMATCHED")),
            _internal_field("match_confidence", "匹配置信度", "float64", "自动匹配置信度。", nullable=False, unit="decimal"),
            _internal_field("matched_quantity", "匹配数量", "decimal128(38, 10)", "该关系覆盖的成交数量。", role="measure", unit="base_unit"),
            _internal_field("matched_amount", "匹配金额", "decimal128(38, 6)", "该关系覆盖的成交金额。", role="measure", unit="currency"),
            _internal_field("status", "匹配状态", "string", "匹配是否已确认。", nullable=False, enum_values=("PROPOSED", "CONFIRMED", "REJECTED", "UNMATCHED")),
            _internal_field("confirmed_at", "确认时间", "timestamp[us, UTC]", "人工或规则确认时间。", role="audit"),
            _internal_field("notes", "说明", "string", "匹配说明。"),
            *control_audit_fields(),
        ),
        source_mappable=False,
    ),
    _table(
        "operations.portfolio_allocation",
        "成交组合分摊",
        "把账户级成交按冻结规则分配到真实组合，确保数量、金额、费用和税费守恒。",
        "每个成交分配到每个组合的一条记录",
        ("portfolio_allocation_id",),
        (
            primary_id("portfolio_allocation_id", "分摊 ID", "成交组合分摊稳定标识。"),
            foreign_id("trade_execution_id", "成交 ID", "operations.trade_execution.trade_execution_id", "被分摊的实际成交。"),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "获得成交分配的组合。"),
            _internal_field("trade_requirement_id", "交易需求 ID", "string", "分摊对应的原组合交易需求。", reference="operations.trade_requirement.trade_requirement_id"),
            _internal_field("allocated_quantity", "分摊数量", "decimal128(38, 10)", "分配给组合的成交数量。", nullable=False, role="measure", unit="base_unit"),
            _internal_field("allocated_gross_amount", "分摊总额", "decimal128(38, 6)", "分配给组合的成交总额。", nullable=False, role="measure", unit="currency"),
            _internal_field("allocated_fee", "分摊费用", "decimal128(38, 6)", "分配给组合的费用。", nullable=False, role="measure", unit="currency"),
            _internal_field("allocated_tax", "分摊税费", "decimal128(38, 6)", "分配给组合的税费。", nullable=False, role="measure", unit="currency"),
            _internal_field("allocated_net_amount", "分摊净额", "decimal128(38, 6)", "分配给组合的净金额。", nullable=False, role="measure", unit="currency"),
            _internal_field("currency", "币种", "string", "分摊金额币种。", nullable=False, unit="ISO-4217"),
            _internal_field("allocation_method", "分摊方式", "string", "预分摊、按需求比例、人工或余数调整。", nullable=False, enum_values=("PREALLOCATION", "PRO_RATA", "MANUAL", "RESIDUAL")),
            _internal_field("allocation_version", "分摊版本", "int64", "同一成交的分摊修订号。", nullable=False),
            _internal_field("status", "分摊状态", "string", "草稿、已确认或已冲销。", nullable=False, enum_values=("DRAFT", "CONFIRMED", "REVERSED")),
            _internal_field("confirmed_at", "确认时间", "timestamp[us, UTC]", "分摊确认时间。", role="audit"),
            *control_audit_fields(),
        ),
        source_mappable=False,
    ),
    _table(
        "operations.cash_movement",
        "现金流水",
        "统一账户和组合层资金划入划出、交易交收、费用、税费、分红和利息现金变动。",
        "每个现金变动事实、数据源和修订版本一条记录",
        ("cash_movement_id", "source_id", "revision"),
        (
            primary_id("cash_movement_id", "现金流水 ID", "平台生成的稳定现金流水标识。"),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "现金实际发生账户。", source_mappable=False),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "已分配组合；未认领时为空。", nullable=True, source_mappable=False),
            field("source_cash_id", "来源现金流水 ID", "string", "银行或机构现金流水标识。", nullable=False),
            field("movement_type", "现金类型", "string", "现金变动业务类型。", nullable=False, enum_values=("DEPOSIT", "WITHDRAWAL", "TRADE_SETTLEMENT", "DIVIDEND", "INTEREST", "FEE", "TAX", "TRANSFER", "OTHER")),
            field("value_date", "资金价值日", "date32", "资金开始计息或可使用日期。", nullable=False, role="observation_time"),
            field("transaction_date", "交易日期", "date32", "现金变动发起日期。", role="observation_time"),
            field("available_at", "最早可得时间", "timestamp[us, UTC]", "流水最早可被平台取得的时间。", role="available_time"),
            field("amount", "金额", "decimal128(38, 6)", "正数流入、负数流出。", nullable=False, role="measure", unit="currency"),
            field("currency", "币种", "string", "现金流水币种。", nullable=False, unit="ISO-4217"),
            field("external_flow_flag", "外部现金流", "bool", "是否属于组合绩效计算中的外部现金流。", nullable=False),
            field("related_execution_id", "关联成交 ID", "string", "交易交收对应成交。", reference="operations.trade_execution.trade_execution_id"),
            field("related_transaction_id", "关联外部交易 ID", "string", "对应账户业务流水。", reference="operations.external_transaction.external_transaction_id"),
            field("status", "现金状态", "string", "预计、在途、已入账、取消或冲销。", nullable=False, enum_values=("EXPECTED", "IN_TRANSIT", "POSTED", "CANCELLED", "REVERSED")),
            field("description", "摘要", "string", "现金流水摘要。"),
            _internal_field("source_id", "数据源 ID", "string", "现金流水来源。", nullable=False, role="primary_key", reference="governance.data_source.data_source_id"),
            _internal_field("source_record_hash", "来源记录哈希", "string", "原始现金记录哈希。", nullable=False, role="audit"),
            _internal_field("revision", "修订序号", "int64", "同一来源现金记录修订号。", nullable=False, role="primary_key"),
            _internal_field("ingested_at", "采集时间", "timestamp[us, UTC]", "平台取得该记录的时间。", nullable=False, role="audit"),
        ),
        source_mappable=True,
    ),
    _table(
        "operations.settlement",
        "交收记录",
        "跟踪交易或申赎的证券、份额和资金交收状态。",
        "每个成交的一条资产或现金交收记录",
        ("settlement_id",),
        (
            primary_id("settlement_id", "交收 ID", "交收记录稳定标识。"),
            foreign_id("trade_execution_id", "成交 ID", "operations.trade_execution.trade_execution_id", "交收对应成交。"),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "交收所在账户。"),
            field("settlement_leg", "交收腿", "string", "证券、份额或现金。", nullable=False, enum_values=("SECURITY", "FUND_SHARE", "CASH")),
            field("expected_settlement_date", "预计交收日", "date32", "根据产品和市场规则推算的日期。", nullable=False, role="observation_time"),
            field("actual_settlement_date", "实际交收日", "date32", "实际完成交收日期。", role="observation_time"),
            field("quantity", "交收数量", "decimal128(38, 10)", "证券或基金份额交收数量。", role="measure", unit="base_unit"),
            field("amount", "交收金额", "decimal128(38, 6)", "现金交收金额。", role="measure", unit="currency"),
            field("currency", "币种", "string", "交收金额币种。", unit="ISO-4217"),
            field("status", "交收状态", "string", "预计、部分、完成、失败或取消。", nullable=False, enum_values=("EXPECTED", "PARTIAL", "SETTLED", "FAILED", "CANCELLED")),
            field("failure_reason", "失败原因", "string", "交收失败说明。"),
            field("source_id", "数据源 ID", "string", "交收状态来源。", reference="governance.data_source.data_source_id"),
            field("available_at", "最早可得时间", "timestamp[us, UTC]", "交收状态最早可得时间。", role="available_time"),
            *control_audit_fields(),
        ),
        source_mappable=True,
        update_strategy="upsert",
    ),
    _table(
        "operations.position_lot",
        "持仓成本批次",
        "按组合、账户和交易批次维护数量、成本、已实现损益和剩余数量。",
        "每个组合、账户、标的和成本批次一条记录",
        ("position_lot_id",),
        (
            primary_id("position_lot_id", "成本批次 ID", "持仓成本批次稳定标识。"),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "持仓所属组合。"),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "持仓所在账户。"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "持仓标的。"),
            _internal_field("opening_execution_id", "开仓成交 ID", "string", "创建成本批次的成交。", reference="operations.trade_execution.trade_execution_id"),
            _internal_field("acquisition_date", "取得日期", "date32", "成本批次取得日期。", nullable=False, role="observation_time"),
            _internal_field("original_quantity", "原始数量", "decimal128(38, 10)", "批次初始数量。", nullable=False, role="measure", unit="base_unit"),
            _internal_field("remaining_quantity", "剩余数量", "decimal128(38, 10)", "尚未处置数量。", nullable=False, role="measure", unit="base_unit"),
            _internal_field("unit_cost", "单位成本", "decimal128(38, 10)", "含指定费用口径的单位成本。", nullable=False, role="measure", unit="currency/base_unit"),
            _internal_field("total_cost", "总成本", "decimal128(38, 6)", "剩余持仓账面总成本。", nullable=False, role="measure", unit="currency"),
            _internal_field("realized_pnl", "已实现损益", "decimal128(38, 6)", "该批次累计已实现损益。", nullable=False, role="measure", unit="currency"),
            _internal_field("currency", "币种", "string", "成本和损益币种。", nullable=False, unit="ISO-4217"),
            _internal_field("cost_method", "成本方法", "string", "FIFO、移动平均或指定批次。", nullable=False, enum_values=("FIFO", "AVERAGE", "SPECIFIC")),
            _internal_field("status", "批次状态", "string", "开放或已关闭。", nullable=False, enum_values=("OPEN", "CLOSED")),
            *control_audit_fields(),
        ),
        source_mappable=False,
    ),
    _table(
        "operations.position_snapshot",
        "持仓快照",
        "保存账户和组合在指定时点的数量、冻结、在途和来源类型，用于 IBOR 与外部对账。",
        "每个快照时点、账户、组合、标的和来源一条记录",
        ("position_snapshot_id",),
        (
            primary_id("position_snapshot_id", "持仓快照 ID", "持仓快照稳定标识。"),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "持仓所在账户。", source_mappable=False),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "已分配组合；账户级外部快照可为空。", nullable=True, source_mappable=False),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "持仓标的。", source_mappable=False),
            field("snapshot_at", "快照时间", "timestamp[us, UTC]", "持仓状态对应时点。", nullable=False, role="observation_time"),
            field("position_source", "持仓来源", "string", "外部机构、IBOR 或组合子账。", nullable=False, enum_values=("EXTERNAL", "IBOR", "PORTFOLIO_SUBLEDGER")),
            field("settled_quantity", "已交收数量", "decimal128(38, 10)", "已完成交收可用数量。", nullable=False, role="measure", unit="base_unit"),
            field("unsettled_quantity", "未交收数量", "decimal128(38, 10)", "已成交未交收数量。", nullable=False, role="measure", unit="base_unit"),
            field("blocked_quantity", "冻结数量", "decimal128(38, 10)", "冻结或不可用数量。", nullable=False, role="measure", unit="base_unit"),
            field("total_quantity", "总数量", "decimal128(38, 10)", "已交收、未交收和冻结数量合计。", nullable=False, role="measure", unit="base_unit"),
            field("average_cost", "平均成本", "decimal128(38, 10)", "来源报告或内部计算平均成本。", role="measure", unit="currency/base_unit"),
            field("market_value", "市值", "decimal128(38, 6)", "快照时点市值。", role="measure", unit="currency"),
            field("currency", "币种", "string", "成本和市值币种。", nullable=False, unit="ISO-4217"),
            field("available_at", "最早可得时间", "timestamp[us, UTC]", "该快照最早可用时间。", role="available_time"),
            _internal_field("source_id", "数据源 ID", "string", "外部快照来源；内部快照可为空。", reference="governance.data_source.data_source_id"),
            _internal_field("source_record_hash", "来源记录哈希", "string", "外部快照行哈希。", role="audit"),
            _internal_field("ingested_at", "采集时间", "timestamp[us, UTC]", "快照进入平台时间。", role="audit"),
        ),
        source_mappable=True,
    ),
    _table(
        "operations.cash_balance",
        "现金余额快照",
        "保存账户和组合在指定时点的可用、冻结、在途和总现金余额。",
        "每个快照时点、账户、组合、币种和来源一条记录",
        ("cash_balance_id",),
        (
            primary_id("cash_balance_id", "现金余额 ID", "现金余额快照稳定标识。"),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "现金所在账户。", source_mappable=False),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "已分配组合；账户级快照可为空。", nullable=True, source_mappable=False),
            field("snapshot_at", "快照时间", "timestamp[us, UTC]", "现金余额对应时点。", nullable=False, role="observation_time"),
            field("balance_source", "余额来源", "string", "外部机构、IBOR 或组合子账。", nullable=False, enum_values=("EXTERNAL", "IBOR", "PORTFOLIO_SUBLEDGER")),
            field("currency", "币种", "string", "现金币种。", nullable=False, unit="ISO-4217"),
            field("available_balance", "可用余额", "decimal128(38, 6)", "可立即使用现金。", nullable=False, role="measure", unit="currency"),
            field("blocked_balance", "冻结余额", "decimal128(38, 6)", "冻结或受限现金。", nullable=False, role="measure", unit="currency"),
            field("in_transit_balance", "在途余额", "decimal128(38, 6)", "预计流入减预计流出的在途净额。", nullable=False, role="measure", unit="currency"),
            field("total_balance", "总余额", "decimal128(38, 6)", "总现金余额。", nullable=False, role="measure", unit="currency"),
            field("available_at", "最早可得时间", "timestamp[us, UTC]", "余额快照最早可用时间。", role="available_time"),
            _internal_field("source_id", "数据源 ID", "string", "外部余额来源；内部余额可为空。", reference="governance.data_source.data_source_id"),
            _internal_field("source_record_hash", "来源记录哈希", "string", "外部余额记录哈希。", role="audit"),
            _internal_field("ingested_at", "采集时间", "timestamp[us, UTC]", "余额进入平台时间。", role="audit"),
        ),
        source_mappable=True,
    ),
    _table(
        "operations.corporate_action",
        "公司行动",
        "统一分红、拆并股、配股、换股、到期、赎回和其他影响持仓或现金的公司行动。",
        "每个公司行动事件、数据源和修订版本一条记录",
        ("corporate_action_id", "source_id", "revision"),
        (
            primary_id("corporate_action_id", "公司行动 ID", "公司行动稳定标识。"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "发生公司行动的标的。", source_mappable=False),
            field("action_type", "行动类型", "string", "公司行动类型。", nullable=False, enum_values=("CASH_DIVIDEND", "STOCK_DIVIDEND", "SPLIT", "REVERSE_SPLIT", "RIGHTS", "MERGER", "SPINOFF", "MATURITY", "REDEMPTION", "OTHER")),
            field("announced_at", "公告时间", "timestamp[us, UTC]", "公司行动公告时间。", role="available_time"),
            field("record_date", "登记日", "date32", "权益登记日。", role="observation_time"),
            field("ex_date", "除权除息日", "date32", "除权除息日期。", role="observation_time"),
            field("pay_date", "支付日", "date32", "现金或证券支付日期。", role="observation_time"),
            field("available_at", "最早可得时间", "timestamp[us, UTC]", "历史研究最早可用时间。", role="available_time"),
            field("cash_per_unit", "单位现金", "decimal128(38, 10)", "每单位现金权益。", role="measure", unit="currency/base_unit"),
            field("quantity_ratio", "数量比例", "float64", "拆股、送股或换股比例。", role="measure", unit="ratio"),
            field("currency", "币种", "string", "现金权益币种。", unit="ISO-4217"),
            field("status", "事件状态", "string", "公告、已确认、已完成或取消。", nullable=False, enum_values=("ANNOUNCED", "CONFIRMED", "COMPLETED", "CANCELLED")),
            field("details_json", "事件详情", "json", "复杂公司行动条款。"),
            _internal_field("source_id", "数据源 ID", "string", "公司行动来源。", nullable=False, role="primary_key", reference="governance.data_source.data_source_id"),
            _internal_field("source_record_hash", "来源记录哈希", "string", "原始公司行动记录哈希。", nullable=False, role="audit"),
            _internal_field("revision", "修订序号", "int64", "同一来源事件修订号。", nullable=False, role="primary_key"),
            _internal_field("ingested_at", "采集时间", "timestamp[us, UTC]", "平台取得事件时间。", nullable=False, role="audit"),
        ),
        source_mappable=True,
    ),
    _table(
        "operations.reconciliation_case",
        "对账差异",
        "管理现金、持仓、成交、费用、估值和组合分摊的对账差异及处理过程。",
        "每个对账差异一条记录",
        ("reconciliation_case_id",),
        (
            primary_id("reconciliation_case_id", "差异 ID", "对账差异稳定标识。"),
            foreign_id("workspace_id", "工作空间 ID", "portfolio.workspace.workspace_id", "差异所属工作空间。"),
            foreign_id("asset_owner_id", "资产主体 ID", "portfolio.asset_owner.asset_owner_id", "差异所属资产主体。", nullable=True),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "差异对应外部账户。", nullable=True),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "差异对应组合。", nullable=True),
            _internal_field("reconciliation_type", "对账类型", "string", "现金、持仓、成交、费用、估值或分摊。", nullable=False, enum_values=("CASH", "POSITION", "TRANSACTION", "FEE", "VALUATION", "ALLOCATION")),
            _internal_field("as_of", "对账时点", "timestamp[us, UTC]", "本次对账的业务截止时点。", nullable=False, role="observation_time"),
            _internal_field("source_a_type", "A 侧来源", "string", "第一侧数据来源类型。", nullable=False),
            _internal_field("source_a_id", "A 侧记录 ID", "string", "第一侧记录或快照标识。", nullable=False),
            _internal_field("source_b_type", "B 侧来源", "string", "第二侧数据来源类型。", nullable=False),
            _internal_field("source_b_id", "B 侧记录 ID", "string", "第二侧记录或快照标识。", nullable=False),
            _internal_field("difference_quantity", "数量差异", "decimal128(38, 10)", "两侧数量差异。", role="measure", unit="base_unit"),
            _internal_field("difference_amount", "金额差异", "decimal128(38, 6)", "两侧金额差异。", role="measure", unit="currency"),
            _internal_field("currency", "币种", "string", "金额差异币种。", unit="ISO-4217"),
            _internal_field("severity", "严重级别", "string", "差异严重级别。", nullable=False, enum_values=("INFO", "WARNING", "ERROR", "BLOCKER")),
            _internal_field("status", "处理状态", "string", "待处理、调查中、已解决、已接受或已撤销。", nullable=False, enum_values=("OPEN", "INVESTIGATING", "RESOLVED", "ACCEPTED", "VOID")),
            _internal_field("reason_code", "差异原因", "string", "稳定差异原因代码。"),
            _internal_field("resolution", "处理说明", "string", "差异处理结论。"),
            _internal_field("resolved_at", "解决时间", "timestamp[us, UTC]", "差异关闭时间。", role="audit"),
            *control_audit_fields(),
        ),
        source_mappable=False,
        update_strategy="upsert",
    ),
)
