"""Asset-owner, external-account, and actual-portfolio master contracts."""

from __future__ import annotations

from ..types import CategoryDefinition, TableDefinition, control_audit_fields, field, foreign_id, primary_id


CATEGORY = CategoryDefinition(
    category_id="portfolio",
    label="资产主体、账户与组合",
    description="定义工作空间、资产所有者、所有权、外部账户、真实组合、账户关系、责任人与目标版本。",
    order=90,
)


def _internal_field(*args, **kwargs):
    kwargs["source_mappable"] = False
    return field(*args, **kwargs)


def _table(
    table_id: str,
    label: str,
    description: str,
    grain: str,
    primary_key: tuple[str, ...],
    fields: tuple,
    *,
    source_mappable: bool = False,
    update_strategy: str = "upsert",
) -> TableDefinition:
    return TableDefinition(
        table_id=table_id,
        category_id=CATEGORY.category_id,
        label=label,
        description=description,
        layer="control",
        storage_engine="sqlite",
        storage_location="data/platform.db",
        delivery_phase="next",
        grain=grain,
        primary_key=primary_key,
        update_strategy=update_strategy,  # type: ignore[arg-type]
        fields=fields,
        source_mappable=source_mappable,
        pit_supported=True,
    )


TABLES = (
    _table(
        "portfolio.workspace",
        "工作空间",
        "平台最高层的数据、权限和研究隔离边界。",
        "每个工作空间一条记录",
        ("workspace_id",),
        (
            primary_id("workspace_id", "工作空间 ID", "工作空间稳定标识。"),
            _internal_field("name", "工作空间名称", "string", "工作空间名称。", nullable=False),
            _internal_field("base_currency", "本位币", "string", "工作空间默认汇总币种。", nullable=False, unit="ISO-4217"),
            _internal_field("timezone", "默认时区", "string", "工作空间默认 IANA 时区。", nullable=False),
            _internal_field("status", "状态", "string", "工作空间状态。", nullable=False, enum_values=("ACTIVE", "SUSPENDED", "ARCHIVED")),
            _internal_field("settings_json", "工作空间设置", "json", "默认口径、权限和展示设置。"),
            *control_audit_fields(),
        ),
    ),
    _table(
        "portfolio.asset_owner",
        "资产主体",
        "个人、企业、信托或家族持有实体，是资产所有权、税务和核算边界。",
        "每个资产主体的一段有效主数据记录",
        ("asset_owner_id", "valid_from"),
        (
            primary_id("asset_owner_id", "资产主体 ID", "平台生成的稳定资产主体标识。"),
            foreign_id("workspace_id", "工作空间 ID", "portfolio.workspace.workspace_id", "所属工作空间。"),
            _internal_field("owner_type", "主体类型", "string", "资产主体法律或自然人类型。", nullable=False, enum_values=("INDIVIDUAL", "COMPANY", "TRUST", "FOUNDATION", "FAMILY_ENTITY", "OTHER")),
            _internal_field("legal_name", "法定名称", "string", "主体法定或正式名称。", nullable=False),
            _internal_field("short_name", "简称", "string", "内部使用简称。"),
            _internal_field("registration_number", "登记编号", "string", "身份证明、统一社会信用代码或其他登记编号的脱敏引用。"),
            _internal_field("domicile", "注册地", "string", "法律注册国家或地区。", unit="ISO-3166-1"),
            _internal_field("base_currency", "本位币", "string", "主体资产和账簿本位币。", nullable=False, unit="ISO-4217"),
            _internal_field("accounting_policy_code", "核算政策代码", "string", "适用于该主体的核算政策。"),
            _internal_field("tax_profile_code", "税务口径代码", "string", "适用于该主体的税务辅助口径。"),
            _internal_field("status", "主体状态", "string", "主体生命周期状态。", nullable=False, enum_values=("ACTIVE", "INACTIVE", "TERMINATED")),
            _internal_field("valid_from", "生效起始", "date32", "该主数据版本开始生效日期。", nullable=False, role="primary_key"),
            _internal_field("valid_to", "生效结束", "date32", "该主数据版本结束日期。", role="effective_time"),
            _internal_field("recorded_at", "记录时间", "timestamp[us, UTC]", "该版本进入平台的时间。", nullable=False, role="audit"),
            *control_audit_fields(),
        ),
        update_strategy="scd2",
    ),
    _table(
        "portfolio.ownership_relation",
        "主体所有权关系",
        "维护资产主体、个人、企业或家族实体之间的所有权和控制关系。",
        "每对主体的一段有效所有权或控制关系",
        ("ownership_relation_id",),
        (
            primary_id("ownership_relation_id", "关系 ID", "所有权关系稳定标识。"),
            foreign_id("workspace_id", "工作空间 ID", "portfolio.workspace.workspace_id", "所属工作空间。"),
            foreign_id("parent_owner_id", "上级主体 ID", "portfolio.asset_owner.asset_owner_id", "拥有或控制下级主体的资产主体。"),
            foreign_id("child_owner_id", "下级主体 ID", "portfolio.asset_owner.asset_owner_id", "被拥有或控制的资产主体。"),
            _internal_field("relation_type", "关系类型", "string", "所有权或控制关系。", nullable=False, enum_values=("OWNERSHIP", "CONTROL", "BENEFICIAL_INTEREST", "GUARANTEE", "OTHER")),
            _internal_field("ownership_ratio", "所有权比例", "float64", "小数制所有权或受益比例。", role="measure", unit="decimal"),
            _internal_field("voting_ratio", "表决权比例", "float64", "小数制表决权比例。", role="measure", unit="decimal"),
            _internal_field("valid_from", "生效起始", "date32", "关系开始生效日期。", nullable=False, role="effective_time"),
            _internal_field("valid_to", "生效结束", "date32", "关系结束日期。", role="effective_time"),
            _internal_field("notes", "说明", "string", "关系说明。"),
            *control_audit_fields(),
        ),
        update_strategy="scd2",
    ),
    _table(
        "portfolio.external_account",
        "外部账户",
        "银行、券商、基金销售、托管或现金账户主档。",
        "每个外部账户的一段有效主数据记录",
        ("external_account_id", "valid_from"),
        (
            primary_id("external_account_id", "外部账户 ID", "平台生成的稳定账户标识。"),
            foreign_id("workspace_id", "工作空间 ID", "portfolio.workspace.workspace_id", "所属工作空间。"),
            foreign_id("asset_owner_id", "资产主体 ID", "portfolio.asset_owner.asset_owner_id", "账户法律归属主体。"),
            foreign_id("institution_id", "机构 ID", "master.organization.organization_id", "开户银行、券商、销售机构或托管机构。", nullable=True, source_mappable=False),
            field("account_type", "账户类型", "string", "账户主要用途。", nullable=False, enum_values=("BROKERAGE", "BANK", "FUND_DISTRIBUTION", "CUSTODY", "CASH", "OTHER")),
            field("account_name", "账户名称", "string", "外部账户名称。", nullable=False),
            field("masked_account_number", "脱敏账号", "string", "仅保存脱敏账号或安全引用。"),
            field("currency", "账户币种", "string", "账户主币种。", nullable=False, unit="ISO-4217"),
            field("country_code", "开户国家或地区", "string", "账户所在地。", unit="ISO-3166-1"),
            field("purpose_code", "用途", "string", "交易、现金管理、托管、申赎等用途。"),
            field("data_connection_id", "数据连接 ID", "string", "后续外部接口连接标识。"),
            field("reconciliation_enabled", "启用对账", "bool", "是否纳入自动对账。", nullable=False),
            field("status", "账户状态", "string", "账户状态。", nullable=False, enum_values=("ACTIVE", "FROZEN", "CLOSED", "UNKNOWN")),
            field("valid_from", "生效起始", "date32", "账户主数据版本开始日期。", nullable=False, role="primary_key"),
            field("valid_to", "生效结束", "date32", "账户主数据版本结束日期。", role="effective_time"),
            _internal_field("recorded_at", "记录时间", "timestamp[us, UTC]", "该版本进入平台的时间。", nullable=False, role="audit"),
            _internal_field("source_id", "数据源 ID", "string", "账户主档来源；人工维护时为空。", reference="governance.data_source.data_source_id"),
            _internal_field("source_record_hash", "来源记录哈希", "string", "来源账户记录哈希。", role="audit"),
            _internal_field("ingested_at", "采集时间", "timestamp[us, UTC]", "来源账户主档取得时间。", role="audit"),
            *control_audit_fields(),
        ),
        source_mappable=True,
        update_strategy="scd2",
    ),
    _table(
        "portfolio.external_account_identifier",
        "外部账户标识映射",
        "系统内部保存来源账户代码与 external_account_id 的对照，由导入配置和身份解析维护；账户主档、交易和持仓才是外部导入的业务数据。",
        "每个数据源命名空间中的每个账户代码一段有效记录",
        ("source_id", "namespace", "external_code", "valid_from"),
        (
            foreign_id("source_id", "数据源 ID", "governance.data_source.data_source_id", "外部账户代码所属数据源。"),
            field("namespace", "代码空间", "string", "外部账户标识类型。", nullable=False),
            field("external_code", "外部账户代码", "string", "来源系统账户代码。", nullable=False),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "映射后的平台账户。"),
            field("mapping_method", "映射方式", "string", "账户映射方式。", nullable=False, enum_values=("EXACT", "MANUAL", "RULE")),
            field("confidence", "映射置信度", "float64", "映射置信度。", nullable=False, unit="decimal"),
            field("valid_from", "生效起始", "date32", "映射开始生效日期。", nullable=False, role="primary_key"),
            field("valid_to", "生效结束", "date32", "映射结束日期。", role="effective_time"),
            _internal_field("recorded_at", "记录时间", "timestamp[us, UTC]", "映射写入时间。", nullable=False, role="audit"),
        ),
        source_mappable=False,
        update_strategy="scd2",
    ),
    _table(
        "portfolio.portfolio",
        "真实组合",
        "平台内部绩效、风险、责任和管理边界，不等同于外部基金法律主体。",
        "每个真实组合的一段有效主数据记录",
        ("portfolio_id", "valid_from"),
        (
            primary_id("portfolio_id", "组合 ID", "平台生成的稳定真实组合标识。"),
            foreign_id("workspace_id", "工作空间 ID", "portfolio.workspace.workspace_id", "所属工作空间。"),
            foreign_id("asset_owner_id", "资产主体 ID", "portfolio.asset_owner.asset_owner_id", "组合所属资产主体。"),
            _internal_field("portfolio_code", "组合代码", "string", "工作空间内唯一组合代码。", nullable=False),
            _internal_field("name", "组合名称", "string", "真实组合名称。", nullable=False),
            _internal_field("portfolio_type", "组合类型", "string", "策略、目标或资金用途类型。", nullable=False, enum_values=("INVESTMENT", "LIQUIDITY", "PENSION", "ENDOWMENT", "MODEL", "OTHER")),
            _internal_field("base_currency", "组合本位币", "string", "绩效与风险汇总币种。", nullable=False, unit="ISO-4217"),
            _internal_field("benchmark_instrument_id", "主要基准 ID", "string", "组合主要基准标的。", reference="master.instrument.instrument_id"),
            _internal_field("inception_date", "组合起始日", "date32", "组合管理绩效开始日期。", role="effective_time"),
            _internal_field("termination_date", "组合终止日", "date32", "组合终止日期。", role="effective_time"),
            _internal_field("status", "组合状态", "string", "组合生命周期状态。", nullable=False, enum_values=("PLANNING", "PENDING_ACTIVATION", "ACTIVE", "PAUSED", "LIQUIDATING", "TERMINATED")),
            _internal_field("valid_from", "生效起始", "date32", "组合主数据版本开始日期。", nullable=False, role="primary_key"),
            _internal_field("valid_to", "生效结束", "date32", "组合主数据版本结束日期。", role="effective_time"),
            _internal_field("recorded_at", "记录时间", "timestamp[us, UTC]", "主数据版本记录时间。", nullable=False, role="audit"),
            *control_audit_fields(),
        ),
        update_strategy="scd2",
    ),
    _table(
        "portfolio.account_portfolio_link",
        "账户—组合关系",
        "支持同一主体内账户与真实组合的多对多关系，并按用途和有效期版本化。",
        "每个账户与组合的一段有效关系",
        ("account_portfolio_link_id",),
        (
            primary_id("account_portfolio_link_id", "关系 ID", "账户组合关系稳定标识。"),
            foreign_id("external_account_id", "外部账户 ID", "portfolio.external_account.external_account_id", "关联的外部账户。"),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "关联的真实组合。"),
            _internal_field("link_type", "关系用途", "string", "交易、现金、托管、申赎或核算用途。", nullable=False, enum_values=("TRADING", "CASH", "CUSTODY", "SUBSCRIPTION", "ACCOUNTING", "OTHER")),
            _internal_field("allocation_priority", "分配优先级", "int64", "一个账户服务多个组合时的默认优先级。"),
            _internal_field("default_allocation_ratio", "默认分摊比例", "float64", "没有明确指令时的默认分摊比例。", role="measure", unit="decimal"),
            _internal_field("valid_from", "生效起始", "date32", "关系开始生效日期。", nullable=False, role="effective_time"),
            _internal_field("valid_to", "生效结束", "date32", "关系结束日期。", role="effective_time"),
            _internal_field("status", "关系状态", "string", "关系状态。", nullable=False, enum_values=("ACTIVE", "INACTIVE")),
            *control_audit_fields(),
        ),
        update_strategy="scd2",
    ),
    _table(
        "portfolio.responsibility_assignment",
        "组合责任分配",
        "按有效期关联组合、内部投资单元、负责人和职责角色。",
        "每个组合责任角色的一段有效分配",
        ("responsibility_assignment_id",),
        (
            primary_id("responsibility_assignment_id", "责任分配 ID", "责任关系稳定标识。"),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "责任对应组合。"),
            _internal_field("responsible_party_type", "责任方类型", "string", "人员、团队或机构。", nullable=False, enum_values=("PERSON", "TEAM", "ORGANIZATION")),
            _internal_field("responsible_party_id", "责任方 ID", "string", "人员、团队或机构标识。", nullable=False),
            _internal_field("role_code", "职责角色", "string", "投资负责人、研究员、运营、复核或审批角色。", nullable=False, enum_values=("PORTFOLIO_MANAGER", "RESEARCHER", "OPERATIONS", "ACCOUNTANT", "REVIEWER", "APPROVER", "OTHER")),
            _internal_field("sleeve_code", "投资单元代码", "string", "组合内部 Sleeve 或投资单元。"),
            _internal_field("valid_from", "生效起始", "date32", "责任开始日期。", nullable=False, role="effective_time"),
            _internal_field("valid_to", "生效结束", "date32", "责任结束日期。", role="effective_time"),
            *control_audit_fields(),
        ),
        update_strategy="scd2",
    ),
    _table(
        "portfolio.target_binding",
        "组合目标版本绑定",
        "把已确认的研究配置方案版本绑定到真实组合，并保留决策、确认和生效日期。",
        "每个真实组合的一段目标配置绑定",
        ("target_binding_id",),
        (
            primary_id("target_binding_id", "目标绑定 ID", "目标配置绑定稳定标识。"),
            foreign_id("portfolio_id", "组合 ID", "portfolio.portfolio.portfolio_id", "绑定目标配置的真实组合。"),
            _internal_field("allocation_plan_version_id", "配置方案版本 ID", "string", "绑定的不可变配置方案。", nullable=False, reference="research.allocation_plan_version.allocation_plan_version_id"),
            _internal_field("decision_date", "决策日期", "date32", "内部决策形成日期。", nullable=False, role="observation_time"),
            _internal_field("approved_at", "确认时间", "timestamp[us, UTC]", "平台外部或内部确认完成时间。", role="audit"),
            _internal_field("effective_from", "生效起始", "date32", "目标配置开始生效日期。", nullable=False, role="effective_time"),
            _internal_field("effective_to", "生效结束", "date32", "目标配置结束生效日期。", role="effective_time"),
            _internal_field("status", "绑定状态", "string", "目标绑定状态。", nullable=False, enum_values=("PENDING", "ACTIVE", "SUPERSEDED", "CANCELLED")),
            _internal_field("approval_reference", "确认记录引用", "string", "外部审批或内部确认记录引用。"),
            *control_audit_fields(),
        ),
        update_strategy="scd2",
    ),
)
