"""Versioned research definitions, bindings, runs, and artifact contracts."""

from __future__ import annotations

from ..types import CategoryDefinition, TableDefinition, control_audit_fields, field, foreign_id, primary_id


CATEGORY = CategoryDefinition(
    category_id="research",
    label="研究定义与版本",
    description="统一管理研究口径、指标、评价方案、产品池、大类、配置、回测、情景及不可变运行依赖。",
    order=80,
)


def _internal_field(*args, **kwargs):
    kwargs["source_mappable"] = False
    return field(*args, **kwargs)


def _control_table(
    table_id: str,
    label: str,
    description: str,
    grain: str,
    primary_key: tuple[str, ...],
    fields: tuple,
    *,
    update_strategy: str = "append",
    delivery_phase: str = "core",
) -> TableDefinition:
    return TableDefinition(
        table_id=table_id,
        category_id=CATEGORY.category_id,
        label=label,
        description=description,
        layer="control",
        storage_engine="sqlite",
        storage_location="data/platform.db",
        delivery_phase=delivery_phase,  # type: ignore[arg-type]
        grain=grain,
        primary_key=primary_key,
        update_strategy=update_strategy,  # type: ignore[arg-type]
        fields=fields,
        source_mappable=False,
        pit_supported=True,
    )


TABLES = (
    _control_table(
        "research.parameter_template",
        "研究口径模板",
        "保存基准、无风险利率、频率、年化、复权、币种和缺失值策略等版本化研究口径。",
        "每个研究口径模板修订一条记录",
        ("parameter_template_id", "revision"),
        (
            primary_id("parameter_template_id", "模板 ID", "研究口径模板稳定标识。"),
            _internal_field("revision", "修订号", "int64", "不可变修订号。", nullable=False, role="primary_key"),
            _internal_field("name", "模板名称", "string", "研究口径模板名称。", nullable=False),
            _internal_field("scope", "适用范围", "string", "产品、组合、情景或通用研究范围。", nullable=False, enum_values=("PRODUCT", "PORTFOLIO", "REGIME", "SCENARIO", "GENERAL")),
            _internal_field("frequency", "数据频率", "string", "研究默认频率。", nullable=False, enum_values=("DAILY", "WEEKLY", "MONTHLY", "QUARTERLY", "ANNUAL")),
            _internal_field("annualization_factor", "年化因子", "float64", "收益与风险的年化期数。", nullable=False, role="configuration", unit="period/year"),
            _internal_field("price_basis", "价格口径", "string", "复权净值、交易收盘价或总收益口径。", nullable=False, enum_values=("ADJUSTED_NAV", "RAW_CLOSE", "TOTAL_RETURN", "SETTLEMENT")),
            _internal_field("currency_policy", "币种策略", "string", "本币、原币或统一基准币种。", nullable=False, enum_values=("NATIVE", "BASE_CURRENCY", "HEDGED")),
            _internal_field("base_currency", "基准币种", "string", "统一换算使用的币种。", unit="ISO-4217"),
            _internal_field("risk_free_series_id", "无风险利率序列", "string", "引用的标准利率序列 ID。", reference="market.rate_observation.rate_series_id"),
            _internal_field("missing_policy", "缺失值策略", "string", "严格交集、拒绝或明确允许的其他策略。", nullable=False, enum_values=("STRICT_INTERSECTION", "REJECT", "ASOF_JOIN")),
            _internal_field("outlier_policy_json", "异常值策略", "json", "异常识别、裁剪和拒绝规则。"),
            _internal_field("calendar_code", "交易日历", "string", "默认交易日历代码。", reference="master.trading_calendar.calendar_code"),
            _internal_field("config_json", "完整配置", "json", "冻结的研究口径参数。", nullable=False),
            _internal_field("content_hash", "内容哈希", "string", "模板内容哈希。", nullable=False, role="audit"),
            _internal_field("status", "状态", "string", "模板生命周期。", nullable=False, enum_values=("DRAFT", "PUBLISHED", "DEPRECATED", "RETIRED")),
            _internal_field("published_at", "发布时间", "timestamp[us, UTC]", "修订发布为可使用版本的时间。", role="audit"),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "research.indicator_revision",
        "指标修订",
        "保存标量、时序、矩阵、产品和组合指标的不可变定义、公式、类型和执行合同。",
        "每个指标修订一条记录",
        ("indicator_id", "revision"),
        (
            primary_id("indicator_id", "指标 ID", "指标稳定标识。"),
            _internal_field("revision", "修订号", "int64", "不可变指标修订号。", nullable=False, role="primary_key"),
            _internal_field("name", "指标名称", "string", "指标名称。", nullable=False),
            _internal_field("result_kind", "结果类型", "string", "指标最终输出类型。", nullable=False, enum_values=("SCALAR", "TIME_SERIES", "VECTOR", "MATRIX")),
            _internal_field("context_kind", "上下文", "string", "单产品或组合计算上下文。", nullable=False, enum_values=("SINGLE_PRODUCT", "PORTFOLIO", "GENERAL")),
            _internal_field("expression", "执行表达式", "string", "受限 DSL 的可执行表达式。", nullable=False),
            _internal_field("display_latex", "展示公式", "string", "服务端生成的标准 LaTeX。", nullable=False),
            _internal_field("output_schema_json", "输出合同", "json", "输出通道、类型、单位、形状和展示规则。", nullable=False),
            _internal_field("required_variables_json", "依赖变量", "json", "运行需要的标准数据变量。", nullable=False),
            _internal_field("applicable_instrument_types_json", "适用标的类型", "json", "允许计算的标的类型。", nullable=False),
            _internal_field("dsl_version", "DSL 版本", "string", "表达式语法版本。", nullable=False),
            _internal_field("operator_registry_version", "算子注册表版本", "string", "算子和内核版本。", nullable=False),
            _internal_field("data_contract_version", "数据合同版本", "string", "指标依赖的内部数据合同版本。", nullable=False),
            _internal_field("content_hash", "定义哈希", "string", "指标定义内容哈希。", nullable=False, role="audit"),
            _internal_field("status", "状态", "string", "指标生命周期。", nullable=False, enum_values=("DRAFT", "PUBLISHED", "DEPRECATED", "RETIRED")),
            _internal_field("published_at", "发布时间", "timestamp[us, UTC]", "修订发布时间。", role="audit"),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "research.evaluation_plan_revision",
        "评价方案修订",
        "定义产品分组、指标方向、权重、缺失策略、归一化和排名逻辑。",
        "每个评价方案修订一条记录",
        ("evaluation_plan_id", "revision"),
        (
            primary_id("evaluation_plan_id", "评价方案 ID", "评价方案稳定标识。"),
            _internal_field("revision", "修订号", "int64", "不可变修订号。", nullable=False, role="primary_key"),
            _internal_field("name", "方案名称", "string", "评价方案名称。", nullable=False),
            _internal_field("instrument_scope_json", "产品范围", "json", "适用产品类型和筛选边界。", nullable=False),
            _internal_field("period_code", "评价周期", "string", "评价使用的标准周期。", nullable=False),
            _internal_field("missing_policy", "缺失策略", "string", "缺失指标的处理方式。", nullable=False, enum_values=("EXCLUDE_PRODUCT", "FAIL_RUN")),
            _internal_field("normalization_method", "归一化方法", "string", "指标横截面归一化方法。", nullable=False, enum_values=("MIN_MAX", "Z_SCORE", "RANK_PERCENTILE", "NONE")),
            _internal_field("tie_breaker_json", "并列规则", "json", "评分并列时的稳定排序规则。"),
            _internal_field("parameter_template_id", "研究口径模板 ID", "string", "引用的研究口径模板。", nullable=False, reference="research.parameter_template.parameter_template_id"),
            _internal_field("parameter_template_revision", "模板修订", "int64", "锁定的口径模板修订。", nullable=False),
            _internal_field("content_hash", "定义哈希", "string", "方案定义内容哈希。", nullable=False, role="audit"),
            _internal_field("status", "状态", "string", "评价方案生命周期。", nullable=False, enum_values=("DRAFT", "PUBLISHED", "DEPRECATED", "RETIRED")),
            _internal_field("published_at", "发布时间", "timestamp[us, UTC]", "方案修订发布时间。", role="audit"),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "research.evaluation_plan_indicator",
        "评价方案指标",
        "把评价方案修订绑定到精确指标修订、方向、权重和展示顺序。",
        "每个评价方案修订中的每个指标一条记录",
        ("evaluation_plan_id", "plan_revision", "indicator_id", "indicator_revision"),
        (
            foreign_id("evaluation_plan_id", "评价方案 ID", "research.evaluation_plan_revision.evaluation_plan_id", "所属评价方案。"),
            _internal_field("plan_revision", "方案修订", "int64", "所属方案修订号。", nullable=False, role="primary_key"),
            foreign_id("indicator_id", "指标 ID", "research.indicator_revision.indicator_id", "绑定的指标。"),
            _internal_field("indicator_revision", "指标修订", "int64", "锁定的指标修订号。", nullable=False, role="primary_key"),
            _internal_field("direction", "指标方向", "string", "越大越好或越小越好。", nullable=False, enum_values=("HIGHER_BETTER", "LOWER_BETTER")),
            _internal_field("weight", "指标权重", "float64", "评价方案中的小数制权重。", nullable=False, role="measure", unit="decimal"),
            _internal_field("minimum_coverage", "最低覆盖率", "float64", "指标进入排名要求的最低数据覆盖率。", nullable=False, role="configuration", unit="decimal"),
            _internal_field("sort_order", "展示顺序", "int64", "方案中的指标顺序。", nullable=False),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "research.product_pool",
        "产品池",
        "产品池稳定主档；成员变化只通过不可变产品池版本发布。",
        "每个产品池一条记录",
        ("product_pool_id",),
        (
            primary_id("product_pool_id", "产品池 ID", "产品池稳定标识。"),
            _internal_field("name", "产品池名称", "string", "产品池名称。", nullable=False),
            _internal_field("description", "说明", "string", "产品池用途和准入边界。"),
            _internal_field("owner", "负责人", "string", "产品池研究负责人。"),
            _internal_field("status", "状态", "string", "产品池状态。", nullable=False, enum_values=("ACTIVE", "INACTIVE", "ARCHIVED")),
            *control_audit_fields(),
        ),
        update_strategy="upsert",
    ),
    _control_table(
        "research.product_pool_version",
        "产品池版本",
        "冻结评价方案、准入规则、数据版本、成员和发布状态。",
        "每个产品池版本一条记录",
        ("product_pool_version_id",),
        (
            primary_id("product_pool_version_id", "产品池版本 ID", "不可变产品池版本标识。"),
            foreign_id("product_pool_id", "产品池 ID", "research.product_pool.product_pool_id", "所属产品池。"),
            _internal_field("version", "版本号", "int64", "产品池内递增版本号。", nullable=False),
            _internal_field("effective_from", "生效起始", "date32", "版本开始生效日期。", role="effective_time"),
            _internal_field("effective_to", "生效结束", "date32", "版本结束日期。", role="effective_time"),
            _internal_field("data_release_id", "数据版本 ID", "string", "构建该版本使用的数据发布版本。", nullable=False, reference="governance.data_release.data_release_id"),
            _internal_field("selection_rule_json", "准入规则", "json", "自动准入和排除规则快照。", nullable=False),
            _internal_field("review_summary", "研究摘要", "string", "本次发布的研究结论。"),
            _internal_field("content_hash", "版本哈希", "string", "成员、规则和依赖版本哈希。", nullable=False, role="audit"),
            _internal_field("status", "状态", "string", "版本生命周期。", nullable=False, enum_values=("DRAFT", "PUBLISHED", "SUPERSEDED", "RETIRED")),
            _internal_field("published_at", "发布时间", "timestamp[us, UTC]", "版本发布时间。", role="audit"),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "research.product_pool_member",
        "产品池成员",
        "保存产品池版本中的产品状态、来源评价方案、限制、替换关系和研究理由。",
        "每个产品池版本中的每个标的一条记录",
        ("product_pool_version_id", "instrument_id"),
        (
            foreign_id("product_pool_version_id", "产品池版本 ID", "research.product_pool_version.product_pool_version_id", "所属产品池版本。"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "产品池成员。"),
            _internal_field("member_status", "成员状态", "string", "准入、观察、限制或排除。", nullable=False, enum_values=("ADMITTED", "WATCH", "RESTRICTED", "EXCLUDED")),
            _internal_field("asset_class_code", "适用资产类别", "string", "产品在产品池中的资产类别标签。"),
            _internal_field("evaluation_plan_id", "评价方案 ID", "string", "支持准入结论的评价方案。", reference="research.evaluation_plan_revision.evaluation_plan_id"),
            _internal_field("evaluation_plan_revision", "评价方案修订", "int64", "锁定的评价方案修订号。"),
            _internal_field("evaluation_run_id", "评价运行 ID", "string", "产生评分和排名的运行标识。"),
            _internal_field("score", "评分", "float64", "准入时锁定的评价分数。", role="measure"),
            _internal_field("rank", "排名", "int64", "准入时锁定的评价排名。", role="measure", unit="rank"),
            _internal_field("max_weight", "最大权重", "float64", "该产品在组合中的最大允许权重。", role="measure", unit="decimal"),
            _internal_field("capacity_limit", "容量限制", "decimal128(38, 6)", "该产品可承载的内部投资规模限制。", role="measure", unit="currency"),
            _internal_field("reason_codes_json", "原因代码", "json", "准入、观察、限制或排除原因。", nullable=False),
            _internal_field("replacement_instrument_id", "替代产品 ID", "string", "建议替代标的。", reference="master.instrument.instrument_id"),
            _internal_field("reviewed_at", "复核时间", "timestamp[us, UTC]", "成员结论复核时间。", role="audit"),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "research.asset_class_version",
        "资产大类版本",
        "冻结资产大类定义、成员构成、权重规则和研究依赖。",
        "每个资产大类定义版本一条记录",
        ("asset_class_version_id",),
        (
            primary_id("asset_class_version_id", "资产大类版本 ID", "不可变资产大类版本标识。"),
            _internal_field("asset_class_id", "资产大类 ID", "string", "跨版本稳定资产大类标识。", nullable=False),
            _internal_field("version", "版本号", "int64", "资产大类递增版本号。", nullable=False),
            _internal_field("name", "大类名称", "string", "资产大类名称。", nullable=False),
            _internal_field("construction_method", "构建方式", "string", "人工、规则、聚类或其他方法。", nullable=False, enum_values=("MANUAL", "RULE", "CLUSTER", "MODEL")),
            _internal_field("weight_method", "类内权重方法", "string", "等权、固定权重、风险预算或优化。", nullable=False, enum_values=("EQUAL", "FIXED", "RISK_BUDGET", "OPTIMIZED")),
            _internal_field("parameter_json", "构建参数", "json", "冻结的大类构建参数。", nullable=False),
            _internal_field("data_release_id", "数据版本 ID", "string", "构建和验证使用的数据发布版本。", nullable=False, reference="governance.data_release.data_release_id"),
            _internal_field("content_hash", "定义哈希", "string", "成员、权重和参数内容哈希。", nullable=False, role="audit"),
            _internal_field("status", "状态", "string", "资产大类版本状态。", nullable=False, enum_values=("DRAFT", "PUBLISHED", "SUPERSEDED", "RETIRED")),
            _internal_field("published_at", "发布时间", "timestamp[us, UTC]", "版本发布时间。", role="audit"),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "research.asset_class_member",
        "资产大类成员",
        "保存资产大类版本的具体产品、类内权重和有效约束。",
        "每个资产大类版本中的每个产品一条记录",
        ("asset_class_version_id", "instrument_id"),
        (
            foreign_id("asset_class_version_id", "资产大类版本 ID", "research.asset_class_version.asset_class_version_id", "所属资产大类版本。"),
            foreign_id("instrument_id", "标的 ID", "master.instrument.instrument_id", "大类成员产品。"),
            _internal_field("target_weight", "目标权重", "float64", "类内目标权重，小数制。", nullable=False, role="measure", unit="decimal"),
            _internal_field("minimum_weight", "最小权重", "float64", "类内最小权重。", role="measure", unit="decimal"),
            _internal_field("maximum_weight", "最大权重", "float64", "类内最大权重。", role="measure", unit="decimal"),
            _internal_field("role_code", "成员角色", "string", "代表产品、备选产品或观察产品。", nullable=False, enum_values=("PRIMARY", "ALTERNATIVE", "WATCH")),
            _internal_field("sort_order", "排序", "int64", "大类内展示顺序。", nullable=False),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "research.allocation_plan_version",
        "资产配置方案版本",
        "冻结 SAA、TAA 或产品配置目标、约束、成本、调仓与研究依赖。",
        "每个资产配置方案版本一条记录",
        ("allocation_plan_version_id",),
        (
            primary_id("allocation_plan_version_id", "配置方案版本 ID", "不可变配置方案版本标识。"),
            _internal_field("allocation_plan_id", "配置方案 ID", "string", "跨版本稳定配置方案标识。", nullable=False),
            _internal_field("version", "版本号", "int64", "方案内递增版本号。", nullable=False),
            _internal_field("name", "方案名称", "string", "配置方案名称。", nullable=False),
            _internal_field("allocation_type", "配置类型", "string", "SAA、TAA 或产品配置。", nullable=False, enum_values=("SAA", "TAA", "PRODUCT_ALLOCATION", "COMPLETE_PORTFOLIO")),
            _internal_field("base_currency", "基准币种", "string", "方案统一计价币种。", nullable=False, unit="ISO-4217"),
            _internal_field("product_pool_version_ids_json", "产品池版本", "json", "方案允许使用的产品池版本。", nullable=False),
            _internal_field("parameter_template_id", "研究口径模板 ID", "string", "锁定的研究口径模板。", nullable=False, reference="research.parameter_template.parameter_template_id"),
            _internal_field("parameter_template_revision", "模板修订", "int64", "锁定的模板修订。", nullable=False),
            _internal_field("constraints_json", "配置约束", "json", "单资产、分组、风险、流动性和容量约束。", nullable=False),
            _internal_field("rebalance_policy_json", "调仓规则", "json", "周期、阈值、信号和恢复规则。", nullable=False),
            _internal_field("cost_model_json", "成本模型", "json", "交易费、申赎费、冲击和确认时滞。", nullable=False),
            _internal_field("data_release_id", "数据版本 ID", "string", "研究方案使用的数据版本。", nullable=False, reference="governance.data_release.data_release_id"),
            _internal_field("content_hash", "方案哈希", "string", "目标、约束和依赖内容哈希。", nullable=False, role="audit"),
            _internal_field("status", "状态", "string", "方案生命周期。", nullable=False, enum_values=("DRAFT", "VALIDATING", "PUBLISHED", "SUPERSEDED", "RETIRED")),
            _internal_field("published_at", "发布时间", "timestamp[us, UTC]", "方案发布时间。", role="audit"),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "research.allocation_target",
        "配置目标权重",
        "保存配置方案版本在资产大类和产品层的目标权重、上下限与来源。",
        "每个配置方案版本中的每个目标节点一条记录",
        ("allocation_plan_version_id", "target_level", "target_id"),
        (
            foreign_id("allocation_plan_version_id", "配置方案版本 ID", "research.allocation_plan_version.allocation_plan_version_id", "所属配置方案版本。"),
            _internal_field("target_level", "目标层级", "string", "资产大类或产品层。", nullable=False, role="primary_key", enum_values=("ASSET_CLASS", "INSTRUMENT", "CASH")),
            _internal_field("target_id", "目标对象 ID", "string", "资产大类版本、instrument_id 或现金代码。", nullable=False, role="primary_key"),
            _internal_field("parent_target_id", "父目标 ID", "string", "产品目标对应的资产大类目标。"),
            _internal_field("target_weight", "目标权重", "float64", "小数制目标权重。", nullable=False, role="measure", unit="decimal"),
            _internal_field("minimum_weight", "最小权重", "float64", "允许的最小权重。", role="measure", unit="decimal"),
            _internal_field("maximum_weight", "最大权重", "float64", "允许的最大权重。", role="measure", unit="decimal"),
            _internal_field("weight_source", "权重来源", "string", "人工、优化器、评分或状态偏移。", nullable=False, enum_values=("MANUAL", "OPTIMIZER", "SCORE", "RISK_BUDGET", "REGIME_OFFSET")),
            _internal_field("sort_order", "排序", "int64", "展示和计算顺序。", nullable=False),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "research.backtest_run",
        "回测运行",
        "记录一次不可变回测的时间边界、信号时点、执行规则、成本、随机种子和状态。",
        "每次回测运行一条记录",
        ("backtest_run_id",),
        (
            primary_id("backtest_run_id", "回测运行 ID", "一次回测运行的稳定标识。"),
            _internal_field("name", "运行名称", "string", "回测运行名称。", nullable=False),
            _internal_field("run_mode", "运行模式", "string", "研究模式或严格 PIT 模式。", nullable=False, enum_values=("RESEARCH", "STRICT_PIT")),
            _internal_field("allocation_plan_version_id", "配置方案版本 ID", "string", "回测使用的配置方案版本。", reference="research.allocation_plan_version.allocation_plan_version_id"),
            _internal_field("start_date", "开始日期", "date32", "回测开始日期。", nullable=False, role="observation_time"),
            _internal_field("end_date", "结束日期", "date32", "回测结束日期。", nullable=False, role="observation_time"),
            _internal_field("decision_timing", "决策时点", "string", "信号何时计算。", nullable=False),
            _internal_field("execution_timing", "执行时点", "string", "交易何时生效。", nullable=False),
            _internal_field("confirmation_policy_json", "确认规则", "json", "场外基金净值确认和结算规则。", nullable=False),
            _internal_field("cost_model_json", "成本模型", "json", "本次运行冻结的成本模型。", nullable=False),
            _internal_field("random_seed", "随机种子", "int64", "随机优化或模拟使用的种子。"),
            _internal_field("status", "运行状态", "string", "回测运行状态。", nullable=False, enum_values=("QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED")),
            _internal_field("started_at", "开始时间", "timestamp[us, UTC]", "运行开始时间。", role="audit"),
            _internal_field("finished_at", "结束时间", "timestamp[us, UTC]", "运行结束时间。", role="audit"),
            _internal_field("warning_codes_json", "警告代码", "json", "运行产生的结构化警告。", nullable=False),
            _internal_field("error_code", "错误代码", "string", "失败时的稳定错误代码。", role="audit"),
            _internal_field("error_message", "错误说明", "string", "失败说明。", role="audit"),
            _internal_field("engine_version", "引擎版本", "string", "回测执行引擎版本。", nullable=False, role="audit"),
            *control_audit_fields(),
        ),
    ),
    _control_table(
        "research.run_dependency",
        "研究运行依赖",
        "冻结回测、评价、情景、指标或组合运行使用的数据、定义、模型、参数和代码版本。",
        "每个研究运行的每个依赖对象一条记录",
        ("run_type", "run_id", "dependency_type", "dependency_id", "dependency_version"),
        (
            _internal_field("run_type", "运行类型", "string", "依赖所属运行类型。", nullable=False, role="primary_key", enum_values=("BACKTEST", "EVALUATION", "INDICATOR", "REGIME", "SCENARIO", "PORTFOLIO")),
            _internal_field("run_id", "运行 ID", "string", "具体运行标识。", nullable=False, role="primary_key"),
            _internal_field("dependency_type", "依赖类型", "string", "数据、指标、参数、模型、配置、产品池或代码。", nullable=False, role="primary_key", enum_values=("DATA_RELEASE", "TABLE_CONTRACT", "INDICATOR", "PARAMETER_TEMPLATE", "MODEL", "ALLOCATION", "PRODUCT_POOL", "CODE")),
            _internal_field("dependency_id", "依赖对象 ID", "string", "依赖对象稳定标识。", nullable=False, role="primary_key"),
            _internal_field("dependency_version", "依赖版本", "string", "不可变版本或修订号。", nullable=False, role="primary_key"),
            _internal_field("content_hash", "内容哈希", "string", "依赖对象内容或制品哈希。", nullable=False, role="audit"),
            _internal_field("resolved_at", "解析时间", "timestamp[us, UTC]", "运行启动时解析依赖的时间。", nullable=False, role="audit"),
        ),
    ),
    _control_table(
        "research.artifact",
        "研究制品",
        "登记净值、权重、交易、诊断、报告和导出文件等不可变研究结果。",
        "每个研究运行制品一条记录",
        ("artifact_id",),
        (
            primary_id("artifact_id", "制品 ID", "研究制品稳定标识。"),
            _internal_field("run_type", "运行类型", "string", "产生制品的运行类型。", nullable=False),
            _internal_field("run_id", "运行 ID", "string", "产生制品的运行标识。", nullable=False),
            _internal_field("artifact_type", "制品类型", "string", "结果制品类别。", nullable=False, enum_values=("NAV", "WEIGHT_PATH", "TRADES", "METRICS", "DIAGNOSTICS", "REPORT", "EXPORT", "LOG")),
            _internal_field("storage_uri", "存储地址", "string", "Parquet、JSON、Excel 或其他制品地址。", nullable=False),
            _internal_field("storage_format", "存储格式", "string", "制品文件格式。", nullable=False, enum_values=("PARQUET", "JSON", "XLSX", "CSV", "HTML", "TEXT")),
            _internal_field("schema_version", "结果 Schema 版本", "string", "制品数据结构版本。", nullable=False),
            _internal_field("checksum", "校验和", "string", "制品内容校验和。", nullable=False, role="audit"),
            _internal_field("row_count", "行数", "int64", "表格制品的行数。", role="measure", unit="row"),
            _internal_field("byte_size", "文件大小", "int64", "制品字节大小。", nullable=False, role="measure", unit="byte"),
            _internal_field("created_at", "生成时间", "timestamp[us, UTC]", "制品生成完成时间。", nullable=False, role="audit"),
        ),
    ),
    _control_table(
        "research.regime_definition_version",
        "历史情景识别版本",
        "冻结 Regime Graph、状态字典、数据依赖、实时/事后模式、验证与发布状态。",
        "每个历史情景识别定义版本一条记录",
        ("regime_version_id",),
        (
            primary_id("regime_version_id", "情景识别版本 ID", "不可变历史情景识别版本。"),
            _internal_field("regime_definition_id", "定义 ID", "string", "跨版本稳定定义标识。", nullable=False),
            _internal_field("version", "版本号", "int64", "定义内递增版本。", nullable=False),
            _internal_field("name", "名称", "string", "历史情景识别名称。", nullable=False),
            _internal_field("mode", "识别模式", "string", "事后解释或实时可交易。", nullable=False, enum_values=("RETROSPECTIVE", "REALTIME")),
            _internal_field("state_dictionary_json", "状态字典", "json", "状态代码、名称和业务解释。", nullable=False),
            _internal_field("graph_json", "Regime Graph", "json", "版本化数据、特征、模型和后处理图。", nullable=False),
            _internal_field("data_release_id", "数据版本 ID", "string", "验证和发布时使用的数据版本。", nullable=False, reference="governance.data_release.data_release_id"),
            _internal_field("parameter_template_id", "参数模板 ID", "string", "锁定的研究口径模板。", nullable=False, reference="research.parameter_template.parameter_template_id"),
            _internal_field("parameter_template_revision", "模板修订", "int64", "锁定参数模板修订。", nullable=False),
            _internal_field("validation_artifact_id", "验证报告制品 ID", "string", "发布门槛验证报告。", reference="research.artifact.artifact_id"),
            _internal_field("taa_eligible", "允许 TAA 使用", "bool", "是否通过实时性和样本外门槛。", nullable=False),
            _internal_field("content_hash", "定义哈希", "string", "图、状态、参数和依赖哈希。", nullable=False, role="audit"),
            _internal_field("status", "状态", "string", "版本生命周期。", nullable=False, enum_values=("DRAFT", "VALIDATING", "PUBLISHED", "DEPRECATED", "RETIRED")),
            _internal_field("published_at", "发布时间", "timestamp[us, UTC]", "版本发布时间。", role="audit"),
            *control_audit_fields(),
        ),
        delivery_phase="next",
    ),
    _control_table(
        "research.scenario_definition_version",
        "情景模拟版本",
        "冻结历史重演、假设路径、Monte Carlo 或反向压力测试的变量、映射和组合推进规则。",
        "每个情景模拟定义版本一条记录",
        ("scenario_version_id",),
        (
            primary_id("scenario_version_id", "情景版本 ID", "不可变情景模拟版本标识。"),
            _internal_field("scenario_definition_id", "定义 ID", "string", "跨版本稳定情景标识。", nullable=False),
            _internal_field("version", "版本号", "int64", "定义内递增版本。", nullable=False),
            _internal_field("name", "情景名称", "string", "情景模拟名称。", nullable=False),
            _internal_field("scenario_type", "情景类型", "string", "情景生成方法。", nullable=False, enum_values=("HISTORICAL_REPLAY", "SENSITIVITY", "DETERMINISTIC_PATH", "MONTE_CARLO", "STATE_CONDITIONAL", "REVERSE_STRESS")),
            _internal_field("narrative", "情景叙事", "string", "情景假设和业务解释。", nullable=False),
            _internal_field("horizon_days", "持有期", "int64", "情景模拟期限。", nullable=False, unit="day"),
            _internal_field("variable_paths_json", "变量路径", "json", "宏观和市场变量冲击路径。", nullable=False),
            _internal_field("mapping_models_json", "冲击映射", "json", "变量到资产、产品和组合的版本化映射。", nullable=False),
            _internal_field("portfolio_policy_json", "组合推进规则", "json", "静态持有、调仓或 TAA 推进方式。", nullable=False),
            _internal_field("probabilistic", "概率情景", "bool", "是否具有明确概率模型。", nullable=False),
            _internal_field("random_seed", "随机种子", "int64", "随机情景的默认种子。"),
            _internal_field("validation_artifact_id", "验证报告制品 ID", "string", "情景验证报告。", reference="research.artifact.artifact_id"),
            _internal_field("content_hash", "定义哈希", "string", "情景、映射和依赖内容哈希。", nullable=False, role="audit"),
            _internal_field("status", "状态", "string", "版本生命周期。", nullable=False, enum_values=("DRAFT", "VALIDATING", "PUBLISHED", "DEPRECATED", "RETIRED")),
            _internal_field("published_at", "发布时间", "timestamp[us, UTC]", "版本发布时间。", role="audit"),
            *control_audit_fields(),
        ),
        delivery_phase="next",
    ),
)
